### ISSUE TITLE
v-server-table - example please

### ISSUE THREAD

**Issue by ab-su-rd** [matfish2/vue-tables-2#10]
could you give an example for wrapping the v-server-table with a v-if please?

i am finding that putting the v-if directive with false never triggers the network call to fetch data, and setting it to true triggers the loading event, but vue-tables errors out with `Cannot read property 'get' of undefined`
not seeing a network call in either case.

my code
```
                <div id="assets-vue"
                     v-if="!loading"
                >
                    <v-server-table
                            url="/people"
                            :columns="columns"
                            :options="options"
                            name="assets-table"
                    >
                    </v-server-table>
                </div>
```

btw, i'm using the library after compiling it with browserify
sections from package.json:
```
    "build-vue-tables": "browserify node_modules/vue-tables-2/index.js --s VueTables | uglifyjs -c > public/js/vue-tables.js"
```
```
  "browserify": {
    "transform": [
      "babelify",
      {
        "presets": [
          "es2015"
        ],
        "plugins": [
          "transform-vue-jsx"
        ]
      }
    ]
  },
```
i also had to set .babelrc, for some reason
```
{
    "plugins": ["transform-vue-jsx"],
    "presets": ["es2015"]
}
```

**Comment by matfish2** [comment]
Not sure. Need to test this scenario.
In the meantime you can probably use `v-show` instead.

**Comment by ab-su-rd** [comment]
`v-show` has the same behaviour, i'm afraid.

**Comment by matfish2** [comment]
Ok. I've tested both `v-if` and `v-show` and was unable to reproduce.
I believe your bug has nothing to do with those directives.

`Cannot read property 'get' of undefined`
Probably stems from the fact that you didn't include `vue-resource`

**Comment by ab-su-rd** [comment]
Indeed!

I was missing `vue-resource`

Thank you very much for pointing it out and for what you are doing here!
