### ISSUE TITLE
question: possible to pass in callback to format column data?

### ISSUE THREAD

**Issue by PsychicCat** [matfish2/vue-tables-2#100]
I can't really tell via the documentation, but I'd like to apply some formatting to certain columns. For example, formatting money amounts to be `$1.00` instead of `1`. 

It seems like to only way to do this is create a custom component, kind of feels like overkill just to format data.

What do you think about having something like `callbacks` in the options prop, where the passed in function formats a given column's data as a computed property in the cell?

somewhat related to #95

**Comment by matfish2** [comment]
This is exactly what the `templates` option is for. You don't have to create a custom component for it. You can pass a function that return a virtual node (If you don't want to install a jsx transformer you can use the online transformer (here)[https://vuejs.org/v2/guide/render-function.html])

**Comment by matfish2** [comment]
```js
templates:{
amount:function(h, row) {
return Number(row.amount).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,') + '$';
}
}
```

**Comment by PsychicCat** [comment]
ah, thank you! i had a feeling i was missing something.

**Comment by shobeurself** [comment]
@matfish2 In this case, where is this.toDollars defined?  I am trying something similar, and have it defined as a method in the component, but I am getting the error "this.toDollars is not a function".
