### ISSUE TITLE
sync template's checkbox to vue-tables, custom event?

### ISSUE THREAD

**Issue by eminos** [matfish2/vue-tables-2#101]
First I wanna thank you for a great component.

I've created a vue component based template to display a checkbox, and the goal is to have the state of that checkbox sync back to the parent components table data.

```vue
<template>
    <input type="checkbox" v-model="data.selected" @change="checked()">
</template>
<script>
    export default {
        name: 'checkbox',
        props: ['data'],
        methods: {
            checked() {
                console.log('checked from checkbox.vue');
                this.$emit('checked');
            }
        }
    }
</script>
```

```js
// parent component StoreProducts
...
data() {
        return {
            store_products: [],
            columns: ['selected','store','name','price'],
            options: {
                templates: {
                    selected: checkbox,
                    store: function(h, row) {
                        return row.store.name;
                    },
                    price: function(h, row) {
                        let value = row.price / 100;
                        return value.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,');
                    }
                }
            }
        }
    },
methods: {
        onChecked() {
            console.log('checked from parent!!');
        },
    },
...
```

```vue
<v-client-table :data="store_products" :columns="columns" :options="options" @checked="onChecked()"></v-client-table>
```

The issue is that `onChecked()` is not firing at all.
But also, would this be the correct way to do what I want? To sync the `row.selected` back to the parent's table data array?

**Comment by matfish2** [comment]
I don't know why the event is not propagated up the tree. 
Until I figure that out you can use the independent event bus to achieve the same result (i.e `Event.$emit` and `Event.$on`).

As for the scenario itself, I had a similar issue with row clicked event, where I wanted to send through the original row and not the computed one, which is deeply cloned. That way, the row can be directly manipulated in the callback, without requiring the user to hunt it down in the original dataset.  In this specific case I solved the problem by returning the original row by a unique identifier (i.e I did the job for the user). This is also what you can do in your case (emit the event with the row id, and grab the original in your `Event.$on` callback).
 
However, in case of the entire dataset such a solution would be too wasteful in terms of performance. 
I will try to think of a way that doesn't require deep cloning the original data before passing it to be filtered. Any suggestions\PRs are most welcome.

**Comment by eminos** [comment]
Yea, to link the cell template data to the original row data, byt not deep cloning would probably the the best solution in my case. Unfortunately I'm not experienced enough in js/vue to  help you out there.

Regarding the solution by using `Event.$emit` and `Event.$on`, could you please elaborate on that? Just switching out `this` to `Event` doesn't work ("not a function").

**Comment by eminos** [comment]
OK. So I think I've figured out what you meant by `Event.$on`. I had to `import {Event} from 'vue-tables-2'` on both the parent component and the checkbox.vue component. Now the event is working as expected. But I'm not sure this is the best way. What is `Event` anyway, it just seems to be the Vue instance?

**Comment by matfish2** [comment]
https://laracasts.com/series/learn-vue-2-step-by-step/episodes/13
