### ISSUE TITLE
Unknown custom element: <v-client-table>...

### ISSUE THREAD

**Issue by inzanez** [matfish2/vue-tables-2#102]
Hi

I was using vue-tables before, switched to vue-tables-2 because of VueJS2. At that point I want to thank you for the nice component, solved a lot of problems! 👍 

But I'm afraid I'm having some difficulties with vue-tables-2, maybe also because I'm trying to use it in own components:
I'm trying to use vue-tables-2 in a sample application based on the 'webpack-simple' template.

So I got a 'main.js':
```
import Vue from 'vue'
import App from './App.vue'
import VueResource from 'vue-resource'
import ClientTable from 'vue-tables-2'

Vue.use(VueResource)
Vue.use(ClientTable, {}, false, null);

new Vue({
  el: '#app',
  render: h => h(App)
})
```

an App.vue:

```
<template>
  <div id="app">
<Tabletest></Tabletest>
  </div>
</template>

<script>
import Tabletest from './components/Tabletest.vue'

export default {
  name: 'app',
  components: { Tabletest },
  data () {
    return {  
    }
  }
}
</script>

<style>
</style>
```

and finally the Tabletest.vue component with the v-client-table:
```
<template>
<div id="sometest">
{{tableData}}<br/>
<v-client-table :data="tableData" :columns="columns" :options="options"></v-client-table>
</div>
</template>

<script>
export default {
	data() {
		return {
			columns:['id','name','age'],
    		        tableData: [
    		             {id:1, name:"John",age:"20"},
    		             {id:2, name:"Jane",age:"24"},
    		             {id:3, name:"Susan",age:"16"},
   			     {id:4, name:"Chris",age:"55"},
    		             {id:5, name:"Dan",age:"40"}
   		       ],
    		       options: {
                          // see the options API
    		       }
		}
	}
}
```

I tried different ways of registering 'vue-tables-2', as 'components: { ... }' for instance, or importing it directly in the "Tabletest.vue" component and so on, but nothing worked so far.

In addition, I'm not sure whether or not the 'template' parameter can be 'null'? It's not quite clear to me from the documentation...

**Comment by matfish2** [comment]
**As documented**, Instead of
```js
import ClientTable from 'vue-tables-2';
```
Use
```js
import {ClientTable} from 'vue-tables-2';
```
As for the additional parameters in Vue.use, they are all optional:
```js
Vue.use(ClientTable);
```

**Comment by inzanez** [comment]
Damn, thank you! I thought the curly braces were lik "either or"...:-)
