### ISSUE TITLE
Show/hide table column

### ISSUE THREAD

**Issue by leonfather** [matfish2/vue-tables-2#105]
- Vue.js version: 2
Is this version support show / hide column in table? Just like filtering by column

**Comment by matfish2** [comment]
The `columnsDisplay` option allows you to control the display of the columns by screen size

**Comment by leonfather** [comment]
There is an option to control the display of the columns by checkbox? For instance if a checkbox is checked the column related to this checkbox will disappear?

**Comment by leonfather** [comment]
I think this issue is not yet closed because i mean show or hide column by checkbox not by screen size

**Comment by techytuppers** [comment]
@matfish2 do you think this enhancement request is possible? I've seen @leonfather 's suggestion implemented elsewhere http://filamentgroup.github.io/tablesaw/demo/toggle.html

This would provide users a greater deal of flexibility for users rather than the developer deciding what columns should or should not be shown on smaller screens.

**Comment by matfish2** [comment]
Interesting suggestion. I think the best way would be to combine those two. I.e allow the developer to set the default visible columns for each screen size, and the user to customize it on run-time using the checkbox. 
I will reopen the issue and hopefully implement it in the near future.

**Comment by techytuppers** [comment]
@matfish2 merging the two concepts sounds like a great idea 👍

**Comment by RileyIsland** [comment]
As a workaround, I implemented something like this and based the data off of a computed `useTable` property. It's a bit hacky but seems to work just fine for what I need.
```
<v-server-table url="useTable.url" ref="table"
                v-if="useTable.type == 'first_table'"
                :columns="table.columns.first_table" :options="table.options"
                @loaded="onLoaded"></v-server-table>
<v-server-table url="useTable.url" ref="table"
                v-else-if="usetTable.type == 'second_table'"
                :columns="table.columns.second_table" :options="table.options"
                @loaded="onLoaded"></v-server-table>
```

**Comment by liaoyalien** [comment]
Is it doable to hide toggler column? Cause I toggle by row-click event, so don't need toggler column anymore.
