### ISSUE TITLE
current_page and String values

### ISSUE THREAD

**Issue by anselmobattisti** [matfish2/vue-tables-2#107]
- Vue.js version: 2.2.2
- consumed using: webpack
- relevant code:
      $dados['current_page'] = (int) $currentPage;
- steps for reproducing the issue:

When the API return the current_page value as a STRING value,  with ' the css style of current page not work, its necessary force the variable to INT

Maybe we can use a parseInt to prevent this kind of issue, i kwow its an api error but it took me some time to deal with it.

vuetable is awsome :) tnks a lot for your work!

**Comment by matfish2** [comment]
There is no inherent styling in this package. Did you mean https://github.com/ratiw/vuetable-2?
