### ISSUE TITLE
Column grouping?

### ISSUE THREAD

**Issue by gozcan** [matfish2/vue-tables-2#110]
would you care to implement more features to this awesome repository?

[for example: grouping like this one](https://codepen.io/andrewcourtice/pen/woQzpa)

**Comment by mosinve** [comment]
i've made simple grouping feature to this by custom templates...

**Comment by bdm123** [comment]
Hey @mosinve - can you post your sample code please?

**Comment by mosinve** [comment]
Yep, I already upload it here - https://github.com/mosinve/vue-tables-grouping.

**Comment by bdm123** [comment]
Thanks @mosinve, you rock!
