### ISSUE TITLE
Vue-Router inside Template

### ISSUE THREAD

**Issue by inzanez** [matfish2/vue-tables-2#113]
Hi

I'm trying to use <router-link> from Vue-Router inside a template for a column. It seems that everything works fine if using '<router-link to=...></router-link>'. But when trying to use:

`<router-link to="{ name: 'viewjobdetails', params: { id: {{data.id }} }}">{{data.name }}</router-link>`

it doesn't display anything anymore, and javascript console tells me:

> invalid expression: :to="{ name: 'viewredactionjob', params: { id: {data.artifactID }}}"

Is it possible to use <router-link ...> inside the template at any rate?

**Comment by matfish2** [comment]
You can you whatever you want inside the template. The error you are getting has nothing to do with templates limitations. It seems more like invalid json (which is exactly what the error tells you)

**Comment by inzanez** [comment]
No, I don't quite agree with that.

```
name: function(h, row) {
	return <router-link :to={ name: 'user', params: { id: 123 }}>Some Link</router-link>
}

That does not work. The JSON is fine, the whole "expression" comes from the Vue-Router documentation, so that should be fine as well. It does work outside of vue-tables-2, but it doesn't when being used as a template for a vue-tables-2 column. Why?
```

**Comment by matfish2** [comment]
It does not work because it is not a valid JSX. Try this:

name: function(h, row) {
	return <router-link :to={{ name: 'user', params: { id: 123 }}}>Some Link</router-link>
}

Or better still, extract the object to a data property or a method and reference it instead (As documented you have access to the parent instance via the `this` keyword)

**Comment by inzanez** [comment]
Ok, funny, that works. Many thanks. I don't quite understand why I can leave out the ":" before the "to" in the <router-link>,...I thought that was mandatory for a link to a named route. Does that have anything to do with JSX?
