### ISSUE TITLE
example for vue-tables-2

### ISSUE THREAD

**Issue by Gorniv** [matfish2/vue-tables-2#114]
Do you have an actual example for VueTables 2 on https://jsfiddle.net/ (or another place)?

**Comment by Gorniv** [comment]
I know only http://requirebin.com/

**Comment by matfish2** [comment]
Cool. I'll have a look

**Comment by Gorniv** [comment]
https://rawgit.com/Gorniv/vue-tables-2/master/dist/index.min.js -build

**Comment by vinayakkulkarni** [comment]
so, requirebin example anyone?
