### ISSUE TITLE
Not found what prop "records" is missing

### ISSUE THREAD

**Issue by afucher** [matfish2/vue-tables-2#115]
- Vue.js version: 2.0.7
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace):
build.js:9074 [Vue warn]: Invalid prop: type check failed for prop "records". Expected Number, got Undefined. 
(found in component <pagination>)
- relevant code:
- steps for reproducing the issue:
Just use the example

**Comment by matfish2** [comment]
Are you using the server component? If so make sure your server returns a numeric `count` property. Otherwise I need to see your code

**Comment by afucher** [comment]
That is the problem! Thanks @matfish2 ...

Can I send a PR creating a FAQ inside readme, putting this info?

**Comment by matfish2** [comment]
This info is already in the docs so I don't see a reason to repeat it.

**Comment by afucher** [comment]
I just think that the error is about a property record, and the doc refers to count.
So I think to put something like, if you have this warn, this is the cause...
But if you think that there is no reason, ok! :)
