### ISSUE TITLE
Add custom elements to header (right of search field)

### ISSUE THREAD

**Issue by haubix** [matfish2/vue-tables-2#117]
- Vue.js version: 2
- consumed using: webpack

Hello, is it possible to add custom HTML/Components to the right of the search bar?
I want to add buttons there to use the free space.

Thanks in advance

(code of search field below):
> < div class="VueTables VueTables--server">
>     < div class="row">
>         < div class="col-md-6">
>             < div class="form-group form-inline pull-left VueTables__search">
>                 < label for="VueTables__search_LTjxj"></label>
>                 < input type="text" value="" placeholder="Search" id="VueTables__search_LTjxj" class="form-control">
>             < /div>
>         < /div>
>     < div class="col-md-6"></div>
> < /div>

**Comment by matfish2** [comment]
As documented you can manipulate the original template by using the custom template option (4th argument in the `Use` statement)
