### ISSUE TITLE
2 server tables with different Templates and data in the same page. 

### ISSUE THREAD

**Issue by jmverges** [matfish2/vue-tables-2#118]
- Vue.js version: 0.4.54
- consumed using: (browserify/webpack/rollup)

Hi there, 

would you mind to create an example with 2 tables with different columns, templates and data on the same page?

Cheers.

**Comment by matfish2** [comment]
Where are you experiencing difficulty? You can create as many tables as you want. Simply pass different data and options to each table's props.
