### ISSUE TITLE
Template - Possibility to call 'child' function

### ISSUE THREAD

**Issue by inzanez** [matfish2/vue-tables-2#119]
Hi

I wanted to create an 'edit' link as a template column. Now I wondered if there was any possibility to call a function (in the 'parent' of the table I guess?) from within that template.

I tried to call a 'hello' method as follows for instance:

 ```
<template>
...
<v-client-table v-if="rules" :data="rules" :columns="columns" :options="options"></v-client-table>
...
</template>
<script>
...
...
  options: 
    {
      templates:
      {
        edit: function(h, row) {
          return (
            <span
             class={{ 'my-class-3': true }}
             style={{ cursor: 'pointer' }}
             on-click={ this.hello }
             >
             { row.id }
            </span>
          )
        }
      }
    },
    methods: {
      hello() {
        alert('hello')
      }
     }
...
</script>
```

But that doesn't seem to work. Is there a direct way, or would I need a single page component for instance emitting an event?...

**Comment by matfish2** [comment]
As documented the `this` context inside the template function refers to the parent instance. So the `hello` function should be available.
I think the reason it doesn't work has to do with jsx syntax. 

So instead of 
   `on-click={ this.hello }`
try
    `on-click={ this.hello.bind(this) }`
