### ISSUE TITLE
Reactivity of list filters.

### ISSUE THREAD

**Issue by Allexxander** [matfish2/vue-tables-2#12]
- Vue.js version: 2.0
- Consumed using: Webpack with Laravel's Elixir
- Server Table

Hi!

I've [forked](https://github.com/Allexxander/vue-tables-2) this repository in order to add some small features, but I've encountered a little problem.

Firstly, here is what I've added:

- 1. When receiving data from server, before, only `data` and `count` were populated. Now you can return a `custom_data` from the server too. You can access the `custom_data` property directly from the table component(e.g. using `$refs`). Returning `custom_data` on the server is **optional**. It's implemented for parsing table data along with custom data for personal things within 1 request (read further and you'll see a real life example).
- 2. When data is loaded from server, before only a `vue-tables.loaded` event was dispatched, now it also calls an **optional** table's parent callback method `loaded`. I believe this way is more comfortable for writing custom logic for each unique component, rather than using event listeners. Example:
```
Vue.component('something', {
	template: '<v-server-table :url="" :columns="" :options=""></v-server-table>',
	methods: {
		loaded: function (data) {
			// I will be called when the data in the table is loaded.
		},
	}
})
```
- 3. My main goal and the problem: 

I have a table with polls. A poll belongs to a category. Above the "category" column I need a dropdown filter with all the categories listed. 
<img width="1796" alt="screen shot 2016-10-27 at 19 51 21" src="https://cloud.githubusercontent.com/assets/7345874/19777243/f8f3931c-9c7f-11e6-9c27-d10bda23565d.png">
So I must somehow parse the polls and the available categories **within 1 request.**
In order to achieve this goal, my server is returning this data for example:
```
data : $polls,
count : 10,
custom_data : [ 'categories' : $categories ]
```
(Yes, that's why I implemented the feature mentioned in point 1)

Ok, so now my categories are available at `custom_data.categories`. I have to find a way to populate the dropdown filter with these categories.

In the template `list-filter.jsx` all the dropdown options are stored in a **local** variable called `options`. I replaced this **local** variable with a **global** variable so that I could access this data from outside the template.
This new variable is an array, keyed by table's column names, called `selectValues` and is stored in `opts`.  Example: ```THETABLE.opts.selectValues['category']``` will contain the dropdown values for the column `category`.
[See my commit.](https://github.com/Allexxander/vue-tables-2/commit/6103266653cfa4276c34ae58e377d818d14197fd#diff-e079d27d8df36227e9674bfa290335daR1)

And now, using the new callback method `loaded`(mentioned in point 2), I get the `categories` from `custom_data` (parsed from the server) and add them into this "global variable" from `list-filter.jsx`.
Example:
```
loaded: function (data) {
	var that = this;

	// Here we take each category and try to insert them into the dropdown.

	this.$refs.THETABLE.custom_data.subcategories.map(function(option) {
		that.$refs.THETABLE.opts.selectValues['category'].push(option)
	})	
}
```

The `selectValues['category']` updates and the dropdown from the screenshot is linked to this variable as well, HOWEVER the list filters are not reactive! The dropdown doesn't update.
Once the jsx has been compiled, you can't update it? (I'm not familiar with reactivity at all)

Do you have any ideas? I hope you understood the idea correctly, let me know if it's not clear.
P.S. If you think these small features are useful, I can do a pull request when the problem is solved. :) 
Looking forward to hearing from you, thanks in advance!

**Comment by matfish2** [comment]
This all seems rather convoluted. Why do you need to update the categories list in the first place? What is wrong with including all the categories in the list, regardless of the returned polls?

**Comment by Allexxander** [comment]
@matfish2 So I have to send a request to retrieve the categories first, then create the table component? I was thinking of retrieving the categories along with the polls so I don't have to double request.
Well, on the other side, the categories list will be re-parsed and re-populated each time I paginate/filter, which is not good ( :

**Comment by matfish2** [comment]
No need for an Ajax request. Why don't you send the categories from the server along with the initial response and assign them to a global JS variable? Jeffery Way has a great [package](https://github.com/laracasts/PHP-Vars-To-Js-Transformer) to streamline this.

**Comment by Allexxander** [comment]
@matfish2 I feel pretty dumb right now :) Sometimes the most simple things aren't seen. Thanks a lot!
