### ISSUE TITLE
How to use it with relations

### ISSUE THREAD

**Issue by ServerJunge** [matfish2/vue-tables-2#120]
- Vue.js version: Vue 2
- consumed using: Webpack

Maybe you can give an example of use with laravel for example? 

I return my users with a roles relation.

 $users = User::with('roles')->get();

I have no problem to show my user with name, email and so on. But how can I display the roles? 

Do you understand what I mean?

**Comment by matfish2** [comment]
The plugin does not know how to display an object, without your input. Use a template or a child row to convert the `roles` object to a string

**Comment by ServerJunge** [comment]
Can you give an example template?

**Comment by matfish2** [comment]
```html
 <v-client-table :data="entries" :columns="['id', 'name' ,'age', 'edit']">
      <template slot="roles" scope="props">
        <div>
           Name: {{props.roles.name}}
           Role: {{props.roles.role}}
        </div>
      </template>
    </v-client-table>
```
