### ISSUE TITLE
Model binding input element in vue-tables

### ISSUE THREAD

**Issue by vincent-lu** [matfish2/vue-tables-2#121]
- Vue.js version: 2.2.1
- Consumed using: webpack
- FULL error message (including stack trace): N/A
- Relevant code:

```javascript
<template>
    <div>
        <v-client-table ref="table" :data="products" :columns="columns" :options="options" @input="changed"></v-client-table>
    </div>
</template>

<script>
    const columns = [
        'id',
        'name'
    ];

    export default {
        data() {
            return {
                products: [
                    {id: 1, name: 'Phone'},
                    {id: 2, name: 'Computer'},
                    {id: 3, name: 'TV'}
                ],
                columns: [
                    'id',
                    'name'
                ],
                options: {
                    templates: {
                        name: (createElement, row) => {
                            const self = this;

                            return createElement('input', {
                                domProps: {
                                    value: row.name
                                },
                                on: {
                                    input: function (event) {
                                        row.name = event.target.value; // this doesn't update the products array
                                        self.$emit('input', event.target.value); // this line doesn't produce error, but changed() method doesn't get fired either.
                                    }
                                }
                            });
                        }
                    }
                }
            }
        },

        methods: {
            changed(value) {
                // this doesn't get fired
            }
        }
    }
</script>
```

- Steps for reproducing the issue:

I'm trying to replace the default value output in vue-tables cells to `<input>` tags with so not only the value is displayed in the `<input>` tag, when the value is updated in the field the model value gets updated.

However I'm not sure how to achieve the two-way update; although I can create the `<input>` element via createElement with proper event listeners. The code above is what I got so far.

Another issue I'm running into is I'm not able to sort or filter those columns with `<input>` field. Even if using custom sorting function for those columns.

Note: one of the main issues seem to be that self.$emit('input', event.target.value); is not reaching upwards. Although the key thing is how to achieve reactivity for input fields inside vue-tables.

Thanks for your time.

**Comment by matfish2** [comment]
See #101

**Comment by vincent-lu** [comment]
Hi @matfish2 again thanks.

Yeah I figured out a way to let template tag (in above example, the `<input>` tag in the `name` column) via vuex (which is not that different than global event bus). But for some tables I have a few thousands rows, so finding the updated row by id is not ideal.

The problem is it circumvents Vue's default model binding mechanism: because the the `self.$emit('input', event.target.value)` on `<input>` didn't get sent upwards to automatically update the `:value` for that row's column. (see https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events)

For example for a very basic Vue table below, change in input field `rrp` will automatically update the row `rrp` value in `list` array.

```js
<template>
    <table>
        <tr>
            <td v-for="column in columns">
                <a href="#" @click="sortBy(column)" class="column" onclick="return false">
                    {{ column }}
                </a>
            </td>
        </tr>
        <tbody>
        <tr v-for="product in list">
            <td>{{ product.sku }}</td>
            <td><input name="rrp" v-model="product.rrp"></td>
        </tr>
        </tbody>
    </table>
</template>

<script>
    export default {
        data() {
            return {
                list         : [
                    {sku: 'TV', rrp: 50 },
                    {sku: 'Phone', rrp: 60 }
                ],
                sortKey      : 'sku',
                reverse      : false,
                columns      : [
                    'sku',
                    'rrp'
                ]
            };
        },

        methods: {
            sortBy: function (sortKey) {
                this.reverse = (this.sortKey == sortKey) ? !this.reverse : false;
                this.sortKey = sortKey;
                this.list    = this.filteredList;
            }
        },

        computed: {
            filteredList () {
                if (this.reverse) {
                    return this.list.sort((a, b) => a[this.sortKey] > b[this.sortKey] ? 1 : -1);
                } else {
                    return this.list.sort((a, b) => a[this.sortKey] < b[this.sortKey] ? 1 : -1);
                }
            }
        }
    }
</script>
```

I guess this is because the `input` fields are cloned? Do you think there is a way to not clone the fields?

**Comment by matfish2** [comment]
A. I havn't figured out why the event is not propagated when using `this.$emit`. Any ideas are welcome.
B. The `input` fields are not cloned, but the data is, which results in no influence on the original set when you change to cloned value. Unfortunately I had to clone the data, otherwise filtering would reduce the size of the original set. Again you are welcome to fiddle with it and see if there is a better solution.
