### ISSUE TITLE
Client side sorting for numeric values

### ISSUE THREAD

**Issue by vincent-lu** [matfish2/vue-tables-2#122]
- Vue.js version: 2.2.1
- Consumed using: webpack
- FULL error message (including stack trace):
- Steps for reproducing the issue:

For client table, the default sorting by columns feature works fine for columns with alphabetic values. But when the columns are numeric, the default sorting seem to act somewhat weird: it seems to not able to differentiate `0` and empty/null. Also it put `10` next to `1` basically assuming they are strings not numbers.

A more difficult problem I ran into is when the column value is output via options.templates. For example if I have a column that outputs the sum of the other two columns:

```javascript
templates: {
    sum: (createElement, row) => {
        return row.number_one - row.number_two;
    }
}
```

When I try to sort the `sum` column, the sorted order doesn't seem to make any sense. But if I provide customSorting settings for the column, it does work again. But I will have to provide the similar customSorting settings for every single columns with custom template values.

```javascript
customSorting: {
    sum: function (ascending) {
        return function (a, b) {
            let lastA = parseFloat(a.number_one - a.number_two);
            let lastB = parseFloat(b.number_one - b.number_two);

            if (ascending) {
                return lastA <= lastB ? 1 : -1;
            }

            return lastA >= lastB ? 1 : -1;
        }
    }
}
```

Considering how common it'd be to have pure numeric columns, is there a way we can flag the sorting logic to treat whatever the template renders in that cell as floating number and sort them accordingly?

Thanks again.

**Comment by vincent-lu** [comment]
Raised a PR #127 for this issue.

**Comment by matfish2** [comment]
Numeric values are sorted as numbers if you pass the data as a number. E.g instead of 

```js
{age:'33'}
```

```js
{age:33}
```

As for sorting template data, the issue is that the template itself is only rendered at the end of the chain, after sorting already took place. So, at least for now, `customSorting` is the way to go.

**Comment by vincent-lu** [comment]
Thanks @matfish2 . I can confirm after casting the numeric column data from Laravel end the sorting works.

However the string columns, JS seems still convert empty string to null object and it confuses the sorting function. Changing `lib/methods/get-sort-fn.js:` line 8 and 9 to the code below seems to fix the issue. Can you advise whats the best solution here?

```
var aVal = a[column] == null ? '' : a[column];
var bVal = b[column] == null ? '' : b[column];
```

**Comment by matfish2** [comment]
`JS seems still convert empty string to null object 
`
I was not able to reproduce such a behaviour. See the `name` property in the following screenshot:

![sort](https://cloud.githubusercontent.com/assets/1510460/24322714/cd464f50-117a-11e7-99ae-5adb4ab48253.png)


 As a rule I don't interfere with the data the user passes. If he wants `null` or an empty string, it is his choice.

**Comment by vincent-lu** [comment]
Yeah you are right it's coming from the endpoint (although I'm having trouble pinpointing the place where the empty string to null conversion exactly happens).

On the other hand, what would be the expected behaviour when sorting a column with some rows with `null` value?

**Comment by matfish2** [comment]
I agree that `null` is a problematic value, and should therefore probably be avoided in general. However, if someone finds a reason to use it tomorrow I don't to force the data into something he didn't intend. So the best option IMHO is to make sure you pass sensible values, rather than relying on the package to somehow handle it.

**Comment by vincent-lu** [comment]
Thanks @matfish2, agreed.
