### ISSUE TITLE
where can I find the compiled standalone js file?

### ISSUE THREAD

**Issue by zhlc2008** [matfish2/vue-tables-2#123]
I want to import the standalone js file into HTML
where can I find the compiled one like vue-tables-2.min.js

**Comment by matfish2** [comment]
The is no precompiled version

**Comment by zhlc2008** [comment]
will it be precompiled in the future?

**Comment by matfish2** [comment]
Since I'm using an event bus, which is a plain instance of view, a precompiled version would inevitably result in vue loading twice: once by the package and once by the user. For that reason I am rather reluctant to provide a precompiled file.
