### ISSUE TITLE
Example on Using Vuex

### ISSUE THREAD

**Issue by alexflorea2** [matfish2/vue-tables-2#124]
- Vue.js version: 2.2.4
- consumed using: (browserify/webpack/rollup) : browserify
- FULL error message (including stack trace): cannot figure out how to use Vuex

How exactly can we use Vuex for showing messages on Loading / Loaded or any other states when using Server

for example, if using vuex and setting the store name to tableStore

```
<v-server-table url="/api/" name="tableStore" :columns="columns" :options="options"
                            ref="testTable"
                            v-bind:class="{ 'table--loading': isLoadingVuex }"
                            ></v-server-table>
```

then from docs added a tableStore.js  that contains:

```
const state = {
    table_loaded: false;
};

const getters = {
    isloading: (state) => {
        return state.table_loaded;
    }
};
const actions = {};
const mutations = {
   LOADED: (state, data) => {
        state.table_loaded = true;
    },

    LOADING: (state, data) => {
        state.table_loaded = false;
    },

};

export default {
    namespaced: true,
    state,
    getters,
    actions,
    mutations
}

```

then in app on computed

```
  computed:{
            isLoadingVuex() {
                return this.$store.getters['tableStore/isloading'];
            }
}

```

The computed property isLoadingVuex is always false, and only trigered(computed) once. If you browse through pages it does not update.

We did try setting up another store module for main app, and leave tableStore untouched. In Vuex dev tool we see the state gets populated there. But do not know how we can link mutations.

Eg in mainStore we tried adding but did not get triggered.

```
mutations:{
  ['tableStore/LOADED'] (state, data) {
    console.log('Table Loaded')
  }
}
```

**Comment by matfish2** [comment]
Using Chrome dev tools you can see exactly what mutations are being triggered. 
![vuex](https://cloud.githubusercontent.com/assets/1510460/24320582/2b7644ae-1149-11e7-9da6-5f2c81f81e1b.png)

Look there and make sure you are listening for the correct mutation

**Comment by alexflorea2** [comment]
Ok, thank you for the tip. I was not aware that we could subscribe toa  store and listen on it's mutations.

**Comment by amaixent** [comment]
Hi,
I'm trying to use vuex as well with a client table.
I see in the vue dev tool that a state module has been created with my table name.
How can I watch changes on this state module? Is there a getter somewhere or how can I create a getter to access these values? For example I would like to know when the page value changes.
Thank you :)

**Comment by matfish2** [comment]
The equivalent of events in vuex is _commits_. As you can read in the docs on the `Events` section, there are a few "empty" commits that you can hook into and respond accordingly. However, most commits are used by the package to update the state. E.g in case of pagination a `myTable\PAGINATE` commit is triggered (see `mutations.js`), which is used to update the state. The thing is, I don't know if you can latch into an existing commit and add functionality without discarding to original. If anyone has an idea I'm open to suggestions.

**Comment by amaixent** [comment]
I don't want commit a change and modify the state, I just want to know if the "page" value has changed. In vuex we can get the state values without modifying them thanks to the getters, and I was wondering if adding these getters to the store would be possible?
