### ISSUE TITLE
vue-image-grid-2 ?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#125]
I see that at some time you had a package named vue-image-grid-2 (which is still referenced on this page https://github.com/nivv/vue-image-grid)

I imagine you removed it because the same result could be achieved using vue-tables-2 ?

I've had lots of pleasant experiences using vue-tables-2 to display a normal table.. but I would like to display an actual grid now. Something like an imagewall (think masonry grid but without masonry auto-fitting behavior ) with each grid cell containing an image and a name. Of course building this from scratch using vue wouldn't be too difficult but I'm curious if there's a way to achieve this with vue-tables-2 ?

If so could you possibly provide a short example or explanation of how to do this?

Thanks!

**Comment by matfish2** [comment]
vue-image-grid-2 was never mine.

I don't quite understand what you mean by imagewall. Maybe send a link to an example.

**Comment by vesper8** [comment]
oh i see.. that's weird that he links to you then. well I meant something similar to https://github.com/MopTym/vue-waterfall.. where each "row" is contained within a square

this is another example https://kasuga.is/wp-content/uploads/2016/07/imagewall-2-1920x1080.jpg

basically i am asking if there's any way to have vue-tables-2 produce a layout that doesn't look quite like a table but more like a grid where each item can be contained within a div that stacks horizontally

**Comment by mosinve** [comment]
IMHO, vue-tables notsuitable for this task, it's a data table not layout.
Something similar you can do with Bootstrap's `cards-column` layout
http://v4-alpha.getbootstrap.com/components/card/#card-columns
or if you want to use Vue, there is library [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue), which implements Bootstrap components as Vue components.

**Comment by matfish2** [comment]
Yes. I agree with @mosinve
