### ISSUE TITLE
Sorting Template Row Data

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#126]
- Vue.js version: 2.2.1
- consumed using: webpack
- FULL error message (including stack trace): n/a (functionality)
- relevant code:
`<v-client-table :data="data" :columns="columns" :options="options">
<template slot="derivation" scope="props">
       <span>{{ props.row.something }} {{ props.row.somethingElse}}</span>
</template>
</v-client-table>`
- steps for reproducing the issue:
When sorting this table the slotted column will not sort, how can I achieve sorting?

**Comment by matfish2** [comment]
See #122
