### ISSUE TITLE
How to access $event from row-click

### ISSUE THREAD

**Issue by Mubeen-Inamdar** [matfish2/vue-tables-2#128]
- Vue.js version: 2.0.1
- consumed using: webpack
- FULL error message (including stack trace): N/A
- relevant code: N/A
- steps for reproducing the issue: N/A

Hi, brilliant package!

Got a questions: How do you access the $event object from a row-click event? It only seems to pass the payload (I want to check if a key was held down when the row was clicked).

Thanks.

**Comment by matfish2** [comment]
Unfortunately the event is not sent along. I could add it by sending an object containing the row and the event, but that would be a problem with backward compatibility. Unless you know a way of passing multiple parameters to Vue's `$emit` method.

**Comment by Mubeen-Inamdar** [comment]
Ahhh that's a shame. Is there anyway you could pass in an option decide if the event should be passed in the payload?

For example if you passed: `{passEvent: true}` into the component then the payload returns the event as well? This would work for backwards compatibility if this was set to `false` by default?

**Comment by matfish2** [comment]
I don't like the idea of bending the API to accommodate backward compatibility needs.
I will add the event and bump up the version to 0.5.0.
