### ISSUE TITLE
Update custom template values

### ISSUE THREAD

**Issue by vincent-lu** [matfish2/vue-tables-2#129]
- Vue.js version: 2.2.6
- Consumed using: webpack
- FULL error message (including stack trace): N/A
- Relevant code:

```js
<template>
    <v-client-table :columns="['id', 'price', 'double']" :data="data">
        <template slot="price" scope="props">
            <input type="text" v-model="props.row.price" @input="update(props)">
        </template>
        <template slot="double" scope="props">
            {{ props.row.price * 2 }}
        </template>
    </v-client-table>
</template>

<script>
    export default {
        data() {
            return {
                data: [
                    {id: 1, price: 100},
                    {id: 2, price: 250},
                    {id: 3, price: 150}
                ]
            }
        },

        methods: {
            // Direct update the data doesn't change numbers in the `double` column
            update(props) {
                this.data[props.index] = props.row; // using index instead id to locate the current row in data for demo
            },

            // If we use slice(0) to create a shadow copy, it works by updating the numbers in the `double` column
            update(props) {
                let data = this.data.slice(0);
                data[props.index] = props.row; // using index instead id to locate the current row in data for demo
                this.data = data;
            },
        }
    }
</script>
```

- Steps for reproducing the issue:

in the code above, in the first `update(props)` method, that changing the `data` directly won't change the values in `double` column. But if we use the second `update(props)` method it works if we create a shadow copy of the data array, update it, and assign it back to `this.data`.

Why `vue-tables-2` won't update itself when the `data` changes unless using the shadow copy method?

Also I noticed when the table is rather large, the delay for the table update is quite noticeable, when all we are updating here is just one cell (assuming no filtering/ordering etc)

**Comment by matfish2** [comment]
I don't think the update has to do with the shadow copy per se. I believe the reason is that you assign the whole dataset again rather than just replacing a single row. Anyway, this seems to be unrelated to the package, and has to do with vue's reactivity. In short, I don't know why it's not updating. 

As for the delay, I suppose it happens because you replace the entire dataset, rather than updating a specific row.

**Comment by vincent-lu** [comment]
Thanks @matfish2 ; closing this.
