### ISSUE TITLE
Initial page and filters

### ISSUE THREAD

**Issue by alexflorea2** [matfish2/vue-tables-2#133]
- Vue.js version: 2.2.4
- consumed using: browserify
- FULL error message: cannot set initial page and filters
- relevant code:
- steps for reproducing the issue:

Is there a way to setup initial page when using Server Component?
Tried from https://jsfiddle.net/matfish2/823jzuzc/embedded/result/ using  requestKeys

```
requestKeys:{
    page:3,
}
```
--- EDIT:: my bad here I misunderstood what requestKeys actually do, let you remap the names of params.

Q still remains, how can I initialize the table with filters and a page?

We use the table with a vue router. Each row has a View button that uses router to load a new component.
That one has a back button that again, uses router to go back to the table component.
When the table is mounted I want to be able to specify the page where it was and the filters it had.

If I use setPage and setFilters methods on mounted, it will do 3 request: 1 with initial setup, one with the page I mentioned in setPage and 1 with filters from setFilters

**Comment by matfish2** [comment]
Is there not keep-alive option on the router, that keeps the view state when you navigate between views?

**Comment by matfish2** [comment]
Solved with `saveState` (See #136)
