### ISSUE TITLE
Custom template for filter input?

### ISSUE THREAD

**Issue by zmkpr0** [matfish2/vue-tables-2#134]
- Vue.js version: 2.2.4
- consumed using: (browserify/webpack/rollup) webpack

Is there any way to set a custom template for filter input?

**Comment by mnlj** [comment]
Looking for the exact same thing! I'd like to restyle inputs and also add a filter reset above non-filterable "actions" column. Any ideas?

**Comment by zmkpr0** [comment]
One option I found is to create your own custom input next to your vue-tables-2 component and on keyup manually trigger table search. For server table its `v-on:keyup="$refs.table.serverSearch($event)"`;

Then you need to hide default filter input with 
`.VueTables__search {
  display: none; }`

And it works. 
I think methods section in readme should be updated, as from what i found there is no method called `setFilter`

**Comment by matfish2** [comment]
No custom template for filter input. Like @mnlj commented the best option is to use a custom template for the entire table. The filters are an integral part of the table and as such are laden with logic. IMHO, Opening it to free user manipulation presents a danger of breaking the code (The same is true for the table template, of course, which is an option I was reluctant to add, but at least there it is clear that it is a "hope you know what you're doing" kinda option).

**Comment by JackEdwardLyons** [comment]
I wish this didn't have to be such a hack
