### ISSUE TITLE
stateSave a table's propperties in localStorage

### ISSUE THREAD

**Issue by imade-nl** [matfish2/vue-tables-2#136]
Hello I'm wondering if it will be possible to save the state of a table in localStorage much like the stateSave option in Datatables (https://datatables.net/reference/option/stateSave). 
When I move back and forward between components the table always resets its self to the default state and forgets the ordering, page number, filtering, etc.
If column ordering and typing in the search box would emit events, like the pagination does, it would be easier to implement, but a native solution would be great! :)

**Comment by matfish2** [comment]
I suppose you are talking of routing using vue-router. Is there no option to keep the component alive when navigating between components?

**Comment by imade-nl** [comment]
Hi Matanya, thanks for your response!
In my current project I'm working with vue-router. So keep-alive could be a possible solution. Although I am concerned about performance when there will be 20 or so pages with lots of data. I will have to check how that works out. 
But beside SPA's I would also like to use vue-tables in single html pages where stateSave would be very welcome. (Trying to get rid of jquery :))

**Comment by zmkpr0** [comment]
I would also add, that there are situations when it would be required to keep table state even after leaving the page. In that case having params saved in localStorage would be very useful, or at least having an option to set initial params like ordering, page number, filtering.

**Comment by imade-nl** [comment]
Using keep-alive gives some extra unwanted challenges. I use the table for CRUD operations. When I edit a row (with an edit component) the changes are not reflected in the table when I return. With keep-alive the edit component also keeps showing the same row properties no matter what row I choose.

**Comment by matfish2** [comment]
See the new `stateSave` and `storage` options

**Comment by imade-nl** [comment]
Wow this is great! Thank you so much.
I have one issue though. Every time I visit the table a new record in the storage is being created (local and session). So I end up with a list of `vuetables_0sXAg, vuetables_Z3iug, vuetables_dA00i, etc` keys and the saved state isn't shown.
Maybe you know a way to solve this. Maybe the saveState option could in addition receive a string like `{ saveState: 'users' }` and the storage key would end up like `vuetables_users`.

**Comment by matfish2** [comment]
Sorry. I forgot to mention you should use the `name` prop when using the `saveState` option (same as when using `vuex`). Will add it to the docs.

**Comment by imade-nl** [comment]
Thanks again. It works great!
