### ISSUE TITLE
Option to hide pagination when not needed

### ISSUE THREAD

**Issue by SebastianS90** [matfish2/vue-tables-2#14]
How about the following feature:
* Assume we have `perPageValues = [10, 25, 50, 100]` (that is the default)
* If the unfiltered data contains `<= 50` records, then we do not show the `100` option in the select box.
* If the unfiltered data contains `<= 25` records, then
  * we no not show the limit select box at all
  * and the pagination arrows will be hidden (that is already the case)
  * and we do not show the sentence _Showing 1 to X out of X Records_ (that would be new)

Right now, small signle-paged tables (e.g. only one record) look somehow cluttered.

**Comment by matfish2** [comment]
Good idea. 
I do think that a single page table (whether by filtering or not) should still show how many records are displayed, but in a shorter form, such as "X Records". This specific change would be implemented on the pagination plugin.

**Comment by SebastianS90** [comment]
Good point with changing the text. One more addition: we could add the unfiltered total when a filter is applied, i.e. _Showing 25 to 50 out of 75 records (filtered from 278 total records)_
But only when a filter is applied.

**Comment by matfish2** [comment]
Dunno. 
Seems a bit cumbersome and long. 
Also means that on the server component one will have to pass the total count before filtering in addition to to count after filtering. I think I'll pass on this one.

**Comment by SebastianS90** [comment]
Thanks for your feedback. All ideas from this issue, except for the last one you didn't like, have been implemented in the pull requests #15, #16 and matfish2/vue-pagination-2#2.
Let me know if I should revise something, otherwise you can merge them and close this issue.
