### ISSUE TITLE
Template return is text and not html

### ISSUE THREAD

**Issue by gergo2007** [matfish2/vue-tables-2#140]
- Vue.js version: 2.2.0
- consumed using: (browserify/webpack/rollup) webpack 2.1.0
- FULL error message (including stack trace):
- relevant code:

```

$(document).ready(function() {
    new Vue({
        el: "#contact-messages",
        data: {
            columns: ['id', 'name', 'email', 'is_read', 'is_starred', 'created_at', 'open'],

            options: {
                filterable: ['id', 'name', 'email', 'created_at'],
                sortable: ['id', 'name', 'email', 'is_read', 'is_starred', 'created_at'],
                dateColumns: ['created_at'],
                templates: {
                    is_starred:function(h,row) {
                        if(row.is_starred) return `<i class="fa fa-star" aria-hidden="true"></i>`;
                    }
                }
            }
        }
    });
```

- steps for reproducing the issue:

The font awesome icon is displayed as text and not html:

http://prntscr.com/ewwgna

**Comment by matfish2** [comment]
AS DOCUMENTED, When using templates as functions you should return a virtual node, not HTML text. You can use JSX to make the syntax more HTML-like, or opt for the other options to use templates.
