### ISSUE TITLE
How to use Custom Filters

### ISSUE THREAD

**Issue by kubacode** [matfish2/vue-tables-2#141]
Hi There,

I'm after some help using Custom Filters. I have some nested data that I want to filter on when using the 'global' search on a table. I was expecting the customFilters option to work in a similar way to the customSorting option, but it doesn't appear that this is the case.

This is the code that I've been working with:

```
new Vue({
	el: '#app',
	data: {
		columns: ['bu', 'name', 'channel', 'state', 'actions'],
		tableData: [
			{
				id: 1,
				bu: "BU 1",
				name: "Business Unit 1",
				channel: {
					id: 1,
					name: "Channel Name 1",
				},
				state: {
					id: 1,
					name: "State Name 1",
				},
			},
			{
				id: 2,
				bu: "BU 2",
				name: "Business Unit 2",
				channel: {
					id: 2,
					name: "Channel Name 2",
				},
				state: {
					id: 2,
					name: "State Name 2",
				},
			},
		],
		options: {
			customSorting: {
				channel: function(ascending) {
					return function (a, b) {
						return this.app.sort(a.channel.name, b.channel.name, ascending);
					}
				},
				state: function(ascending) {
					return function (a, b) {
						return this.app.sort(a.state.name, b.state.name, ascending);
					}
				}
			},
			customFilters: [
				{
					name:'channel',
					callback: function(row, query) {
						return row.channel.name.indexOf(query) > -1;
					}
				}
			]
		}
	},
	methods: {
		sort(a, b, ascending) {
			if (typeof a === 'string') a = a.toLowerCase();
			if (typeof b === 'string') b = b.toLowerCase();

			if (ascending) return a >= b ? 1 : -1;

			return b >= a ? 1 : -1;
		}
	}
});
```

I was expecting that when a query is entered into the search box, the 'channel' custom filter would be used to filter the 'channel' column, however it does not appear that this is the case. The only way I can get this filter to apply is to set ```initFilters: {channel: 'Channel Name 1'}```, however this filter is then always applied and is not able to be updated.

Any guidance on how to get customer filtering working as I expect would be appreciated!

**Comment by matfish2** [comment]
AS DOCUMENTED, custom filters don't use the native search box\es. It responds to an event you emit. E.g, using the event bus:

```js
Event.$emit('vue-tables.filter::channel', query);
```
