### ISSUE TITLE
add id to the row (tr)

### ISSUE THREAD

**Issue by SuperMedo** [matfish2/vue-tables-2#143]
- Vue.js version:
 2.2.6
- consumed using: (browserify/webpack/rollup)
 Webpack
- relevant code:
`  <tr id="1">`

Sorry if it already exists, I searched and read the docs aside from uniqueKey & trackBy, it seems I can't add id to a row so I can dynamically add css class to it for example

**Comment by matfish2** [comment]
Check out the `rowClassCallback`option in the options API
