### ISSUE TITLE
Template, JSX - Call function referencing to 'row'

### ISSUE THREAD

**Issue by inzanez** [matfish2/vue-tables-2#145]
Hi

I'm using VueJs 2. I'm trying to create a column template that shows a radio button for each row (which is working fine). I finally want to emit an event using my global Event instance and attach a property of 'row' to that event.

I'm currently playing with the following code (where I don't emit an event but log to console):
```
templates:
{
    selection: function(h, row)
      {
         return <span><input type="radio" name="document" value={row.id} onclick={console.log(row)}/></span>
       }
},
```
I tried different variations of that 'onclick' event. Either I receive a "row not defined" error in the console, or (as it is the case for the code above) the 'onclick' event is executed on page load but never again when I click a radio button...

Is what I'm trying to achieve here possible within a template definition somehow? Or do I have to chose a different route,...?

Kind regards

**Comment by matfish2** [comment]
In your template, bind a function rather than calling it:

```jsx
<span on-click={this.doSomething.bind(this,row)}></span>
```

Define the method on your instance:

```js
methods:{
  doSomething(row) {
     console.log(row)
    }
}
```

**Comment by inzanez** [comment]
Thanks for the answer. What I'm wondering though: I now defined the method on the vue-instance. Like that, the method is not "part" of the component I was developing, but it's part of the instance. So I guess there's no way to reference the 'parent' component directly in this case...

**Comment by inzanez** [comment]
Ok, just if somebody else is trying to do something similar in future:
As I have an "Event" Vue instance, I didn't have to define any method in the root instance.

I just used:
`<span><input type="radio" name="test" on-click={this.$emit.bind(Event,'selected', row)}/></span>`

and that does the trick.

Many thanks @matfish2 for the help, I'm starting to see through things,....:-)
