### ISSUE TITLE
Custom pagination template

### ISSUE THREAD

**Issue by yosokus** [matfish2/vue-tables-2#146]
Hi, first let me start by saying this is a wonderful script. Its easy to use and its very flexible
Im able to override the table template with a custom one, but can I do the same for the pagination?

**Comment by matfish2** [comment]
The pagination component is a different package, so you cannot override the template unless you fork it.

**Comment by kennethllamasares** [comment]
Hi i would like to ask how can you use the forked pagination instead of the default pagination?

**Comment by vesper8** [comment]
I would also like to know how we can use a custom pagination template. The default one is not very mobile responsive when you have a lot of pages as it shows too many pages.
