### ISSUE TITLE
Server Tables Pagination Does Nothing

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#147]
The server tables pagination does not do anything when clicked. There isn't an AJAX request or a mutation for Vuex.
I can see that a "vue-pagination" event is emitted but that is all.

**Comment by scs-ben** [comment]
Sorry for posting in wrong repo, thanks for cleaning that up.

**Comment by matfish2** [comment]
I was only able to reproduce it by using `v-if` on the component, and toggling it off and on. Is that your use case?

**Comment by scs-ben** [comment]
I had a v-if a few levels up, I removed it but am still not seeing the mutations fire for Vuex.

I'm using vue-router.

The other events are working (search, sort, displayed records); just not pagination.

**Comment by scs-ben** [comment]
Here's the code part of my .vue file:
`<template>
    <div class="box box-solid">
        <div class="box-body">
            <div>
                <v-server-table ref="account" name="account" :columns="columns" url="/accounts/table" :options="options">
                    
                    <template slot="name" scope="props">
                            {{ props.row.name }}
                    </template>

                    <template slot="search_address" scope="props">
                        <address>
                            <span v-if="props.row.street_1 != null">
                                {{ props.row.street_1 }}<br />
                            </span>
                            <span v-if="props.row.street_2 != null">
                                {{ props.row.street_2 }}<br />
                            </span>
                            <span v-if="props.row.street_3 != null">
                                {{ props.row.street_3 }}<br />
                            </span>
                            <span v-if="props.row.city != null">
                                {{ props.row.city }}, 
                            </span>
                            <span v-if="props.row.state != null">
                                {{ props.row.state }} 
                            </span>
                            <span v-if="props.row.zip != null">
                                {{ props.row.zip }} 
                            </span>
                        </address>
                    </template>

                    <template slot="search_contact" scope="props">
                        <address>
                            <span v-if="props.row.phone != null">
                                Phone: {{ props.row.phone_format }} 
                                <a :href="'tel:' + props.row.phone" class="btn btn-primary btn-xs"><i class="fa fa-phone"></i></a>
                                <br />
                            </span>
                            <span v-if="props.row.fax != null">
                                Fax: {{ props.row.fax_format }} 
                                <br />
                            </span>
                            <span v-if="props.row.web != null">
                                Web: <a :href="props.row.web_format" target="_blank">{{ props.row.web }}</a>
                            </span>
                        </address>
                    </template>

                </v-server-table>

            </div>
        </div>
    </div>
</template>`

**Comment by matfish2** [comment]
You said you see a "vue-pagination" event emitted. However, this event should not be emitted if you are using Vuex. Are you using another table (client or server) on this page which does NOT use vuex?

**Comment by scs-ben** [comment]
This is the only table on this page. I am using client tables in other places and those aren't set up to use vuex. Here is my instanciation code:
`import {ServerTable, ClientTable, Event} from 'vue-tables-2';

/* Vue Tables 2 */
window.Vue.use(ClientTable);
window.Vue.use(ServerTable, null, true);`

**Comment by matfish2** [comment]
Ok. I think I know what the problem is. Can you temporarily disable the client tables by commenting out the use statement? I suspect there is an isolation problem.

**Comment by scs-ben** [comment]
Removing the client table does resolve the issue.

**Comment by scs-ben** [comment]
How can I "locally" load the client table?

**Comment by matfish2** [comment]
The problem is the the component pagination is declared globally, which means it is registered twice if you use both the client and the server component on the same page. If one is using vuex and the other does not, the first one seems to take precedence.
 
I will see if I can make it local, even though that will require quite a through change, because local components are not registered with a use statement, so the vuex param will become a prop, and rather than merging the correct state management methods, a run-time conditional or some sort of polymorphism will be used.

**Comment by scs-ben** [comment]
I put the ClientTable second and they are both working

**Comment by matfish2** [comment]
Great! And odd... Anyway, I will look into making the pagination component local. Declaring a global component twice is not a good idea.

**Comment by Mandy27** [comment]
I am having a similar issue where I am having a page with server table and another server table in a Modal.  The server table pagination in the Modal doesn't do anything.
