### ISSUE TITLE
Server Table Vuex

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#148]
I'm using vue-router and vuex, I'd like to leverage my persistent vuex state and not reload the data when the page loads again. Is there a way that I can stop the server load in certain cases?

**Comment by scs-ben** [comment]
Can you explain the "cache" option?

**Comment by matfish2** [comment]
I believe vue-router has a keep-alive option that prevents the state from being destroyed when navigating away. 

The cache option was added in one of the PR's, and I'm not sure what it is about, or if it has any reference in the code aside from the option itself.

**Comment by matfish2** [comment]
See the new `saveState` and `storage` options
