### ISSUE TITLE
Loading relations in Collection (server side)

### ISSUE THREAD

**Issue by ixperiencenl** [matfish2/vue-tables-2#151]
- Vue.js version: 2.1.0
- Laravel 5.4.22 
- Server Side implementation (as provided by you)

I'm using a lot of related models when getting data.

Question is:
_How to correctly load (and filter) related tables with a collection? Or is this even possible this way?_

**Comment by matfish2** [comment]
The server-side implementation is more of a basic example how to go about retrieving the data in the correct format. You can alter it to your needs. I suppose when you say related models you mean _eager loading_. The table doesn't natively support presenting hierarchical data, but you can use `templates` to "flatten" objects by turning them into strings.

**Comment by ixperiencenl** [comment]
Allright, yeah I understand that it's a basic example. I'll put something together and post it here for anyone who might be interested. Your package is very useful once you get all the ins and outs. Thanks!
