### ISSUE TITLE
Allow the user to set new labels form table headers (columns)

### ISSUE THREAD

**Issue by Frondor** [matfish2/vue-tables-2#152]
Let's say I don't want to use the column names in my DB. If I'm using a third party API and I can't modify the column names, I'd need to parse the whole list of records to "normalize" the property names so instead of `{"qty": 2}` I need to make it like `{"quantity": 2}`.

![](https://i.gyazo.com/eb5d42577c312c8091febf119d02e68d.png)

I'm proposing another way to set up the columns beside of `['id', 'name', 'qty']`, also with objects like
`[id, 'name', {"qty": "quantity"}]` (the value is now the label)
or even use a notation like `[id, 'name', 'qty,quantity'}]` where `column.split(',')[1]` is the label if defined.

**Comment by matfish2** [comment]
What is wrong with using the `headings` option to set the titles?

**Comment by Frondor** [comment]
My apologizes, I wasn't aware of that option. :weary:
