### ISSUE TITLE
No supported ajax library was found.

### ISSUE THREAD

**Issue by xushaocong** [matfish2/vue-tables-2#153]
I import the `axios` in the `main.js`
but when I use the `v-server-table` 
console print `[Vue warn]: Error in created hook: "vue-tables: No supported ajax library was found. (jQuery, axios or vue-resource)"`
who can tell me what's wrong? thx!

**Comment by matfish2** [comment]
You need to make axios a _global_ variable so that it is accessible to the package.
```js
window.axios = require('axios');
```

**Comment by xushaocong** [comment]
@matfish2 it works. thx very much!

**Comment by xushaocong** [comment]
@matfish2 thx!
