### ISSUE TITLE
serverTable custom params

### ISSUE THREAD

**Issue by xushaocong** [matfish2/vue-tables-2#154]
I use the serverTable and have some problem.
when I turn to page2, it send the `{page: 2, ascending: 1}`, how can i set the request params `{page: 10, ascending: true}`, and there are some params useless such as `byColumn`, how can i delete it.

**Comment by matfish2** [comment]
The request params are decided by the package. You shouldn't have to meddle with them at all. On the server side use whatever params are relevant in your case, and simply ignore the others.

**Comment by xushaocong** [comment]
Sry. I dont really understand. 
![image](https://cloud.githubusercontent.com/assets/22735791/25978958/2f569388-36f8-11e7-8df7-2f5a0ba689c5.png)
I hope that when i turn to page one, the `start: 0`. when i turn to page 2, the `start: 10`. when i sort the table, the `sortAasc` must be `true` or `false`. How can i write. thx!

**Comment by matfish2** [comment]
There is only so much I can do to accommodate for foreign non-alterable API's. 
If you need to change the request *values*, and not just the request *keys*, I suggest you fork the repo and adjust it to your needs.
