### ISSUE TITLE
Question: How to query joined tables

### ISSUE THREAD

**Issue by ixperiencenl** [matfish2/vue-tables-2#159]
I would like to know how we can filter on joining tables.

Example:
Users -> Posts
Get me posts with title 'test'

Thanks a lot!

**Comment by CoolGoose** [comment]
@ixperiencenl that looks more like a backed implementation issue than a Vue tables.
If we are talking strictly about the eloquent server response it needs custom code for returning the relations

**Comment by matfish2** [comment]
I agree with @CoolGoose

**Comment by ixperiencenl** [comment]
For anyone interested, I added a filter on the` $field` parameter in the filter function:

`$field = stripos($field, " AS ") !== false ? substr($field, 0, stripos($field, " AS")) : $field;`
Now, aliased columns (needed in joined tables sometimes) can also be safely searched without a problem.
