### ISSUE TITLE
Option to change icons

### ISSUE THREAD

**Issue by ramakrishnamundru** [matfish2/vue-tables-2#161]
As bootstrap 4 is shipping with out glyphicons it would be a good thing to allow user to set the icons they use, like fontawesome etc..

**Comment by ramakrishnamundru** [comment]
Sorry, Just overridden the options.

**Comment by mandersondesign** [comment]
@ramakrishnamundru can you share your solution to this? Still looking to figure this out.

**Comment by ramakrishnamundru** [comment]
@mandersondesign Its been a long time since this issue is posted and my solution might not work now. Currently this component seems to support a theme option and also seem to support bootstrap-4. you can try that.

**Comment by spacewaffle** [comment]
Switching to bootstrap 4 in the theme options did not fix this for me. It was still using the old bs3 icon classes. For folks coming here in the future, you can fix this by following the instructions here:
https://matanya.gitbook.io/vue-tables-2/custom-template#font-awesome-sort-icon
