### ISSUE TITLE
Feature Request:  Slots for Custom Component Above Headings

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#165]
We want to be able to add a bulk "filter" to show or hide table options that are "active" or "inactive" (or to show records based on a list of criteria). How could we add a dropdown by the filter search box to accomplish this for both server and client side tables?

**Comment by matfish2** [comment]
You can add your own filters using the `customFilters` option but the UI is external to the table.
If you want to modify the template itself you can use a custom template. I am not inclined to introduce changes to the template only to tailor it for a rather specific need.
