### ISSUE TITLE
v-server-table attempting to generate table before getting data from server

### ISSUE THREAD

**Issue by ericdude4** [matfish2/vue-tables-2#166]
- Vue.js version: 2.3.3
- consumed using: webpack
- FULL error message (including stack trace):
```
[Vue warn]: Error in render function: "TypeError: Cannot read property 'map' of undefined"

found in

---> <ServerTable>
       <Loadlist> at /home/vagrant/Code/all-source/resources/assets/js/components/LoadList.vue
         <Root>
```
```
load.js:27279 TypeError: Cannot read property 'map' of undefined
    at module.exports (load.js:66786)
    at Proxy.<anonymous> (load.js:60157)
    at VueComponent.Vue._render (load.js:30659)
    at VueComponent.updateComponent (load.js:29195)
    at Watcher.get (load.js:29534)
    at Watcher.run (load.js:29604)
    at flushSchedulerQueue (load.js:29371)
    at Array.<anonymous> (load.js:27411)
    at nextTickHandler (load.js:27358)
    at <anonymous>
```
- relevant code:
```
<template>
    <div>
        <v-server-table url="/loads/getTableData" :columns="columns" :options="options"></v-server-table>
    </div>
</template>

<script>
    import {ServerTable, Event} from 'vue-tables-2';
    import items from './items'
    window.Vue.use(ServerTable)
    export default {
        data () {
            return {
                columns: ['work_order_id','customer_order_number','company_name', 'items'],
                options: {
                    headings: {
                        id: 'Work Order No.'
                    },
                    templates: {
                        items
                    }
                }
            }
        },
        mounted() {
            console.log('Loads List Component mounted.')
        }
    }
</script>
```
Works perfectly if I use a v-client-table. I have confirmed that the data URL works and retrieves data. Is there anything I am missing here?

**Comment by matfish2** [comment]
I cannot reproduce this. Since the server component depends on the response from the server I can only assume that the response doesn't match the expected format. Can you take a screenshot of the response (in the Network tab)?

**Comment by ericdude4** [comment]
We decided to use the client table as it seems to work fine for our purposes. I will create a branch on my repo and test this with a v-server-table soon and get back to you.

**Comment by juljupy** [comment]
Hi, I was getting the same issue when I returned just one array from the server: 

[{"id":1,"name":"Value"},{"id":2,"name":"Value"}].

Debugging the set-data method it waits for a structure like this:

{"data":[{"id":1,"name":"Value"},{"id":2,"name":"Value"}],"count":2}.

Then It works for me.  Hope it helps.
