### ISSUE TITLE
Question - Use without pagination

### ISSUE THREAD

**Issue by bmfteixeira** [matfish2/vue-tables-2#167]
- Vue.js version: 2.2.2
- consumed using: Webpack

QUESTION! :)

Any way to use vue-tables-2 without pagination?

**Comment by matfish2** [comment]
Pagination isn't shown when the number of records fits into one page. You can control the number of records per page using the `perPage` option.
Otherwise, why would you want no pagination? How is the user supposed to paginate?

**Comment by bmfteixeira** [comment]
@matfish2 This could easily implemented by setting a parameter to false. No pagination tables can be used depending on the context. Sometimes you can try to ignore pagination and just implement, for example, infinite scroll with dynamic load of content.

**Comment by kolesoffac** [comment]
@bmfteixeira ,
hi, do you implement  infinite scroll?

**Comment by bmfteixeira** [comment]
@kolesoffac I'm now using other lib as this one lacks some features that I can easily find in others.
