### ISSUE TITLE
server side table: custom queries in request

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#168]
- Vue.js version: 2.2.1
- consumed using: webpack

hi @matfish2 , first of all you've done a great work, thanks for this component, it really saved a lot of time for me. i have two questions:
1) what is the difference between `orderBy` and `byColumn` parameters? ![](http://joxi.ru/823LbReC66b8YA.jpg) 
2) is there any way to pass special GET-params (component not depends on them) to the table query in v-server-table?

**Comment by matfish2** [comment]
1. `orderBy`: which column should be used to sort the results. `byColumn`: a boolean parameter designating whether you are using a single filter for all columns, or a different filter for each column (see the `filterByColumn` option) 
2. Yes. A. the `params` option allows you to pass additional parameters to the request. B. the `customFilters` option allows you to pass your own filters using an event bus.

**Comment by VladZen** [comment]
@matfish2 thanks a lot!

**Comment by VladZen** [comment]
@matfish2 i have another question: is there any way to emit several filters at one moment? I see there is way using bus event, but it supposed to refresh table every time i make changes in each filter. what if i need to customize several filters and send response only after I make changes?

**Comment by matfish2** [comment]
Under `Methods`:

`setFilter(query)` - query should be a string, or an object if `filterByColumn` is set to true.
