### ISSUE TITLE
Row click event is not defined

### ISSUE THREAD

**Issue by Manrix** [matfish2/vue-tables-2#170]
- Vue.js version: 2.3.3
- consumed using: webpack2
- FULL error message (including stack trace): ReferenceError: event is not defined

Hi. I've a server table with listening for events with:
`@loading="onLoading" @loaded="onLoaded" @error="onError" @row-click="onTest"`
All events work except row click. When i click on a row i get _ReferenceError: event is not defined_.

**Comment by suenot** [comment]
I have the same bug, but only in Firefox.

**Comment by gjamot** [comment]
Any news about this bug on Firefox. I am actually facing the same issue :(

**Comment by matfish2** [comment]
Until I figure this out you can use the event bus.

```js
Event.$on('row-click', (data)=>{

});
``

**Comment by gjamot** [comment]
Thank you for the fix in the new release !!!
