### ISSUE TITLE
How to add "check/uncheck all" functionality to header

### ISSUE THREAD

**Issue by cihadturhan** [matfish2/vue-tables-2#171]
- Vue.js version: 2.2.6
- consumed using: browserify
- FULL error message (including stack trace):
I need to add a custom functionality that user can check/uncheck and delete all rows from the header. However, I realized there is no way to access datatable properties when defining `headings` template e.g.
```js
headings: {
    ...
    delete: function(h){
        return (<div>
                    <input type="checkbox" v-model="allChecked" @click="toggleCheckAll">
                    <button title="Delete all keywords">Delete</button>
                </div>);
    },
}
```
Is there any way that I can provide a data flow for `allChecked` and `toggleCheckAll` from data-table to its header?

Last but foremost, I realized that I can't define a slot for header. Slots work only for rows? If using slots for headings is made possible, that would also resolve my issue. 

Thanks for the plugin

**Comment by matfish2** [comment]
I've updated the package to make the `this` context inside the function refer to the direct parent of the table instance.

**Comment by danielok1303** [comment]
Hello @cihadturhan how did you solve this problem?
