### ISSUE TITLE
server table, filters and page are lost when using $refs.table.refresh()

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#174]
I don't know if this is a bug or simply the way it is, but I would like to overcome this behaviour.

Right now I have a on/off toggle on each row and when I activate it, it updates on the server side and then causes multiple tables to be refreshed. However I noticed that if I hit while I'm on page 2 for example it resets to page 1. Same thing with sorting or other custom filters.

What would be the best strategy to save all filters before the refresh and then re-apply them.

Or is there perhaps a built-in way to achieving this? Like a save-filters / load-filters mechanism?

**Comment by matfish2** [comment]
Call `getData()` instead. That would retrieve the data without resetting the state.

**Comment by vesper8** [comment]
thanks! works perfectly

**Comment by yuugou727** [comment]
I found this useful while using server table.
Is there any reason that `getData()` method isn't in document?
