### ISSUE TITLE
I18n ?

### ISSUE THREAD

**Issue by ReynerHL** [matfish2/vue-tables-2#175]
First of all, congratulations, this is a great project!
I'm not reporting an error, I just want to now if there is any way for putting some i18n to the resultant table (Spanish, French....).

Thanks in advance for your attention.

**Comment by matfish2** [comment]
You can pass a translation function of your own to the `headings` and `texts` options, rather than hard-coded strings.

**Comment by molerat619** [comment]
@matfish2 we are doing that right in the headings, and he shows the right translation. But once the language is changed, the heading translations don't update. Everything else is translated correctly. If we do it in a heading-slot template it will also work.

Does not update
```headings: { test: this.$t("my_key") }```

Updates:
```<span slot="test">{{ $t("my_key) }}</span```

**Comment by molerat619** [comment]
I have fixed it following this issue: https://github.com/matfish2/vue-tables-2/issues/315

```
headings: { 
   test: () => this.$t("my_key") 
}
``` 

That worked fine (minor improvement using es6 style functions)

**Comment by sebastian-raubach** [comment]
Could anyone post an example for the `texts` option? This isn't working:

```
const tableOptions = {
  texts: {
    count: function () { return i18n.t('paginationCount') },
    first: function () { return i18n.t('paginationFirst') },
    last: function () { return i18n.t('paginationLast') },
    filter: function () { return i18n.t('paginationFilter') },
    filterPlaceholder: function () { return i18n.t('paginationFilterPlaceholder') },
    limit: function () { return i18n.t('paginationLimit') },
    page: function () { return i18n.t('paginationPage') },
    noResults: function () { return i18n.t('paginationNoResult') },
    filterBy: function () { return i18n.t('paginationFilterBy') },
    loading: function () { return i18n.t('paginationLoading') },
    defaultOption: function () { return i18n.t('paginationDefaultOption') },
    columns: function () { return i18n.t('paginationColumns') }
  }
}
```

Throws this error: `TypeError: this.opts.texts.count.split is not a function`.

I get the text to show up without the function, but it doesn't change when the locale changes, hence the method approach.

**Comment by sebastian-raubach** [comment]
Ok, I solved it by defining a base class called `I18nTable` that has a `options.texts` property that gets updated when the locale is changed in the UI. All other tables extend this base class and also have an `options` object, but don't set the `texts` property. This now updates the text correctly.

**Comment by Nosnickers** [comment]
Same error : `Throws this error: TypeError: this.opts.texts.count.split is not a function.`

Then, I change options to computed props:
`
computed: {
    editorOptions() {
      const options = Object.assign({}, defaultOptions, this.options);
      options.texts = {
        count: this.$t('table.count'),
      };
      return options;
    }
  },
`
It works.
