### ISSUE TITLE
Docs GH Pages

### ISSUE THREAD

**Issue by CoolGoose** [matfish2/vue-tables-2#176]
Hi @matfish2 

I've started an initial cleanup of sorts of the documentation at https://coolgoose.github.io/vue-tables-2-docs
Excluding the cleanup that I still need to do on the options is there something that you would like to see changed ?

**Comment by matfish2** [comment]
Thanks! It looks great. 

Just one thing: you can remove the Issues Policy link from the "table of contents" as it no longer exists.

**Comment by CoolGoose** [comment]
@matfish2 removing that and cleaning up the options section most likely today.
Can you create a gh-pages branch please ?

**Comment by matfish2** [comment]
What for? Isn't the plan to replace the README on the master branch?

**Comment by CoolGoose** [comment]
@matfish2 I was thinking on actually publish it like a github page.  If not I'm fine with just replacing the readme 👍

**Comment by matfish2** [comment]
I don't see a reason for redundancy. Your version is better, so let's use
it instead. Send a PR when you are done

**Comment by CoolGoose** [comment]
@matfish2 pull #177 is up. I've renamed the readme to README for consistency.

**Comment by matfish2** [comment]
Merged. Thanks again.
