### ISSUE TITLE
How to remove the whole search function

### ISSUE THREAD

**Issue by dhdmstjs** [matfish2/vue-tables-2#182]
I want to remove this whole search function, but can't find how to.
<img width="220" alt="screen shot 2017-06-13 at 4 05 51 pm" src="https://user-images.githubusercontent.com/24529218/27072208-403b2a38-5052-11e7-8b0f-5bee816b2be2.png">

**Comment by dhdmstjs** [comment]
or how could I edit it so instead of being on the top of the page, above the datatable, it is below it?

**Comment by CoolGoose** [comment]
@dhdmstjs set filterable: false as per the docs (Set to false or an empty array to hide the filter(s))

**Comment by dhdmstjs** [comment]
is there a way to move the filter to the bottom of the datatable?

**Comment by CoolGoose** [comment]
@dhdmstjs there's currently no option of moving elements around although i guess @matfish2 would appreciate a contribution in that regard.

The template can be checked looking at https://github.com/matfish2/vue-tables-2/blob/master/compiled/template.js
