### ISSUE TITLE
perform scrolling whenever pagination is used.. is there an event?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#184]
I want to scroll back to the top whenever the pagination is clicked on, whether it's a page number or using the arrows.

I'm using some jquery right now and have got it semi-working but it's being inconsistent for some reason.. would have been much easier if there was an event triggered whenever the pagination is handled. I'm using server-side tables by the way. Is there such an event, or can you recommend a way?

Thanks!

**Comment by CoolGoose** [comment]
hi @vesper8 
Didn't had the chance to test yet, but if you look at https://github.com/matfish2/vue-tables-2/blob/master/lib/state/mutations.js you'll see that there's an PAGINATE event that might do the trick

**Comment by matfish2** [comment]
There are pagination events for both "normal" and vuex (the PAGINATE commit that @CoolGoose mentioned) use-cases. However, those events are already handled by the package. I suppose I can fire a different event\commit whenever pagination occurs. Will think about it.

**Comment by matfish2** [comment]
I've add a "pagination" event. See README file for details.
