### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by afuno** [matfish2/vue-tables-2#185]
people.vue:

```vue
<template lang="html">
  <div id="people">
    <client-table :data="tableData" :columns="columns" :options="options"></client-table>
  </div>
</template>

<script>
import {ClientTable} from 'vue-tables-2'

export default {
  props: [],
  data() {
    return {
      columns: ['id','name','age'],
      tableData: [
          {id:1, name:"John",age:"20"},
          {id:2, name:"Jane",age:"24"},
          {id:3, name:"Susan",age:"16"},
          {id:4, name:"Chris",age:"55"},
          {id:5, name:"Dan",age:"40"}
      ],
      options: {
          // see the options API
      }
    }
  },
  components: {
    ClientTable
  }
}
</script>
```

Because of this I get an error:

> [Vue warn]: Failed to mount component: template or render function not defined.
> found in `<ClientTable>`

How to use your component?

**Comment by afuno** [comment]
The error is saved with this code:

```js
import Vue from 'vue/dist/vue.esm'
import {ServerTable, ClientTable, Event} from 'vue-tables-2'

Vue.use(ServerTable)
```

**Comment by CoolGoose** [comment]
@afuno seems like a vue initialization issue similar to https://github.com/vuejs/vue-router/issues/713#issuecomment-250966053

Please check https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

**Comment by lurein** [comment]
I had this problem, just a note for people still looking:
vue-tables-2 is a plugin, so we can't register it as an component. To get it working simply add these two lines to your vue file:

```
import {ServerTable, ClientTable, Event} from 'vue-tables-2';
Vue.use(ClientTable)
```

If you're trying to run unit tests and facing issues with this, simply add these two lines into your testing file too!
