### ISSUE TITLE
updating table dynamically 

### ISSUE THREAD

**Issue by dhdmstjs** [matfish2/vue-tables-2#186]
is there a way to have the table update the data dynamically?
the user enters data in a textarea, and when you press enter, the data is saved, but I don't know how to get the data to show on the table without reloading the whole page, and I want to avoid this. 

this is the code

 ```
 inputHandler(e) { // when control enter is pressed
      if (e.keyCode === 13 && e.ctrlKey) {
        this.saver()
      }
    },

    saver() {
      let blob = { // this is what the textarea would be sending 
        cname: this.cname,
      }
      let url = `/api/lessonvocab/${blob.cname}`
      let p = this.$http.post(url, blob)
      p.then(response => {
        this.tableData = response.body
        this.ready = true
      })
      return p
    },
```

**Comment by CoolGoose** [comment]
@dhdmstjs that would be normally done by the server-side component and a column filter ? Is it something else that you're trying to achieve ?

**Comment by matfish2** [comment]
That depends on whether you are using the server- or client-side component. 
On the server component you can call the `refresh` or `reload` method to get the new data.
On the client component simply update you original dataset and vue's reactivity will take care of the rest.

**Comment by kaerimichi** [comment]
Hello @matfish2!

Could you tell me if this should work? The `changeTableContent()` method is not updating the datatable content. I'm using Vue.js 2.3.4 and Vue Tables 0.6.53.

```
<script>
  import Vue from 'vue'
  import { ClientTable } from 'vue-tables-2'

  Vue.use(ClientTable, {}, true)

  export default {
    methods: {
      changeTableContent () {
        this.tableData = []
      }
    },
    data () {
      return {
        columns: ['id', 'name', 'email'],
        tableData: [
          {
            id: 1,
            name: 'Bob Sacamano',
            email: 'bob.sacamano@mailinator.com'
          },
          {
            id: 2,
            name: 'Frank Costanza',
            email: 'frank.costanza@mailinator.com'
          },
          {
            id: 3,
            name: 'Joe Davola',
            email: 'joe.davola@mailinator.com'
          }
        ]
      }
    }
  }
</script>

<template>
  <div class="main">
    <button @click="changeTableContent">Change table content</button>
    <v-client-table name="myTable" :data="tableData" :columns="columns"></v-client-table>
  </div>
</template>
```

Thanks in advance!

**Comment by lbineau** [comment]
I'm experiencing the same issue than @kaerimichi Nuxt 1.0.0.RC7 Vue Tables 0.6.64
If I inspect the data of the table with developer tools they are changed, but the DOM doesn't refresh, that's really strange.

**Comment by matfish2** [comment]
This will work only when not using `vuex`.
Since you *are* using `vuex` the  `data` prop in not reactive, as it is assigned to the `vuex` store.
In order to change the data, you need to affect the `data` property on the `vuex` table module.

E.g, say your table has a `name` prop of `table`:

In your vuex store mutations:
```js
{
   UPDATE_TABLE(state, data) {
   state.table.data = data; // replace `table` with your own table name 
  }
}

```
In your vue instance:

```js
methods:{
  updateTable() {
   data = []; // whatever data you wish to pass;
   this.$store.commit('UPDATE_TABLE', data);
  }
}  
```

**Comment by singiankay** [comment]
@matfish2 how do I declare this in the root mutation if I use constants and modules?

```
{
   UPDATE_TABLE(state, data) {
   state.table.data = data; // replace `table` with your own table name 
  }
}
```

I'm doing something like this but it throws an error:  **Uncaught Error: [vuex] mutations should be function but "mutations.UPDATE_CLIENTTABLE" is {}.**

```
import * as types from './mutation-types'

export const UPDATE_CLIENTTABLE = {

	[types.UPDATE_CLIENTTABLE] (state, data) {
		state.ClientTableLine.data = data
	}
	
}
```
