### ISSUE TITLE
more template example

### ISSUE THREAD

**Issue by JackyTung** [matfish2/vue-tables-2#191]
- Vue.js version: 2.8.2

I want to use template to create "delete", "edit" icon just like your tutorial
However, I suffer in not so much example on how to use it

when I use your example code https://jsfiddle.net/matfish2/f5h8xwgn/,
your delete return type is string
```
delete: function(row) {
          return `<a href='javascript:void(0);' @click='$parent.deleteMe(${row.id})'><i class='glyphicon glyphicon-erase'></i></a>`
```

but in the https://github.com/matfish2/vue-tables-2/issues/140
you said that can not return raw data.

So, why in your example code return string can work?
and how to use template correctly?

**Comment by matfish2** [comment]
The example if for vue-tables version 1 (i.e for Vue 1).
The templates section in the docs is very specific as to the different ways of creating a template.
