### ISSUE TITLE
Turning off prepending of column for toggling child rows

### ISSUE THREAD

**Issue by gborcherds** [matfish2/vue-tables-2#192]
Would you take a PR that has an option to turn off the prepended row for opening up child rows?

I can do the leg work, but wanted to see if you'd be open to it before doing the work. It'd be nice to be able to put in a custom column for opening should you choose to.

It's basically 3 things, add a new option, check that option in the template files for heading and rows files before prepending it to the row.

Thanks.

**Comment by matfish2** [comment]
Im not sure I understand the logic. How is the user supposed to know that a
click on that particular column will open the child row?

**Comment by gborcherds** [comment]
I'm just looking for more flexibility to add my own column where I want it rather than at the beginning. Plus it allows for more action items in the table and flexibility in how it is built. This is what I have built already, the green eye opens the table, but as you can see I have a blank column from your code that I'd like to turn off. I just think it's a bit more flexible, but this is your awesome package, so you get to decide.

![screen shot 2017-06-21 at 2 59 57 pm](https://user-images.githubusercontent.com/7691166/27406588-91c5c0fc-5692-11e7-8e35-5db3adcaee11.png)

**Comment by matfish2** [comment]
The togglers column has it own logic and I think it shouldn't be open to manipulation by the user. The presentation is completely up to the user, who can use his own css to design the toggler.
As for the position of the column I think the only two logical positions are at the beginning and at the end. So I think a more subtle change is in place, namely, to add an option for choosing whether that column is prepended or appended to the table.

**Comment by gborcherds** [comment]
Fair enough, I also wanted the ability to add a delete record in the same column as the view column, but I can implement my own solution for my needs. Thanks for considering it.

**Comment by trevorgehman** [comment]
I actually would like this ability as well, since having multiple options in an "Actions" column seems like a common use case.
