### ISSUE TITLE
The default sorting causes the original data to be out of order

### ISSUE THREAD

**Issue by liwenlong** [matfish2/vue-tables-2#193]
- Vue.js version:^2.1.10
- consumed using: webpack
- FULL error message (including stack trace): display out out expect
- relevant code:  options: {
                               orderBy:{ },
                           }    
- steps for reproducing the issue:  
        1、when orderBy is set, and orderBy.column is undefined (because my column is dynamic)  , i expect the tables items display  as the original data's order， but it didn't work , it sort weird .
        2、i read related code , and find in 'vue-tables-2\compiled\computed\filtered-data.js' ,  if orderBy.column is undefined , it still do 'data.sort(this.getSortFn(column))' . so it change the  original data's order . 
          3、i tried set the orderBy to false , it didn't work as the same .  so i want to know it's a bug or not  ？ and  how to set the 'options'   to keep  the original data's order

**Comment by CoolGoose** [comment]
@liwenlong it might be that you're hitting and edge case and the this.orderBy.column needs to be wrapped into a conditional. I can't think of a case at the moment that might cause a problem if that would be wrapped into a if statement.

**Comment by liwenlong** [comment]
@CoolGoose   I tried , it's not a edge case . i just want the table display as the original data order ,how to set it ?
for example, i create a test data ：
  ` data: [
                            {ids:99, name:"John",cost:"100"},
                            {ids:21,name:"asfd",cost:"99"},
                            {ids:2, name:"Jasdfane",cost:"98"},
                            {ids:3, name:"Susafdsan",cost:"97"},
                            {ids:4, name:"Chris",cost:"96"},
                            {ids:11,name:"John",cost:"95"},
                            {ids:31,name:"Susan",cost:"94"},
                            {ids:41,name:"Chris",cost:"92"},
                            {ids:11,name:"John",cost:"85"},
                            {ids:31,name:"Susan",cost:"84"},
                            {ids:41,name:"Chris",cost:"82"},
                            {ids:131,name:"Susan",cost:"84"},
                            {ids:241,name:"Chris",cost:"82"},
                            {ids:531,name:"Susan",cost:"84"},
                            {ids:412,name:"Chris",cost:"82"},
                            {ids:1, name:"Dan",cost:"91"}
                        ]`
i want it display as the data array show ,but it didn't .  
the result is :  (copy the url and past in browser)
   [https://github.com/liwenlong/liwenlong.github.io/blob/master/result_table.png](url)

**Comment by CoolGoose** [comment]
@liwenlong and if you wrap that data.sort / column initialization in an if statement in compiled/computed/filtered-data.js does that solve the issue ? basically have it like:
```
if (this.orderBy.column) {
    var column = this.orderBy.column;
    data.sort(this.getSortFn(column));
}
```

**Comment by liwenlong** [comment]
@CoolGoose   Yes ,  I did that just like you do, I got the  right result as i want .  
so i want to know it's a bug or not  ?  
if not ,how to set in 'options' .  i should not modify the vue-table-2 source code in the node_modules.

**Comment by CoolGoose** [comment]
@liwenlong you're covered by @matfish2 next release should have the fix built in.
