### ISSUE TITLE
Access entire filteredData

### ISSUE THREAD

**Issue by MedoHaleem** [matfish2/vue-tables-2#195]
- Vue.js version:  2
- consumed using: (browserify/webpack/rollup): Webpack

I'm using client side vue-table and I want to access filteredData but for the entire array, for example if the data contained 1000 records there no filetedData for 1000 records but instead it contains the number of records that you set per page.

What I'm planning to do that there is map with markers and clicking on the markers will scroll to the row related to the marker, the problem is if row isn't rendered because isn't from the original  20 records that are currently displayed.

I was planning on iterating over filteredData to figure out the page and use setPage method and fire scrolling animation after it.

**Comment by matfish2** [comment]
I suppose you can fork the repo and add an event on `filtered-data.js` line 23, i.e before the splicing takes place. Send through the `data` array along with the event, and use it for whatever you need.
