### ISSUE TITLE
Need an option to change sort icons from <span> to <i> tag. 

### ISSUE THREAD

**Issue by fossbalaji** [matfish2/vue-tables-2#197]
- Vue.js version:2
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

**Comment by fossbalaji** [comment]
I am not using bootstrap . I am using Semantics UI . I need to change <span> tag to <i> tag for sort icons. How do i achieve this ?

**Comment by CoolGoose** [comment]
@fossbalaji there's no way of changing the span to an i at the moment. The only solution would be to write css code that emulates the i for the span that vue-tables-2 is generating.

**Comment by fossbalaji** [comment]
@CoolGoose Thanks a lot for your kind  reply. Any example would be much appreciated for the above problem.
