### ISSUE TITLE
Customize Styling

### ISSUE THREAD

**Issue by arddor** [matfish2/vue-tables-2#20]
- Vue.js version: **2**
- consumed using: **webpack**

I'm using bulma for styling and not bootstrap. Now problematically some class names are overlapping, but do not the same. Is there a possibility (I saw the one for table in the options) to customize most of the class names? What would be the intended way? 

I especially would like to change the styling of the pagination.

**Comment by matfish2** [comment]
The package is designed for `bootstrap`.
You can use `sass`'s `@extend` functionality to give `bootstrap`s classes the `bulma` appearance,
or fork the repo and modify the class names.

**Comment by arddor** [comment]
Thank you. This is what I expected. I will check if I can emulate the behavior I wish with extend in sass or if I have to fork the repo. I will make sure that I properly cite this project in case I have to fork it. Thank you again for this great module!

**Comment by matfish2** [comment]
I have added an optional custom template for the entire table, passed as the fourth argument to the `Vue.use`. You can use it to modify the template to match bulma.
