### ISSUE TITLE
Question: Adding columns dynamically

### ISSUE THREAD

**Issue by mzatt** [matfish2/vue-tables-2#201]
First off, love this library. Thanks @matfish2 for all your work.

I'm looking for some insight on how to add a column dynamically using the server-table and filterByColumns set to true. Currently I have a dropdown that onchange will push the value to the columns object, successfully adding a column. This duplicates the input of the last column before it was created under the new column. Say I have col1  col2 with filter inputs under them. I add col3 and the input is a duplicate of col2's input. The query in the request is  not updated, although orderBy is.

Without resorting to me hacking around, I was wondering if there was a more elegant solution to what I'm trying to accomplish.

**Comment by matfish2** [comment]
I am doing something very similar in my own project, toggling between all columns to one column, by making `columns` a computed property. I didn't encounter any issues. 
Can you paste your code? Duplicate values in filters usually mean that the column name is identical.

**Comment by mzatt** [comment]
https://gist.github.com/mzatt/4f8409ba4083732b83c3db16ed6c3883

Here is a redacted version of my table. Id would be the first column created, and any subsequent  columns added would have the vf_id input.

**Comment by matfish2** [comment]
After testing a similar scenario myself, I saw that when using multiple select, vue sometimes duplicates values on the model. I don't know why this happens or if it is a bug, but I think this could be the source of your problem.
Look at the `selected` property in the dev tools and see if that is indeed the case.

**Comment by mzatt** [comment]
No duplicates on my end, the values for selected show the exact same values as columns does.

**Comment by matfish2** [comment]
Is the whole column duplicated (i.e. the heading and the data as well) or only the filter?

**Comment by mzatt** [comment]
Just the filter input, the div wrapper (VueTables__columnname-filter-wrapper) is the correct name.

**Comment by matfish2** [comment]
Unable to reproduce.
I see to problems in your code, but I don't think they are related to the issue you are having:

1. `:multiple="true"` on `v-server-table`. No such prop
2. `Events` instead of `Event` in the import statement.
