### ISSUE TITLE
Fixed/pinned columns support?

### ISSUE THREAD

**Issue by random-one** [matfish2/vue-tables-2#206]
Is there a way to have such column, at least I didn't see in the docs. I have horizontal scrollbar but I want the right most column to be always visible/pinned. Is it possible or should I just rely on css classes?

**Comment by matfish2** [comment]
Currently there is no support for fixed columns. You can use an external plugin after the table is loaded.

**Comment by servocoder** [comment]
Vote for this feature

**Comment by rugged-service** [comment]
Another Vote

**Comment by DealerUp** [comment]
+1

**Comment by ETSmukesh** [comment]
Please work on this issue as soon as possible.

**Comment by fazi8808** [comment]
Any update on this one?
