### ISSUE TITLE
Feature request - multi column sorting

### ISSUE THREAD

**Issue by Klainer** [matfish2/vue-tables-2#207]
Hi, I love yor work! Is in plan multiple column sorting capability ? 
Thanks!

**Comment by matfish2** [comment]
Check out the new `multiSorting` option in the docs

**Comment by Klainer** [comment]
Wow, Thanks! It is possible to get array of sorted clumns and directions for external API ?

**Comment by matfish2** [comment]
I don't understand. Please elaborate.

**Comment by Klainer** [comment]
Sorry, I only want know if your implementation also suport server side multi sorting eg. generate appropriate query.

**Comment by matfish2** [comment]
The server component is not responsible for the sorting itself. This is completely up to the consumer. If you know in advance that a certain column needs secondary sorting, make you server code reflect that.
The option that I added is *not* a run-time multi-sort, and therefore it is only useful for the client component.
That being said, I am currently working on a run-time sort for the client component (using Shift + click). I might add this to the server-component as well (i.e make the request reflect the sorting hierarchy).
