### ISSUE TITLE
Question - checkbox in header and in rows for mass actions

### ISSUE THREAD

**Issue by Klainer** [matfish2/vue-tables-2#208]
Hello, I have another question. I read issuses but I can´t find proper solution how to implement selectable rows using checkbox and header three state checkbox behaviour. I´m js/vue beginner so I do not know how properly do that. Thanks for any example.

**Comment by matfish2** [comment]
You can use the `templates` option and the ability to create vue-compiled `headers` to create a bulk select mechanism. The details are of course more complicated but this is where you get to be creative.

**Comment by nuneramu** [comment]
Can you give a proper functional example with a jsfiddle, i tried a lot it is very difficult to implement.
i want to implement like the one in https://jsfiddle.net/thanhmabo/atxj3786/

Example: single file component
Grid.vue
<template>
    <v-client-table :data="users" :columns="columns" :options="options"></v-client-table>
</template>
<script>
	export default {
		computed: {
			selectAll: {
				get: function () {
					return this.users ? this.selected.length === this.users.length : false
				},
				set: function (value) {
					var selected = []
					if (value) {
						this.users.forEach(function (user) {
							selected.push(user.id)
						})
					}
					this.selected = selected
				}
			}
		},
		methods: {
			deleteMe: function (selected) {
			}
		},
		data () {
			return {
				users: [
					{ 'id': '1', 'name': 'Shad Jast', 'email': 'pfeffer.matt@yahoo.com' },
					{ 'id': '2', 'name': 'Duane Metz', 'email': 'mohammad.ferry@yahoo.com' },
					{ 'id': '3', 'name': 'Myah Kris', 'email': 'evolkman@hotmail.com' },
					{ 'id': '4', 'name': 'Dr. Kamron Wunsch', 'email': 'lenora95@leannon.com' }
				],
				selected: [],
				columns: ['select', 'name'],
				options: {
					// see the options API
					filterByColumn: true,
					headings: {
						select: function (h) {
// 							return <input type="checkbox" v-model={this.selectAll}/>
							return <div class="checkbox" style="display: inline-block; margin-top: 0; margin-bottom: 0;">
								<label>
									<input type="checkbox" class="checkbox style-0" v-model={this.selectAll}/>
									<span></span>
								</label>
							</div>
						}
					},
					templates: {
						select: function (h, row) {
							return (
								<div class="checkbox">
									<label>
										<input type="checkbox" class="checkbox style-0" v-model={this.selected} value={row.id}/>
										<span></span>
									</label>
								</div>
							)
						},
						delete: function (row) {
							return `<a href='javascript:void(0);' @click='$parent.deleteMe(${row.id})'><i class='fa fa-erase'></i></a>`
						},
						username: function (h, row) {
							return <a href={'#/auth/sip_user_edit/' + row.id}><i class='fa fa-edit'></i> {row.username}</a>
						}
					}
				}
			}
		}
	}
</script>
