### ISSUE TITLE
Feature Request: setData method

### ISSUE THREAD

**Issue by HardlyMirage** [matfish2/vue-tables-2#209]
Can we have a `setData` method so we can use our own API libraries if needed?

**Comment by matfish2** [comment]
I am not sure I understand your intention, but if you are referring to the server component, it currently supports `jQuery`, `axios` and `vue-resource`. I think that is flexible enough, as it covers most use cases.

**Comment by HardlyMirage** [comment]
I've already got an API library in my app that handles authentication, caching and request queuing. Using vue-tables-2 breaks the pattern by directly calling the API (which requires an Authorization header, I see no way of adding a header to API requests), then I'll copy over the caching and request queuing methods in the component forcing me to maintain them at two places.

Also, there will be newer resource fetching libraries coming up all the time, do you want to keep supporting them as they come? I think a `setData` method will users to use whatever data source they want. For instance, right now, how can I allow a user to upload a csv and display it in this table? Those 3 server components can't help, but `setData` can.

**Comment by matfish2** [comment]
I assume you are referring to the complementary `send-request.js` and `get-response-data.js` files. If it helps I can allow the user to override the methods with his own logic.

**Comment by HardlyMirage** [comment]
You already have a `responseAdapter` override method, which I think is good enough. However, a `sendRequest` override would be great. But cannot there be a way to manually set the data / add / delete rows at any time.

P.S.: I'm impressed at how responsive you are to issues and feature requests on this project. Keep up the good work!

**Comment by matfish2** [comment]
Thanks :) 

The server component is completely agnostic as far as data management is concerned. It receives whatever response you feed it and displays the result. Whatever parsing or data update that needs to take place should be handled on the server-side. So, whenever a change takes place that affects the returned dataset, you should call the `refresh` method to get an updated copy of the data. Any direct manipulation of the data on the client-side alone, will be erased whenever a new request is sent (which happens on just about every interaction).

**Comment by HardlyMirage** [comment]
Yes, but the manner in which the data is requested should be customizable. For instance, take the example scenario I mentioned earlier. If I need to upload / manually enter a csv and show it in the table, how can I do that with the currently available methods and options?

**Comment by matfish2** [comment]
If I understand your scenario correctly, you should let the user upload the file, and then activate the table (using a `v-if`), with a request to a different route that takes the file and returns its content in the expected format. If not, please elaborate.

**Comment by HardlyMirage** [comment]
Not exactly. I just mean that the data does not come from an API and can change frequently. Let me make this simpler.

I have a page with a textarea and this table. If I paste in a csv file into the textarea, the table shoud display the data parsed from the textarea. I should be able to do this multiple times without being required to reinitialize the table.

**Comment by matfish2** [comment]
As I explained above, the server component cannot process data directly from the client (You can theoretically inject `data` and `count` directly to the table and it will be reflected in the display, but no interaction with table will be possible. E.g sorting, filtering, pagination etc.). 

If your dataset is relatively small, you can and should use the *client* component for this scenario. Simply replace the data you pass to the table and it will be updated accordingly.

**Comment by HardlyMirage** [comment]
Got it, that makes sense. Thanks!
