### ISSUE TITLE
How to apply existing filter input values to custom filters?

### ISSUE THREAD

**Issue by seaneagan** [matfish2/vue-tables-2#21]
- Vue.js version: 2.0.1
- consumed using: webpack

I have column templates that generate links (`<a href="url">text</a>`).  I have custom filters to match the same text that is displayed in the links.  I want to use the queries from the existing filter input fields (top-left "normal filter" field and/or individual column filter fields) to be applied to these custom filters.

What is the easiest way to accomplish this?

Thanks for your help!

**Comment by matfish2** [comment]
I suppose you can watch the `query` property (this will differ according to whether you are using `vuex` or not), and apply the query to your custom filters on change.
