### ISSUE TITLE
Question: child rows example

### ISSUE THREAD

**Issue by Dahje** [matfish2/vue-tables-2#212]
I am trying to use your table and add child rows however I am unable to get a single row to show up. Do you have a working example with the child rows implemented?

**Comment by Dahje** [comment]
I have been following the explanation in the documentation as well. Just an FYI.

**Comment by matfish2** [comment]
Code please. 
Note that:
A, You must have a unique identifier in your dataset,
B. By default it is set to `id`. If yours is different you should set it using the `uniqueKey` option.

**Comment by Dahje** [comment]
I can't say for certain if this code is working or not as I realized the entire time I have been in your fiddles, you have not been using vue-tables-2, it has been vue-tables. Adding to that, you don't currently have any working demos with vue-tables-2. Regardless here is the code, I believe I may have been forgetting to specify the id on a per row basis. https://jsfiddle.net/ntcndtmg/

**Comment by Dahje** [comment]
I now have it working in my project!
I believe my issue was 2 things:
1. I was not including an id in each row.
2. I was attempting to add child rows into fiddles that were using vue-tables instead of the vue 2.x.x version vue-tables-2

On that note I have solved my problem, but would recommend that you add a working example using vue-tables-2. There is an example in your fiddles @ https://jsfiddle.net/matfish2/95evzcj2/ but it has a broken link for vue-tables-2.
