### ISSUE TITLE
How do you use the beforeBody and afterBody slots?

### ISSUE THREAD

**Issue by jasonlfunk** [matfish2/vue-tables-2#214]
How are you supposed to use the beforeBody and afterBody slots? I see them referenced in the code but not in the documentation. Nothing that I do seems to actually work. Here is what I think `should` be working but isn't:

```jsx
<v-server-table
      v-if="loaded"
      ref="relationship"
      :url="tblUrl"
      :columns="columns"
      :options="options"
>
      <tr slot="beforeBody">
        <td colspan='4'>
          <h3>Test</h3>
        </td>
      </tr>
</v-server-table>
```

**Comment by matfish2** [comment]
I've added those for my own project. Haven't got to documenting it yet.
Anyway, the way you use it should work. I honestly don't know why it isn't showing in your case.

**Comment by jasonlfunk** [comment]
I didn't have the newest version installed. Sorry.
