### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jeanaio** [matfish2/vue-tables-2#215]
1. I want to click + open one child row instead of all. 
2. I need to select and deselect the checkbox in the list and header column of vue-tables-2 and get selected data.
how should I do?

I'm sorry for my poor English.

**Comment by jeanaio** [comment]
3. How can I get all the data of the current page.

**Comment by matfish2** [comment]
1. Use a unique id. See #212 and the docs.
2. I don't understand
3.  See #195

**Comment by jeanaio** [comment]
2. Meaning how to add checkbox of the column and get selected data？
