### ISSUE TITLE
Question: prevent row-click event on certain columns

### ISSUE THREAD

**Issue by akhchan99** [matfish2/vue-tables-2#218]
My row-click event will trigger a route-redirect, how to prevent row-click event to trigger on certain columns?

 ie. I have a column which show an URL, so clicking on the URL I just want the browser to launch the new link on a new page, without trigger the application's row-click event.
or
having a column which is a checkbox, then I just want to trigger the checkbox event.

- Vue.js version: 234
- consumed using: webpack

**Comment by matfish2** [comment]
Use the `stopPropagation` method of the `event` object. E.g

```vue
<a @click="doSomething($event)">Link</a>
```
```js
methods:{
  doSomething(e) {
    e.stopPropagation();
  }
}
```

**Comment by akhchan99** [comment]
assuming <a @click="doSomething($event)">Link</a> is inside the template
I get "@click" unexpected tokens on the "@" sign

and If I use onclick, it say "doSomething" is not defined.

Is there any working fiddle example that I could see?

**Comment by vesper8** [comment]
I wasn't able to use stopPropagation in my case, the row_click event would still launch and cause my page location to change

I was able to get it to work by using this:

```
        ['posts/ROW_CLICK'](state, data) {
            if(data.event.srcElement.type != "checkbox") {
                location.href = data.row.url;
            }
        },
```

**Comment by akhchan99** [comment]
I did managed to do it like @matfish2 said

**Slot Template for vue-tables-2**
```
<template slot="ipAddress" scope="props">
  <a @click="launchWebSite($event, props.row)">{{props.row.ipAddress}}</a>
</template>

```
**Method**
```
launchWebUI: function (e, o) {
  e.stopPropagation()
  window.open('http://' + o.ipAddress, '_blank')
}
```
