### ISSUE TITLE
Pagination on reloading page

### ISSUE THREAD

**Issue by jpg5f2** [matfish2/vue-tables-2#22]
- Vue.js version: 2.0.1
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace): n/a
- relevant code:
- steps for reproducing the issue:
This may be a problem with the pagination plugin.  If you create a table, navigate away with vue-router (no page refresh), and navigate back the pagination now triggers 2 get requests on each pagination change.  This will grow infinitely.  

It seems the pagination module in vuex maybe needs to be destroyed and re-registered?

**Comment by lockljc** [comment]
has this issue been fixed?
