### ISSUE TITLE
Question: Can you add additional props to templates?

### ISSUE THREAD

**Issue by Dahje** [matfish2/vue-tables-2#221]
- Vue.js version: 2.3.3
When adding a template as a vue component like shown in the templates examples, can you add additional props to be passed to the template? I know that the value "data" is passed in for the row, but I need another variable to be sent in to the template.

**Comment by matfish2** [comment]
Not possible at the moment. You can either pass it to each row as an additional property or use `$parent` to get it from up the components tree.
