### ISSUE TITLE
Feature request - different templates for multiple tables

### ISSUE THREAD

**Issue by Manrix** [matfish2/vue-tables-2#225]
I often use multiple tables on same page. Sometimes i want a table to have a different template but keep the others with default template. 
Using `Vue.use(ClientTable, {}, false, require('./template.js')('client'))` i can't achieve that.

**Comment by matfish2** [comment]
If the custom template has only additional elements you can use a `v-if` conditional to control their rendering depending on the instance. Otherwise, this seems like an edge case, so I think I'll pass for now.

**Comment by Manrix** [comment]
Thanks for the suggestion. I'm trying to set a class dinamically:
`'class': {
    'row no-gutters': true,
    'table-tools': this.test
 }`
this.test is a data attribute set to true, but the class isn't added. If i replace this.test with true the class appears. Where am i wrong ?

**Comment by matfish2** [comment]
The this keyword refers to the table instance. Try this.$parent.test, to
hunt down your Vue instance

**Comment by Manrix** [comment]
It worked. Thanks.
