### ISSUE TITLE
Hide column

### ISSUE THREAD

**Issue by jlagger** [matfish2/vue-tables-2#227]
Hello. 
Can you please tall me, how I can hide some column?
For example I have one table, which should hide column for some users.

**Comment by Dahje** [comment]
Don't include the hidden column in the column list.

**Comment by matfish2** [comment]
@Dahje, he was asking about *conditionally* hiding this column.
@jlagger, You can achieve this by manipulating the `columns` prop. E.g you can make it a computed property that depends on the user id.
