### ISSUE TITLE
Connect row-click event to a parent component method when using vuex?

### ISSUE THREAD

**Issue by random-one** [matfish2/vue-tables-2#228]
I am using `v-server-table` with vuex but I was wondering if it's possible to catch the `row-click` event in the parent component (the one that contains the table component). From what I've seen so far when using vuex it's not possible to connect to the event bus signal but I wanted @matfish2 to confirm if that is the case.
- Vue.js version: 2.2.1
- consumed using: webpack

**Comment by matfish2** [comment]
I've removed the conditional that prevents events emission when using vuex. You should now be able to listen to events even when using vuex.
