### ISSUE TITLE
emit multiple filters at once ?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#229]
I have a custom filter working.

But because of the way I use pagination, I also am constantly setting the page manually.

Right now setting the custom filter and setting the page results in two calls to the server and it's causing me problems.

How can I set the page and the custom filter in a single operation so only one call is made ?

```
          Event.$emit('vue-tables.filter::root-id', 'somevalue');
          this.$refs.emailSingle.setPage(pageNumber);
```

How to do the above so only one call is made to the server ?

**Comment by matfish2** [comment]
rather than emitting the event, you can call the `getData()` method after manually setting the page and custom filter.

E.g:

```js
var table = this.$refs.myTable;
var page = 5;
table.page = page;
table.$refs.pagination.Page = page; // this will update the page on the pagination component
table.customQueries.root_id = 'somevalue';
table.getData(); // this will send the request
```
