### ISSUE TITLE
JSX not loading in templates

### ISSUE THREAD

**Issue by erikwestlund** [matfish2/vue-tables-2#23]
- Vue.js version: 2.0.5
- consumed using: (browserify/webpack/rollup) webpack
- relevant code:

vue tables:

                columns: ['approved', 'date', 'title', 'city', 'state', 'moderate'],
                options: {
                    orderBy: { 
                        column: 'date',
                    }, 
                    sortable: ['approved', 'date', 'city', 'state'],
                    templates: {
                        approved(h, row) {
                            if(row.approved == 1) {
                                var fa_class = 'fa fa-check inline-success';
                            } else if(row.approved == 0) {
                                var fa_class = 'fa fa-ban inline-danger';
                            } else {
                                var fa_class = 'fa fa-question';
                            }

                            return h('span', {
                                    attrs:{
                                        'class': fa_class
                                    }
                                });                        
                        },
                        moderate(h, row) {
                            return <moderate-link></moderate-link>
                        }
                    },

here's the moderate-link
```

Vue.component('moderate-link', {
  render (h) { // <-- h must be in scope
    return <div id="foo">bar</div>
  }
})
```

Typing

`<moderate-link></moderate-link> . `

renders correctly in an ordinary template

It does not render in the moderate() function in the VueTable2 row template.

at a loss...

No errors.

**Comment by siganurame** [comment]
Face the same issue, just come up with the error:
`ReferenceError: Can't find variable: React`

I think there is a problem with loading jsx, but i have no clue to fix it even i'm trying to add webpack configuration like this:
```
elixir((mix) => {
    Elixir.webpack.mergeConfig({
        module: {
            loaders: [{
                test: /\.jsx?$/,
                loader: 'babel',
                exclude: /node_modules(?!\/(vue-tables-2|vue-pagination-2))/
            }]
        }
    });

    mix.sass('app.scss')
       .webpack('app.js');
});
```

**Comment by matfish2** [comment]
@erikwestlund, was unable to reproduce.
@siganurame, See the issues labeled with 'jsx-transform'.

**Comment by siganurame** [comment]
@matfish2 Referred to this [issue#13](https://github.com/matfish2/vue-tables-2/issues/13) before, with come no luck. So, right now i'm using `createElement` function instead of jsx.

**Comment by erikwestlund** [comment]
I'm also using createElement. It's ugly but it works.

**Comment by pfzwaan** [comment]
What about this sollution:

Vue.component('moderate-link', {
    props: ['id'],
    template: '<a class="delete" v-on:click="doTheThing"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></a>',
    methods: {
        doTheThing: function(){
            alert(this.id);
        }
    }
})

                erase: function(h, row) {
                    return h('moderate-link',  {
                        attrs: {
                            'id': row.id
                        }
                    });
                }

**Comment by pfzwaan** [comment]
`Vue.component('moderate-link', {
    props: ['id'],
    template: '<a class="delete" v-on:click="doTheThing"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></a>',
    methods: {
        doTheThing: function(){
            alert(this.id);
        }
    }
})`

**Comment by kelchm** [comment]
I would love to find a solution for this that avoids using createElement.

**Comment by matfish2** [comment]
In case you are using `vue` files, the templates should be included as external `jsx` files to be compiled correctly. Otherwise I was unable to reproduce.

**Comment by verwilst** [comment]
Could the docs be updated on how you use external .jsx files as templates?

**Comment by matfish2** [comment]
Not sure what isn't clear, but to give an example

my-template.jsx

```
export default function(h, row) {
     return <a href={'/' + row.id + '/edit'}></a>
}

```
app.vue

```
import edit from 'edit.jsx'
...
templates:{
     edit
}
...
```

Also, check out the new option to use templates as components (see docs), which doesn't require jsx.

**Comment by verwilst** [comment]
I didn't know i had to put it in an export default function() {} block, that's why it didnt work. I'm pretty new at Vuejs/jsx, and had a very hard time to get it to work, while it might seem pretty obvious to experienced coders. Having that inside the documentation would have saved me many hours of searching and trial and error. :-) So maybe you want to add this to the docs?

Using components forces me to declare them globally, which seems icky..

Thanks!
