### ISSUE TITLE
how to use the name prop?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#230]
ok I tried many many ways to use a name prop.. I guess I'm still a vuejs noob because I can't get it to work

I tried with and without vuex.

I just wanted to be able to listen to my table this way:

```
Event.$on('vue-tables.myTableName.loaded', function (data) {
// Do something
});
```

I don't particular want to use vuex. My event listener works fine if I just do vue-tables.loaded but then it listens to table events for all tables I have on the page.

How do I use this new 'name prop' ?

I tried

```
<v-server-table url="/emails/api" :columns="tableColumns" :options="tableOptions" name="myTableName"></v-server-table>
```

```
<v-server-table url="/emails/api" :columns="tableColumns" :options="tableOptions" name="my-table-name"></v-server-table>
```

I tried adding it as a computed property. I tried camelCase/snake_case on the listener

just can't get it to work.. what am I missing? Can I get an example pretty please?

**Comment by matfish2** [comment]
Are you using the most recent version? (0.6.6.2)
