### ISSUE TITLE
Using a '@change' method in dropdown fires on load

### ISSUE THREAD

**Issue by ixperiencenl** [matfish2/vue-tables-2#232]
vue-tables-2@0.6.63
Since latest update the @change method in field in the table gets fired on table load. So if I have 10 rows with a dropdown with an @change method attached to it, is emits this event 10 times on load. This wasn't a problem before the update so I think it has something to do with the update. @matfish2 can you please look into this? Or point me in a direction away from using this method and solve it otherwise?

**Comment by matfish2** [comment]
Please post your code
