### ISSUE TITLE
[v-server-table] When change page no show loading

### ISSUE THREAD

**Issue by kolesoffac** [matfish2/vue-tables-2#234]
- Vue.js version: 2.4.2
- consumed using: webpack
- FULL error message (including stack trace): no
- steps for reproducing the issue:
1) setup api v-server-table
2) change page

**Comment by matfish2** [comment]
There is a loading indicator when the table first mounts, before it is populated with data. 
On subsequent requests I didn't want to hide\remove the previous data, before rendering the newly arrived dataset, as I thought this might result in a bad sort of flickering UX.
I did however emit both a `loading` and a `loaded` event, which can be used together by the consumer of the package to indicate loading however he sees fit.

From the docs:

> You can listen to those complementary events on a parent component and use them to add and remove a loading indicator, respectively.

If you or anyone else have a better idea I am open to suggestions.
