### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by matt-burgess** [matfish2/vue-tables-2#235]
The grid loads data.  Searching will highlight results, but the search does not actual limit the results.  Filtering nor sorting work either.

- Vue.js version: 2.4.2
- consumed using: webpack
- FULL error message (including stack trace):
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Object.responseAdapter (defaults.js?8c6e:63)
    at VueComponent.eval (v-server-table.js?8891:82)
    at <anonymous>
responseAdapter @ defaults.js?8c6e:63
(anonymous) @ v-server-table.js?8891:82
- relevant code:

<v-server-table url="Job/IndexData" :columns="columns" :options="options" name="jobs-table"></v-server-table>

import { ServerTable } from 'vue-tables-2';

Vue.use(ServerTable, {}, false, null);

new Vue({
    el: "#grid-jobs",
    data: {
        columns: ['PostedDate', 'Category', 'Company', 'Title', 'Location', 'State', 'Approved', 'Teaser'],
        options: {
            highlightMatches: true,
            perPage: 25,
            perPageValues: [10, 25, 50, 100],
            requestFunction: function (data) {
                return Axios.get(this.url)
                    .then(response => { this.data = response.data.data; this.count = response.data.count; })
                    .catch(function (e) {
                      this.dispatch('error', e);
                    }.bind(this));
            }
        }
    }
});

- steps for reproducing the issue:
Load the page initially.  Also occurs when searching, filtering and sorting a column.

**Comment by danielok1303** [comment]
Return "Promisse.resolve(response.data)" in you then method. This solved in my case.

`
return http.get(this.url, {params: data}).then(response => {
                this.data = response.data.data
                this.count = response.data.count
                return Promise.resolve(response.data)
              })
              .catch(function (e) {
                this.dispatch('error', e)
              }).bind(this))
`

**Comment by matt-burgess** [comment]
Adding Promise.resolve() seemed to deal with the javascript error, but the grid itself is not functional.  The grid loads data. Searching will highlight results, but the search does not actual limit the results. Filtering nor sorting work either.

**Comment by matt-burgess** [comment]
I am going to open another issue since this title is now misleading.

**Comment by muhamma1** [comment]
I added return Promise.resolve(this); This one is fixed I think it resolve all Object properties.
