### ISSUE TITLE
how can i change css style to clicked row?

### ISSUE THREAD

**Issue by KsCorrales** [matfish2/vue-tables-2#236]
- Vue.js version: "2.2.1"
- consumed using: (browserify/webpack/rollup): Webpack

i get the data with row-click="" but i wish to change the background color for example of that row.

**Comment by KsCorrales** [comment]
# **UPDATE: **

**I did it with this way:**

i set the class of `tr` selected with `data.event.path[1].className` and store in a temporary variable for delete the class added when change the selected row

**1st:** declare window var "exData" outside the method of `row-click` for delete the class of previous selected row

`window.exData = null;`

**2nd:** Check if the winwdow.exData has data for delete my active class of the `tr`, i set the tr class name with `data.event.path[1].className` to set empty string and delete the previous active class:

```
if(window.exData != null) {
   window.exData.event.path[1].className = '';
}
```
**3rd:** i set the active class in new selected row when the previous is deleted

`data.event.path[1].className = 'activeRow';`

**4th:** i store the selected row in exData for delete its active class in case the selected row changes

`window.exData = data;`

### **Result Demo:** 

![Image of select row](https://media.giphy.com/media/l1J3Qu4u1iLjzOvXW/giphy.gif)

## **Question:**

is another way to make this?

**Comment by KsCorrales** [comment]
# **UPDATE 2: **

i change `path[1].className` for `target.parentElement.className` because path not exist in firefox, 

Result:
`data.event.target.parentElement.className = 'activeRow';`

**Comment by matfish2** [comment]
You can use the `row-click` event to set an `active` property to `true` , and the `rowClassCallback` option to determine the class.

E.g:

```js
function(row) { 
   return row.active?'active':'';
} 
```

**Comment by saifhimayat** [comment]
data.event.target.parentElement.className = 'activeRow';
this is not removing "activeRow" class from previous row ?
