### ISSUE TITLE
ChildRow Question

### ISSUE THREAD

**Issue by jeffcj** [matfish2/vue-tables-2#237]
- Vue.js version: 2.4.2
- consumed using: webpack
- FULL error message (including stack trace): N/A

My intention is to use a childrow component that will show an edit form for the parent row/record. I'm loading data for the edit form via remote API call when the user opens the child row.

My problem is that every time a user toggles more than one child row, the mounted method for every open childrow component is called. Looks like all the active child row components are re-created when a child row is toggled.  Tested with a simple alert(this.$props.data.id) in the mounted function of the child component. It fires for every active component when a new one is toggled open.

So I would like to either:

A) Persist the state of an open child row component so if an edit is in progress and the user expands an additional child row the state of the first one remains the same.

or

B)  Limit the user to only having one childrow component toggled/expanded at a time.

Either option will work for my use case. 

Thanks in advance for any guidance.

**Comment by vpillinger** [comment]
A crude but simple method would be to hide the child row toggler using CSS
.VueTables__child-row-toggler {
display: none;
}

Then add a custom row with a template that has a button or link and pro grammatically toggles the row in a Javascript method. This will allow you to customize the toggling behavior for option B.

**Comment by matfish2** [comment]
Solved by c49a536
