### ISSUE TITLE
How to handle API unavailable

### ISSUE THREAD

**Issue by mavame** [matfish2/vue-tables-2#241]
I'm trying to handle my API endpoint(s) not being available for whatever reason.

But when the API isn't available I'm getting:
`Uncaught (in promise) TypeError: Cannot read property 'data' of undefined`

- Vue.js version: 2.4.1
- consumed using: webpack

I'm using [Server side](https://github.com/matfish2/vue-tables-2#server-side) and custom [request function](https://github.com/matfish2/vue-tables-2#custom-request-function). I'm using axios for xhr requests and the `api.get` function in my code below just makes and returns a call to `axios.get(...)`.

```
requestFunction(params) {
    return api.get(this.url, params)
      .catch(function (e) {
        this.isLoading = false;
        this.dispatch('error', e);
      }.bind(this));
  }
};
```

When there is no connection or no response, it looks like set-data.js still is looking for some response, and it gets caught up with an uncaught error.

#### FULL error message (including stack trace):

VM2764:1 GET http://localhost:4000/Accounts/1.0/1234567890/ net::ERR_CONNECTION_REFUSED

then...

Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at VueComponent.module.exports (set-data.js:4)
    at VueComponent.boundFn [as setData] (vue.esm.js:178)
    at VueComponent.<anonymous> (v-server-table.js:82)
    at <anonymous>
module.exports @ set-data.js:4
boundFn @ vue.esm.js:178
(anonymous) @ v-server-table.js:82
Promise resolved (async)
created @ v-server-table.js:79
callHook @ vue.esm.js:2646
Vue._init @ vue.esm.js:4197
VueComponent @ vue.esm.js:4367
createComponentInstanceForVnode @ vue.esm.js:3649
init @ vue.esm.js:3470
createComponent @ vue.esm.js:5118
createElm @ vue.esm.js:5061
createChildren @ vue.esm.js:5189
createElm @ vue.esm.js:5094
createChildren @ vue.esm.js:5189
createElm @ vue.esm.js:5094
createChildren @ vue.esm.js:5189
createElm @ vue.esm.js:5094
createChildren @ vue.esm.js:5189
createElm @ vue.esm.js:5094
patch @ vue.esm.js:5577
Vue._update @ vue.esm.js:2395
updateComponent @ vue.esm.js:2519
get @ vue.esm.js:2862
Watcher @ vue.esm.js:2851
mountComponent @ vue.esm.js:2523
Vue$3.$mount @ vue.esm.js:7842
Vue$3.$mount @ vue.esm.js:10045
Vue._init @ vue.esm.js:4207
Vue$3 @ vue.esm.js:4292
chooseAccount @ chooseAccount.js:171
__webpack_exports__.a @ portal.js:20
__webpack_require__ @ bootstrap 143e7b73e3eaccb20052:19
(anonymous) @ bootstrap 143e7b73e3eaccb20052:62
(anonymous) @ bootstrap 143e7b73e3eaccb20052:62

Any ideas on how I could go about fixing? The problem is the table and I think the vue app are not re-rendering. Because the `this.isLoading` data property I'm setting to false should trigger a change.

**Comment by matfish2** [comment]
A. `this` refers to the table component instance, not your root instance. Use `$parent` to find your instance,
B. Since you are using your own request function, I cannot determine why the error is not caught.
