### ISSUE TITLE
Daterangepicker

### ISSUE THREAD

**Issue by joepsyko** [matfish2/vue-tables-2#242]
I'm wondering if would be possible to use an external date picker.

And if yes, someone can help me with that?

**Comment by matfish2** [comment]
Using custom filters *inside* the table is now possible:

A. Define the `filterable` option so as to exclude the relevant column (i.e use a white list and omit the column in question)
B. Add a slot called `filter__{column}` (replace `{column}` with your column name), with the filter you want to use.
C. Use [custom filters](https://github.com/matfish2/vue-tables-2#custom-filters) to attach the query on change.
