### ISSUE TITLE
Question - Append parameter to query

### ISSUE THREAD

**Issue by gergo2007** [matfish2/vue-tables-2#244]
Hello
I have a table and i want to append a custom query parameter, how can i do this?

Thanks!

**Comment by matfish2** [comment]
use the `params`  option

**Comment by gergo2007** [comment]
I want to append to query and not after the query. I see there is a requestFunction option, I have added it but its not doing anything.

**Comment by matfish2** [comment]
What have you added? You need to pass a function of your own with all the relevant params

**Comment by gergo2007** [comment]
options:{
  requestFunction: function(data) {
    return axios.get(this.url, { params: {"owner_id":1} }).catch(function (e) {
      this.dispatch('error', e);
    }.bind(this));
}
}

But its not doing anything

**Comment by codisfy** [comment]
Doing something like below worked for me. 
```
          params: {
            additional: {
              drill_id: this.drillId,
            }
          }, 
          requestFunction: function (data) {
              data.query = _.isObject(data.query) ? data.query : {}
              data.query = {...data.additional, ...data.query};
              data.additional = null;
              return axios.get(this.url, {
                  params: data
              }).catch(function (e) {
                  this.dispatch('error', e);
              }.bind(this));
          }
```
