### ISSUE TITLE
Receiving "data.json is not a function" error

### ISSUE THREAD

**Issue by humblecoder** [matfish2/vue-tables-2#246]
**- Vue.js version: 2.4.2**
**-Laravel version: 5.5**
**- consumed using: webpack / laravel mix**
**- FULL error message (including stack trace):**

vue.app.js:76815 Uncaught (in promise) TypeError: data.json is not a function
    at VueComponent.<anonymous> (vue.app.js:76815)
    at <anonymous>
(anonymous) @ vue.app.js:76815
Promise rejected (async)
created @ vue.app.js:78209
callHook @ vue.app.js:3624
Vue._init @ vue.app.js:5068
VueComponent @ vue.app.js:5237
createComponentInstanceForVnode @ vue.app.js:4586
init @ vue.app.js:4420
createComponent @ vue.app.js:5969
createElm @ vue.app.js:5912
createChildren @ vue.app.js:6040
createElm @ vue.app.js:5945
createChildren @ vue.app.js:6040
createElm @ vue.app.js:5945
patch @ vue.app.js:6375
Vue._update @ vue.app.js:3384
updateComponent @ vue.app.js:3507
get @ vue.app.js:3846
Watcher @ vue.app.js:3829
mountComponent @ vue.app.js:3511
Vue$3.$mount @ vue.app.js:8639
Vue$3.$mount @ vue.app.js:10738
init @ vue.app.js:4426
createComponent @ vue.app.js:5969
createElm @ vue.app.js:5912
patch @ vue.app.js:6375
Vue._update @ vue.app.js:3384
updateComponent @ vue.app.js:3507
get @ vue.app.js:3846
Watcher @ vue.app.js:3829
mountComponent @ vue.app.js:3511
Vue$3.$mount @ vue.app.js:8639
Vue$3.$mount @ vue.app.js:10738
init @ vue.app.js:4426
createComponent @ vue.app.js:5969
createElm @ vue.app.js:5912
createChildren @ vue.app.js:6040
createElm @ vue.app.js:5945
createChildren @ vue.app.js:6040
createElm @ vue.app.js:5945
patch @ vue.app.js:6375
Vue._update @ vue.app.js:3384
updateComponent @ vue.app.js:3507
get @ vue.app.js:3846
Watcher @ vue.app.js:3829
mountComponent @ vue.app.js:3511
Vue$3.$mount @ vue.app.js:8639
Vue$3.$mount @ vue.app.js:10738
init @ vue.app.js:4426
createComponent @ vue.app.js:5969
createElm @ vue.app.js:5912
createChildren @ vue.app.js:6040
createElm @ vue.app.js:5945
createChildren @ vue.app.js:6040
createElm @ vue.app.js:5945
patch @ vue.app.js:6375
Vue._update @ vue.app.js:3384
updateComponent @ vue.app.js:3507
get @ vue.app.js:3846
Watcher @ vue.app.js:3829
mountComponent @ vue.app.js:3511
Vue$3.$mount @ vue.app.js:8639
Vue$3.$mount @ vue.app.js:10738
init @ vue.app.js:4426
createComponent @ vue.app.js:5969
createElm @ vue.app.js:5912
createChildren @ vue.app.js:6040
createElm @ vue.app.js:5945
patch @ vue.app.js:6375
Vue._update @ vue.app.js:3384
updateComponent @ vue.app.js:3507
get @ vue.app.js:3846
Watcher @ vue.app.js:3829
mountComponent @ vue.app.js:3511
Vue$3.$mount @ vue.app.js:8639
Vue$3.$mount @ vue.app.js:10738
init @ vue.app.js:4426
createComponent @ vue.app.js:5969
createElm @ vue.app.js:5912
patch @ vue.app.js:6411
Vue._update @ vue.app.js:3384
updateComponent @ vue.app.js:3507
get @ vue.app.js:3846
Watcher @ vue.app.js:3829
mountComponent @ vue.app.js:3511
Vue$3.$mount @ vue.app.js:8639
Vue$3.$mount @ vue.app.js:10738
Vue._init @ vue.app.js:5078
Vue$3 @ vue.app.js:5163
(anonymous) @ vue.app.js:11565
__webpack_require__ @ vue.app.js:20
(anonymous) @ vue.app.js:57734
__webpack_require__ @ vue.app.js:20
module.exports.list @ vue.app.js:66
(anonymous) @ vue.app.js:69

**- relevant code:**
Very basic implementation with absolutely no customization
`import {ServerTable, ClientTable, Event} from 'vue-tables-2';`
`import Vue from 'vue'`
`Vue.use(ServerTable)`

**- steps for reproducing the issue:**
Server simply returns a JSON response with a "data" array of row objects and "count"

**-Sample data:**

{
    "count": 5,
    "data": [
        {
            "id": "16F74AB24D844C078593687B",
            "name": "Domenick Center",
            "description": "Omnis incidunt et repellat rerum harum omnis. Voluptas sed fugiat saepe placeat nihil eum repudiandae. Ad quas sit suscipit ipsa nesciunt voluptatem. Architecto dolorem aut delectus eum eligendi corrupti.",
            "created_by": 1,
            "street_address": "9537 Marks Road",
            "city": "Lake Francoburgh",
            "state_province": "Louisiana",
            "postal_code": "78289",
            "status": "open",
            "created_at": "2017-08-08 04:54:01",
            "updated_at": "2017-08-08 04:54:01",
            "deleted_at": null
        },
        {
            "id": "45637A6F65F44BC68809719F",
            "name": "Sedrick Stream",
            "description": "Incidunt eum nihil quae omnis. Dolorem pariatur dolorum rerum labore cupiditate. Sit minus quam id. Esse autem ea in eaque deleniti cupiditate.",
            "created_by": 1,
            "street_address": "14496 Nya Common",
            "city": "Yundtborough",
            "state_province": "New Mexico",
            "postal_code": "48564-3125",
            "status": "open",
            "created_at": "2017-08-08 04:54:01",
            "updated_at": "2017-08-08 04:54:01",
            "deleted_at": null
        },
        {
            "id": "78373E1027E2469D8B2BDC16",
            "name": "Kozey Harbor",
            "description": "Quibusdam voluptate atque temporibus aut. Quidem ipsam rerum ut doloremque. Et accusantium alias ullam et aliquid. Veniam officia odit ut vel fuga. Quia voluptatem id dignissimos ut.",
            "created_by": 1,
            "street_address": "589 McKenzie Harbors",
            "city": "South Kathrynemouth",
            "state_province": "Idaho",
            "postal_code": "07046-2731",
            "status": "open",
            "created_at": "2017-08-08 04:54:01",
            "updated_at": "2017-08-08 04:54:01",
            "deleted_at": null
        },
        {
            "id": "BBCEFAC1A12143DBB00066C0",
            "name": "Jakubowski Centers",
            "description": "Laudantium maiores ut ut facere omnis. Impedit voluptatem expedita sint unde repudiandae. Beatae ex molestias ab accusantium. Ea inventore non exercitationem consequuntur dolore dolor.",
            "created_by": 1,
            "street_address": "628 Flatley Gateway",
            "city": "New Reginald",
            "state_province": "Massachusetts",
            "postal_code": "02382",
            "status": "open",
            "created_at": "2017-08-08 04:54:01",
            "updated_at": "2017-08-08 04:54:01",
            "deleted_at": null
        },
        {
            "id": "E52CDE7A77654B9ABD82EF65",
            "name": "Michel Court",
            "description": "Sint voluptatem perferendis autem inventore. Et distinctio hic delectus sunt voluptatibus dignissimos. Ut excepturi aut omnis recusandae ut. Quaerat odit et sed hic ut facere labore.",
            "created_by": 1,
            "street_address": "848 Spencer Harbors",
            "city": "East Taureanshire",
            "state_province": "North Carolina",
            "postal_code": "11912",
            "status": "open",
            "created_at": "2017-08-08 04:54:01",
            "updated_at": "2017-08-08 04:54:01",
            "deleted_at": null
        }
    ]
}

**Comment by humblecoder** [comment]
**UPDATE**
Consider the code inside "send-request.js":

`  if (typeof this.$http !== 'undefined') return this.$http.get(this.url, { params: data }).then(function (data) {`
`	return data.json();`
`  }.bind(this), function (e) {`
`    this.dispatch('error', e);`
`  }.bind(this));`



It appears that instead of returning `data.json()` (which is invalid), you need to return `data.data`.  I'm not sure this is the official "fix", but it works in my case.

**Comment by matfish2** [comment]
As stated in the docs, in case you choose to use `vue-resource`, the minimum version is 0.9.0. The API has changed since this release from `data.data` to `data.json()`

**Comment by humblecoder** [comment]
Apologies for being obtuse, but, I'm using vue-tables-2 (not 1) and I see nothing about "data.json".  That said, I did need to update my current version of Axios, and now I'm receiving "data.map is not a function".  Again, I'm sure there's something  simple being missed, but I don't see it.

**Comment by matfish2** [comment]
I meant the minimum version of `vue-resource`, but since you are using `axios` that isn't relevant.

Can you log `response` and `response.data` in `get-response-data.js`? I want to see what is returned from the server.

**Comment by humblecoder** [comment]
**This is the full response (as far as I could "reveal" it):**
`
{data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, …}config: adapter: ƒ xhrAdapter(config)data: undefinedheaders: Accept: "application/json, text/plain, */*"Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjJjZDhjMWIxMzJkZGQwNjg1NTAwYWYwZWE2YTI4ZmEwNGI1YjY2NWQzYTM1M2U5NjNhMGM1NzdkNjljOTU0NzE2M2IzNzU2N2E4MGZiZTY0In0.eyJhdWQiOiIyIiwianRpIjoiMmNkOGMxYjEzMmRkZDA2ODU1MDBhZjBlYTZhMjhmYTA0YjViNjY1ZDNhMzUzZTk2M2EwYzU3N2Q2OWM5NTQ3MTYzYjM3NTY3YTgwZmJlNjQiLCJpYXQiOjE1MDMyNDIwNzYsIm5iZiI6MTUwMzI0MjA3NiwiZXhwIjoxNTAzODQ2ODc1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.TzLflqHXvOShxloydNz0pJXuMO7Lq5hYjJ45TBf_qXwlhFDoQnBCAqcv5IPZgCLpJtC3G4QMmTjUikciWmvJ6DpOzQ0RIjVMquuh9XfKsWWXArfNVsipRtbDM79iIEpv_iXiEgNzLH9nmNYjfAi_RzFp_IdgLc46nzcrS70XnTAzhhKQo_Xmnh8v11TCjjYx3t_lxtw-wTrA5hMUMw0qpsfUJEosCBPO5bKSZY0fT66BzXoge2B-GBk4Azk8GY3SEiblF3fnO3z7suxJ7eZdudqUQ7EeWfjKKhcsgXe3PPTYLJznRp4uDXEtnJZBaxIevpbFEClqhHSyRcPqhmR4Ni8NCkmYtgk9csWxk09m9eSX8wucY4T-PSfKyckUs4syAkaziBCeqjbBv7H7iLGf7TO-9CsJEPRn3a0K9fm54G0w6Tn2enC-YuOh6g5T1Ae8-mUDsAWwMAh3PK6owx-vqGOsE86iDLvNMriPQQtAZ4upwVz0se15jaILOyVbsl6D2kedEXvspEh9W96vz-2gDAu1MKqIwxgTtqiZN1EhMOAhzXTfi2GDjUnTqjPm7yjo5a4dMOsZTxwN7we-TLpV5TZz87cKatdCAp2gmf4Ondz_Dh-CXueRPr37OG16MZeQ0NiNVsVQWI1V5uhAPYLhXN5gP3uG489DKIPn_h1kHv4"X-XSRF-TOKEN: "eyJpdiI6IjdZOEhLM0liRDNhMTBvbStKZVJBOFE9PSIsInZhbHVlIjoiZFhKSE1xeFByRUFVbTJDOEVGbStoOUJRTUQxNnNaMUNRNWgrTTFpUnpPV0ZPTnJwMHFBMStMVkxCQ3Rrcm9zK1NWZktxZFU2bmxLZ3VQUURhNDlsb2c9PSIsIm1hYyI6ImE5NWRkNTVhZjE2YjE0YTczOTAzOGY0NzRkNDE4MzRmNzg5MjAwZGQxNzUyZGI5MDRiYWU2YjIxZjQ5Zjg2ZjYifQ=="__proto__: ObjectmaxContentLength: -1method: "get"params: {query: "", limit: 10, orderBy: "id", ascending: 1, page: 1, …}timeout: 0transformRequest: {0: ƒ}transformResponse: {0: ƒ}url: "/api/projects"validateStatus: ƒ validateStatus(status)xsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"__proto__: Objectdata: count: 5data: Array(5)0: {id: "16F74AB24D844C078593687B", name: "Domenick Center", description: "Omnis incidunt et repellat rerum harum omnis. Volu…tecto dolorem aut delectus eum eligendi corrupti.", created_by: 1, street_address: "9537 Marks Road", …}1: {id: "45637A6F65F44BC68809719F", name: "Sedrick Stream", description: "Incidunt eum nihil quae omnis. Dolorem pariatur do…m id. Esse autem ea in eaque deleniti cupiditate.", created_by: 1, street_address: "14496 Nya Common", …}2: {id: "78373E1027E2469D8B2BDC16", name: "Kozey Harbor", description: "Quibusdam voluptate atque temporibus aut. Quidem i…t ut vel fuga. Quia voluptatem id dignissimos ut.", created_by: 1, street_address: "589 McKenzie Harbors", …}3: {id: "BBCEFAC1A12143DBB00066C0", name: "Jakubowski Centers", description: "Laudantium maiores ut ut facere omnis. Impedit vol…ore non exercitationem consequuntur dolore dolor.", created_by: 1, street_address: "628 Flatley Gateway", …}4: {id: "E52CDE7A77654B9ABD82EF65", name: "Michel Court", description: "Sint voluptatem perferendis autem inventore. Et di…dae ut. Quaerat odit et sed hic ut facere labore.", created_by: 1, street_address: "848 Spencer Harbors", …}length: 5__proto__: Array(0)__proto__: Objectheaders: cache-control: "no-cache, private"connection: "keep-alive"content-type: "application/json"date: "Mon, 21 Aug 2017 01:35:19 GMT"server: "nginx/1.11.1"transfer-encoding: "chunked"x-ratelimit-limit: "60"x-ratelimit-remaining: "58"__proto__: Objectrequest: XMLHttpRequestonabort: nullonerror: ƒ handleError()onload: nullonloadend: nullonloadstart: nullonprogress: nullonreadystatechange: ƒ handleLoad()ontimeout: ƒ handleTimeout()readyState: 4response: "{"count":5,"data":[{"id":"16F74AB24D844C078593687B","name":"Domenick Center","description":"Omnis incidunt et repellat rerum harum omnis. Voluptas sed fugiat saepe placeat nihil eum repudiandae. Ad quas sit suscipit ipsa nesciunt voluptatem. Architecto dolorem aut delectus eum eligendi corrupti.","created_by":1,"street_address":"9537 Marks Road","city":"Lake Francoburgh","state_province":"Louisiana","postal_code":"78289","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"45637A6F65F44BC68809719F","name":"Sedrick Stream","description":"Incidunt eum nihil quae omnis. Dolorem pariatur dolorum rerum labore cupiditate. Sit minus quam id. Esse autem ea in eaque deleniti cupiditate.","created_by":1,"street_address":"14496 Nya Common","city":"Yundtborough","state_province":"New Mexico","postal_code":"48564-3125","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"78373E1027E2469D8B2BDC16","name":"Kozey Harbor","description":"Quibusdam voluptate atque temporibus aut. Quidem ipsam rerum ut doloremque. Et accusantium alias ullam et aliquid. Veniam officia odit ut vel fuga. Quia voluptatem id dignissimos ut.","created_by":1,"street_address":"589 McKenzie Harbors","city":"South Kathrynemouth","state_province":"Idaho","postal_code":"07046-2731","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"BBCEFAC1A12143DBB00066C0","name":"Jakubowski Centers","description":"Laudantium maiores ut ut facere omnis. Impedit voluptatem expedita sint unde repudiandae. Beatae ex molestias ab accusantium. Ea inventore non exercitationem consequuntur dolore dolor.","created_by":1,"street_address":"628 Flatley Gateway","city":"New Reginald","state_province":"Massachusetts","postal_code":"02382","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"E52CDE7A77654B9ABD82EF65","name":"Michel Court","description":"Sint voluptatem perferendis autem inventore. Et distinctio hic delectus sunt voluptatibus dignissimos. Ut excepturi aut omnis recusandae ut. Quaerat odit et sed hic ut facere labore.","created_by":1,"street_address":"848 Spencer Harbors","city":"East Taureanshire","state_province":"North Carolina","postal_code":"11912","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null}]}"responseText: "{"count":5,"data":[{"id":"16F74AB24D844C078593687B","name":"Domenick Center","description":"Omnis incidunt et repellat rerum harum omnis. Voluptas sed fugiat saepe placeat nihil eum repudiandae. Ad quas sit suscipit ipsa nesciunt voluptatem. Architecto dolorem aut delectus eum eligendi corrupti.","created_by":1,"street_address":"9537 Marks Road","city":"Lake Francoburgh","state_province":"Louisiana","postal_code":"78289","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"45637A6F65F44BC68809719F","name":"Sedrick Stream","description":"Incidunt eum nihil quae omnis. Dolorem pariatur dolorum rerum labore cupiditate. Sit minus quam id. Esse autem ea in eaque deleniti cupiditate.","created_by":1,"street_address":"14496 Nya Common","city":"Yundtborough","state_province":"New Mexico","postal_code":"48564-3125","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"78373E1027E2469D8B2BDC16","name":"Kozey Harbor","description":"Quibusdam voluptate atque temporibus aut. Quidem ipsam rerum ut doloremque. Et accusantium alias ullam et aliquid. Veniam officia odit ut vel fuga. Quia voluptatem id dignissimos ut.","created_by":1,"street_address":"589 McKenzie Harbors","city":"South Kathrynemouth","state_province":"Idaho","postal_code":"07046-2731","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"BBCEFAC1A12143DBB00066C0","name":"Jakubowski Centers","description":"Laudantium maiores ut ut facere omnis. Impedit voluptatem expedita sint unde repudiandae. Beatae ex molestias ab accusantium. Ea inventore non exercitationem consequuntur dolore dolor.","created_by":1,"street_address":"628 Flatley Gateway","city":"New Reginald","state_province":"Massachusetts","postal_code":"02382","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"E52CDE7A77654B9ABD82EF65","name":"Michel Court","description":"Sint voluptatem perferendis autem inventore. Et distinctio hic delectus sunt voluptatibus dignissimos. Ut excepturi aut omnis recusandae ut. Quaerat odit et sed hic ut facere labore.","created_by":1,"street_address":"848 Spencer Harbors","city":"East Taureanshire","state_province":"North Carolina","postal_code":"11912","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null}]}"responseType: ""responseURL: "http://myapp.app/api/projects?query=&limit=10&orderBy=id&ascending=1&page=1&byColumn=0"responseXML: nullstatus: 200statusText: "OK"timeout: 0upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}withCredentials: false__proto__: XMLHttpRequeststatus: 200statusText: "OK"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
>>>>>>> External Changes
vue.app.js:75750 Uncaught (in promise) TypeError: data.map is not a function
    at VueComponent.module.exports (vue.app.js:75750)
    at VueComponent.boundFn [as applyFilters] (vue.app.js:1590)
    at VueComponent.module.exports (vue.app.js:76426)
    at VueComponent.boundFn [as setData] (vue.app.js:1590)
    at VueComponent.<anonymous> (vue.app.js:77803)
    at <anonymous>
module.exports @ vue.app.js:75750
boundFn @ vue.app.js:1590
module.exports @ vue.app.js:76426
boundFn @ vue.app.js:1590
(anonymous) @ vue.app.js:77803
Promise resolved (async)
created @ vue.app.js:77800
callHook @ vue.app.js:3982
Vue._init @ vue.app.js:5426
VueComponent @ vue.app.js:5595
createComponentInstanceForVnode @ vue.app.js:4944
init @ vue.app.js:4778
createComponent @ vue.app.js:6327
createElm @ vue.app.js:6270
createChildren @ vue.app.js:6398
createElm @ vue.app.js:6303
createChildren @ vue.app.js:6398
createElm @ vue.app.js:6303
patch @ vue.app.js:6733
Vue._update @ vue.app.js:3742
updateComponent @ vue.app.js:3865
get @ vue.app.js:4204
Watcher @ vue.app.js:4187
mountComponent @ vue.app.js:3869
Vue$3.$mount @ vue.app.js:8997
Vue$3.$mount @ vue.app.js:11096
init @ vue.app.js:4784
createComponent @ vue.app.js:6327
createElm @ vue.app.js:6270
patch @ vue.app.js:6733
Vue._update @ vue.app.js:3742
updateComponent @ vue.app.js:3865
get @ vue.app.js:4204
Watcher @ vue.app.js:4187
mountComponent @ vue.app.js:3869
Vue$3.$mount @ vue.app.js:8997
Vue$3.$mount @ vue.app.js:11096
init @ vue.app.js:4784
createComponent @ vue.app.js:6327
createElm @ vue.app.js:6270
createChildren @ vue.app.js:6398
createElm @ vue.app.js:6303
createChildren @ vue.app.js:6398
createElm @ vue.app.js:6303
patch @ vue.app.js:6733
Vue._update @ vue.app.js:3742
updateComponent @ vue.app.js:3865
get @ vue.app.js:4204
Watcher @ vue.app.js:4187
mountComponent @ vue.app.js:3869
Vue$3.$mount @ vue.app.js:8997
Vue$3.$mount @ vue.app.js:11096
init @ vue.app.js:4784
createComponent @ vue.app.js:6327
createElm @ vue.app.js:6270
createChildren @ vue.app.js:6398
createElm @ vue.app.js:6303
createChildren @ vue.app.js:6398
createElm @ vue.app.js:6303
patch @ vue.app.js:6733
Vue._update @ vue.app.js:3742
updateComponent @ vue.app.js:3865
get @ vue.app.js:4204
Watcher @ vue.app.js:4187
mountComponent @ vue.app.js:3869
Vue$3.$mount @ vue.app.js:8997
Vue$3.$mount @ vue.app.js:11096
init @ vue.app.js:4784
createComponent @ vue.app.js:6327
createElm @ vue.app.js:6270
createChildren @ vue.app.js:6398
createElm @ vue.app.js:6303
patch @ vue.app.js:6733
Vue._update @ vue.app.js:3742
updateComponent @ vue.app.js:3865
get @ vue.app.js:4204
Watcher @ vue.app.js:4187
mountComponent @ vue.app.js:3869
Vue$3.$mount @ vue.app.js:8997
Vue$3.$mount @ vue.app.js:11096
init @ vue.app.js:4784
createComponent @ vue.app.js:6327
createElm @ vue.app.js:6270
patch @ vue.app.js:6769
Vue._update @ vue.app.js:3742
updateComponent @ vue.app.js:3865
get @ vue.app.js:4204
Watcher @ vue.app.js:4187
mountComponent @ vue.app.js:3869
Vue$3.$mount @ vue.app.js:8997
Vue$3.$mount @ vue.app.js:11096
Vue._init @ vue.app.js:5436
Vue$3 @ vue.app.js:5521
(anonymous) @ vue.app.js:14990
__webpack_require__ @ vue.app.js:20
(anonymous) @ vue.app.js:89071
__webpack_require__ @ vue.app.js:20
module.exports.list @ vue.app.js:66
(anonymous) @ vue.app.js:69
>>>>>>> External Changes
`

**This is the sample data returned:**

`
{"count":5,"data":[{"id":"16F74AB24D844C078593687B","name":"Domenick Center","description":"Omnis incidunt et repellat rerum harum omnis. Voluptas sed fugiat saepe placeat nihil eum repudiandae. Ad quas sit suscipit ipsa nesciunt voluptatem. Architecto dolorem aut delectus eum eligendi corrupti.","created_by":1,"street_address":"9537 Marks Road","city":"Lake Francoburgh","state_province":"Louisiana","postal_code":"78289","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"45637A6F65F44BC68809719F","name":"Sedrick Stream","description":"Incidunt eum nihil quae omnis. Dolorem pariatur dolorum rerum labore cupiditate. Sit minus quam id. Esse autem ea in eaque deleniti cupiditate.","created_by":1,"street_address":"14496 Nya Common","city":"Yundtborough","state_province":"New Mexico","postal_code":"48564-3125","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"78373E1027E2469D8B2BDC16","name":"Kozey Harbor","description":"Quibusdam voluptate atque temporibus aut. Quidem ipsam rerum ut doloremque. Et accusantium alias ullam et aliquid. Veniam officia odit ut vel fuga. Quia voluptatem id dignissimos ut.","created_by":1,"street_address":"589 McKenzie Harbors","city":"South Kathrynemouth","state_province":"Idaho","postal_code":"07046-2731","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"BBCEFAC1A12143DBB00066C0","name":"Jakubowski Centers","description":"Laudantium maiores ut ut facere omnis. Impedit voluptatem expedita sint unde repudiandae. Beatae ex molestias ab accusantium. Ea inventore non exercitationem consequuntur dolore dolor.","created_by":1,"street_address":"628 Flatley Gateway","city":"New Reginald","state_province":"Massachusetts","postal_code":"02382","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null},{"id":"E52CDE7A77654B9ABD82EF65","name":"Michel Court","description":"Sint voluptatem perferendis autem inventore. Et distinctio hic delectus sunt voluptatibus dignissimos. Ut excepturi aut omnis recusandae ut. Quaerat odit et sed hic ut facere labore.","created_by":1,"street_address":"848 Spencer Harbors","city":"East Taureanshire","state_province":"North Carolina","postal_code":"11912","status":"open","created_at":"2017-08-08 04:54:01","updated_at":"2017-08-08 04:54:01","deleted_at":null}]}
`


If you need more specific info just let me know.  Thanks.

**Comment by excitedcat** [comment]
axios is not work. data.json is not a function

**Comment by matfish2** [comment]
If you get `data.json is not a function` it means that `axios` is not available at the global `window` scope, and thus cannot be found by the plugin, which then resorts to `vue-resource`, of which you probably have an old version (below 0.9).
So try:

```js
window.axios = require('axios');
```

**Comment by jblotus** [comment]
would it be possible to provide a direct reference to axios as opposed to pulling from window? possible something that could be configured when calling Vue.use()

perhaps this is already possible with a custom global request funciton?
