### ISSUE TITLE
heading returns escaped html

### ISSUE THREAD

**Issue by ravi35** [matfish2/vue-tables-2#247]
Hello,

first of all thank you for this package. 

I'm facing some issues when trying to render HTML inside the table headers. I'm using the headings and columns options as follows:
```
columns: [
     'checkbox',
     'a',
     'b',
     'c',
     'd'
],
options: {
    headings: {
        checkbox: function (h) { return '<h2>a</h2>' }
    }
}
```

Which results in this output:
![image](https://user-images.githubusercontent.com/31092040/29400133-5ad4b7c6-832c-11e7-9699-bf1418d2d9d9.png)

```
<span class="VueTables__heading">&lt;h2&gt;a&lt;/h2&gt;</span>
```
Is there anything that I'm doing wrong here?

- Vue.js version: 2.2.6
- consumed using: webpack

Thank you!

**Comment by matfish2** [comment]
Your JSX syntax is wrong, Don't use quotes:

```jsx
function (h) { 
  return <h2>a</h2> 
}
```

**Comment by drolean** [comment]
i have a same problem, but i tried compile with you example and have a error

`ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./resources/assets/js/components/ContaSelect.vue
Module build failed: SyntaxError: C:/#Sites/sarapanew/resources/assets/js/components/ContaSelect.vue: Unexpected token (104:15)

  102 |     },
  103 |     razao: function(h, row, index) {
> 104 |         return <br>
      |                ^
  105 |     },
  106 |     '#':  'Status'
  107 |   },
`

**Comment by matfish2** [comment]
You need to install the [jsx transform](https://github.com/vuejs/babel-plugin-transform-vue-jsx)

**Comment by webdevnerdstuff** [comment]
What if you are not using jsx?

Ex.
```
headings: { 
    checkbox: () => {
        const checkbox = '<input type="checkbox">';
        return checkbox;
    },
},
