### ISSUE TITLE
Sorting Data

### ISSUE THREAD

**Issue by agungid** [matfish2/vue-tables-2#248]
Hi. I have a problem with sorting data.
How to sort data based on existing data index
Ex:
```
data: {
0: {id:1, cust:'test 1'},
1: {id:2, cust:'test 2'},
2: {id:3, cust:'test 3'},
3: {id:4, cust:'test 4'},
}
```

**Comment by matfish2** [comment]
`data` should be an `array`, not an `object`.
If you want to maintain the original order use:

```js
options:{
 orderBy:{column:false}
} 
```
