### ISSUE TITLE
add data from top to bottom

### ISSUE THREAD

**Issue by dhdmstjs** [matfish2/vue-tables-2#250]
hi, i was wondering if it was possible to display data by date added from top to bottom. basically newest data should be on top. I've tried:
orderBy: {ascending: true}
orderBy: {column: false}
not quite sure what to do 
thanks in advance!

**Comment by matfish2** [comment]
To maintain the original order of the dataset `orderBy: {column: false}` should do the trick.
Otherwise you can pass a `created_at` property to each object and make it a `moment` object (You can you the `toMomentFormat` option which converts it for you). Then:

```js
{
orderBy:{
column:'created_at',
ascending:false // newest(=highest) date first
}
}
```

**Comment by matfish2** [comment]
Update: Since the last version (0.6.70) omitting `orderBy` will default to the original dataset order. So there is no need for `orderBy:{column:false}`
