### ISSUE TITLE
Events issue

### ISSUE THREAD

**Issue by Dahje** [matfish2/vue-tables-2#252]
Vue@2.3.3
Webpack

I am unable to get the filter event to trigger, I feel as though I must be doing something wrong.

`<v-client-table :data="data" :columns="columns" :options="options" @filter="$emit('update')"></v-client-table>`

I know the function to emit works and is being captured properly as using @change.native works to fire the emit.

**Comment by matfish2** [comment]
Unable to reproduce:

```vue
	<v-client-table name="client1"  @filter="filterCb" :data="cData" :columns="cColumns" :options="c1Options"></v-client-table>		
```

```js
methods:{
		filterCb(q) {
			console.log(q);

		}
	}
```

Console output:
![2017-11-04 2](https://user-images.githubusercontent.com/1510460/32406076-6b7cb15c-c169-11e7-9fac-3cf4cdf50484.png)
