### ISSUE TITLE
Highlight Matches in Custom Templates Slot?

### ISSUE THREAD

**Issue by austenc** [matfish2/vue-tables-2#253]
- Vue.js version: 2.3.4
- consumed using: webpack

Hi there, I've got a custom slot setup inside `v-server-table` like follows:
```
<template slot="city" scope="props">
    {{ props.row.city }}, {{ props.row.state }}
</template>
```

Is there a supported or easy built-in way to have searching by column highlight matches in the city field? In this case I don't want "State" to be its own column. It's fine if it isn't matched in the search but it had me wondering if search-match-highlighting (via `highlightMatches` option) could work with custom templates?

**Comment by matfish2** [comment]
`highlightMatches` adds a `<b>` tag to the original dataset, because the search is performed on the original data and not on the custom template. So at the moment you can't highlight matches on a custom template.

**Comment by An-AngryBear** [comment]
For people looking for a solution here is how I implemented it:

```javascript
        // search filter highlighting for vuetables2 custom column templates
        // to be used with 'v-html="$options.filters.highlight(*stringVariable*, filterValue)'
        // filterValue needs to be a data property set in response to VueTables "@filter" event.
        Vue.filter('highlight', (words, query) => {
            const regExpQuery = new RegExp(query, 'ig');
            return words.toString().replace(regExpQuery, matchedTxt => (`<b class="text-primary">${matchedTxt}</b>`));
        })
```

**Comment by luchorengo** [comment]
Isn't there a native solution yet? There will be one?
