### ISSUE TITLE
Server Table with Custom Filter - Initialization Doesn't Add Correct Parameter

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#254]
The table sends off an Ajax request as soon as the element is instantiated. This is, unfortunately, before the vuex store has loaded and I can't properly send out an initial value for a custom filter from the stored values. Is there a way I can make the table wait to load until I have access to the store or just until I want it to load?

**Comment by scs-ben** [comment]
In a similar request, I'd like for the table to cancel previous requests when it sends out a new request, as it is, it could spin up any number of requests that bog down the server.

**Comment by matfish2** [comment]
You can control the table rendering using a `v-if` conditional with some data property you set to `true` when you are ready.

As for redundant requests, the `debounce` option makes sure that a request is only sent when the user has finished typing. If your typical user types slower than usual you can always increase the debounce value.
