### ISSUE TITLE
Updating table data through template

### ISSUE THREAD

**Issue by Dahje** [matfish2/vue-tables-2#256]
![table_pagination_checkbox_bug](https://user-images.githubusercontent.com/29611739/29883000-0e7b4d78-8d6c-11e7-83c3-4d5913fc9704.gif)

- Vue.js version: 2.3.3
- consumed using: webpack
- relevant code:

Checkbox.vue
```
<template>
  <input type="checkbox" :id="data.id" v-model="data.Selected"></input>
</template>

<script>
export default {
  props: ['data'],
};
</script>
```
BasicTable.vue
```
<template>
  <div>
    <v-client-table
      name="basicTable"
      :data="tableData"
      :columns="['Selected', 'name', 'age', 'favourite color']"
      :options="options"
    ></v-client-table>
  </div>
</template>

<script>
import checkbox from '@/components/table/templates/Checkbox';

export default {
  name: 'basic-table',
  methods: {
    toggleAll($event) {
      this.tableData.forEach((element) => {
        // eslint-disable-next-line
        element.Selected = $event.target.checked;
      });
    },
  },
  data() {
    return {
      options: {
        perPage: 2,
        headings: {
          Selected: h => h('input', {
            attrs: { id: 'SelectAll', type: 'checkbox' },
            on: {
              click: this.toggleAll,
            },
          }),
        },
        templates: {
          Selected: checkbox,
        },
        filterable: false,
        childRow: false,
        sortIcon: {
          base: 'fa',
          up: 'fa-chevron-up',
          down: 'fa-chevron-down',
        },
      },
      tableData: [
        {
          id: '0',
          name: 'Mr. Example',
          age: '42',
          'favourite color': 'Blue',
          Selected: true,
        },
        {
          id: '1',
          name: 'Mrs. Example',
          age: '41',
          'favourite color': 'Purple',
          Selected: false,
        },
        {
          id: '2',
          name: 'Mr. Test',
          age: '28',
          'favourite color': 'Blue',
          Selected: true,
        },
        {
          id: '3',
          name: 'Mrs. Test',
          age: '25',
          'favourite color': 'Red',
          Selected: true,
        },
        {
          id: '4',
          name: 'Mr. Try',
          age: '23',
          'favourite color': 'Orange',
          Selected: false,
        },
      ],
    };
  },
};
</script>
```

- steps for reproducing the issue:
With the above code you should be able to replicate the issue.
When you select a checkbox without the selectAll functionality, then change to another page and come back, the old value will be present again.

**Example** 
State 1: No checkboxes checked and page 1 is visible
Action: Click a checkbox visible on page one to set the attribute Selected to true.
State 2: One checkbox on page 1 is selected and the other is not.
Action: Change the visible page to page 2.
State 3: Page 2 is visible with no checkboxes checked
Action: Change the visible page to page 1.
State 4: Page 1 is visible with no checkboxes checked.

Expected: In state 4 the checkbox that you selected initially should be checked.

**Comment by matfish2** [comment]
The `v-for` loop building the table is NOT iterating through the original dataset. It is a computed property that contains the data after it has been filtered/sorted/limited etc.
Therefore, using a `v-model` inside a template has no impact on the original dataset. Of course, if you were to change the original you WOULD see it reflected and persisted.

What I did when facing a similar situation was using a *external* `markedRows` property, which I declared as an empty array (Obviously you can prefill it with some ids if this is necessary).

So, on `BasicTable.vue` you can add `markedRows:[]` to the data object.
Then, on your `Checkbox.vue`:

```vue
 <input type="checkbox" :id="data.id" :value="data.id" v-model="$parent.$parent.markedRows"></input>
```

The other path you can take is firing a native change event whenever the checkbox is clicked, and then iterating through your original dataset, finding the correct row and changing its `Selected` property.

I will try to think of a way of automating the process, maybe using a computed property setter.
