### ISSUE TITLE
Changing data doesn't refresh DOM

### ISSUE THREAD

**Issue by lbineau** [matfish2/vue-tables-2#257]
I'm experiencing the same issue than @kaerimichi Nuxt 1.0.0.RC7 Vue Tables 0.6.64
If I inspect the data of the table with developer tools they are changed, but the DOM doesn't refresh, that's really strange.

- Vue.js version: latest (Nuxt 1.0.0.RC7)
- consumed using: (webpack)
- relevant code: Same code than the comment of @kaerimichi https://github.com/matfish2/vue-tables-2/issues/186

**Comment by lbineau** [comment]
Any news about this issue ?

**Comment by matfish2** [comment]
Please check out my response to #186 
https://github.com/matfish2/vue-tables-2/issues/186#issuecomment-331449197
