### ISSUE TITLE
How to use 'slot, appendBody'

### ISSUE THREAD

**Issue by JaemyungChong** [matfish2/vue-tables-2#262]
- Vue.js version: "vue": "^2.3.3", "vue-tables-2": "^0.6.67",
- consumed using: (browserify/webpack/rollup) : webpack
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

How to use 'slot'?
I tried slot as option like this

```
<template>
<v-client-table :options="options" slots="slots" ...>
</template>

<script>
options: {
   appendBody: "<div>appendBody</div>"
   ...
}
</script>
```

Also tried as a slot prop.
```
slots: {
   appendBody: "<div>appendBody</div>"
}
```

Can you show example how to use 'slot'? 
Thanks.

**Comment by matfish2** [comment]
https://vuejs.org/v2/guide/components.html#Named-Slots

**Comment by vesper8** [comment]
I am struggling to use slots as well, and I clicked the link above and I am still doing it wrong apparently. Can you just show us please @matfish2 

Here's what I tried based on the link above

```

<v-table-server :options="{{ json_encode($options) }}">
    <h1 slot="prependBody">test</h1>
</v-table-server>
```

**Comment by dvitt90** [comment]
@vesper8 
any help would be much appreciated. I have this html

<bkmtech-productimport :user="user" inline-template>
    <div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary bkmtech-panel-minheight">
                    <div class="panel-heading">Import</div>
                    <div class="panel-body">
                        <bkmtech-import-table>
                            <div slot="beforeFilters"><button>some button</button></div>
                        </bkmtech-import-table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</bkmtech-productimport>

and  this for template

<v-server-table url="/products/import/scrapedata" :columns="columns" :options="options" ref="scrapedataTable" @loaded="onLoaded()" @pagination="pageChange()">
    <slot name="beforeFilters"></slot>
</v-server-table>


where are the slots supposed to be located?

**Comment by dvitt90** [comment]
@vesper8 

any help would be much appreciated. I have this for html

`
<bkmtech-productimport :user="user" inline-template>
    <div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary bkmtech-panel-minheight">
                    <div class="panel-heading">Import</div>
                    <div class="panel-body">
                        <bkmtech-import-table>
                            <div slot="beforeFilters"><button>some button</button></div>
                        </bkmtech-import-table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</bkmtech-productimport>
`

and this for a template

`
<v-server-table url="/products/import/scrapedata" :columns="columns" :options="options" ref="scrapedataTable" @loaded="onLoaded()" @pagination="pageChange()">
    <slot name="beforeFilters"></slot>
</v-server-table>
`

bkmtech-import-table is the v-server-table component. Where are the slots supposed to be?

**Comment by vesper8** [comment]
This is what worked for me (examples)

This is inside my single-file .vue component file

```
<template>
    <div>
        <v-server-table>

            <tr slot="prependBody">
                <td colspan="100">
                    <button type="button" class="btn btn-primary">Wheeeeeeeee</button>
                </td>
            </tr>
            
            <tr slot="appendBody">
                <button type="button" class="btn btn-primary">Whee</button>
            </tr>
            
        </v-server-table>
    </div>
</template>
```

My mistake before was that I was trying to add the slots in my blade templates and that wasn't working. But now that I'm adding them inside of a custom vue component they work fine.
