### ISSUE TITLE
Question: Modify data in function

### ISSUE THREAD

**Issue by FOLLGAD** [matfish2/vue-tables-2#263]
I use the server-table and call an api with a response like below:
``` javascript
[
  {
    name: {
      first: "Firstname",
      last: "Lastname"
    },
    otherProperty: true
  },
  // ...
]
```
I am wondering: is there a way to render a column "Full Name" with a function like this?
```
function (name) { return name.first + " " + name.last }
```
Help is much appreciated.

**Comment by matfish2** [comment]
Yes. Use the templates option like so:

```js
templates:{
  name(h, row) {
       return `${row.first} ${row.last}`;
  }
}
```

Note: `name` must be included in your `columns` prop
