### ISSUE TITLE
Download button?

### ISSUE THREAD

**Issue by arstanton** [matfish2/vue-tables-2#270]
- Vue.js version: 2.1.10
- consumed using: webpack
- FULL error message (including stack trace): None
- relevant code: N/A
- steps for reproducing the issue:
Is there a way to download the contents of the table to an excel file?

**Comment by matfish2** [comment]
You can fetch the current dataset\request parameters off the table (scan the data using Vue Devtools to find what you need), pass it to the server and create an excel file. This is out of the scope of a client library.
