### ISSUE TITLE
Heading, how to implement click event, and show icon conditionally?

### ISSUE THREAD

**Issue by akhchan99** [matfish2/vue-tables-2#273]
With the custom heading,

```
headings: {
  selection: function (h) {
    return <div><i class='fa fa-square-o'></i><i class='fa fa-check-square-o'></i></div>
  },
```

how do I implement a click event and conditionally show one of the two icons?
as **JSX** can't use **v-if** and **@click**

let say I have a vue methods - toggleAll (to toggle selection on/off), and vue computed value - allSelected (to determine if all records were selected)

I could implement all of them outside of the vue-tables-2 components, but it just doesn't feel right not having a Select All Checkbox above the Checkbox column

Thanks

**Comment by matfish2** [comment]
I've recently implemented a "mark all" functionality in one of my projects. Here is the relevant stripped down code:

```vue
<v-server-table ref="table"
:url='url' 
:options="options" 
:columns="Columns">

<div slot="filter__id">
	<input type="checkbox" 
          class="form-control" 
           v-model='allMarked' 
           @change="toggleAll()"/>
</div>	

<template slot="id" scope="props">
<input type="checkbox" 
       @change="unmarkAll()" 
         class="form-control" :value="props.row.id" 
         v-model="markedRows"/>
</template>

</v-server-table>
```

```js
{
...
data() {
   return {
     options:{
      filterable:['column1','column2'] // omit the `id` column
  },
     allMarked:false,
     markedRows:[]
    }
  },
  methods:{
    unmarkAll() {
	this.allMarked=false;
	},
     toggleAll() {
	this.markedRows = this.allMarked?this.$refs.table.data.map(row=>row.id):[];
   }
...
}
```

**Comment by akhchan99** [comment]
I figure out an alternative option, as I don't want to use filter by column and the checkbox on a filter by column row.

I utilize the h__ scopedSlot, here is my codesnip

```
<v-client-table ref="table" :data="data" :columns="columns" :options="options">
  <template slot="h__selection" scope="props">
    <i class="fa fa-check-square-o" v-if="allSelected" @click="toggleAll()"></i>
    <i class="fa fa-square-o" v-else @click="toggleAll()"></i>
  </template>
  ...
</v-client-table>
```

where **h__selection** => **selection** is the column name
