### ISSUE TITLE
Ability to refresh filterList options

### ISSUE THREAD

**Issue by vpillinger** [matfish2/vue-tables-2#275]
It would be nice to have the ability to refresh the options on a list filter. Sometimes the options to filter by are not known on instantiation. In my case, I get the drop-down options from an API based on the users permissions and items in the database. This creates challenges because the a-sync call does not finish until after the component is mounted.

**Comment by matfish2** [comment]
Simply update the `options` prop value (not the prop itself, as it should be immutable). E.g

```js
this.myOptions.listColumns.pet.push({id:'dog',text:'Dog'}); // 
```
