### ISSUE TITLE
Server table loading error event

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#276]
- Vue.js version: 2.3.3
- consumed using: webpack

Hi, @matfish2 ! Is there any way to get error payload in `vue-tables.error`? For example, error message text is generated on server and i want to display it properly in other component. I use it like
```
  Event.$on('vue-tables.loaded', (e, payload) => {
   // but there are no any e info or payload info
  });
```

**Comment by matfish2** [comment]
As documented there is an event dedicated for catching the error: `vue-tables.error`. Sends through the response.

**Comment by VladZen** [comment]
Sorry, that was my stupidity
