### ISSUE TITLE
[Question] Templating in cells and dynamic count of colums.

### ISSUE THREAD

**Issue by jagst** [matfish2/vue-tables-2#278]
Hi!
I have two questions:
1) Is it possible to have dynamic count of columns depending on what I got back from the API?
2) Is there a way for templating in cells.
Both for v-client-table.

Thanks, Alex

- Vue.js version: 2.3.3

**Comment by matfish2** [comment]
1. I am not sure what you mean by "dynamic count of columns". If you mean add or removing columns dynamically, than yes, simply change the `columns` prop value and vue's magical reactivity should take care of the rest.
2. Again, not sure I understood. I assume you meant to ask if there is a way to render a template only on specific cell(s). Well, the `templates` options applies to the entire column. However, you can use a conditional in a template function to render it only in specific cells. E.g (Using JSX):

```js
name(h, row) {
   if ([4,6].includes(row.id)) 
      return <div>My template: {row.name}</div>;

return row.name;
}
```
