### ISSUE TITLE
[Question] How to show numbers of records filtered compared to total and set the pagination list correctly ?

### ISSUE THREAD

**Issue by kikan** [matfish2/vue-tables-2#280]
- Vue.js version: 2.4.2
- consumed using: webpack

```html
<v-server-table url="/instruments.json" :columns="columns" :options="options" />
```

I've got a database table containing 562 records.
I type in the filter to get 16 revelant records (according to my filter) ; my server returns 16 records over a total of 562.

But the footer doesn't show how many records are found by the filter and the pagination still show 10 pages whereas there can only be 2 pages (to contain 16 records, as a I left the pagination to 10 by default).

I mean, I see this :
```<<|<|1|2|3|4|5|6|7|8|9|10|>|>>```
```Showing 1 to 10 of 562 records```

and I'd like to see something like that :
```<<|<|1|2>|>>```
```Showing 1 to 10 of 16 records found over a total of 562 records```

**Comment by matfish2** [comment]
As the docs indicate you need to return the total count from your server. The server component is agnostic, i.e it doesn't know the total count of your dataset unless you inform it.

Considering the small number of records (unless it is expected to grow significantly) I would suggest using the **client** component (`v-client-table`) instead. This will save you all the hassle of writing your own backend to handle pagination, filtering, sorting etc.
