### ISSUE TITLE
Change child row toggler position

### ISSUE THREAD

**Issue by blendsoft** [matfish2/vue-tables-2#281]
How to change position of column .VueTables__child-row-toggler ?

**Comment by matfish2** [comment]
The toggler position is currently hard-coded as the first column. Changing it would require using a custom template for the table (see docs) or forking the repo. I suppose you want it positioned as the last column?

**Comment by blendsoft** [comment]
exactly I need it at last column

**Comment by terryw3316** [comment]
@blendsoft 

Its a bit hack-y but I was able to get around this by hiding the toggle column using CSS and using the toggle function to toggle the child row with a button in the final column.

**Comment by matfish2** [comment]
I've added a `childRowTogglerFirst` option. It defaults to `true`, so just set it to `false` and the toggler will appear on the last column.

**Comment by blendsoft** [comment]
thank you
