### ISSUE TITLE
Filter, Sort Client Side but Pagination Server Side

### ISSUE THREAD

**Issue by phamvanthanh** [matfish2/vue-tables-2#282]
Hi @matfish2,
I am trying to take the advantages of Pagination Server side but Filter and Sort Client Side. 
I think this will help best perform when working with the table. 
However, if that is not available I would like to disable built-int page LIMIT as well as  dropdown  pagination and implement separate ones.
Could you please give some advises? 

Thank you

**Comment by AngryElephant** [comment]
Why this has been closed  ?
