### ISSUE TITLE
How to render a column data that is a boolean?

### ISSUE THREAD

**Issue by jocII** [matfish2/vue-tables-2#283]
- Vue.js version: 2.4.2
- consumed using: webpack
- FULL error message (including stack trace): N/A
- relevant code: N/A
- steps for reproducing the issue:
Build an array of data that includes objects with a boolean value. That column is rendered empty.....

Ex. [
     {id: 1, name: 'Joe', active: true},
     {id: 2, name: 'Bob', active: false}
]

**Comment by matfish2** [comment]
Use the templates option to define the representation of the boolean value

**Comment by matfish2** [comment]
E.g:

```js
templates:{
    active: function(h, row) {
      return row.active?'ACTIVE':'INACTIVE';
  }
}
```
