### ISSUE TITLE
Can a column be populated by a nested field?

### ISSUE THREAD

**Issue by jocII** [matfish2/vue-tables-2#284]
- Vue.js version: 2.4.2
- consumed using: webpack
- FULL error message (including stack trace): N/A
- relevant code: N/A
- steps for reproducing the issue:

I have a result that has nested fields like this:
[
{ id: 1, name: 'Joe', data: { testing: 'yes'}}
]

How can I include the testing field in the column list?

I tried columns: ['id', 'name', 'data.testing'], but this did not work.

Thanks.

**Comment by matfish2** [comment]
Use `templates`:

```js
{
columns:['id','name','test'],
templates:{
   test(h, row) {
    return row.data.testing;
  }
 }
}
```

**Comment by techytuppers** [comment]
Hey @matfish2 - I came across the same problem, and your solution works great for displaying the data in the table. Unfortunately the data isn't filterable though. Is there something else that needs to be implemented for that to work? Many thanks!

**Comment by matfish2** [comment]
The data isn't filterable because the template is a "fake" column.
This can be solved by applying the template to an actual column. 
Then the filtering will refer to the underlying column.

**Comment by matfish2** [comment]
There is currently no support for search inside objects. 
For a column to be filterable it must:
A. Exist in the original dataset (i.e not be a fake column)
B. Be a primitive value (i.e string or number), with the exception being date fields, which have their own filter.

**Comment by techytuppers** [comment]
Okay thanks @matfish2 - I will process my data object to make the structure flat, and then use it as a real column.
