### ISSUE TITLE
No auto ordering/sort?

### ISSUE THREAD

**Issue by KsCorrales** [matfish2/vue-tables-2#285]
- Vue.js version: 2.2.1
- webpack

How can I prevent table ordering at first column? before i use the ids in first column and sort works good because the rows are ordered by the id, but now i remove the id column, and now is ordering by name, i wish prevent automatic ordering before click in headings, this is possible?

**Comment by matfish2** [comment]
Have you upgraded to the most recent version?
As of version `0.6.7` there is no more default sorting by first column.
