### ISSUE TITLE
URL params not sync

### ISSUE THREAD

**Issue by phamvanthanh** [matfish2/vue-tables-2#286]
Hi @matfish2,
When passing computed `options {params{} }` along with the request It does not sync. It always go behind one step.
In vue devtool, it shows the `v-server-table` the `params` updated correctly but the request  `params` always go behind one step.

OR to 
`setTimeout(function(){
   this.$refs.table_ref.refresh(), 1
})`
as a solution

**Comment by vincent-lu** [comment]
@phamvanthanh any reason for closing this one? I'm running into the same problem and for now had to use setTimeout to circumvent the issue.
