### ISSUE TITLE
data.map is not a function on server-side with custom requestFunction

### ISSUE THREAD

**Issue by jigarzon** [matfish2/vue-tables-2#288]
- Vue.js version: 2.3.4
- consumed using: webpack
- FULL error message (including stack trace):
```
Uncaught (in promise) TypeError: data.map is not a function
    at VueComponent.module.exports (apply-filters.js?c856:4)
    at VueComponent.boundFn [as applyFilters] (vue.runtime.esm.js?ff9b:164)
    at VueComponent.module.exports (set-data.js?1d48:4)
    at VueComponent.boundFn [as setData] (vue.runtime.esm.js?ff9b:164)
    at VueComponent.eval (v-server-table.js?44f6:82)
    at <anonymous>
```
- relevant code:
Component:
```
<v-server-table url="/people"
                    :columns="columns"
                    :options="options">
```
Data table options:
```
options: {
        requestFunction: (data) => {
          let req = this.$auth.httpConfig();
          req.url = "/people";
          req.method = 'get';
          req.data = {
            params: data
          };
          return this.$http(req).catch(function(e) {
            //this.dispatch('error', e);
          });
        }
      }
```
Server response:
```{"data":[{"first_name":"Ryan","last_name":"Chenkie","email":"ryanchenkie@gmail.com"},{"first_name":"Chris","last_name":"Sevilleja","email":"chris@scotch.io"},{"first_name":"Holly","last_name":"Lloyd","email":"holly@scotch.io"},{"first_name":"Adnan","last_name":"Kukic","email":"adnan@scotch.io"},{"first_name":"Leonel Adri\u00e1n","last_name":"Silva","email":null}],"count":5}```
- steps for reproducing the issue:

It seems that `map` function is called on the base object, it should be: `data.data.map`

**Comment by matfish2** [comment]
Try the `responseAdapter`:

```js
responseAdapter: function(resp) { 

var d = resp.data;

return { 
             data: d.data, 
             count: d.count 
   } 
}
```

**Comment by jigarzon** [comment]
Thanks that worked!

**Comment by alexeycrystal** [comment]
Thanks a lot! This issue is also solved to me!
