### ISSUE TITLE
Define custom value field for listColumn array

### ISSUE THREAD

**Issue by Sharvadze** [matfish2/vue-tables-2#289]
Hi, I have a quick question regarding the listColumns. Is it possible to change the value field, and instead of "text" use name for example. Couldn't find in the documentation, any help is greatly appreciated

Thanks

**Comment by matfish2** [comment]
I am not sure I understood the question. If you are asking whether the `id` and `text` **keys** are changeable, then the answer is no. If your list options are coming from the server in a different format, and you can't control the response, you can map over your array on the client-side and match it to the required format.

**Comment by Sharvadze** [comment]
@matfish2 yes, that was the question. Thanks, I changed the object keys on my side and it works fine
