### ISSUE TITLE
define deafault sort column

### ISSUE THREAD

**Issue by DeepakAryal** [matfish2/vue-tables-2#290]
I have many column in table but initially on table loading, i want to sort data according to specific column. is it possible??

**Comment by Sharvadze** [comment]
Check out the [documentation](https://github.com/matfish2/vue-tables-2#options)

<img width="891" alt="screen shot 2017-10-06 at 3 53 11 pm" src="https://user-images.githubusercontent.com/964784/31281063-a7336b9a-aaae-11e7-96ae-6b129e5899a1.png">

**Comment by DeepakAryal** [comment]
thank you.
