### ISSUE TITLE
costumized rendered output

### ISSUE THREAD

**Issue by t0n1zz** [matfish2/vue-tables-2#296]
hi, i looking for a way to costumize the rendered table... like 

1. how do i add my own class to header/thead? 
2. how do i change output from server or json? like i want to change 1 and 0 value from some column into checklist icon and ban/cancel icon? or i want to change my timestamp value from laravel created_at into something more easy to read like dd-mm-yyyy only?
3. how to rearrange or add some class or div into other component beside table itself? like pagination button style and position? or like selectbox for show per_page or information label showing total enty?
4. how do i get the data on selected row? i.e i want to put button that will act as edit or delete for those row?
5. how to hide entire column? since i want to add hide/show column toggle?
6. how to do row grouping?

**Comment by matfish2** [comment]
1. You can't, unless you use a [custom template](https://github.com/matfish2/vue-tables-2#installation) for the table.
2. use the [templates](https://github.com/matfish2/vue-tables-2#templates) option
3. Open vue devtools, explore the data which is available, get it using a `ref` on the table, and use it in the other component. Or, if you are using `Vuex`, this data will be available on the store.
4. check out https://github.com/matfish2/vue-tables-2/issues/298#issuecomment-340204780
5. simply manipulate the value of your `columns` prop.
6. Not supported at the moment.
