### ISSUE TITLE
Unknown custom element: <v-server-table> - did you register the component correctly?

### ISSUE THREAD

**Issue by zeeshanyshaikh** [matfish2/vue-tables-2#299]
- Vue.js version: 2.4.2
- consumed using: webpack
- FULL error message (including stack trace):

> [Vue warn]: Unknown custom element: <v-server-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
> (found in <Root>)
> warn @ app.js:sourcemap:1984
> 20:37:58.708 

- relevant code:
It's showing the same error for me. I am using Laravel and Webpack. Below is my settings

> resources/assets/js/app.js
```javascript
window.Vue = require('vue');
import {ServerTable, ClientTable, Event} from 'vue-tables-2';

Vue.use(ServerTable, {}, false, require('../vuetable/compiled/v-server-table.js')('server'));
```
I have copied the "complied" folder and placed in my resource/assets directory under folder "vuetable"
i tried both lines of code, but both failed
> Vue.use(ServerTable, {}, false, require('../vuetable/compiled/v-server-table.js')('server'));

>Vue.use(ServerTable, {}, false, require('../vuetable/compiled/template.js')('server'));

> index.blade.php
```html
<div class="box-body">
    <v-server-table url="{{ route('users.data') }}" :columns="columns" :options="options" name='serverTable'></v-server-table>
</div>
```

**Comment by alaevka** [comment]
+

**Comment by zeeshanyshaikh** [comment]
Any update on this?

**Comment by matfish2** [comment]
Do you get this error even when NOT using  a custom template?
