### ISSUE TITLE
Bus is not listening to event?

### ISSUE THREAD

**Issue by forddyce** [matfish2/vue-tables-2#3]
- Vue.js version: 2.0.1
- consumed using: browserify
- issue:

Trying to convert date string to moment using server side tables. console.log('test') does not run, do I have to import. Checked the `bus` value and it appears the $children is an empty array so I'm guessing the bus is not linked to the table. How do you listen to the event properly?

- relevant code:
the html:
`<v-server-table url="/items" :columns="columns" :options="options" ref="listTable"></v-server-table>`

the js:
```
import moment from 'moment'
import bus from 'vue-tables-2/lib/bus'
import ShowLink from './../../components/button/showlink.vue'
import EditLink from './../../components/button/editlink.vue'
import DeleteLink from './../../components/button/deletelink.vue'

var tableColumns = ['name', 'stock', 'sku', 'price', 'created_at']
var options = {
  pagination: {
    dropdown: true,
    chunk: 10
  },
  filterByColumn: true,
  dateColumns: ['created_at'],
  toMomentFormat: true,
  texts: {
    limit: 'Records: '
  },
  datepickerOptions: {
    showDropdowns: true
  },
  debounce: 1000,
  headings: {
    name: 'Nama',
    stock: 'Stok',
    sku: 'SKU',
    price: 'Harga',
    created_at: 'Tanggal',
    action: 'Actions'
  },
  templates: {
    action: function (h, row) {
      return <div class="btn-group">
        <show-link id={row.id} module="item"></show-link>
        <edit-link id={row.id} module="item"></edit-link>
        <delete-link id={row.id} module="item" table={this.$refs.listTable}></delete-link>
      </div>
    }
  },
  customFilters: [
    {
      name: 'formatDate',
      callback: function (row) {
        console.log(row.created_at)
        var value = row.created_at
        if (value == null) return ''
        var fmt = (typeof fmt === 'undefined') ? 'D MMM YYYY' : fmt
        return moment(value, 'YYYY-MM-DD').format(fmt)
      }
    }
  ]
}

export default {
  name: 'ItemList',
  data: function () {
    return {
      elink: '#',
      options: options,
      columns: tableColumns
    }
  },
  components: {
    ShowLink: ShowLink,
    EditLink: EditLink,
    DeleteLink: DeleteLink
  },
  mounted () {
    document.title = 'List Item - PT. Sukses Mandiri'
  },
  created () {
    this.$on('id-selected', function (e) {
      this.elink = '/item/edit/' + e
    })

    bus.$on('vue-tables.loaded', function () {
      console.log('test')
      bus.$emit('vue-tables.filter::formatDate')
    })
  }
}

```

**Comment by forddyce** [comment]
Interestingly enough, `vue-tables.loading` does work. But that's on request fired, not after all the data was loaded.

**Comment by matfish2** [comment]
I'm not sure what you are trying to accomplish.
Converting dates to `moment` objects  only makes sense in the **client** component where the data is filtered and sorted by the client. It has no use in the server component where you sort and filter on the server side.
For the same reason, custom filters only receives a callback on the **client** component. On the server component you pass a simple array of strings. When an event is fired the filter value is sent to the server, where it should be handled.

This is all in the docs, and marks the fundamental difference between the client and server components.

**Comment by matfish2** [comment]
As for the event issue, to detect the inital response move the listener from the `created` to the `mounted` method

**Comment by forddyce** [comment]
I was about to filter using daterangepicker on date filter column, but it won't run at all, and since your docs said it has to be moment object then I thought maybe because my created_at data is a string then I have to convert it to moment.

So, as I understand by your response, it's not possible to pick from 2 date ranges? If possible, I would really love to see a simple example (I'm using laravel eloquent as server side, but any code from yours is welcome).

On your example:

$start = Carbon::createFromFormat('Y-m-d',$query['start'])->startOfDay();
$end = Carbon::createFromFormat('Y-m-d',$query['end'])->endOfDay();

`start` and `end` does not exists as params, where do these come from?

**Comment by matfish2** [comment]
Using `daterangepicker` doesn't require any conversion from you side. The date range is sent as request parameters. 
I have just double checked it on my end and everything seems to be in order.
When I apply the filter a request is sent containing the following params:

```js
query[year][start]:2016-09-27
query[year][end]:2016-10-05
```

**Comment by forddyce** [comment]
This is my request params in console: http://imgur.com/a/iU5HS

ascending	1
byColumn	1
limit	10
orderBy	name
page	1
query[created_at]	
query[name]	
query[price]	
query[sku]	
query[stock]

**Comment by matfish2** [comment]
Are these the params you see after selecting a daterange?
Does selecting the daterange trigger a request?

**Comment by forddyce** [comment]
My date filter does not even have a range, that's why I'm trying to make it work.

When I have no `dateColumns` option: http://imgur.com/a/2N7gM
When I have `dateColumns: ['created_at']` option (that `Filter by date` button does not work, clicking does not do anything, the range picker is not showing, I have tried input the bootstrap datepicker as separate file, did not work): http://imgur.com/a/xorC8

**Comment by matfish2** [comment]
Ok. So it is a problem of initializing the `daterangepicker` itself.
You need to include JQuery + moment + Daterangeicker as GLOBAL dependencies. This can be done either by using script tags before the your own script or inside your script like so:

```js
window.$ = window.jQuery = require('jquery')
window.moment = require('moment')
require('daterangepicker')
```

**Comment by forddyce** [comment]
Still not working (clicking the filter button does not work), this is my entire entry point (index.js):
```

window.$ = window.jQuery = require('jquery')
window.moment = require('moment')
require('bootstrap')
require('daterangepicker')

import Vue from 'vue'
import VueResource from 'vue-resource'
import VueRouter from 'vue-router'
import VuexRouterSync from 'vuex-router-sync'
// import VueTables from 'vue-tables-2'

import ExtendDisableButton from './utils/ExtendDisableButton'
import ExtendForm from './utils/ExtendForm'

import routes from './app/routes'
import store from './app/store'

new ExtendDisableButton() // eslint-disable-line no-new
new ExtendForm() // eslint-disable-line no-new

$.ajaxSetup({ // TODO: need to remove this
  crossDomain: false,
  dataType: 'json',
  cache: true,
  async: false,
  headers: {
    'X-CSRF-Token': $('meta[name="_t"]').attr('content')
  }
})

Vue.use(VueResource)
Vue.http.headers.common['X-CSRF-Token'] = $('meta[name="_t"]').attr('content') // eslint-disable-line no-undef
store.dispatch('checkAuthentication')

Vue.use(VueRouter)

export const router = new VueRouter({
  mode: 'history',
  routes
})

router.beforeEach((to, from, next) => {
  if (to.matched.some(m => m.meta.auth) && !store.state.auth.authenticated) {
    next({
      name: 'admin.login'
    })
  } else if (to.matched.some(m => m.meta.guest) && store.state.auth.authenticated) {
    next({
      name: 'admin.index'
    })
  } else {
    next()
  }
})

VuexRouterSync.sync(store, router)
Vue.router = router

var VueTables = require('vue-tables-2')
Vue.use(VueTables.server)

import * as App from './app/index.vue'

new Vue(App).$mount('#root')

```

**Comment by matfish2** [comment]
You must have some non-related JS error in the console which halts execution (I have seen one in one of the images that you have sent).

**Comment by forddyce** [comment]
Ok I know the problem now, my table column has the "action" column for buttons, which i didn't define on tableColumns array. I do wish the error is more generic though, thanks for your reply and help.

And for those newbie in the future that need help, you do have to import daterangepicker and moment library by yourself since the package does not have them by default (at least not in my case).

**Comment by szabomikierno** [comment]
Hey,

I'm having the same issue (I think), I'm loading moment and  daterangepicker globally:

```
window._ = require('lodash');

window.$ = window.jQuery = require('jquery');

window.moment = require('moment');
require('daterangepicker');

require('bootstrap-sass');

import Vue from 'vue';
import VueRouter from 'vue-router';
import VueResource from 'vue-resource';


import axios from 'axios';
import noty from 'noty';
import sweetalert from 'sweetalert';

window.Vue = Vue;
Vue.use(VueRouter);

window.axios = axios;
window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest'
};
```


```
import {ServerTable, Event} from 'vue-tables-2';
Vue.use(ServerTable, {
    filterByColumn: true,
    compileTemplates: true,
    responseAdapter: function (resp) {
        return {
            data: resp.data,
            count: resp.total
        }
    },
    templates: {
        open: 'open-vuetable-resource'
    },

    sortIcon: {
        base:'fa',
        up:'fa-sort-amount-asc',
        down:'fa-sort-amount-desc'
    },
    rowClassCallback: function(row) {return `row-${row.id}`},

    datepickerOptions: {
        showDropdowns: true
    }
});

Vue.component('open-vuetable-resource', {
    props: ['data'],
    template: `<a :href="data.ShowAdmin" class='btn btn-primary'><i class="fa fa-eye"></i></a>`
});
```


```
$(document).ready(function() {
    new Vue({
        el: "#people",
        data: {
            columns: ['id', 'username', 'email', 'created_at', 'open'],

            options: {
                filterable: ['id', 'username', 'created_at', 'email'],
                sortable: ['id', 'username', 'created_at', 'email'],
                dateColumns: ['created_at']
            }
        }
    });
});

```

I have no console errors, any ideas on why daterangepicker is not showing up?

Thanks

**Comment by SwithFr** [comment]
Same problem. Datepickerrange is not showin up. I'have a similar code than @szabomikierno 

Any idea ?

**Comment by boriskogan81** [comment]
+1

**Comment by sublimedatasys** [comment]
+1
