### ISSUE TITLE
I got this issue

### ISSUE THREAD

**Issue by mdanielarena** [matfish2/vue-tables-2#300]
Cannot find module "./template.js"
    at webpackMissingModule (admin_books.vue:12)
    at Object../node_modules/babel-loader/lib/index.js?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread"]}!./node_modules/vue-loader/lib/selector.js?

**Comment by matfish2** [comment]
Please paste your code (HTML and JS).
