### ISSUE TITLE
is the row index retrievable when using the server table?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#302]
I have hundreds of records that I am fetching via the v-server table. They are paginated and in one of my custom templates I would like to retrieve the row index. So if I have 10 rows per page on page 4 the 5th item would have a row index or '45'

Is there any way to retrieve this information from within the table custom template?

**Comment by matfish2** [comment]
I've added index retrieval to all template options. Please see docs.

**Comment by vesper8** [comment]
awesome thank you!
