### ISSUE TITLE
problem with using uncomiled custom templates 

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#303]
Hi there!

I'm running into two problems using custom templates.

The first is that, it seems I can only get one of my tables to use a custom template if it's the only table on the page. On pages that have more than one table, it seems the custom templates are completely ignored

How can I use two tables on the same page with custom templates if one is using the default template and the other is using a custom template?

Edit: I tried defining custom templates for ALL tables on the page and it seems all tables use whatever custom template the first table defines.. subsequent custom templates are ignored and only the first is used

Second problem is.. I installed the JSX compiler and tried using the uncompiled JSX lib/templates.js as well as the files inside /lib/templates/*

I get this error during compilation

```
[Vue warn]: Error in render: "TypeError: that.columnClass is not a function"
```

Am I not supposed to use the uncompiled jsx templates ?

It seems I can use a combination of the uncompiled templates.js with the compiled templates/* files

Is the option of using uncompiled JSX vs compiled JSX just a convenience when making edits to the template?

Thanks!

**Comment by matfish2** [comment]
A. wasn't able to reproduce. I need to see your code (HTML and JS or .vue file)
B. Again, wasn't able to reproduce (used JSX version). And to answer your question, yes, it is only a convenience. You can use the compiled version if you can't be bothered with installing the jsx compiler.

**Comment by vesper8** [comment]
Here I can show you what I mean. What I want is to be able to display these two tables on the same page and have a 'toggle' button to allow to switch between one or the other

One table, table layout: https://www.facesofgaming.com/games?mode=list
One table, grid layout: https://www.facesofgaming.com/games?mode=grid
Two tables on same page: https://www.facesofgaming.com/games?mode=both

As you can see, the first two work well on their own, but if I try to have both of them on the same page, then the custom template that I am declaring in the 2nd table (the grid layout) is ignored

List layout:

```
    import {ClientTable} from "vue-tables-2";
    Vue.use(ClientTable);
```

Grid layout:

```
    import {ClientTable} from "vue-tables-2";
    Vue.use(ClientTable, {}, false, require('./template-uncompiled-grid.js')('client'));
```

It doesn't matter whether the list is first or the grid is first. If a non-custom-template table is used on the page.. the one with the custom template is ignored

**Comment by matfish2** [comment]
`Vue.use` registers the component globally, and should be called only once.  If called more than once, the command is ignored and the first registration holds.

So, I don't know if you can use two different global settings for a component on the same page.
