### ISSUE TITLE
can you add a "never" option to columnsDisplay please

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#304]
I had a situation where my only column is a template and I want to enabled filtering

Since my template is associated to a non-column, then the filtering doesn't work.

I can add the column I want to filter by + the template but now I am showing an extra column which I do not want

So I looked into how I can hide that column. Using columnsDisplay works easily but there is no way to completely hide the column that way. I can only hide it for all screen sizes except one (mobile for example)

So in the end the solution is to attach the template to the existing column which resolves the problem.. but it's not a pretty solution

An easy solution would be to add an extra option to the columnsDisplay so that this column would be *always* hidden

**Comment by matfish2** [comment]
I have a simpler, and I believe, more elegant, suggestion. Declare the column you want to filter by in the `columns` array, and make the very same column a template.

**Comment by vesper8** [comment]
As I wrote `So in the end the solution is to attach the template to the existing column which resolves the problem.. but it's not a pretty solution` that is exactly what I ended up doing.. however I don't consider this an elegant solution.. rather I consider it kind of a hack.

What if I wanted to allow two columns to be filterable but I only want to use one column/template ?

**Comment by matfish2** [comment]
I don't know why you think this is a hacky approach. You declare only the column you need, and derive the properties for the template from an extra property, which can be one object containing all the additional data for other templates.

I don't understand what you mean by 

> What if I wanted to allow two columns to be filterable but I only want to use one column/template ?

**Comment by vesper8** [comment]
hrmm.. that's weird.. I could have sworn that previously I wasn't able to add columns to the filterable array if they weren't also included in the columns array. But now I see that it works.. I did recently update to the latest version so maybe that's why it wasn't working before.

Now I can see that you can have columns in filterable but not in the columns array and the filtering works fine

Seems all is good now. Thanks!
