### ISSUE TITLE
Initial page in server-side table

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#306]
- Vue.js version: 2.3.3
- consumed using: webpack

Hi, @matfish2 . Is there any way to set initial page in server-side table? For example: i want to share exact state of table with filters, sorting, even exact page number. I have some url with initial params for table , set with get params `?day=10%2F18%2F2017%2000%3A00%20-%2010%2F18%2F2017%2023%3A59&groupBy=&landerId=&ascending=0&orderBy=group&page=1`.
I have found workarounds for all these parameters except page number.

**Comment by matfish2** [comment]
Added an `initialPage` option. See docs.

**Comment by vesper8** [comment]
@matfish2 I just noticed if you have the initialPage set, but then you use another filter.. search as the filterable, when you empty out the filter after using it, it doesn't revert to the initialPage, it just goes back to the first page

**Comment by AyushiBShah** [comment]
Any progress on this?
