### ISSUE TITLE
The table data clone is too slow in filtered-data.js

### ISSUE THREAD

**Issue by jeanaio** [matfish2/vue-tables-2#307]
I use vue-tables-2 Client Side mode. I have 31238 records data. 
![clone is too slow](https://user-images.githubusercontent.com/21098191/31807539-536bcafe-b5a1-11e7-89de-8045e811c6b9.png)

**Comment by matfish2** [comment]
The client side table is not meant to be used with that many records. You should consider using the server table instead.
