### ISSUE TITLE
on refresh callback

### ISSUE THREAD

**Issue by beniaminorossini** [matfish2/vue-tables-2#308]
- Vue.js version: 2.3
- consumed using: webpack

It is possible to run a callback after refreshing table? Typical scenario would be ondeleting row event to remove spinner overlay after correct table refresh.
If it is not possible, i can help to improve...

**Comment by beniaminorossini** [comment]
I'have found events, sorry.

**Comment by beniaminorossini** [comment]
I have see that we can use events, but seems that on refresh only loading is fired, no loaded.
I think it could be a bug.

**Comment by beniaminorossini** [comment]
I have see that we can use events, but seems that on refresh only loading is fired, no loaded.
I think it could be a bug.

**Comment by VladZen** [comment]
@beniaminorossini i'm using `loaded` event successfully, but the only situation, when it doesn't fire is error in response.

**Comment by beniaminorossini** [comment]
@VladZen thx for reply.
I'm using vue tables 0.6.78 and only loading get fired (as you can see in image attached).
![schermata 2017-10-24 alle 15 33 15](https://user-images.githubusercontent.com/4621873/31946088-24db88d6-b8d1-11e7-886c-6a59e63379b3.png)

Very strange...

My code:
`<template>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <v-server-table url="" :columns="columns" :options="options" name="funds" ref="funds"
                                        @loading="toggleLoading" @loaded="toggleLoading" @row-click="showFund">
                             ...templates...
                        </v-server-table>
                    </div>
                    
                    <div class="overlay" v-show="loading">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script>
  import types from '../../store/mutation-types'
  import fundsApi from '../../api/funds'

  export default {
    data () {
      return {
        columns: [
         ......
        ],
        options: {
          headings: {
           ......
          },
          sortable: [
           ......
          ],
          requestFunction: function (query) {
            return fundsApi.index(query)
          }
        },
        loading: false
      }
    },

    methods: {
      toggleLoading () {
        this.loading = !this.loading
      }
    }
  }
</script>

<style>
    
</style>
`

**Comment by VladZen** [comment]
@beniaminorossini ![](http://joxi.ru/v29O4keiGlaXvr.jpg)
![](http://joxi.ru/DrlzN1Pt4Ookd2.jpg)
I'd like to help you, but i really don't know how.

**Comment by beniaminorossini** [comment]
@VladZen thx, but no way, nor using Event bus :(
Which versions (vuejs and vue-tables-2) are you using?

**Comment by matfish2** [comment]
@beniaminorossini , You are using a custom request function which overrides the original. I suspect I has something to do with it.
Please go to `set-data.js` and `console.log('dispatched loaded event')` after line 8. Let me know if the message shows in the console when you refresh.

**Comment by beniaminorossini** [comment]
@matfish2 thx for reply.
No message displayed after each request (refresh, initial load, change page, etc.)

**Comment by matfish2** [comment]
A. Comment out `requestFunction` temporarily and make sure this is where the problem lies.
B. If this is the source (and I'm quite sure it is), make sure that your custom request function returns _a valid `promise`, which fires a `then` method._ Look at set-data:24, where the `promise` is saved, and 28 where the `then` callback is invoked. (All ajax libraries which are supported by default return a valid promise).

**Comment by beniaminorossini** [comment]
@matfish2 `requestFunction` removed, but no way, same result (no `loaded` event fired...)
I can not find set-data:24, file's rows are 10... maybe i look for qrong file? or i'm using a wrong version of package? `"vue-tables-2": "^0.6.78",`

**Comment by matfish2** [comment]
Sorry, my bad, the file is `get-data.js`.

You say you removed `requestFunction` and still no `loaded` event. Do you have one of the following ajax libraries: JQuery, vue-resource or axios? Is the library available on the `window` scope? (Look at the console and see if there is an error related to this). Is the data itself being loaded to the view?

The most recent version if `0.6.82`.

**Comment by beniaminorossini** [comment]
No errors for the libraries (no error or warning at all).
Look if it is useful this screenshot sf get-data status (it seems to be ok, no?)
![schermata 2017-10-30 alle 10 17 52](https://user-images.githubusercontent.com/4621873/32163176-be9c69b6-bd5b-11e7-9c6a-cc4f1f5713a1.png)

**Comment by beniaminorossini** [comment]
@matfish2 i'm using `vuex`! 
If i set it to false on initialization, then every events are emitted correctly.... Sorry, but i was a bit confused by Events documentation and i was expecting events would be emitted as well (not only vuex dispatch).
So the new question: it is not possible to emit events also when using vuex? 
Or is a design error?

**Comment by matfish2** [comment]
In older versions bus events were indeed not emitted when using `vuex`. I've recently changed it to allow more flexibility, so please update to the most recent version (0.6.8.3) and see whether you get the event or not.

**Comment by beniaminorossini** [comment]
@matfish2 just upgraded to 0.6.83 but no events emitted...

**Comment by beniaminorossini** [comment]
@matfish2 do you have read my last response? i have upgraded but no luck with events... Source code at the relevant parts seems to be untouched. Maybe i am wrong?

**Comment by matfish2** [comment]
Yes, sorry, I won't be able to work in it before Saturday. 
In the meantime, try to do some debugging by yourself.  Follow the route which starts at `get-data.js` and sprinkle `console.log` along the way. This will tell you where the problem lies. You can also start from the end (i.e `dispatch.js`) and go backwards.
 
The event is dispatched in `set-data.js`:
```js
module.exports = function (data) {
  this.data = this.applyFilters(data.data);
  this.count = parseInt(data.count);

  setTimeout(function () {
    this.dispatch('loaded', data);
  }.bind(this), 0);
};
```

**Comment by beniaminorossini** [comment]
@matfish2 no problem ;)
for now i think it would be safe to move` this.dispatch('loaded', data);` from `set-data.js` to `get-data.js` in promise.then callback (`this.dispatch('loaded', data);` is already in `get-data.js`).
What do you think?

**Comment by matfish2** [comment]
Sure, if you tried and it works then why not.

Sent from Mail for Windows 10

**Comment by matfish2** [comment]
@beniaminorossini , any luck? Did you find out if the event is dispatched?

**Comment by beniaminorossini** [comment]
@matfish2 yeah, it works! Can i send you a PR?

**Comment by matfish2** [comment]
I don't really want the event to be dispatched in `get-data.js`. It belongs after the data was assigned in `set-data.js`. If for some reason it is not dispatched there I want to figure out why.

**Comment by beniaminorossini** [comment]
I do not understand if you really want to emit event and vuex dispatch at the same time. 
The issue is about that.
If you don't want to emit `loaded` event in `get-data.js`, we can put it in `state/vuex.js`?
Something like that:
`function serverExtra() {
  return {
    methods: {
      setData: function setData(_ref) {
        var data = _ref.data,
            count = _ref.count;

        this.commit('SET_DATA', { data: data, count: count });
        this.commit('LOADED', { data: data, count: count });

        setTimeout(function () {
          this.dispatch('loaded', data);
        }.bind(this), 0);
      }
    }
  };
}`

What do you think about it?

**Comment by matfish2** [comment]
Merged. Thanks
