### ISSUE TITLE
Adding child row functionality

### ISSUE THREAD

**Issue by metamet** [matfish2/vue-tables-2#31]
It would be immensely helpful to have an innate method to toggle a child row that has a single td with colspan equal to the number active cols.

For reference, here's DataTable's implementation: https://datatables.net/examples/api/row_details.html

**Comment by metamet** [comment]
Hey @matfish2 ,

Thanks for a quick turn around on this.

A couple things: 

- It appears that toggling one row toggles all of them? 
- I would like to have the content render conditionally for each row (as in v-if) after starting off collapsed, and I am uncertain if this is the default behavior. 
- It would also be nice to use straight HTML instead of the css switching for this. A toggle I would like to use is used like this: 

```
        <div class="togglebutton">
            <label>
                <input type="checkbox" v-model="historyVisible" v-bind:true-value="true" v-bind:false-value="false"><span class="toggle"></span>
            </label>
        </div>
```

So perhaps a more flexible way of handling this would be 

```
options:{
    ...
    child: {
        row: function(h, row) {
            return <div>My custom content for row {row.id}</div>
        }, 
        toggle: function(h, row) {
            return ... 
        }
```
        
I haven't fully thought out that implementation, but hopefully that makes sense. It would also be a nice feature to allow the toggle position to be appended instead of prepended as well. 

Great work!

**Comment by matfish2** [comment]
* I couldn't replicate the one-toggler-toggles-all bug.
* I agree. I tried to use conditional rendering but it was more complicated than I thought. I will give it another shot.
* Not sure about this one. For one thing, using CSS is exactly the approach datatables are using. More importantly, I think it allows for more flexibility in terms of design, as opposed to being limited to a checkbox. Allowing for custom HTML for the toggler itself would be very problematic, because of the inherent logic, that the user would have to implement correctly himself. I think I will leave this one as it is.

**Comment by metamet** [comment]
* I am still getting the one one-toggler-toggles-all bug. Here's the relevant main.js, so perhaps I am misconfiguring something? https://gist.github.com/metamet/e13645ff5c5b2e9b9cfc6b3a7238b7d4
* This is understandable. Unfortunately the default styles you included in the manual aren't present in the build itself, so it requires external CSS to get child rows working and collapsed.
* Along with that, maybe including a default style in vue-tables-2 would be convenient? And perhaps an easy way of overriding it that doesn't require external css (since I am not using a .vue template for the table implementation--which maybe I should?--I have to put it on the home html page). Something like the following would be pretty universally applicable. Just thoughts here, though: 

```
.VueTables__child-row-toggler {
  width:16px;
  height:16px;
  line-height: 16px;
  display: block;
}

.VueTables__child-row-toggler--closed::before {
   content: "+";
}

.VueTables__child-row-toggler--open::before  {
    content: "-";
}

.VueTables__child-row--closed {
    display: none;
}
```

Good work.

**Comment by matfish2** [comment]
* Does your dataset have a unique `id` column? (see docs). This column is necessary for keeping track of the toggle position of each row. 
* I have added your suggested styling to the docs, and in a dedicated `style.css` file.

**Comment by metamet** [comment]
It looks like my unique ID on this server-side request is actually RequestId. Is it possible to set the unique id property to a particular column?

**Comment by matfish2** [comment]
I've added a `childRowKey` option. Use it like so:
```
{
childRow: function(h, row) {
return <div>My Row Data</div>
},
childRowKey:"RequestId"
}
```

**Comment by metamet** [comment]
Beautiful. It's working. Glad to be your personal tester here, and thanks for the quick turnaround! Very helpful feature.

For future reference, in case someone comes across this, @matfish2 's example has an opening bracket, so the ending bracket is from that (caused me a slight moment of confusion, hah): 

```
{
    childRow: function(h, row) {
        return <div>My Row Data</div>
    },
    childRowKey:"RequestId"
}
```

Great work, again.

**Comment by matfish2** [comment]
As for appending rather than prepending the toggler, I've added a custom template option which allows you to duplicate the template and modify it to your needs. You can use this option for fine-grained control over the template. It is passed as the fourth argument to the `Vue.use` statement. E.g: 
```js
Vue.use(VueTables.client, null, false, require('my-template.jsx')('client'))
```
