### ISSUE TITLE
Vuex Store Commit/Refresh

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#311]
I'm using Vuex with server tables and I am updating data (from broadcast event):
`store.commit('vSTable/SET_DATA', {data: newData, count: newData.length});`
I am using templates in the table and the data in the table is not updating after the commit (though the store shows the new data).

**Comment by matfish2** [comment]
May I ask why you need to update server data manually in the client? This is highly problematic since every time the table is reloaded your change will be overridden by the original server data.
