### ISSUE TITLE
Vue2.5

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#312]
Vue 2.5 is killing off the attribute scope and replacing it with "slot-scope". Can you update your code to work with that attribute so we don't have a plethora of compile errors?

Thanks for all your hard work, do you have a donate page?

**Comment by matfish2** [comment]
That's odd. I'm using 2.5.2 and not getting any errors. Can you post the error message? 

I don't have a donate page yet. Thanks for the suggestion.

**Comment by scs-ben** [comment]
I can't replicate, I'm not sure why. I had 2 projects throw errors but now: nothing.
