### ISSUE TITLE
Issue when sorting complex objects

### ISSUE THREAD

**Issue by anudwigna** [matfish2/vue-tables-2#313]
- Vue.js version:2.2.6
- consumed using: browserify

When the data to the table is nested objects and the column is displayed using the template, then there is problem sorting the column. 

For eg: The datasource of the table is list of bills and each bill contains student object. The name of the student is shown using the template. I am trying to sort using the student name but there is problem while sorting this field.

**Comment by matfish2** [comment]
The plugin can't magically guess how you want to sort the objects. 
You have two options: 

A. Tell it explicitly how to sort using the [customSorting](https://github.com/matfish2/vue-tables-2#custom-sorting) functionality.
B. Change your data structure: Add a property that includes only the student name as a simple string, and use it as a displayable column. Then on that same column you can define the template using the original object in your data set.
