### ISSUE TITLE
TypeError with saveState: true, filterable: false, filterByColumn: false

### ISSUE THREAD

**Issue by sanna-woo** [matfish2/vue-tables-2#314]
- Vue.js version: 2.5
- consumed using: webpack

Hello @matfish2 !

It seems like that having saveState=true and both filterByColumn and filterable set to false gives a TypeError: 

> TypeError: Cannot set property 'value' of null

Thank you!

**Comment by matfish2** [comment]
Server or client component?

**Comment by sanna-woo** [comment]
> Server or client component?

sorry forgot to mention: client component

**Comment by matfish2** [comment]
Fixed in commit c0564d0af7f3caebf35778d67468402ee80a8d81
