### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by vdasus** [matfish2/vue-tables-2#316]
- Vue.js version: "vue": "^2.5.2", "@kazupon/vue-i18n-loader": "^0.2.1","vuex": "^2.5.0",
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace): vue.js:577 [Vue warn]: Invalid prop: type check failed for prop "countText". Expected String, got Function.
- relevant code:

//not working
texts: {
                        **count: function () { return this.$t("count") },
                        filter: function () { return this.$t("filter") },**
                        filterPlaceholder: "Search query",
                        limit: "Records:",
                        page: "Page:",
                        noResults: "No matching records",
  ...
                    },
                    filterable: ['name', 'shop', 'available', 'price'],
                    headings: {
//below - working
                        thumb: function () { return this.$t("thumb") },
                        name: function () { return this.$t("name") },
                        shop: function () { return this.$t("shop") },
                        available: function () { return this.$t("available") },
                        price: function () { return this.$t("price") }
                    }
________________________________________________________________________
OR
...
count: this.filtertext,
filter: this.filterPlaceholder,
...
watch: {
            lang: function () {
                this.$i18n.locale = this.lang;
                this.filtertext = this.$t("filter", this.lang);
                this.placeholderfiltertext = this.$t("filterPlaceholder", this.lang);
            }

- steps for reproducing the issue:
________________________________________________________________________
even:
filtertext: "Filter: ",
filterPlaceholder: "Search query",
...
texts: {
                        count: this.filtertext,
                        filter: this.filterPlaceholder,

not working...

just try to localize
![201710262155fds00](https://user-images.githubusercontent.com/4681649/32071643-8e58ff32-ba98-11e7-9ac2-c2cb8d70212b.png)

Localization is VERY important, take a look, please. It's not a bug, just feature request, i think

**Comment by matfish2** [comment]
The `options.texts` object doesn't take a `function`, but a `string`. As can be seen in your console, both `count` and `filter` are functions, which is why they are shown as empty. 

Obviously you can *call* a function that will return the right localization. E.g, in my own project I used a `trans` function, that had access to the locale info (a `localStorage` property, that was populated on the server side with the correct locale). Then all I had to do was call the function. E.g:

```js
texts:{
count:trans('count'),
filter:trans('filter')
}
```

**Comment by vdasus** [comment]
methods: {
            getTrans(str) {
                if (this.lang !== undefined)
                    return this.$t(str, this.lang);
                else return this.$t(str, "en");
            }

texts: {
                        count: "Showing {from} to {to} of {count} records|{count} records|One record",
                        filter: this.getTrans("filter"),

filter text shown as expected, but not changes when i change locale...
________________________
filtertext: "AAA",
...
filter: this.filtertext,
...
watch: {
            lang: function () {
                this.$i18n.locale = this.lang;
                this.filtertext = this.$t("filter", this.lang === undefined ? "en" : this.lang);
            },

not working at all (empty space)
_____________________________________
filter: this.$t("filter", this.lang === undefined ? "en" : this.lang),
show as expected,, but not changes when i change locale...
____________
i've tryed so many variants, but filter string localization not working...
__________________________________________________________________________
press here and try to change locale (beta.nuigde.com, Alias, first checkbox)
![201710281353esbc9](https://user-images.githubusercontent.com/4681649/32133776-8a327faa-bbe7-11e7-8d7b-ce12753876e3.png)

**Comment by matfish2** [comment]
A. Always look at Vue Devtools to see what the current value is, and see whether you change took effect and what is the new value (function, string, empty string etc.). Of course, you should paste it with any request for help, as it gives me invalueble insight into the current state of the component.

B. Changing locale on the fly depends on vue's reactivity. Check if the value is updating. If not, you can always modify the `options` objects directly, by using a `ref`. 
E.g: `this.$refs.myTable.options.texts.filter = this.myTransFunction('filter');`
