### ISSUE TITLE
The sorting problem in Templates with vue components

### ISSUE THREAD

**Issue by hhashoww** [matfish2/vue-tables-2#317]
- Vue.js version: 2.8.2
- consumed using: webpack

I use the templates option to render a column in the vue table like below:
```
import test from './test'
    ...
    ...
options: {
    templates: {
        test
    },
    ...
}
```

After each table's record was pushed, 

I found a problem, the "test" field at each record will not change the order with his original record

For example:

```
test field_A field_B
111     1     1
222     2     2
333     3     3 

```

sorting by field_A, I expect the result is:

```
test field_A field_B
333     3     3
222     2     2
111     1     1
```

but the result is:

```
test field_A field_B
111     3     3
222     2     2
333     1     1
```

"test" field didn't change the order together

Hope you guys can understand what I say

thanks!

**Comment by matfish2** [comment]
That really depends on the way your `test` template is defined. Please past the code.

**Comment by hhashoww** [comment]
This is my test template

```
<template>
  <div>
    <input list="orderList" v-model.lazy="orderNumber">
    <datalist id="orderList">
      <option v-for="item in orderNumberList">
        {{item}}
      </option>
    </datalist>
    </input>
  </div>
</template>
<script>
// import $ from 'jquery'

export default {
  props: ['data'],
  data: function () {
    return {
      initFlag: false,
      orderNumberList: this.data.orderNumberList,
      orderNumber: this.data.orderNumber
    }
  }
}
</script>
```

**Comment by matfish2** [comment]
Please paste your data set as well

**Comment by matfish2** [comment]
Also, to see the raw data received by the template, please add a `mounted` function to your `test` component and `console.log(this.data)`. If the data is correct then the problem lies with your component definitions.

**Comment by hhashoww** [comment]
This is the console.log(this.data) result in the test component
![image](https://user-images.githubusercontent.com/8544406/32141714-f791cee4-bc54-11e7-838b-4f6c9119f12a.png)

According to the result, the problem is occurred by the definitions of my component??
If yes, how should I check it?

**Comment by matfish2** [comment]
This is just one row. You need to look at the ORDER of the rows.  I suppose the field you were referring to was the `orderNumber`. See if the order of the logs is correct when you sort the table.
 
I can tell you already that I suspect this might have to do with your reassignment of the `data` property to the component. Try using the original `data` property instead:

```vue
<template>
  <div>
    <input list="orderList" v-model.lazy="data.orderNumber">
    <datalist id="orderList">
      <option v-for="item in data.orderNumberList">
        {{item}}
      </option>
    </datalist>
    </input>
  </div>
</template>
```

Also, what is the `list` attribute you add to the `input` element?

**Comment by hhashoww** [comment]
The "list" attribute is used for auto-complement
Reference: https://www.w3schools.com/tags/tag_datalist.asp

**Comment by hhashoww** [comment]
Oh yes!!!
I use "data.orderNumber" replace "orderNumber"
It works !!!
 
```
<template>
  <div>
    <input list="orderList" v-model.lazy="data.orderNumber">
    <datalist id="orderList">
      <option v-for="item in data.orderNumberList">
        {{item}}
      </option>
    </datalist>
    </input>
  </div>
</template>
```
