### ISSUE TITLE
Default Filter

### ISSUE THREAD

**Issue by bongolan** [matfish2/vue-tables-2#318]
is there a way to set filter value on load?

**Comment by matfish2** [comment]
Yes. Check out the `initFilters` option

**Comment by bongolan** [comment]
Does it work with custom filters? And i can't also understand the structure of that option.

**Comment by bongolan** [comment]
`<v-server-table ref="mytable" url="{{ URL::route('api.v2.cep.subject.index') }}" :columns="[id, name, actions]" :options="{filterable: ['status'], initFilters: {status:'active'},  customFilters: ['trigger', 'status', 'q', 'departments[]']}" class="full">`

Managed to make it work by scouring the sourcecode, but is this the right way?

**Comment by bongolan** [comment]
ok got it, i should set filterable to true, then put the key and value on initFilters?

**Comment by molerat619** [comment]
Correct. I had to update the EloquentVueTables class one more time, because currently it only knows either strings or date ranges - no boolean. So if you pass `true` it does not pass "is_string()" and directly goes to the else-block which checks for date ranges.
