### ISSUE TITLE
It seems __actions is removed for vue-tables-2

### ISSUE THREAD

**Issue by HolaMan** [matfish2/vue-tables-2#32]
- Vue.js version: 2.0
- consumed using: webpack
- FULL error message (including stack trace):
    actions can't render properly

I check the Vuetable.vue, and can't found the __actions related code.
I just want to confirm, Thanks!

**Comment by matfish2** [comment]
What is "the __actions related code"?

**Comment by HolaMan** [comment]
sorry, I doesn't provide enough information.
According to the document ==> https://github.com/ratiw/vue-table/wiki/Special-Field

We can provide a field named "__actions" and the vuetable will render the action buttons
But it seems not work, and after tracking the code, I found vue-table2 doesn't have __actions logic code to expand the template but vue-table does.

After using customized component actions instead of __actions, then it works.

Chris Chang

**Comment by matfish2** [comment]
You are confusing two different packages. This package is the vue 2 version of `vue-tables`, not `vue-table`
