### ISSUE TITLE
Version 0.6.83 adds 'false' to orderBy

### ISSUE THREAD

**Issue by ixperiencenl** [matfish2/vue-tables-2#320]
- Vue.js version: 2.5.2
- Tables version: 0.6.83
- consumed using: NPM Webpack
- Server side usage

The new update added 'false' to the orderBy param in the url. 
Before the url was like '?orderBy=&...' but now it is '?orderBy=false&...' so it tries to order by column 'false' which obviously doesn't exist.

I changed the EloquentVueTables model to check on this value to make sure we don't order by the 'false' column.
`if (isset($orderBy) && $orderBy && $orderBy != 'false') {`

**Comment by matfish2** [comment]
Yes, I've decided to forego the default sorting by first column, that was applied before. I think I will remove the `orderBy` parameter from the request altogether in case no column was specified, in which case an `isset($orderBy)` should be enough.
