### ISSUE TITLE
Hiding generic input filter, while using customFilters.

### ISSUE THREAD

**Issue by bongolan** [matfish2/vue-tables-2#321]
- Vue.js version: 2.5.2
- consumed using: webpack
Hiding generic input filter, while using customFilters.
Version 1
`<v-server-table ref="mytable" url="{{ URL::route('api.v2.cep.subject.index') }}" :columns="[id, name, actions]" :options="{filterable: true, initFilters: {status:'active'}, customFilters: ['trigger', 'status', 'q', 'departments[]']}" class="full">`
Version 2
`<v-server-table ref="mytable" url="{{ URL::route('api.v2.cep.subject.index') }}" :columns="[id, name, actions]" :options="{filterable: ['status', 'departments[]'], initFilters: {status:'active'}, customFilters: ['trigger', 'status', 'q', 'departments[]']}" class="full">`

Managed to make init filter work by scouring the sourcecode, but is this the right way?
i think what i did is hacking a solution, but i don't think that is the way it's designed?
And also i want to hide the default filter box but to hide that is thru filterable option.

**Comment by matfish2** [comment]
Settings `filterable` to `false` doesn't affect custom filters.

**Comment by bongolan** [comment]
Ill check, what im trying is initfilter and filterable set to false
