### ISSUE TITLE
Records footer

### ISSUE THREAD

**Issue by nlefebvre1410** [matfish2/vue-tables-2#322]
- Vue.js version: ^2.5.2

Hello,
I'm looking to put Records footer but I do not see an option?
Thank you for your help

**Comment by matfish2** [comment]
I don't understand the question. What is "records footer"?

If you mean footer headings then checkout the `footerHeadings` option.

**Comment by nlefebvre1410** [comment]
not look
![capture d ecran 2017-11-02 a 12 09 15](https://user-images.githubusercontent.com/3309884/32322979-b294a9b8-bfc6-11e7-86d3-a3a94478d8c9.png)

To the question?
is it possible to customize sortable?
If yes, share columns?

**Comment by nlefebvre1410** [comment]
hi
I try to make an order on the red arrow on the equals and on the green arrow is it planned the customization of the header table?
![capture d ecran 2017-11-02 a 17 10 48](https://user-images.githubusercontent.com/3309884/32337044-395b305a-bff1-11e7-9d1b-759ea3ae87cb.png)

**Comment by matfish2** [comment]
The sorting is built so that clicks on the sort icon alternate between ascending and descending order.
