### ISSUE TITLE
Unable to adapt orderBy in requestAdapter

### ISSUE THREAD

**Issue by tpolydoro** [matfish2/vue-tables-2#327]
- Vue.js version:2.4
- consumed using: webpack
- relevant code:
The propertie orderBy is not accessible in requestAdapter function. In this example the if statement is never executed. I believe that the orderBy field is injected in request data after requestAdapter call:

```javascript 
Vue.use(ServerTable, {
    requestAdapter: function(data) {
        if (data.orderBy) {
            console.log("OrderBy:",data.orderBy);
        }
        return data;
    }
}, false);
```
 
- steps for reproducing the issue: 

Initialize ServerTable with requestAdapter option and click in any column name.

**Comment by matfish2** [comment]
When the consumer of the package does not explicitly specify the initial column to order by, using the `orderBy` option,  that data is presented in its original order. Therefore, the request data will not contain an `orderBy` property unless the user orders by one of the sortable columns.

**Comment by tpolydoro** [comment]
@matfish2 Even if you pass an orderBy in options or after you click in column name, the property "orderBy" in data params is injected **after** the execution of requestAdapter.  You can check that in methods/get-data.js, between lines 15-17:

```javascript
var data = this.opts.requestAdapter((_opts$requestAdapter = {}, _defineProperty(_opts$requestAdapter, keys.query, this.query), _defineProperty(_opts$requestAdapter, keys.limit, this.limit), _defineProperty(_opts$requestAdapter, keys.ascending, this.orderBy.ascending ? 1 : 0), _defineProperty(_opts$requestAdapter, keys.page, this.page), _defineProperty(_opts$requestAdapter, keys.byColumn, this.opts.filterByColumn ? 1 : 0), _opts$requestAdapter));

if (this.orderBy.hasOwnProperty('column') && this.orderBy.column) data[keys.orderBy] = this.orderBy.column;
```

**Comment by matfish2** [comment]
You are right. Please try now.
