### ISSUE TITLE
Allow list filter to replace heading

### ISSUE THREAD

**Issue by ibdf** [matfish2/vue-tables-2#328]
Right now the search filter and list filter (which are similar in functionality) are placed under the headings in a new row. That makes sense for the search filter, but it's redundant for the list filter (dropdown) as the heading label repeats within the list itself. It would be interesting to have the option to have the list filter replace the header label instead of adding a second row.

**Comment by matfish2** [comment]
Thanks, but I think I'll pass. The filters need to be consistent. It is not the best UX when you have some filters on the second row and some on the first. Also, the placeholder is not just the name of the column, but "Filter by {column}".
