### ISSUE TITLE
[Question] How to display a row index/running number column?

### ISSUE THREAD

**Issue by NisalG** [matfish2/vue-tables-2#329]
- Vue.js version: 2.1.10
- consumed using: (browserify/webpack/rollup) Laravel Mix
- FULL error message (including stack trace): N/A
- relevant code: N/A
- steps for reproducing the issue: N/A

I check the docs, options and tried uniqueKey, rowClassCallback & trackBy.
But I didn't find a way to display the row index/ row running number column(not the id come from the database record) when using Server Side Loading.

**Comment by matfish2** [comment]
You can use a scoped slot template:

```vue
<template slot="id" scope="props">
	Row index: {{props.index}}
</template>
```
