### ISSUE TITLE
h is not a function

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#336]
- Vue.js version: 2.3.3
- consumed using: webpack
- FULL error message (including stack trace):

Hi, @matfish2. After upgrading to  `0.6.9` have an error `h is not a function`. Dropped to previous version. I'm using jsx templates of the cells. Before updating everything was fine.

**Comment by matfish2** [comment]
Unable to reproduce. Is this a compilation error or a run-time error?

**Comment by VladZen** [comment]
Hi, @matfish2. Finally has time to figure out the problem. Due to updates connected with index parameter in render.js function, there was a difference between [0.5.0](https://github.com/matfish2/vue-tables-2/blob/0.5.0/compiled/methods/render.js) and [1.1.0](https://github.com/matfish2/vue-tables-2/blob/1.1.0/compiled/methods/render.js) versions of this function. Since i'm using complicated fully customized templates in my projected, i've missed index when calling render function, that's why i had a mistake.

P.S. it's a pity that now i should fully rewrite my templates to have compatibility with 1.3.0 version of tables. =(
