### ISSUE TITLE
can't access vuex store from responseAdapter

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#338]
I been trying to get this working for 2 hours.. 

My problem is that when I query my API for table data, I also return extra data in that same api call. And I want to do something with that data.

I noticed that even if I set additional keys in a custom responseAdapter, those are not available in the table/LOADED mutation. Only the data, count and standard queryParams are available.

So I figured I would then do something in my responseAdapter so I can take that extra data returned by the API and commit it to my vuex store

But `this`inside of the responseAdapter refers to the table and I can't seem to access the global vue instance or the store. `this.$store` returns null

Could you please tell me how I can achieve what I want or how I can access vuex from inside the responseAdapter?

Thank you!

**Comment by matfish2** [comment]
I've fixed the loaded event\commit when using vuex.
I've also added added the root vue instance as the `this` context inside the `responseAdapter` method

**Comment by vesper8** [comment]
awesome thanks!
