### ISSUE TITLE
Refresh() doesn't work on Server table

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [matfish2/vue-tables-2#342]
- Vue.js version: 2.5.1
- consumed using: webpack
- relevant code: 
```
<v-server-table ref="Users" :url="url" :columns="columns" :options="options">
  <template slot="actions" scope="props">
    <!-- Single button -->
      <div class="btn-group">
          <button type="button" class="btn btn-primary">Action</button>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
          <li><a href="#" @click.prevent="editUser(props.row)">Edit</a></li>
          <li><a href="#" @click.prevent="deleteUser(props.row)">Delete</a></li>
        </ul>
      </div>
</v-server-table>
```
- steps for reproducing the issue:
Once clicked on delete 

`this.$refs.Users.refresh()`

doesn't work.

Could you please tell me what am I doing wrong?

**Comment by matfish2** [comment]
Please `console.log(this)` in your `deleteUser` method and paste the output.
I suspect I need to bind `this.$root` when using scoped slots like I did for render functions.

**Comment by kashifullahwebdeveloper** [comment]
I am getting this,

`VueComponent {_uid: 35, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
$attrs
:
(...)
$children
:
(2) [VueComponent, VueComponent]
$createElement
:
ƒ (a, b, c, d)
$el
:
div.row
$listeners
:
(...)
$options
:
{parent: VueComponent, propsData: undefined, _parentVnode: VNode, _parentListeners: undefined, _renderChildren: undefined, …}
$parent
:
VueComponent {_uid: 4, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
$refs
:
{Users: VueComponent}
$root
:
Vue$3 {_uid: 2, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: Vue$3, …}
$scopedSlots
:
{}
$slots
:
{}
$validator
:
Validator {strict: true, fields: FieldBag, paused: false, …}
$vnode
:
VNode {tag: "vue-component-6-UserOverview", data: {…}, children: undefined, text: undefined, elm: div.row, …}
addNewURL
:
(...)
columns
:
(...)
deleteUser
:
ƒ boundFn(a)
editUser
:
ƒ boundFn(a)
ferrors
:
(...)
fields
:
(...)
label
:
(...)
options
:
(...)
show
:
(...)
url
:
(...)
_c
:
ƒ (a, b, c, d)
_computedWatchers
:
{ferrors: Watcher, fields: Watcher}
_data
:
{…}
_directInactive
:
false
_events
:
{}
_hasHookEvent
:
false
_inactive
:
null
_isBeingDestroyed
:
false
_isDestroyed
:
false
_isMounted
:
true
_isVue
:
true
_provided
:
{$validator: Validator}
_renderProxy
:
Proxy {_uid: 35, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
_routerRoot
:
Vue$3 {_uid: 2, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: Vue$3, …}
_self
:
VueComponent {_uid: 35, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
_staticTrees
:
null
_uid
:
35
_vnode
:
VNode {tag: "div", data: {…}, children: Array(1), text: undefined, elm: div.row, …}
_watcher
:
Watcher {vm: VueComponent, sync: false, lazy: false, user: false, deep: false, …}
_watchers
:
(3) [Watcher, Watcher, Watcher]
$data
:
(...)
$isServer
:
(...)
$props
:
(...)
$route
:
(...)
$router
:
(...)
$ssrContext
:
(...)
get $attrs
:
ƒ reactiveGetter()
set $attrs
:
ƒ reactiveSetter(newVal)
get $listeners
:
ƒ reactiveGetter()
set $listeners
:
ƒ reactiveSetter(newVal)
get addNewURL
:
ƒ proxyGetter()
set addNewURL
:
ƒ proxySetter(val)
get columns
:
ƒ proxyGetter()
set columns
:
ƒ proxySetter(val)
get ferrors
:
ƒ computedGetter()
set ferrors
:
ƒ ()
get fields
:
ƒ computedGetter()
set fields
:
ƒ ()
get label
:
ƒ proxyGetter()
set label
:
ƒ proxySetter(val)
get options
:
ƒ proxyGetter()
set options
:
ƒ proxySetter(val)
get show
:
ƒ proxyGetter()
set show
:
ƒ proxySetter(val)
get url
:
ƒ proxyGetter()
set url
:
ƒ proxySetter(val)
__proto__
:
Vue$3`

**Comment by matfish2** [comment]
Ok. The `this` context refers to your scoped slot. You need to find the table components by climbing up the tree. I believe `this.$parent.refresh()` should do it. If not, explore the object using chrome dev tools and find the table component.

**Comment by kashifullahwebdeveloper** [comment]
I am getting this in Vue Dev tools, but I can't understand how to go further!

![untitled](https://user-images.githubusercontent.com/12660951/33371551-f1870a88-d51c-11e7-9880-76e0e2082af4.png)

**Comment by matfish2** [comment]
I am talking about the `Console` tab where you spit the `this` object inside the `deleteUser` method. Simply explore it until you find the `ref` you are looking for. Did you try my suggestion to use ` this.$parent.$refs.Users.refresh() `?

**Comment by kashifullahwebdeveloper** [comment]
Yes, I did try but I go this error,

`Uncaught TypeError: Cannot read property 'refresh' of undefined
    at VueComponent.deleteUser (UserOverview.vue?e3d9:133)
    at Proxy.boundFn (vue.esm.js?efeb:188)
    at click (eval at ./node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-0a93e886","hasScoped":false,"transformToRequire":{"video":"src","source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0&bustCache!./src/components/modules/users/UserOverview.vue (app.js:1924), <anonymous>:103:47)
    at invoker (vue.esm.js?efeb:1983)
    at HTMLAnchorElement.fn._withTask.fn._withTask (vue.esm.js?efeb:1781)`

Let me try with `console` tab, and see what can I get!

**Comment by kashifullahwebdeveloper** [comment]
Perfect! Thank you @matfish2, the issue resolved when I use `this.$refs.Users.refresh()` inside axios `.then` function like this:

`axios.get('example.com/api/users/delete/'+ row.id)
      .then((response) => {
        if(response.data.code == 200) {
            this.$refs.Users.refresh()
        } 
      })
     .catch((error) => {
        console.log(error)
        })
      })`

Sorry, my mistake.
