### ISSUE TITLE
dist/ is missing in version available via bower

### ISSUE THREAD

**Issue by larslue** [matfish2/vue-tables-2#343]
When installing vue-tables-2 via bower it complains that it can't find the main file that was specified.

`bower.json` looks for a file `index.js` which is not present.

I think you might want to link the file `dist/vue-tables-2.min.js` but the `dist/` folder is not present in the distributed version.

**Comment by matfish2** [comment]
This file was added via a pull request a year ago. The folder structure has changed since then.
Can you please try to change it to `compiled/index.js` and tell me if it works?

**Comment by larslue** [comment]
Hi mathfish, thanks for replying.
What bower expects is a file without any side dependencies that contains all information to be put into the global namespace.
`compiled/index.js` just defines the other files to load information from but it doesn't contain all information. 
So bower just adds this file, doesn't resolve the dependencies and it doesn't work.

As the `dist` folder was added a year ago via pull-request, are the file still updated to the newest version?

Apart from bower, also other applications use this file. Such as [jsfiddle](https://jsfiddle.net/matfish2/jfa5t4sm/).

**Comment by matfish2** [comment]
I've updated the package to include the dist folder, and modified `bower.json` accordingly. Please download and try again.

**Comment by larslue** [comment]
It works now on Master and should also work with the next release. Thank you!
