### ISSUE TITLE
control of the child row ?

### ISSUE THREAD

**Issue by nlefebvre1410** [matfish2/vue-tables-2#344]
Hello,
I try to control the click of the childrow in funciton of the user.
I thought to go through the template but there may be other way.
If it's green that I have to orient myself how does one go from other paramatrix to row?

```
    that.test = false
  
    if (that.hasChildRow) {
      var childRowToggler = h(
        'td',
        null,
        [h(
          'span',
          {
            on: {
              'click': that.test ? that.toggleChildRow.bind(that, row[rowKey]) : that.$notify({
                    group: 'group',
                    title: 'Alert',
                    text: 'ddd',
                    type: 'alert'
                  })
            },
            'class': 'VueTables__child-row-toggler ' + that.childRowTogglerClass(row[rowKey]) },
          []
        )]
      );
```

**Comment by matfish2** [comment]
No need to alter the template.
Add a click event to the child row component's wrapper (you can use css to make sure it covers the entire span of the row) and respond accordingly.
