### ISSUE TITLE
JSX not compiling markup in template

### ISSUE THREAD

**Issue by matthayzon-sk** [matfish2/vue-tables-2#345]
Hi there, in the example below I am trying to use the templates option to return markup and the rendered output is displaying the string instead of compiled HTML. I saw the JSX plugin installation details in the docs and I installed the needed npm packages, however, I am using laravel-mix and the documentation does not contain any instructions on how to enable the plugin using laravel-mix. I appreciate any help on this or any alternative in getting compiled html into the vue table. Thanks  

- Vue.js version: 2.5.3
- consumed using: (browserify/webpack/rollup): webpack (via laravel-mix)
- FULL error message (including stack trace): No error
- relevant code:
```
templates: {
                   status(h, row, index){
                            if(row.status==1){
                                return `<span class='label label-success'>RUNNING</span>`;
                            }
                        }
                    },
```

webpack.mix.js

```
let mix = require('laravel-mix');


mix.js('public/vue/main.js', './public/vue/compiled.js');

```

**Comment by matfish2** [comment]
Remove the quotes.

```jsx
 status(h, row, index){
                            if(row.status==1){
                                return <span class='label label-success'>RUNNING</span>
                            }
                        }
                    }
```

**Comment by matthayzon-sk** [comment]
I tried without the back tics, that didn't work either. That causes the vue compiler to fail as the JSX compiler isn't enabled.

**Comment by matfish2** [comment]
You need to install the [jsx compiler](https://github.com/vuejs/babel-plugin-transform-vue-jsx)

**Comment by matthayzon-sk** [comment]
Did you read the message? that's the exact issue. I installed the npm packages needed for the JSX compiler, but b/c I am using laravel-mix, like many others, I don't have a babelrc file, which is needed to enable to the JSX plugin..

**Comment by matfish2** [comment]
This question belongs in the laravel-mix repo
