### ISSUE TITLE
How to get elements from object in the data element?

### ISSUE THREAD

**Issue by littleSir** [matfish2/vue-tables-2#346]
- Vue.js version: 2.1.10
- consumed using: webpack

So what I want to know is how to access data from inside an object in the data I get from the request, as in the example below.
If I needed to get the 'idLang' from inside 'details' in a column, how do I navigate through the data element in order to put it in the table?

- relevant code:

This is an example of what I get from the request and then put into 'data':
```javascript
data: {
[
	{
		"id": 1,
		"created_at": "2017-11-29 00:00:00",
		"updated_at": null,
		"deleted_at": null,
		"idParentCategory": null,
		"image": "http://lorempixel.com/250/250",
		"abv": "cam",
		"nameParentCategory": null,
		"status": "Active",
		"name": "Camera",
		"details": 	[
					{
					"id": 1,
					"created_at": "2017-11-29 00:00:00",
					"updated_at": null,
					"idCategory": 1,
					"idLang": 1,
					"name": "camara"
					}
				]
	},
	{
		"id": 2,
		"created_at": "2017-11-29 00:00:00",
		"updated_at": null,
		"deleted_at": null,
		"idParentCategory": null,
		"image": "http://lorempixel.com/250/250",
		"abv": "cab",
		"nameParentCategory": null,
		"status": "Active",
		"name": "Cable",
		"details": [
						{
						"id": 2,
						"created_at": "2017-11-29 00:00:00",
						"updated_at": null,
						"idCategory": 2,
						"idLang": 1,
						"name": "Cable"
						}
					]
	},
]
}
```

I tried doing this inside the table component:
```html
   <template slot="lang">
            {{props.row.details.idLang}}
    </template>
```
but I just get an empty column.

Is there a way to get to these elements of the data? Or do they all HAVE to be in the root of the array element?

**Comment by matfish2** [comment]
```vue  
<template slot="lang" scope="props>
            {{props.row.details.idLang}}
</template>
```

**Comment by littleSir** [comment]
I tried with this, but it gives me an error when compiling:
```html
<template slot="lang" scope="props">
            {{props.row.details.idLang}}
</template>
```
With this error message:
"the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots."

And with this it's still an empty column:
```html
<template slot="lang" slot-scope="props">
            {{props.row.details.idLenguaje}}
</template>
```

**Comment by kashifullahwebdeveloper** [comment]
Hi @littleSir , If I understood you correctly, you actually want to show the `idLang` in one of the column right?
If that is the case then you can try this:

using the **columns** property
`columns: ['id','image', 'status', 'idLang'], `

'id', 'image', 'status' are just names of your data while 'idLang' is your temporary name 

then using **options** property, you can get the idLang value from your data array and show it in table

```
options: {
    templates:{
          idLang(h, row) {
               return `${row.details.idLang}` // details is the nested object in your data
          }
}
```

thus your complete code would be like this:

```
export default {
  data() {
  	return {
           columns: ['id','image', 'status', 'idLang'],
           options: {
              templates:{
                 idLang(h, row) {
                     return `${row.details.idLang}`
                 }
              }
           }
  } 
}
```
Let me know if that works for you!

**Comment by littleSir** [comment]
It does show now!

Thank you very much!
