### ISSUE TITLE
global search when filtering by column

### ISSUE THREAD

**Issue by nlefebvre1410** [matfish2/vue-tables-2#349]
hi,
is there a method to search globally
when the filterByColumn: true because setFilter requests an object.
As I have weighed mest column he does not find them
thank you in advance for your help

**Comment by matfish2** [comment]
Currently not supported. Will consider if others think it might be useful

**Comment by chernandezq** [comment]
Hi, I have this problem, I don't search, this return true, but see 
" No matching records"

**Comment by matfish2** [comment]
@chernandezq, sorry, I don't understand. Please elaborate. Is your problem related to this issue? Otherwise open a new one.
