### ISSUE TITLE
Proper way of using rowClassCallback

### ISSUE THREAD

**Issue by Netsrack** [matfish2/vue-tables-2#351]
Hello,
I've been using your framework here to set up a table for displaying application logging. But I've hit a stump as I am not completely sure, on how I am supposed to use the option: rowClassCallback.

The reason I would like to make use of the feature is to change the color of the table row, by adding a either "danger" or "info" tag to the <tr> for the rows. But I've not been able to figure out how to use the rowClassCallback from the documentation, and I have been unable to find another other infomation on the subject, on the internet.

So my final question really is, how am I supposed to use it? To all the classes to the table row tags?

**Comment by matfish2** [comment]
```js
options:{
    rowClasssCallback(row) {
     return row.danger?'alert-danger':'alert-info'; 
   }
}
```
