### ISSUE TITLE
Should default child row column open the child?

### ISSUE THREAD

**Issue by bliny** [matfish2/vue-tables-2#352]
Hy

I've just started exploring this component and I'm not sure that if this is a default child row column should work this way or I screwed up something.
Here is the example:
https://jsfiddle.net/jfa5t4sm/30/

I was expecting that if I click on the generated extra column the child row should appear but it does not.
I created and extra row called 'click in this'. If you click on that column the child row appears. So I don't think that I messed up the config.

Thanks

**Comment by matfish2** [comment]
You need to style the toggler. There is an example in the docs


Sent from my Samsung device

-------- Original message --------

**Comment by bliny** [comment]
https://jsfiddle.net/jfa5t4sm/32/

There updated, there is the styling from the docs, nothing changed
