### ISSUE TITLE
Not send time in Date parameters

### ISSUE THREAD

**Issue by davnavarro** [matfish2/vue-tables-2#353]
Hi,
The code is:
```javascript
options: {
    ...
    dateColumns: ['sentDate'],
    filterable: ['sentDate'],
    initFilters:{
        sentDate: {start: moment().startOf('month'),end: moment().endOf('month')}
    },
    dateFormat:'DD-MM-YYYY H:mm',
    datepickerOptions:{
        locale: {"format": "DD-MM-YYYY H:mm"}
        startDate: moment().startOf('month').format('DD-MM-YYYY H:mm'),
        endDate: moment().endOf('month').format('DD-MM-YYYY H:mm'),
        ranges: {
            "Current Month": [moment().startOf('month'), moment().endOf('month')]
        }
    }
}
```
In the parameters `$query['sentDate']['start']` and  `$query['sentDate']['end']`  I get "DD-MM-YYYY" values, I don't know because not receive "DD-MM-YYYY H:mm" values

Thanks in advance
David

- Vue.js version: 2.5.9
- consumed using: webpack

**Comment by matfish2** [comment]
Fixed. Note that the values received by the server have nothing to do with the `dateFormat` options, which sepcifies the *presentation* format. The values as sent to the server is always formatted as YYYY-MM-DD HH:mm:ss, which is the format the database server usually expects.

**Comment by davnavarro** [comment]
Thanks Matfish2 :)
