### ISSUE TITLE
Custom Filter Object

### ISSUE THREAD

**Issue by chernandezq** [matfish2/vue-tables-2#354]
- Vue.js version: ^2.5.9
I put `console.log(row.categorias.nombre_categoria === query;)` in the callback, return true but in the table see No matching records why ?
- relevant code: 

                           <v-client-table :options="options" :data="tiendas" :columns="['id','nombre','ciudad','departamento', 'categoria', 'plan', 'telefono', 'created_at', 'edit']">

                            <template slot="ciudad" slot-scope="props">
                                <div>{{props.row.ciudades.nombre_ciu}}</div>
                            </template>

                            <template slot="telefono" slot-scope="props">
                                <div v-if="props.row.info_tienda[0]">{{props.row.info_tienda[0].telefono}}</div>
                            </template>

                            <template slot="categoria" slot-scope="props">
                                <div>{{props.row.categorias.nombre_categoria}}</div>
                            </template>

                            <template slot="plan" slot-scope="props">
                                <div v-if="props.row.tipo == 1"><span class="label label-danger">Gratis</span></div>
                                <div v-if="props.row.tipo == 2"><span class="label label-warning">Plus</span></div>
                                <div v-if="props.row.tipo == 3"><span class="label label-success">Pro</span></div>
                                <div v-if="props.row.tipo == 4"><span class="label label-default">Especial</span></div>
                            </template>

                        </v-client-table>

`<script>

    import Vue from 'vue';
    import {ServerTable, ClientTable, Event} from 'vue-tables-2';
    import PacmanLoader from 'vue-spinner/src/PacmanLoader.vue';

    Vue.use(ClientTable, {
        perPage: 20,
    });

    export default {
        data(){
            return {
                loading: true,
                options: {
                    sortable: ['id', 'created_at'],
                    filterable: ['id','nombre', 'ciudad', 'plan', 'categoria'],
                    filterByColumn: true,
                    customFilters: [{
                        name: 'categoria',
                        callback: function (row, query) {
                            return row.categorias.nombre_categoria === query;
                        }
                    }]
                },
                tiendas: []
            }
        },
        mounted() {
        },
        created(){
            this.obtenerTiendas();
        },
        computed: {},
        methods: {
            obtenerTiendas: function () {
                axios.get('/tiendas/listado').then( (response) => {
                    this.tiendas = response.data.data;
                    this.loading = false;
                }).catch(function (error) {

                });
            }
        },
        components: {
            'PacmanLoader': PacmanLoader
        }
    }
</script>`

**Comment by matfish2** [comment]
I don't see in your code that you emit an event. The callback is only triggered when a filter event was emitted
