### ISSUE TITLE
texts option lacks documentation

### ISSUE THREAD

**Issue by liberty8374** [matfish2/vue-tables-2#355]
What are the names for the other labels?

README only mentions `count` and seems malformed:

> Table default labels:
> `{ count:'Showing {from} to {to} of {count} records {count} records

**Comment by liberty8374** [comment]
[lib/config/defaults.js](https://github.com/matfish2/vue-tables-2/blob/master/lib/config/defaults.js) has this:
```
texts:{
    count:"Showing {from} to {to} of {count} records|{count} records|One record",
    filter:"Filter Results:",
    filterPlaceholder:"Search query",
    limit:"Records:",
    page:"Page:",
    noResults:"No matching records",
    filterBy:"Filter by {column}",
    loading:'Loading...',
    defaultOption:'Select {column}'
}
```

**Comment by matfish2** [comment]
Thanks for that. As it turns out the github can't differentiate the pipe symbol (`|`) which is used to delineate the table, from the a pipe symbol inside a string. I checked it two online markdown editors and there was no problem. I'll try and find a more accurate simulator.

**Comment by Kinrany** [comment]
Perhaps you could just link to the `defaults.js`? The source is still much more readable, and there are links to documentation in other cells of that table anyway.
