### ISSUE TITLE
no matching end tag issue inside a scoped slot

### ISSUE THREAD

**Issue by dmotors** [matfish2/vue-tables-2#357]
- Vue.js version: 2.5.9
- vue-tables-2 version: 0.6.90
- consumed using: browserify

I noticed an issue that only happens when there are html tags inside a scoped slot which results in lots of compiler errors on the browser such as:

tag p has no matching end tag.

However, I do have closing tags as shown here:

	<v-server-table url="getData" :columns="columns" :options="options" ref="myTable">
		<template slot="customers" slot-scope="props">
			<div class="container-fluid">
				<p><button type="button" class="btn btn-primary" @click="clickHandler(props.row)">Add</button></p>
			</div>
		</template>
	</v-server-table>

If i move that p tag line outside of the v-server-table tag then it compiles fine and even displays it without errors.

Not sure what's happening here at the moment.

**Comment by dmotors** [comment]
I discovered something...

I recently upgraded these 2 packages:

laravel-elixir@6.0.0
laravel-elixir-vueify@2.0.0

That's when these errors started happening. No wonder I wasn't experiencing this before.

So on that note, is this a compatibility issue with those versions?

For now I will leave it by using the previous:

laravel-elixir@5.0.0
laravel-elixir-vueify@1.0.6

However would be great if I was able to use the newer version.

**Comment by matfish2** [comment]
One thing I've noticed is that you are using the `template` wrapper which is no longer necessary from v2.5 and on. Can you try the following:

```vue
<div class="container-fluid" slot="customers" slot-scope="props">
<p><button type="button" class="btn btn-primary" @click="clickHandler(props.row)">Add</button></p>
</div>
```

**Comment by dmotors** [comment]
I tried that and it's fine with or without using template but same difference once I install the newer elixir versions it starts telling me this again:

    tag <p> has no matching end tag.

No responses yet on stackoverflow so I'll revert back to the working versions and wait to see what's really going on. Thanks though.
