### ISSUE TITLE
Demo for using dynamic columns and custom icons (material)

### ISSUE THREAD

**Issue by MohammadSabbagh** [matfish2/vue-tables-2#360]
This component is great but changing table controllers like search, limit and pagination is a bit tricky specially if you want to add new one as in the example for displaying columns.

https://jsfiddle.net/Mohammad_Sabbagh/3pg1pk7q/

In this example:
- I use jquery to insert some tags in the top div before table, I hope there is another way to do this ?
- I use VueDraggable & Sortable for drag & drop arranging columns.
- I use Css :after for customizing Icons, in my example to Material Icons.

I hope someone can show how to do same using templates ?

Thanks

**Comment by matfish2** [comment]
I've added many slots for the part above the table. See docs.

**Comment by MohammadSabbagh** [comment]
Many thanks 

here is updated example using slots

https://jsfiddle.net/Mohammad_Sabbagh/rw1j5y3u/
