### ISSUE TITLE
 infinite scroll as an option?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#361]
i'm already using a custom template to create beautiful grids. rather than spinning up my own custom implementation i find it way more useful to use the strong foundation and features found in this package. But I find myself using it not only for traditional tables but for anything that involves repeated and paginated lists of items

now I have a use case where on mobile it isn't handy to use a normal paginator and i'd like to load additional content once you reach the bottom.. well basically just a regular infinite scroll

but i'd like to make it work with this package and the vue-pagination included ideally

any chance you'd consider adding this?

**Comment by matfish2** [comment]
see discussion in #341.
