### ISSUE TITLE
responseAdapter not working as expected

### ISSUE THREAD

**Issue by erwin16** [matfish2/vue-tables-2#363]
- Vue.js version: 2.4.2
- consumed using: webpack
- FULL error message TypeError: data.json is not a function
- relevant code:   using json-server API endpoint

    // OPTIONS
        requestKeys: {
          limit: '_limit',
          ascending: 'asc',
          page: '_page'
        },
        requestAdapter: function (data) {
          delete data.byColumn
          delete data.query
          console.log('REQUEST ADAPTER: ', data)
          return data
        },
        responseAdapter: function (resp) {
          console.log('RESPONSE ADAPTER: ', resp)
          const count = parseInt(resp.getHeader('X-Total-Count'), 10)
          console.log('count: ', count)
          retu=> rn {
            data: resp,
            count: count
          }
        }

CONSOLE.LOG
		REQUEST ADAPTER:  
		 http://localhost:8080/api/users?_limit=5&asc=1&_page=1

		Response payload in webtools network. ( Array of 5 users returned)
      [{"id":1,"firstName":"John"... , ..."created_at":"2017-11-02T07:56:36.405Z"}]

   No console.log from responseAdapter

**Comment by matfish2** [comment]
I am not sure the problem is the response adapter (does it work without it?).
You are probably using an old version of vue-resource.
As stated in the docs the minimal version required is 0.9.0.
Please check.

**Comment by erwin16** [comment]
I am using axios ,  "vue-axios": "^2.0.2",
the request is correctly sent, the response is received ( an array) at least the responseAdapter function should display the console.log() does it ?  or something wrong happen in betwwen ...

**Comment by matfish2** [comment]
Is `axios` exposed to the global `window` scope? (write `axios` in the console)

**Comment by erwin16** [comment]
I wrapped the response from the json-server API endpoint, using the apiRouter.rende() function , so the response is now

    {"count":16,"data":[{"id":1,"firstName":"John",.....}]}

removed the responseAdapter from the options... but nothing is displayed in the table... still Loading...

**Comment by erwin16** [comment]
OK solved ... as per your answer to a previous solved issue ( I searched for axios..)  I need to add 
    window.axios = require('axios')
to make it available at the global level...
