### ISSUE TITLE
updating table data dynamically

### ISSUE THREAD

**Issue by MohammadSabbagh** [matfish2/vue-tables-2#364]
When I try to change table data using @click, will not get updated

if I am using checkbox with v-model to anything then I use @click for same above will get updated.

Please see example 

https://jsfiddle.net/Mohammad_Sabbagh/czs13cc7/2/

I think this issue is related to this [#186](https://github.com/matfish2/vue-tables-2/issues/186)
even thought I am not using Vuex

**Comment by matfish2** [comment]
The row received inside the scoped slot is not the original row. Therefore changing it directly will have no effect on the data set. You need to find the row by its unique identifier in the data set that you passed to the component.
