### ISSUE TITLE
How to output Date column in specific format ?

### ISSUE THREAD

**Issue by erwin16** [matfish2/vue-tables-2#365]
- Vue.js version 2.4.2
- consumed using: webpack
- birthday date column display as YYYY-MM-DD   1951-08-19  ( same as  field from API)

      import { ServerTable } from 'vue-tables-2'
      Vue.use(ServerTable)

      options
      columns: [ 'firstName', 'lastName', 'email', 'birthday', 'actions' ],
      sortable: ['firstName', 'lastName', 'email', 'birthday'],
      dateColumns: ['birthday'],

toMomentFormat  seems to be client-side only ...?

**Comment by matfish2** [comment]
`dateFormat`

**Comment by erwin16** [comment]
sorry , but even with dateFormat

              dateColumns: ['birthday'],
              dateFormat: 'DD/MM/YYYY',

 it's still dispalying  YYYY-MM-DD

**Comment by matfish2** [comment]
I've revised my answer. Thought you were using the client component.

**Comment by erwin16** [comment]
would be nice to have the possibility to have a formatDate() function when using the server component

        formatDate (value, fmt = 'YYYY-MM-DD') {
          return (value == null)
           ? ''
             : moment(value, 'YYYY-MM-DD').format(fmt)
           },

btw , same issue for formatting numbers  ( i.e. with accounting pakage) 

           formatNumber (value) {
              return accounting.formatNumber(value, 2)
           },
