### ISSUE TITLE
Limitations on ClientTable pagination and ServerTable modification

### ISSUE THREAD

**Issue by jeff-pang** [matfish2/vue-tables-2#367]
This library is great but there are limitations which I can't  to work around. I wanted to be able to modify the tables dynamically so that it is more performant but my options are limited to using `ServerTable` which in this case, I have to refresh my table by retrieve all the data from server whenever there are changes to the table. But if I switch to using `ClientTable` then although I can modify the table manually, I can't paginate the server side data, I will need to fetch the entire dataset from server all at once and load it into browser.

The ideal case is that I can either fetch paginated data from server via `ServerTable` and be allowed to modify the table by javascript (e.g add, modify, delete). Or via `ClientTable` and be able to define the pages and load only the active page, and fetch and load the selected page's data as when they occur.

**Comment by matfish2** [comment]
> The ideal case is that I can either fetch paginated data from server via ServerTable and be allowed to modify the table by javascript (e.g add, modify, delete)

You are "allowed" to modify whatever you want, but the data will be overridden once you refresh the page. The solution I came up with is to save the modified data in a vuex store, and merge it with the server data, so it takes precedence. Of course you can also persist changes as they occur and then the server will reflect it. It all depends on your use case.

**Comment by jeff-pang** [comment]
@matfish2 thanks but how can I modify the "ServerTable" tableData? Is there documentation? Where is the tableData stored? Because unless I am doing something wrong, tableData does not represent the data in ServerTable.

I understand it depends on use case. Another way I can think of is for ServerTable is to expose functions to perform add/edit/delete to the table and have optionaly properties to specify the url to call on such events so that the server can receive and persist the data?

**Comment by matfish2** [comment]
If you are using `vuex` the current page will be represented in the `data` property of your module. Otherwise it will be one of the data properties on the component itself. Use vue dev tools to explore.
As I said above it is possible to create a fully functioning server-side editable table without changing anything in the plugin itself, using slots for new rows and templates for deciding cell content.
