### ISSUE TITLE
Possible to have a pagination on top and bottom of table?

### ISSUE THREAD

**Issue by phansch** [matfish2/vue-tables-2#368]
- Vue.js version: 2.5.11
- consumed using: webpack
- relevant code: https://gist.github.com/phansch/9b4e170b60cddf7b50d5a7587cb63367#file-template-js

Hi, first of all, thank you for working on this library! It has been a pretty straightforward experience integrating it into a bigger project and I hope to replace a much older library with this one. My goal is to have the the Vue tables look as close to the old tables as possible, so users don't notice big differences.

I'm currently stuck making a top and bottom pagination work. It seems only one can be used at the same time as the second pagination does not show up. Is this something that's currently not supported? The custom template in the Gist works apart from the two paginations.

**Comment by matfish2** [comment]
When you say top pagination do you mean dropdown pagination? If so, currently "normal" and dropdown pagination are mutually exclusive.

**Comment by phansch** [comment]
I mean having the normal navigation on the top of the table and at the bottom of the table. This would be really useful for longer tables. I made a mockup from the example in the readme:
![selection_0034](https://user-images.githubusercontent.com/2042399/34558271-a97b555e-f13d-11e7-91ce-d918a9481883.png)

(Note that I didn't update the gist with the latest template.js changes, it's still on 1.1.0)

**Comment by matfish2** [comment]
You can update to the latest version and use a custom template based on the `default` template.

**Comment by phansch** [comment]
Nice, thank you! I probably won't have time to do that for the next 2 weeks. I will re-open the issue if it still doesn't work then 👍
