### ISSUE TITLE
Undefined data error when clicking a <router-link> in a table cell.

### ISSUE THREAD

**Issue by chrisjimallen** [matfish2/vue-tables-2#369]
- Vue.js version: 2.5.2
- consumed using: webpack
- FULL error message https://gist.github.com/chrisjimallen/76682caa28a1c59ec6e5d303f96ec49f
- relevant code: https://gist.github.com/chrisjimallen/10fcb77a6edbd2610dd20adcff2ea7b0
- steps for reproducing the issue:

I have a button with a `<router-link>` in one of my cells. Clicking this button changes the component from the table to another 'page', but the `vue-tables.row-click` event still fires. Because the `animalFinder` object is no longer in the vuex state at this point, I get an [error](https://gist.github.com/chrisjimallen/76682caa28a1c59ec6e5d303f96ec49f).

**Comment by matfish2** [comment]
I think this is related to #339.
Please add `preserveState: true` to options and let me know if the problem persists.

**Comment by chrisjimallen** [comment]
This does indeed retain the animalFinder object in the state, and fixes my issue. Thanks!

I'm guessing the `preserveState` option is experimental as I can't see it in the docs?

**Comment by matfish2** [comment]
Glad to hear. This is indeed an experimental option, as you can see in #339. Will probably add it to the docs soon.
