### ISSUE TITLE
Can row click change the tr class or add style

### ISSUE THREAD

**Issue by skynight2018** [matfish2/vue-tables-2#371]
Can row click change the tr class or add style

**Comment by skynight2018** [comment]
sometime, add style is need

**Comment by matfish2** [comment]
Checkout the `rowClassCallback` option. You can change the data on the row in response to row click and it will trigger the callback to alter the class.

**Comment by skynight2018** [comment]
I have set the uniqueKey:'id', and then use 
tableVue.$refs.tableRef.$on('row-click', function (data) {
        console.log(data);
        data.row.active = true;
    });
console result：
{row: {…}, event: MouseEvent}
event
:
MouseEvent {isTrusted: true, screenX: 399, screenY: -657, clientX: 353, clientY: 240, …}
row
:
active
:
true

but rowClassCallback no response

**Comment by matfish2** [comment]
> but rowClassCallback no response

I don't understand. Did you define `rowClassCallback`? E.g:

```js
 rowClassCallback(row) {
    return row.active?'active':'';
 }
```

**Comment by skynight2018** [comment]
Yes, i found it must modify one property value of the row, E.g:  data.row.id = 'abc', it can trigger the callback, if i only data.row.active, it can not trigger

**Comment by matfish2** [comment]
This is a vue reactivity limitation. If the `active` property was not present on the object, adding it will not trigger a change in the dom. You need to add `active:false` to all rows before you assign the data.

**Comment by skynight2018** [comment]
ok, thanks
