### ISSUE TITLE
How to add my own mutations/getters/actions to vuex ?

### ISSUE THREAD

**Issue by erwin16** [matfish2/vue-tables-2#372]
- Vue.js version:  2.4.2 
- consumed using: webpack

I am trying to use vuex with my server-side table. ( Vue.use(ServerTable, {}, true) )

_useVuex is a boolean indicating whether to use vuex for state management, or manage state on the component itself. If you set it to true you must add a name prop to your table, which will be used to to register a module on your store. Use vue-devtools to look under the hood and see the current state._

so I added a name prop to my table   ( <v-server-table name='users' url="users" ref='userTable' ..)

and the users module is registered ...

How can I add my own getters/actions/mutations to this  users module ?

I added it t my vuex/store.js. 

	export default new Vuex.Store({
	  modules: {
            .... my own modules
	    users.  // <= I added it , with users/actions.js, users/getters.js, users.index.js ( ?? right )
	  }
	})

**Comment by matfish2** [comment]
This should work (tested myself):

```js
export default {
	modules:{
		users:{
			state:{
				// your data
			},
			mutations:{
				// your mutations
			}
		}
	}
}
```

**Comment by erwin16** [comment]
OK thanks ... I ad a doubt as I have an error

     [vuex] unknown action type: deleteUser

should be issued by another bad pattern usage w mapActions() ..

**Comment by erwin16** [comment]
working fine... my issue was related to my users module being namespaced...
