### ISSUE TITLE
CSS Class Overrides (New Feature/Question)

### ISSUE THREAD

**Issue by acgentry** [matfish2/vue-tables-2#374]
I don't think this feature exists, outside of the skin property, but I believe removing the soft dependency on Bootstrap would be great.  This could be done by providing developers the ability to pass in whatever framework classes they use for filters/row/pagination/etc.  If this feature does exist my apologies.

Thanks for all the hard work, hope I can contribute in the future when I understand your library better.

acg

**Comment by matfish2** [comment]
Vue tables 2 now supports themes and templates. Please see docs.

**Comment by acgentry** [comment]
Thank you @matfish2 I am going to name my first child after you.  Minus the @ symbol. :)
