### ISSUE TITLE
Custom template for columnsDropdown button and menu

### ISSUE THREAD

**Issue by yuugou727** [matfish2/vue-tables-2#375]
`columnsDropdown` is an awesome feature. But I found some default template classes were not appropriate while using Bootstrap 4 beta 2. e.g. class `.pull-right` has been replaced by `.float-right`, elements under `.dropdown-menu` have to be with `.dropdown-item`. 

And I'd liked to customize the list in `<label>` but not in `<a>`. Therefore I had to write some complicated logic at `updated` hook to manipulate table DOM.

Is there another available or planning implement to customize columns dropdown template?

**Comment by matfish2** [comment]
Vue tables 2 now supports `bootstrap4`. See docs
