### ISSUE TITLE
v-client-table can not show the change value even use Vue.set

### ISSUE THREAD

**Issue by skynight2018** [matfish2/vue-tables-2#378]
- Vue.js version: 2.5.13
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

 <v-client-table ref="newPoolSymbolTableRef"
                                                                                :data="tableData"
                                                                                :columns="columns" :options="options">
                                                                    <div slot="operate" slot-scope="props">
                                                                        <button class="btn btn-default btn-xs"
                                                                                @click.stop="calSymbolQty(props.row, '-', $event)">
                                                                            -
                                                                        </button>
                                                                        <input type="text" style="height: 27px;"
                                                                               :value="props.row.symbolQty"/>
                                                                        val: {{ props.row.symbolQty }}
                                                                        <button class="btn btn-default btn-xs"
                                                                                @click.stop="calSymbolQty(props.row, '+', $event)">
                                                                            +
                                                                        </button>
                                                                    </div>
                                                                </v-client-table>

methods: {
                calSymbolQty: function (row, opt, event) {
                    if (opt == '+') {
                        Vue.set(row, 'symbolQty', row.symbolQty + 100);
                        if (row.symbolQty > row.leftQty) {
                            Vue.set(row, 'symbolQty', row.leftQty);
                        }
                    } else if (opt == '-') {
                        Vue.set(row, 'symbolQty', row.symbolQty - 100);
                        if (row.symbolQty < 0) {
                            Vue.set(row, 'symbolQty', 0);
                        }
                    }
                    console.log(row.symbolQty);
                }
            }

**Comment by skynight2018** [comment]
<template>
                                                                <v-client-table ref="newPoolSymbolTableRef"
                                                                                :data="tableData"
                                                                                :columns="columns" :options="options">
                                                                    
                                                                    <div slot="operate" slot-scope="props">
                                                                        <button class="btn btn-default btn-xs"
                                                                                @click.stop="calSymbolQty(props.row, '-', $event)">
                                                                            -
                                                                        </button>
                                                                        <input type="text" style="height: 27px;"
                                                                               :value="props.row.symbolQty"/>
                                                                        值: {{ props.row.symbolQty }}
                                                                        <button class="btn btn-default btn-xs"
                                                                                @click.stop="calSymbolQty(props.row, '+', $event)">
                                                                            +
                                                                        </button>
                                                                    </div>
                                                                </v-client-table>
                                                            </template>

**Comment by matfish2** [comment]
#364
