### ISSUE TITLE
Hide + symbol when using v-if in slot="child_row"

### ISSUE THREAD

**Issue by iamstevendao** [matfish2/vue-tables-2#379]
I have something similar to this:
```
v-client-table
...
  div(v-if="show", slot="child_row", slot-scope="props")
  ...
```
Even when `show` is `false`, the `+` button appears on the first column on each row, with nothing happens when clicks on. Now we have to use another component just for cases we don't want to display this `+` button and this approach is not good.
Any solutions for this? thank you!

**Comment by matfish2** [comment]
Why would you want to set a `v-if` on the child row? It is already conditioned to show only on toggler click.
