### ISSUE TITLE
Defined key for cell value

### ISSUE THREAD

**Issue by dpollard** [matfish2/vue-tables-2#38]
Is it currently possible to define the specific object key for each cell value?

Ex data:

`var data = { age: 12, name: 'User', location: {city: 'Los Angelos', state: 'CA' }, email: 'test@ex.com'  };`

From with which I would be able to define that for "location", I'd like `location.city` to display?

**Comment by matfish2** [comment]
You can use templates for this.

E.g:

```
templates:{
location: function(h, row) {
    return row.location.city;
}
}
```
