### ISSUE TITLE
Render html inside table fields

### ISSUE THREAD

**Issue by sica07** [matfish2/vue-tables-2#380]
Hi!
Is there any way I could render html code inside the fields? Right now, all the html data is parsed as a string. I'm using the client-side version.
Thanks!

**Comment by matfish2** [comment]
Passing HTML to the original data will result in it being rendered as text. What is your use case? Did you read the `templates` section in the docs?

**Comment by sica07** [comment]
Virtual DOM functions will do it. Thank you for the suggestion!
