### ISSUE TITLE
Cant get vue-tables-2 working

### ISSUE THREAD

**Issue by cisaia07** [matfish2/vue-tables-2#383]
- Vue.js version: 2.1.10
- consumed using: webpack

New to vue and laravel, super excited about using vue-tables-2! It looks like EXACTLY what i was looking for. I can get the server-table to load my data, but it doesn't paginate, all 200 hundred records show at the same time. Search doesnt work either. I know its in the way I set it up, but cant find what i did, please help.

app.js

```js
require('./bootstrap');

window.Vue = require('vue');
window.axios = require('axios');

import swalPlugin from './plugins/VueSweetalert2';
Vue.use(swalPlugin);

import Popover  from 'vue-js-popover'
Vue.use(Popover)

import {ServerTable, ClientTable, Event} from 'vue-tables-2';
window.Vue.use(ServerTable, null, false, 'bootstrap4');
```

html

```html
<div class="row" id="app">
        <div class="col-sm-12 col-md-4">
        </div> <!-- End column -->
        <div class="col-sm-12 col-md-8">
             <v-server-table url="test4/getit" :columns="columns" :options="options"></v-server-table>
        </div>
</div>
```

vue

```vue
<script>
new Vue({
  el: "#app",
  data: {
    columns: ['name', 'code', 'uri'],
    options: {
      sortable: ['name', 'code'],
      filterable: ['name', 'code'],
      perPage: 25,
      headings: {
        name: 'Country Name',
        code: 'Country Code',
        uri: 'View Record'
      },
    }
  }
});
</script>
  ```

**Comment by matfish2** [comment]
Unlike the client table, the server table is data agnostic. It sends a request and relies on the server to return a proper response. What does your server-side code looks like?

**Comment by cisaia07** [comment]
I apologize, I should have put that in there as well

controller

public function getEasyPageInstList()
    {
        $inst = array();
        $rawinst = inst_main::orderBy('inst_man_id', 'ASC')
                            ->get();
        
        foreach($rawinst as $value) {
            $iid = $value->id;
            $inst[] = array(
                        'name' => $value->inst_title,
                        'code' => $value->id,
                        'uri' => $value->manufacturer->name,                       
                    );
        }
        $c = count($inst);

        return response()->json([   'data' => $inst,
                                    'count' => $c
                                ]);
    }

**Comment by matfish2** [comment]
As I wrote above when using the server-side table it is your responsibility to return the correct data. If your dataset has only 200 rows you should use the client side component
