### ISSUE TITLE
Webpack Dev Server & Hot Reloading

### ISSUE THREAD

**Issue by acgentry** [matfish2/vue-tables-2#385]
Once again, this is a GREAT repo and ideally like to contribute, and to this point..

I see that you have a dev ref to webpack-dev-server and was wondering if you could include any development tooling into this repo so that potential contributors can run your code base with sample data, and ideally with hot reloading of transpiled jsx files. 

Am I crazy? Yes.

**Comment by matfish2** [comment]
Guidelines for contribution:

A. Fork the repo and clone to your local machine
B. `npm install`
C. Using `mocha` write tests for the change your are about to make (see the `test` folder)
D. make changes to the `lib` folder
E. `npm run build` will save changes to the `compiled` folder 
F. `npm run test` to test your change and make sure you haven't broken anything
G. run it in the browser yourself to see all works as expected
H. Push to git and send a PR

**Comment by matfish2** [comment]
Guidelines for contribution:

A. Fork the repo and clone to your local machine
B. `npm install`
C. Using `mocha` write tests for the change your are about to make (see the `test` folder)
D. make changes to the `lib` folder
E. `npm run build` will save changes to the `compiled` folder 
F. `npm run test` to test your change and make sure you haven't broken anything
G. run it in the browser yourself to see all works as expected
H. Push to git and send a PR
