### ISSUE TITLE
Option to disable pagination chunk?

### ISSUE THREAD

**Issue by eydreeyawn** [matfish2/vue-tables-2#386]
Hi, 

My goal is to only maintain the numbers pagination [1|2|3].

I would like to ask if there is a way to disable chunk button [<<][>>]? 
and also next and prev[<][>]?

I tried adding boolean and setting it `pagination.chunk` to `0` but it doesn't work.

My temporary solution:

```
removePaginationButtons() {
    $('.VuePagination__pagination-item-prev-chunk').remove();
    $('.VuePagination__pagination-item-next-chunk').remove();
    $('.VuePagination__pagination-item-prev-page').remove();
    $('.VuePagination__pagination-item-next-page').remove();
}
```

I hope we can do this by just adding option

**Comment by matfish2** [comment]
I suppose you mean 'remove' rather than 'disable', as the page and chunk arrows are automatically disabled when relevant.
As for hiding, IMO it is simpler and better to use CSS, rather than removing the elements from the DOM.

**Comment by eydreeyawn** [comment]
Hi @matfish2, thanks for the reply. Yes I mean remove. I tried using css `display:none` but if you are using bootstrap, the button you remove will have sharp edge. Please see image below. 

![screen shot 2018-01-12 at 12 13 25 am](https://user-images.githubusercontent.com/7329321/34834656-847d8bbe-f72d-11e7-989a-d603779311a1.png)

**Comment by matfish2** [comment]
You can add styling to make the corners round using the `:nth-child` selector
