### ISSUE TITLE
Hide child row if he is empty.

### ISSUE THREAD

**Issue by Akshin** [matfish2/vue-tables-2#393]
- Vue.js version 2+

Hi. How can I hide a row if it is not have a data ? 
Have vue-table-2 methods or smth ?

**Comment by matfish2** [comment]
When you say hide I assume you mean hide the toggler, and the row itself isn't presented unless the user pressed the toggler. At any rate, there is no inherent method for identifying "empty" child rows, as the child row is a vue template, not a piece of data.

**Comment by freeman-g** [comment]
We solved this same issue by using a rowClassCallback with some related css:

```
rowClassCallback: row => {
  if (row.childRows.length === 0) {
    return 'hideChildToggler'
  }
}
```

```
>>>.hideChildToggler .VueTables__child-row-toggler {
    display: none;
}
```

`>>>` are needed when using scoped css
