### ISSUE TITLE
prependFilterContainer removed?

### ISSUE THREAD

**Issue by chriscarpenter12** [matfish2/vue-tables-2#396]
- Vue.js version: 2.5.13
- consumed using: (rollup)

I noticed after updating one of my projects that some slots were not rendering. Realized that the slot I used `prependFilterContainer` wasn't working. Its not listed in the latest documentation. Last I saw it was in version 1.2. Has it been removed? I was looking for a changelog, but didn't see that either. I could have overlooked it though.

EDIT:
I can indeed [see](https://github.com/matfish2/vue-tables-2/blob/439afaa4a6aace40e55693d1d10f775801033ec3/compiled/themes/common/template.js#L19) its still there, but not rendering the slot?

Forked the demo on [Jsfiddle](https://jsfiddle.net/jh5bcsyw/) and doesn't seem to be working there either. I feel like I'm missing something simple.

**Comment by chriscarpenter12** [comment]
I moved my slots to use `beforeFilter` instead, and adjusted my css to fix the layout issue. Still would like to know why this stopped working.

**Comment by matfish2** [comment]
Due to significant template changes the "container" slots have been removed
