### ISSUE TITLE
Is there a way to use paginated server table but pre-load entire results ?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#397]
I have a a dataset of a few hundred records. They are paginated 12 per page. But I would like to preload into my Vuex store.. say the first 100

So on initial load it would load the first X pages, and then when the user paginates if this is already into memory then it wouldn't cause an API call to be made.. only once it runs out of preloaded data would it then do another API call.. prefetching the next 10 pages.

The idea is to preload data when the user isn't waiting.. to reduce the wait time when the user does paginate

Can vue-tables-2 handle this kind of behaviour at all?

**Comment by vesper8** [comment]
Similarly.. I was just reading this article here about vuex design patterns https://vuejsdevelopers.com/2017/08/06/vue-js-laravel-full-stack-ajax/

If I wanted to set the initial state this way. Is there a way to achieve this?

That is.. my table is a server-table, but the very first page I want to load from the server and set the state by using window.my_table.data = {}

So that the first page can be interacted with much faster as it doesn't have to wait for an API call.. but subsequent pages would.. and ideally I would also be able to prefetch as detailed in the first post

Is there a way to accomplish this?

**Comment by matfish2** [comment]
There is currently no support for "mixed" client-server pagination.
IMHO, The problem with this approach is that it only works if the user hasn't used sorting or filtering, because those two require the **full** server dataset to be queried, and will make the prefetched records useless.
What **can** be useful is perhaps allowing the consumer to pass the first page from the client, thus making the first AJAX request redundant, and the table initial load faster. However, this requires that the consumer will pass the first page exactly as expected by the predefintions of the server table. I.e order, limit, initial filters etc, i.e it stacks on the consumer the responsibility to generate the correct **request**, not only the correct response.

**Comment by vesper8** [comment]
I'm really struggling to find a working model for making the page load faster

I spent hours trying to get SSR and pre-rendering to work but it seems this is not suited for a server-table that gets its data from an api call

In my application the users can interact with filters, but those are also always persisted to the server so it's easy for me to get the 1st page with the same filters/sorting as what the server-table will use on load.

I would really like to be able to use only the server-table, but to be able to inject some of the data into vuex directly. and then if it was possible to mock the first call (now redundant) or have some change to the logic so that server-tables only make external calls if the data stored in vuex is "not fresh" .. well that would be awesome!

one of the things I'm planning to do to make everything faster is doing a lot of pre-loading inside of vuex

I guess the question is.. would it be possible for this package to develop a 3rd kind of table.. a hybrid between client and server.. one where the data (sometimes ALL the data) is loaded at once into vuex, and then the server interacts with that data directly as far as filtering and sorting goes.

hrmm.. doesn't that sound really cool? in cases where the data is huge then it wouldn't have to be all preloaded but you could still easily preload 10+ pages at little cost while providing a huge speed increase since you no longer have to make any api calls unless needed.

**Comment by matfish2** [comment]
If ALL the data is preloaded, why not use the client table? What role does the server have in this case?
If only some data is preloaded, then as I said above, it is not filterable or sortable, and thus only useful for pagination. Even then, I am not sure I see the benefit of loading more data than requested by the user. If the user is interested in more then X records, he can change the per page value, and have as many records as you allow per call.

I will leave this issue open for now in case anyone wants to pitch in.
