### ISSUE TITLE
Vuex issue: table mutations are not recognized if the table component is once destroyed and rerendered

### ISSUE THREAD

**Issue by singiankay** [matfish2/vue-tables-2#398]
This is my client table, I named it clientTableLine.

```
<v-client-table name="clientTableLine" :data="tableData" :columns="columns" :options="options" v-if="tableData">
</v-client-table>
```

And then I have this saved as clientTableLine.js, imported as clientTableLine.
```
import * as types from '../mutation-types'

const mutations = {

	[types.UPDATE_CLIENTTABLE] (state, data) {
		state.data = data
	},

	[types.CLEAR_CLIENTTABLE] (state) {
		state.data = []
	}
	
}

export default {
	mutations,
}
```
I have this commit mutation event everytime I need to reload the data of the client table.
`this.$store.commit('UPDATE_CLIENTTABLE', this.tableData)`

It works perfectly fine on the first render. But if the component of the v-client-table is destroyed either by the v-if method or just by going to another page, and then if I go back, everytime I reload the tableData,

I will get this error: **using Vuetables-2 [vuex] unknown mutation type: UPDATE_CLIENTTABLE**

**Comment by matfish2** [comment]
By default the module is destroyed together with the component, so every custom mutation you add yourself to the module will be wiped with it. To change this behaviour use `preserveState:true`. Let me know if this solves your problem.
