### ISSUE TITLE
customFilters ServerTable ?

### ISSUE THREAD

**Issue by nlefebvre1410** [matfish2/vue-tables-2#399]
Hello @matfish2 
I do not understand how we do customFilters under serverTable you can show me an example please
thank you in advance

**Comment by matfish2** [comment]
What exactly don't you understand? Did you follow the docs?
Once you have declared the filter and emitted an event, it should be added to your request data.
Then on your server you should use this data to filter as necessary.

**Comment by nlefebvre1410** [comment]
how to pull in the request ?

**Comment by matfish2** [comment]
That depends on your server side language. Open chrome dev tools, and look at the request data after emitting a custom filter event. If the filter is there, then the rest is up to you.

**Comment by nlefebvre1410** [comment]
in fact my question? that's how he passes the data

**Comment by nlefebvre1410** [comment]
@matfish2 
in fact my question? that's how he passes the data
does not it work for me as for 'CLIENT'?

**Comment by matfish2** [comment]
No. The server table is agnostic, i.e it doesn't know anything about your complete data set. Therefore, it is unable to filter the data. All it does is sends a request to the wise server, who should process it and return the correct response, and this is out of the scope of this plugin.
