### ISSUE TITLE
Uncaught ReferenceError: options is not defined

### ISSUE THREAD

**Issue by BrianEstrada** [matfish2/vue-tables-2#4]
**- Vue.js version:**: 2.0
**- consumed using: (browserify/webpack/pre-compiled)** webpack (Is there a precompiled version?)
- FULL error message (including stack trace):  
  

>  Uncaught ReferenceError: options is not defined(anonymous function) 
> @ VM24703:36(anonymous function) 
> @ app.js:232__webpack_require__ 
> @ app.js:20(anonymous function) 
> @ app.js?8b67:9(anonymous function) 
> @ app.js:842__webpack_require__ 
> @ app.js:20(anonymous function) 
> @ app.js:64(anonymous function) 
> @ app.js:67

  
**Babel Config:**  

> {
>   "presets": ["es2015"],
>   "plugins": ["transform-vue-jsx"]
> }
> 

**Bootstrap.js:**  

> window._ = require('lodash');
> 
> window.$ = window.jQuery = require('jquery');
> require('bootstrap-sass');
> 
> window.Vue = require('vue');
> require('vue-resource');
> 
> Vue.http.interceptors.push((request, next) => {
>     request.headers.set('X-CSRF-TOKEN', Laravel.csrfToken);
> 
>     next();
> });
> 
> var VueTables = require('vue-tables-2');
> Vue.use(VueTables.client, options);

- steps for reproducing the issue:

**Comment by matfish2** [comment]
It seems like an error in your `app.js`, not the plugin. Please paste the file's content.

**Comment by BrianEstrada** [comment]
@matfish2   
Bootstrap.js  

> window._ = require('lodash');
> 
> window.$ = window.jQuery = require('jquery');
> require('bootstrap-sass');
> 
> window.Vue = require('vue');
> require('vue-resource');
> 
> Vue.http.interceptors.push((request, next) => {
>     request.headers.set('X-CSRF-TOKEN', Laravel.csrfToken);
> 
>     next();
> });
> 
> var VueTables = require('vue-tables-2');
> Vue.use(VueTables.client, options);
> 
> 
> // import Echo from "laravel-echo"
> 
> // window.Echo = new Echo({
> //     broadcaster: 'pusher',
> //     key: 'your-pusher-key'
> // });
> 

   
App.js  
  

> require('./bootstrap');
> 
> 
> Vue.use(require('vue-resource'));
> 
> Vue.component('example', require('./components/Example.vue'));
> Vue.component('invoices', require('./components/Invoices.vue'));
> Vue.component('cars', require('./components/Cars.vue'));
> 
> const app = new Vue({
>     el: '#app',
> });
> 
> jQuery(document).ready(function($) {
>     $(".clickable-row").click(function() {
>         window.location = $(this).data("href");
>     });
> });
> 
>

**Comment by matfish2** [comment]
You are calling 
`Vue.use(VueTables.client, options)`
 but `options` (as webpack so graciously tells you) is not defined.

**Comment by BrianEstrada** [comment]
> options are set in three layers, where the more particular overrides the more general.
> 
> Pre-defined component defaults.
> Applicable user-defined defaults for the global Vue Instance. Passed as the second paramter to the Use statement.
> Options for a single table, passed through the options prop.

@matfish2 hmm okay I though it was some pre-defined configuration that was included (sorry new to web development and web-pack as a whole)
