### ISSUE TITLE
Add button to table data based on input using templates

### ISSUE THREAD

**Issue by Netsrack** [matfish2/vue-tables-2#400]
Hello, I am currently trying to add a button to the table based on some data that is in the table data field to begin with. However whenever I try, my html code is just displayed as regular text.
I've tried a few different things to make it read the code as regular html text. However I have not had any luck.
So I was wondering if anyone here knew how, or if it was possible.

My template code:

```
templates: {
                        LogType: function (h, row) {
                            switch (row.LogType) {
                                case 0:
                                    return 'Trace';
                                case 1:
                                    return '<button type="button" class="btn btn-danger">Delete</button>';
                                case 2:
                                    return 'Error';
                                case 3:
                                    return 'Info';
                            }
                        },
                    }
```

**Comment by singiankay** [comment]
I can't help you with templates, but slots are easier to do. I don't have the latest VueJS installed so I am using the template slot format instead of the latest.

```
<v-server-table name="SalesOrderTable" :url="'salesorder/?division='+division+'&area='+area+'&format=json'" :columns="columns" :options="options" ref="salesorderTable"> 
 <template slot="so_number" scope="props">
    <a @click="setUpdateID(props.row)">{{ props.row.so_number }}</a>
  </template>
</v-server-table>
```

**Comment by Netsrack** [comment]
Thanks for the note, I did end up using slots inside. However now I am trying to figure out how to change the look for the button, based on the value found in the slot where the button is placed.
Any ideas?

**Comment by matfish2** [comment]
`EDIT: Never solved it using v-bind:class`

Why not? What did you try?

**Comment by Netsrack** [comment]
Im am very sorry about that, while writting my edit I seem to have scatterbrained completly. I meant to say "Never mind" and not "Never solved it" 

The issue was fixed using v-bind:class.
