### ISSUE TITLE
Feature Request : Add Server response to Event Payload

### ISSUE THREAD

**Issue by nonsocode** [matfish2/vue-tables-2#403]
The payload for events like `loaded` should have the server response in case the has other data like meta information which might be useful to the app

**Comment by sebas1983** [comment]
As of version 1.3 I am not receiving response data within the responseAdapter option anymore. 
For example:
`responseAdapter: function(resp) { 
console.log(resp);
console.log('test');
}
`
does not output either of the console.logs.

- The server-table is firing the Axios request;
- The request is valid, handled properly and returns the expected data;
- The "SET_DATA" and "LOADED" mutations are fired and their payload DOES contain the expected data;

What am I overlooking or doing wrong in the responseAdapter?

Thanks in advance!
