### ISSUE TITLE
Modifying global filter

### ISSUE THREAD

**Issue by keithlee96** [matfish2/vue-tables-2#404]
Is there any way to modify the global filter via a slot? For example, to have the page autofocus on the search filter when loaded or to make it use a custom filter.
The documentation has slots for beforeFilter and afterFilter, but is there a way to modify the filter itself?

Edit: I found that you can use the texts option to change the messages in the global filter, but I still want to know if it's possible to add autofocus to the filter.

**Comment by matfish2** [comment]
You can latch into it using JQuery and call the `focus` method
