### ISSUE TITLE
is Filter feature supported in ServerTable?

### ISSUE THREAD

**Issue by Mandy27** [matfish2/vue-tables-2#406]
I am having problem with adding Filter in ServerTable. Anyone has an example? Thank you!

**Comment by Mandy27** [comment]
Closed without an answer?

**Comment by Mandy27** [comment]
I have read the documentation and still not sure how to make custom filter work with ServerTable. Perhaps an example would be helpful please

**Comment by matfish2** [comment]
duplicate of #399
