### ISSUE TITLE
Feature Request: Add Vuex Store mutation for changing data and / or Refresh table

### ISSUE THREAD

**Issue by bayi** [matfish2/vue-tables-2#407]
- Vue.js version:2.5.2
- consumed using: webpack

Hi

I have the following scenario: 
Im using client tables for displaying points in a simple game, there is no backend for it, the games are only for the session, nothing is stored either.
Im having hard time adding / updating data in the table and then refreshing it also.

I solved it currently with the following:
1. Mutation for updating data which accesses root state ( i feel this is a bit hacky ):

```
    [types.GENERAL_UPDATE_TABLE_DATA] (state, { table, data})
    {
        this.state[table].data = data
     }
```

2. This works for initial loading the data etc, but after changing some data the changes arent reflected until "something" happens. I solved it this way which is too hacky for my taste, but didnt found a better solution:

...component methods...
```
  refreshData()
  {
        const oldFilter = this.state[this.table].query // Need to pull in the rootState here also
        this.$store.commit('tableUsers/SET_FILTER', '---') // Other random value
        this.$store.commit('tableUsers/SET_FILTER', oldFilter)
   }
```

- Can you please add a mutation for just refreshing data ? ( This solves only half of my problem )
- Can you please add a mutation for updating/refrehsing table data ? ( This would be preferred )

**Comment by matfish2** [comment]
You can define your own mutations and state on the module and it will be merged when the module is registered. E.g:
```js
modules:{
  myTableName:{
    state:{
      myOwnData:'someData'
	},
      mutations:{
	 addRow(state) {
          state.data.push(row);
      }
    }
  }		
}
```

**Comment by bayi** [comment]
Thanks

**Comment by kevindesousa** [comment]
Hello, can you publish an entire code example, because I have the same problem, but I don't undertsand..

**Comment by Denis4yk** [comment]
@matfish2 

Are you sure, that your snippet still works. Cause now it gives me an error.

**Comment by Denis4yk** [comment]
@matfish2 Please, update on this functionality. I'm even ready to help, just this feature is very-very important. I have to mutate your moudule's store in my actions, what leads to some errors on production and non-trackable changes, what is very hard to debug.

**Comment by matfish2** [comment]
At the moment the module name is reserved and cannot be used by the consumer. I believe you can simply change the name of your module and still achieve the same functionality.

**Comment by Denis4yk** [comment]
@matfish2 

No, I can't.
Imagine, that I have an "actions" column. It makes a request to the server, it performs some complex logic and returns an updated row. 

How can I update your module from my mutation? I can't, cause `rootState` is NOT accessible in mutations. Only actions. And this is quite a bad practice + I can't watch the history changes.

**Comment by matfish2** [comment]
I have applied a fix. Works on my end. Can you please update the package and confirm?

**Comment by Denis4yk** [comment]
@matfish2

Thanks for such a fast response 👟🔥🎉

Yes, from my side I can perform mutations, but I don't know, if new bugs have appeared. If spot any, I'll let you know.

**Comment by andreic96** [comment]
@matfish2 it seems that unregisterModule in the fix breaks the vue-router functionality.
I think we need to add the preserveState check here as well, or why was the unregisterModule added ?
