### ISSUE TITLE
Custom searcher input

### ISSUE THREAD

**Issue by KsCorrales** [matfish2/vue-tables-2#409]
- Vue.js version: 2.4.4
- consumed using: Webpack
- FULL error message (including stack trace): null
- relevant code: used in watch:

```
search: function (newQuery, oldQuery) {
    Event.$emit('vue-tables.filter', newQuery);
},
``` 

how can i create a custom input to search in table?, i try with custom filter creating watch in input and emit the event but when i dispatch the event not filter table.

**Comment by bayi** [comment]
If you are using vuex try this, it worked for me:

```
const tableName = 'theTableName' // what you provided in the name property

this.$store.commit(`${tableName}/SET_FILTER`, 'text to search for')
```
also i think you have to set                 **filterByColumn: false**   in the options so it searches in all filterable fields at once.

**Comment by matfish2** [comment]
> setFilter(query) - query should be a string, or an object if filterByColumn is set to true.

```js
search: function (newQuery, oldQuery) {
    this.$refs.myTable.setFilter(newQuery);
}
```
