### ISSUE TITLE
Feature request: add listener for childRow toggle

### ISSUE THREAD

**Issue by ockam** [matfish2/vue-tables-2#41]
Please consider adding a listener to allow childRow to be triggered from another component or from the clickRow event.

**Comment by matfish2** [comment]
You can do so by calling the `toggleChildRow` method on the component (using a `ref`), add passing it the relevant id (which is either an `id`property or what was defined using the `childRowKey` option). E.g to toggle the row with an id of 4 call:

```js
this.$refs.myTable.toggleChildRow(4); // replace myTable with you own ref
```

**Comment by ockam** [comment]
Thanks! May I suggest you add this to the documentation?

**Comment by ockam** [comment]
There is one caveat though: looks like row-click and the toggler are in conflict.

When clicking elsewhere on the row, this works fine but when clicking on the toggler, nothing happens, but I can see the row-click event is triggered in the console.

**Comment by matfish2** [comment]
That is because `toggleChildRow` is fired twice, one by the toggler and one more time by your click row event handler, which results in returning to the initial state. 
I have added e.stopPropagation() to the toggle event. This should solve the problem.
