### ISSUE TITLE
Question: how to set a default sorting for ServerTable ?

### ISSUE THREAD

**Issue by MosheL** [matfish2/vue-tables-2#411]
- Vue.js version: 2
- consumed using: (browserify/webpack/rollup): script tag
- FULL error message (including stack trace):
- relevant code:

tried this on the Vue element:

      mounted: function () {
			debugger 
			this.$refs.tbl.orderBy.ascending = false
				this.$refs.tbl.setOrder(0, 0);

		}
- steps for reproducing the issue:

I am wroting client with ServerTable. I need to set a default sorting, so the Icons will displayed in the needed column and  the request to server will sent with it.

I was tried to set on mount, but it to late as the request was sent before `mounted` event.

I think the `options` of ServerTable need to set the default sorting, as the  DataTables.net and other older grids does.

Thanks for all !!

**Comment by matfish2** [comment]
As documetned:

```js
options:{
  orderBy:{
     column:'someColumn',
     ascending:false
  }
}
```

**Comment by MosheL** [comment]
arr, I was serched the docs again and again for the word `sorting`.

thanks.
