### ISSUE TITLE
How to alter "Search query" placeholder text

### ISSUE THREAD

**Issue by mware** [matfish2/vue-tables-2#412]
- Vue.js version: 2.5.13
- consumed using: webpack
- FULL error message (including stack trace): NA

How can I change the search input text? Currently it defaults to "Search query" without an option to customize it. Any feedback would be appreciated. Thx.

**Comment by matfish2** [comment]
```js
texts:{
 filterPlaceholder:"my placeholder"
}
```

**Comment by ggedde** [comment]
Nice, @matfish2 would be nice it this was added to the README.md

**Comment by vuphuctho** [comment]
Up. The file https://github.com/matfish2/vue-tables-2/blob/master/lib/config/defaults.js should be mentioned in documentation for reference of available configuration options.
