### ISSUE TITLE
afterTable Slot or custom position of elements

### ISSUE THREAD

**Issue by KsCorrales** [matfish2/vue-tables-2#413]
is possible add something html after table?, i need change the position of the limit filter but there isn't  a option to change the position, I thought about creating custom limit filter and using slots positioning after table but there isn't afterTable slot option. i only need position after the table and before the pages buttons the limit filter, how can i do that?.

**Comment by matfish2** [comment]
I've added an `afterTable` slot. Note that you can also use your own template:


> `template` Use this option to select an HTML template. Currently supported: `default`, `footerPagination` You can also pass your own template. Use a file from the templates folder as boilerplate.

**Comment by KsCorrales** [comment]
I have a question @matfish2 is possible render the pagination buttons in any place? i try accessing in the component but I couldn't do it.
