### ISSUE TITLE
customFilters' value is not saved

### ISSUE THREAD

**Issue by yuugou727** [matfish2/vue-tables-2#414]
- Vue.js version: 2.5.13
- consumed using: webpack
- relevant code:

With `vuex`, `vue-router` and 2 custom filters:
Template:
```
<select v-model="statusFilter">
  <option value="1">1</option>
  ...
</select> 
<select v-model="typeFilter">
  <option value="1">1</option>
  ...
</select> 
<v-server-table name="myTable" ref="myTable" url="..." >...</v-server-table>
```
Script:
```
options: {
  preserveState: true,
  saveState: true,
  customFilters: ['status', 'type' ],
}
...
watch: {
  statusFilter: function(newVal) {
    this.$store.commit('myTable/SET_CUSTOM_FILTER', {filter:'status', value: newVal})
  },
  typeFilter: function(newVal) {
    this.$store.commit('myTable/SET_CUSTOM_FILTER', {filter:'type', value: newVal})
  },
...
```

1. `customQueries` of store does mutate with the value I selected. But when I revisit the same route, the table queries with empty string. Mutation `myTable/SET_STATE` didn't bring value which is saved previously in store.

2. Table will send more than one request after revisit if custom filter has been set.  Could `myTable/SET_CUSTOM_FILTER` deal with multiple custom filters and send http-request only once?

**Comment by matfish2** [comment]
Fixed no. 1.
Unable to reproduce no. 2.

**Comment by yuugou727** [comment]
I could only show this ...
![2](https://user-images.githubusercontent.com/22387083/36086021-c0d6b186-1004-11e8-993d-29c2e076162e.PNG)

At the time custom filter changes, more than one `LOADING` events fire before `SET_CUSTOM_FILTER`.
Each `LOADING` payload carries what I had set on custom filter, like history playback. 

Maybe there is a bug in Vuex saved-state accessing and comparison.

**Comment by matfish2** [comment]
So you meant multiple *events*, not multiple *requests*?

**Comment by yuugou727** [comment]
I expect there will be only one http-request. But there are several (`LOADING`, `SET_DATA` and `LOADED` all come together, why?)

**Comment by matfish2** [comment]
Again, these are client events (aka mutations), not server requests. Please go to the Network tab and let me know if more than one request is sent

**Comment by yuugou727** [comment]
Sorry for my misleading description. I thought mutation `SET_DATA` may trigger http-request.

![3](https://user-images.githubusercontent.com/22387083/36459757-fcd8e892-16ef-11e8-9d51-28beffbfb2f1.PNG)

The first _table_ request was sent when page loaded.
Then each time custom filter changes, it will send three request.

**Comment by Imboga** [comment]
Any updates about this? @yuugou727 is right, I'm using few fields for filtering data. When form submission is done it calls this method:
```
setFilters(){
   this.$store.commit('catalog_list/SET_CUSTOM_FILTER', {filter:'text', value: this.search.text && this.search.text.length ? this.search.text : null })
   this.$store.commit('catalog_list/SET_CUSTOM_FILTER', {filter:'type_id', value: this.search.type?.id || null })
   this.$store.commit('catalog_list/SET_CUSTOM_FILTER', {filter:'status_id', value: this.search.status?.id || null })
},
```
This is triggering the `SET_DATA`, therefore the `http-request`, as many times as filters are set. In my case I have 3 request with a single form submit.
Is there a way to send multiple custom filters in one `commit`? I was thinking in something like:
```
setFilters(){
    this.$store.commit('catalog_list/SET_CUSTOM_FILTER', [
       {filter:'text', value: this.search.text && this.search.text.length ? this.search.text : null },
       {filter:'type_id', value: this.search.type?.id || null },
       {filter:'status_id', value: this.search.status?.id || null }
    ])
},
```

**Comment by kuma-guy** [comment]
If we use custom filters with native ```filterByColumn``` feature,  we need to take account of resets

```
this$refs.table.resetQuery()  // for native filters
this.$store.commit(`table/SET_CUSTOM_FILTER`, { filter: 'search', value: '' }); // for custom filter
```

is triggering two http-requests
