### ISSUE TITLE
Template isn't applied when enclosed within a template tag

### ISSUE THREAD

**Issue by vincemukiiri** [matfish2/vue-tables-2#416]
- Vue.js version: 2.5.8
- consumed using: webpack
- Steps for reproducing the issue:

I'm trying to apply a template to every cell in the table. I initially used the following code.
```
<v-client-table :data="data" :columns="columns" :options="options">
    <span v-for="column in columns" :slot="column " slot-scope="props" 
        :class="props.row[column] < 0 ? 'text-danger' : ''">
        {{ props.row[column] }}
    </span>
</v-client-table>
```
This works, however vue gives this warning while compiling:

`Ambiguous combined usage of slot-scope and v-for on <span> (v-for takes higher priority). Use a wrapper <template> for the scoped slot to make it clearer.`

And so I did like so: 
```
<v-client-table :data="data" :columns="columns" :options="options">
    <template v-for="column in columns">
        <span :slot="column" slot-scope="props"
              :class="props.row[column] < 0 ? 'text-danger' : ''">
            {{ props.row[column] }}
        </span>
    </template>
</v-client-table>
```
But now the template isn't applied to the cells.

**Comment by matfish2** [comment]
I checked the value of `$vm0.$scopedSlots` in Chrome dev tools, and when using the `template` wrapper the slots aren't registered there (i.e I get an empty object). 
So, I am not sure why are you instructed to wrap your slots like that, but I have no way of applying them if they are not registered

**Comment by maxim25** [comment]
Any workaround for this? I just ran into the same problem.

**Comment by matfish2** [comment]
Moving the slot up to the `template` element worked for me:

```html
<template v-for="column in columns" :slot="column" slot-scope="props">
        <span  :key="column"
              :class="props.row[column] < 0 ? 'text-danger' : ''">
            {{ props.row[column] }}
        </span>
</template>
```
