### ISSUE TITLE
number pagination(normal pagination) not displaying

### ISSUE THREAD

**Issue by vinothcl** [matfish2/vue-tables-2#418]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

number pagination(normal pagination) not displaying

`  data: {
		options:{ 
			pagination: { chunk:10, dropdown:false },
			perPage : 10 
		},
		perPage :10,
		columns: ['acc_no', 'acc_name', 'acc_type','contact_email', 'contact_phone', 'acc_portfolio_value'],  
        accountlist_columns: ['Account No123', 'Account Name123', 'Account Type', 'Email', 'Phone Number', 'Portfolio'] ,
		ajax_pagination_url: '/accounts/accountList?auth_token='+JSON.parse(localStorage.getItem("auth_token")).auth_token		
    },`

**Comment by matfish2** [comment]
Closing. Related to #417
