### ISSUE TITLE
Question: multi-sort on other columns, initial click on other columns descending?

### ISSUE THREAD

**Issue by mware** [matfish2/vue-tables-2#419]
- Vue.js version: 2.5.13
- consumed using: webpack

Amazing plugin. Saved me hours and hours of work. My collaborators are also impressed but would like to know if there is a way multi-sort on the other columns (not the main orderBy column) when they are clicked, and if that initial click could be descending instead of ascending? 
Thanks!

**Comment by matfish2** [comment]
Yes. Did you read the [docs](https://github.com/matfish2/vue-tables-2#multiple-sorting) regarding multiple sorting?

**Comment by mware** [comment]
Re-reading the docs made me realize that I can add multi-sort to any column, not just the initial orderBy column. Thanks for that. I didn't find anything about altering the initial click on a column to be descending instead of ascending.
