### ISSUE TITLE
Row Callback

### ISSUE THREAD

**Issue by pmartelletti** [matfish2/vue-tables-2#42]
- Vue.js version: 2.0
- consumed using: webpack

@matfish2 are you planning / are you interested in adding a row class callback function? This would be useful for adding a custom class to couple of data, i.e.: closed itemas, overdue invoices, etc.

**Comment by matfish2** [comment]
I don't know what is a "row class callback function".

**Comment by pmartelletti** [comment]
@matfish2 something like:

https://datatables.net/reference/option/rowCallback

**Comment by pmartelletti** [comment]
@matfish2 I'm using like this in my own fork:

```
     if (that.opts.rowClassCallback) rowClass = that.opts.rowClassCallback(row);

      rows.push(<tr class={rowClass} on-click={that.rowWasClicked.bind(that, row)}>{columns} </tr>);
```

**Comment by matfish2** [comment]
Ok. You are welcome to send a PR and I will merge it.
