### ISSUE TITLE
Enhancement: Immediate search when user press enter

### ISSUE THREAD

**Issue by d-lobanov** [matfish2/vue-tables-2#421]
It's not a bug, it's just an enhancement. 

It would be nice to have a immediate search in text filter field when user press enter even if `debounce` was set. It's kind of unexpected behavior that user has to wait `debounce` time even if enter was pressed, IMHO.

If it's expected behavior just ignore me. If not, I can help to fix that 🐙

**Comment by matfish2** [comment]
Good idea. a PR is most welcome
