### ISSUE TITLE
ResponseAdapter not called when using Vuex as of 1.3.0?

### ISSUE THREAD

**Issue by sebas1983** [matfish2/vue-tables-2#422]
- Vue.js version: 2.5.13
- consumed using: webpack
- steps for reproducing the issue:

When using:
`Vue.use(ServerTable, DatatableOptions, true, 'bulma', 'footerPagination');`
The responseAdapter **is not** called and the table errors out on having no data.

Changing above to:
`Vue.use(ServerTable, DatatableOptions, false, 'bulma', 'footerPagination');`
The responseAdapter **is** called and table renders flawless.

Prior to version 1.3 this used to work. Am I overlooking anything?

Regards,

**Comment by matfish2** [comment]
See README:

>Breaking change notice: As of version 1.3.0 the `loaded` event passes the full response object, not just >the response data. In the same manner, the `responseAdapter` option receives the original response.

**Comment by sebas1983** [comment]
I feel I might have been a bit unclear here.

It seems that when using vue-tables-2 **with** Vuex, the responseAdapter is not used to alter the reponse. 

The setData() method on line 107 in the '/lib/state/vuex.js' file is fired. Which then tries to commit data to the table state, but it received the full response instead of just the data part.

Should this method not have the same change that was made in #403 in '/lib/methods/set-data.js'? Like so:

`setData: function setData(response) {
        var data = this.opts.responseAdapter.call(this, response);

        this.commit('SET_DATA', { data: data });
        this.commit('LOADED', { data: data });

        setTimeout(function () {
          this.dispatch('loaded', response);
        }.bind(this), 0);
      }`

Regards,
