### ISSUE TITLE
Put the filter in EloquentVueTables in closure

### ISSUE THREAD

**Issue by ixperiencenl** [matfish2/vue-tables-2#423]
When using the filter functionality in the disclosed PHP class, this overrides previous made filters on the query because they will be included in the OR statements in the query. I stumbled upon this while filtering data for specific users but it was returning all data when searching in the filter box.

EloquentVueTables.php line ~56:

`foreach ($fields as $index=>$field):
    $method = $index?"orWhere":"where";
    $data->{$method}($field,'LIKE',"%{$query}%");
  endforeach;`

Changed to: 
`$data->where(function($qry) use($data, $query, $fields) {
			foreach ($fields as $index => $field) {
			    $method = $index ? "orWhere" : "where";
			    $qry->{$method}($field, 'LIKE', "%{$query}%");
			}
    	});`

I know this will not be needed for everyone here using this repo but I think it is handy to inform others.

**Comment by matfish2** [comment]
Good catch. You are welcome to send a PR
