### ISSUE TITLE
ResponseAdapter follow up from #422

### ISSUE THREAD

**Issue by sebas1983** [matfish2/vue-tables-2#427]
Vue.js version: 2.5.13
consumed using: webpack
Follow up from: #422 

I feel I might have been unclear there.

It seems that when using vue-tables-2 **with** Vuex, the responseAdapter is not used to alter the reponse. 

The setData() method on line 107 in the '/lib/state/vuex.js' file is fired. Which then tries to commit data to the table state, but it received the full response instead of just the data part.

Should this method not have the same change that was made in #403 in '/lib/methods/set-data.js'? Like so:

```
setData: function setData(response) {
        var data = this.opts.responseAdapter.call(this, response);

        this.commit('SET_DATA', { data: data });
        this.commit('LOADED', { data: data });

        setTimeout(function () {
          this.dispatch('loaded', response);
        }.bind(this), 0);
      }
```

Regards,

**Comment by slusarenkoalexey** [comment]
I have the same problem, and found the same

**Comment by matfish2** [comment]
@sebas1983, you are right. Fixed it. Please upgrade and check again

**Comment by sebas1983** [comment]
Flawless again!
Thanks.
