### ISSUE TITLE
Feature Request: Ability to customize pagination component

### ISSUE THREAD

**Issue by mykeels** [matfish2/vue-tables-2#429]
- Vue.js version: ^2.4.1
- consumed using: webpack
- FULL error message (including stack trace): NONE

If possible, add ability to customize the `vue-pagination-2` component used within this component.

Currently, I'd like to display `Showing 1 to 5 of 25 loaded records` instead of `Showing 1 to 5 of 25 records`, but I can't find anyway to achieve this with the current API.

Perhaps props beginning with the `pagination-` prefix can be passed to this component, and in turn, passed to the `vue-pagination-2` component to override its defaults.

**Comment by mykeels** [comment]
I just realised I could pass in 

```
{
  texts: {
    count: 'Showing {from} to {to} of {count} loaded records|{count} records|One record'
  }
}
```

in the `options` object passed as a prop to this component, which solves my problem. I think this is awesome, and should be in the README docs.

**Comment by matfish2** [comment]
It *is* in the README. `Options` > `texts`. I put a link to the texts file instead of cluttering the options table with the entire object. All the texts are modifiable.
