### ISSUE TITLE
any existing solution for CRUD functionality?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#43]
Really digging this project and am using the tables in my current project.

Doings things like delete a record is pretty easy but what about insert/update? Is there a plan to add this functionality or is there a suggested other package that can be used to make this relatively painless to add? Something that uses the existing columns schema ideally.

What's everyone else using to do this?

Thanks!

**Comment by matfish2** [comment]
There is no plan to add CRUD functionality. However this should be relatively easy to implement using templates. For example, to make the `title` column editable, make the title an object:

```js
{
  value:'Some title',
  editing:false
}
```

Then define the template:

```js
  title: function(h, row) {

        if (!row.title.editing)
          return <span on-click={this.edit.bind(this, row)}>{row.title.value}</span>;

          return  <div><input type='text' value={row.title.value}/>
<button on-click={this.save.bind(this,row)}>Save</button>
</div>;

    }
```

Edit and save methods:

```js
methods:{
edit: function(row) {
    row.title.editing = true;
    return row;
},
save: function(row) {
  row.title.editing = false;
  return row;
}
}
```

**Comment by vertoo** [comment]
Hello,

@matfish2 I have question related to your example. In vue file I have:
```js
// ...
import show from './jsx/show.jsx'
// ...
columns: ['show']
// ...
templates: {
    ...
    show: show
}
// ...
methods: {
    show(row) {
        console.log('CLICK');
    },
}
```

show.jsx file:
```jsx
export default function(h, row) {
    return <span on-click={this.show.bind(this, row)}>show</span>
}
```

I have error: `this.show is undefined`, when trying more attemps with on-click syntax I had errors:
* `TypeError: o.fn is not a function`. 
* Tried change `this` with `that` - `that is undefined`. 
* `on-click={bus.$emit('id-selected', 1)} - `o.fn is not a function`

I use webpack from Laravel 2.1.0-beta.22, all node packages are fresh re-installed. Previous vue version was 2.0.x, current is up to date: 2.1.8.
.babelrc
```
{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}
```

loaders in webpack config:
```
test: /\.jsx?$/,
loader: 'babel',
include: [
    path.resolve(__dirname + '/node_modules/vue-tables-2/'),
    path.resolve(__dirname + '/node_modules/vue-pagination-2/'),
    path.resolve(__dirname + '/resources/assets/js/app/pages/projects/jsx/')
]
```

Currently I don't have idea what is bad in my code.

**Comment by vertoo** [comment]
Found my problem. Methods must be declared in root component.
