### ISSUE TITLE
integrating with vue-cli

### ISSUE THREAD

**Issue by jnal** [matfish2/vue-tables-2#430]
New to this stuff and will be needing help.

- Vue.js version: 2.5.13
- consumed using: vue-cli - webpack
- FULL error message (including stack trace):
Uncaught ReferenceError: process is not defined
    at eval (utils.js?bc36:3)
    at Object../node_modules/micromatch/lib/utils.js (app.js:2740)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (expand.js?58f9:10)
    at Object../node_modules/micromatch/lib/expand.js (app.js:2724)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (index.js?7fb9:10)
    at Object../node_modules/micromatch/index.js (app.js:2708)

- relevant code:

```
<template>
 <v-server-table :columns="['CreatedDate', 'AdminActivityName', 'CreatedBy', 'Changes']" />
</template>

<script>
    import Vue from 'vue'
    import { ServerTable } from 'vue-tables-2';
</script>

```

- steps for reproducing the issue:
1. created a new project from vue cli using default webpack template 
2. npm install vue-tables-2 
3. imported Server table from the .vue file and received the error.

**Comment by mykeels** [comment]
Looks like this might help @jnal https://stackoverflow.com/a/41359607/7396801

**Comment by clementvp** [comment]
Looks this issue is relative with vue-cli v3. I have the same issue with the v3 (In beta) but not in v2.
Same error message for me in v3 process is not defined.
@jnal  did you figured out ? If yes can you explain how :) (I tried to manipulate vue.config.js but it's tricky)

**Comment by vesper8** [comment]
Am also having this issue, also on a project using vue-cli 3 (beta.2)

I tried the solution from the SO above. In my vue.config.js added

```
const webpack = require('webpack');

module.exports = {
  lintOnSave: true,
  dll: true,
  configureWebpack: {
    plugins: [
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('development'),
      }),
    ],
  },
};
```

But that doesn't fix the error:

![screenshot 2018-03-03 15 38 13](https://user-images.githubusercontent.com/816028/36939058-e6d2257a-1ef8-11e8-9771-6473f91bec31.png)

**Comment by vesper8** [comment]
I just found a workaround, see my comment here https://github.com/vuejs/vue-cli/issues/934#issuecomment-370188249

**Comment by vesper8** [comment]
Evan just fixed it :) So that means once v3.beta.4 is tagged the workaround won't be needed anymore
