### ISSUE TITLE
Ability to customize component.

### ISSUE THREAD

**Issue by McGittyHub** [matfish2/vue-tables-2#432]
I would like to be able to:

* Translate the text into my language.

* Remove items-per-page dropdown

* Move columns picker somewhere else

Any advice?

**Comment by matfish2** [comment]
* Use the `texts` option (See Options table at the end of README)
* Pass an empty array to `perPageValues`
* This can only be achieved using a custom template. Copy `templates/default.js`, modify to your needs, and pass it in the `Vue.use` statement.

**Comment by McGittyHub** [comment]
Thanks a lot! 👍 

Could I not in fact make my own columns picker and then update visible columns accordingly in the options object?

**Comment by matfish2** [comment]
You can if you are so inclined. Note that you need to update the `columns` array that you passed, not the `options` object.

**Comment by McGittyHub** [comment]
oh yeah that's right :)

Thanks for the help
