### ISSUE TITLE
is it now possible to have multiple custom templates for multiple tables on the same page?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#433]
So before 1.3.0 it was not possible to have two different table templates on the same page. I had opened an issue about this before #303

With the recent modifications to how you handle custom templates, has this now become possible?

I am still on a version pre 1.3.0 and would like to upgrade but want to know if I will still have the same problem.

Currently it's a big problem because I use Turbolinks so if I visit "Page 1" which uses "Table Template 1" and then I visit "Page 2" which uses "Table Template 2" even though this is a different page, because of how Turbolinks works it will still be using "Table Template 1" because it was globally registered

**Comment by matfish2** [comment]
No, not possible. The template is registered globally with the `Vue.use` declaration and cannot be determined individually for each component instance. Of course, you can have different templates for the server and client components.

As for Turbolinks, if it doesn't register the component on page load (why not? Should it not reload the new assets?), I am quite sure you can do it yourself by listening to the dedicated turbolinks' page load event and calling `Vue.use`

**Comment by vesper8** [comment]
as far as I understand with Turbolinks part of the vue bootstrap isn't re-run on every page where vue is used, so some things that get registered on the initial load don't get re-registered when the page changes.. hence why the custom template that is registered on Page 1 persists to Page 2 and the custom template defined in Page 2 is not respected or overridden as a result

Is there really no way you can think of to allow two server tables on the same page to use two different templates?? this has been a problem for me for many months.. what would need to be changed in order to make this work? Maybe I can help with a PR.. but I'd need to understand better why the table template is resistant to this kind of change for two different components that make use of a server table

**Comment by matfish2** [comment]
> Is there really no way you can think of to allow two server tables on the same page to use two different templates? 

Not that I can think of. AFAIK, This is a limitation inherent to Vue. The template is declared on the component level (i.e on _registration_). Thus, you can't use different templates on instances of the same component, unless you opt for the hacky solution of a huge `v-if`-`v-else` block, to decide the template when the instance is _rendered_. If you think there is a _reasonable_ solution, you are definitely welcome to send a PR.

**Comment by vesper8** [comment]
What about a way of fully tearing down in the beforeDestroy hook ?

Is it possible to explicitly undo/teardown the work done by Vue.use() so that I may use Vue.use() again ?

Oh and.. do you think the problems I am having right now, I would also have if I made use of vue-router (SPA style) instead of using Turbolinks?

**Comment by matfish2** [comment]
I don't know if its possible to undo `Vue.use`, and even if it is I am quite reluctant to do it.
I am pretty sure you won't experience the same issue with `vue-router`
