### ISSUE TITLE
FQ: special filter  template 

### ISSUE THREAD

**Issue by MosheL** [matfish2/vue-tables-2#435]
When I am looking on docs I see a special handling of dates ranges: `dateColumns`
its depend on jQuery and a plugin, and it solve the problem of date-filtering only.

I do not like the option you was selected, and also - I prefer to write a Vue component for handling some special fields (like objects from other tables in the database).

I think it will be better to make a list of  `filterTemplates`, like `templates` option works.

**Comment by matfish2** [comment]
From the docs:

> In addition to these slots you can insert your own filter HTML in the filters row, or add content to the existing filter, e.g a button (When filterByColumn is set to true):
> 
> A. If you just want your own content make sure that the column is not filterable by omitting it from the filterable array. Otherwise the slot content will be appended to the native filter.
> 
> B. Create a slot whose name is formatted filter__{column} (double underscore).
> 
> For example, to insert a checkbox on the id column instead of the normal input filter:
> 
> {
>   filterable:["name","age"] // omit the `id` column
> }
``` 
<div slot="filter__id">
     <input type="checkbox" class="form-control" v-model="allMarked" @change="markAll()">
 </div>
```

This in conjunction with custom filters gives you the ability to create your own filter

**Comment by MosheL** [comment]
No, No

This Idea from docs is not working without workarounds  on Server Table.

I will explain:

- I can add an template *under* the textbox from the internal filter
- I can  completly disable the internal filter and write other tool in-place.
   for your example (mark all) it working, but the slot is  can't pass  value up .

- I can't write a generic search filter for type of columns, and pass the data to JSON without working around.
- the ServerTable AJAX processor will not pass the custom filter information to the server.

I can select a `template` for each col via  `options.templates`, I can't do it for the search.  If I want to change the input into checkbox or date picker for example and pass the information to  `query` on the server - I couldn't.
