### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by sylvaincaillot** [matfish2/vue-tables-2#440]
Hello, 
I am really enjoying your library. 
I have developed a front end based on element-Ui and would like to format the tables as [this example](http://element.eleme.io/#/en-US/component/table). How difficult is it to add a new theme to vue-tables-2?

Thank you very much

**Comment by matfish2** [comment]
As documented, the package allows for using a custom theme (and if necessary, a custom template). Use a file from the `themes` folder as a boilerplate. If you think others could benefit from your theme you are welcome to send a PR.

**Comment by MatiasOlivera** [comment]
How can I register my custom theme/template?
