### ISSUE TITLE
Using Fontawesome 5 for sort icons [enhancement]

### ISSUE THREAD

**Issue by rico** [matfish2/vue-tables-2#441]
It would be nice, if we could use _Fontawesome_ icons version 5 for the sort icons, e.g.

```
sortIcon:{
   is:'fa-sort',
   base:'fas',
   up: 'fa-sort-up',
   down: 'fa-sort-down'
}
```

The `is` value works, but the current implementation is just switching classes for the element, and that is not working for _Fontawesome 5,_ as it replaces the `<span>` elements with `<svg>`.

Thanks for your work, really appreciate it and love to use it!

**Comment by jesuscaridad** [comment]
hice lo mismo pero no me funciono

**Comment by alanaasmaa** [comment]
If there would be an option to add custom template then it would be possible to generate the html using font awesome api.

`https://fontawesome.com/how-to-use/font-awesome-api#advanced-stuff`

**Comment by jblotus** [comment]
customizing the icon tag / template would be handy

**Comment by morficus** [comment]
This actually worked for me

```
sortIcon:{
            base:'fa fas',
            is:'fa-sort',
            up: 'fa-sort-alpha-asc',
            down: 'fa-sort-alpha-desc'
          }
```

**Comment by francislavoie** [comment]
@morficus that's FontAwesome 4, not 5.

**Comment by gitBC** [comment]
My project uses Vue and the Vue compenent. In my case, I'm also swapping icons with SVGs via the dom watcher. I simply needed to instruct fontawesome-svg-core to use the nesting style of swapping instead. 
`
/**
 * Setting this config so that Vue-tables-2 will be able to replace sort icons with chevrons
 * https://fontawesome.com/how-to-use/with-the-api/setup/configuration
 */
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoReplaceSvg = "nest";

/**
 * Allows DOM to change <i> tags to SVG for more features like layering
 * https://fontawesome.com/how-to-use/on-the-web/styling/layering
 */
import { dom } from '@fortawesome/fontawesome-svg-core'
dom.watch();
`

**Comment by molerat619** [comment]
We need it too. I have tried what @gitBC suggested but it didn't help in our case. This is our fontawesome configuration:

```
import Vue from "vue";
import "@fortawesome/fontawesome/styles.css";
import fontawesome from "@fortawesome/fontawesome";
import {
  faAddressCard,
  faCar,
  faCaretLeft,
  faCaretRight,
  faCheck,
  faClone,
  faCoffee,
  faEdit,
  faGripHorizontal,
  faGripVertical,
  faHome,
  faSave,
  faToggleOff,
  faToggleOn,
  faTrash
} from "@fortawesome/free-solid-svg-icons";

import {
  faCircle,
  faSquare
} from "@fortawesome/free-regular-svg-icons";

import { FontAwesomeIcon, FontAwesomeLayers } from "@fortawesome/vue-fontawesome";

/**
 * Setting this config so that Vue-tables-2 will be able to replace sort icons with chevrons
 * https://fontawesome.com/how-to-use/with-the-api/setup/configuration
 */
/**
 * Allows DOM to change <i> tags to SVG for more features like layering
 * https://fontawesome.com/how-to-use/on-the-web/styling/layering
 */
import { config, dom } from "@fortawesome/fontawesome-svg-core";

fontawesome.config = {
  autoAddCss: false
};

// Add Solid SVG Icons (Alphabetically listed)
fontawesome.library.add(
  faAddressCard,
  faCar,
  faCaretLeft,
  faCaretRight,
  faCheck,
  faClone,
  faCoffee,
  faEdit,
  faGripHorizontal,
  faGripVertical,
  faHome,
  faSave,
  faToggleOff,
  faToggleOn,
  faTrash
);

// Add Regular SVG Icons (Alphabetically listed)
fontawesome.library.add(
  faCircle,
  faSquare
);

config.autoReplaceSvg = "nest";
dom.watch();

Vue.component("fa", FontAwesomeIcon);
Vue.component("fa-layers", FontAwesomeLayers);
```

**Comment by nelson6e65** [comment]
### Amazing, @gitBC ! :tada:  This works! Thanks! :heart: 

You just need to import the icons to use, add to library, apply your config and is ready to go:

```js
import Vue from 'vue'
import { library, config, dom } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import {  
  faSort,
  faSortAlphaDown,
  faSortAlphaUp 
} from '@fortawesome/free-solid-svg-icons'

config.autoReplaceSvg = 'nest'

/**
 * Allows DOM to change <i> tags to SVG for more features like layering
 * https://fontawesome.com/how-to-use/on-the-web/styling/layering
 */
dom.watch()

library.add(
  faSort,
  faSortAlphaDown,
  faSortAlphaUp,
)

Vue.component('fa', FontAwesomeIcon)
```

@gitBC comment should be added to documentation

**Comment by indy659** [comment]
@gitBC 
You beauty!
