### ISSUE TITLE
Empty date string returns undefined when using toMomentFormat

### ISSUE THREAD

**Issue by mgattelli** [matfish2/vue-tables-2#443]
- Vue.js version: 2.5.2
- consumed using: webpack
- vue-tables-2 version: 1.2.45

Hi all,

The server can return an empty string as a date and the table print *undefined* as result in the cell, is there a way to say the table to skip the moment formatting  when a value is undefined?

Thanks in advance and.... great great job :)

**Comment by matfish2** [comment]
If you are using the *server* component then the table is "dumb" and displays whatever is returned from the server. You can use the `templates` option to modify the presentation of a column.

If you are using the *client* component then dates should be passed as `moment` objects. You can use the `toMomentFormat` option, which turns all date columns data into `moment` objects.
So which of them are you using, server or client?

**Comment by mgattelli** [comment]
I am usign the *client* component and, as the docs says, I am using the `toMomentFormat` in order to turns the string into `moment` objects, the problem is when the date string is empty, of course the result of the moment formatting is `undefined`.
I'll provide an image of the problem as soon as possible.

**Comment by matfish2** [comment]
> I'll provide an image of the problem as soon as possible.

No need. I see the problem. I need to add an `if` statement to ignore parsing of empty properties.
In the mean time you can do the processing yourself. Just iterate over your data and modify the dates before you pass it to the component.

**Comment by mgattelli** [comment]
Great @matfish2, really appreciate.

I'd like to show an empty string as a date so I can't simply modify the data, but don't worry I'll wait. :)
