### ISSUE TITLE
VServerTable - Paginator strange behavior

### ISSUE THREAD

**Issue by elton182** [matfish2/vue-tables-2#444]
- Vue.js version: 2.5.2
- consumed using: webpack

There is some strange behavior with paginator, and I don't know if I'm using it correctly.

What value should i return on the **count** property? 

1. The total of records?
2. The total of filtered recods?
---
## Total of Records

When I return the total of records in database, it shows the correctly number of pages

![image](https://user-images.githubusercontent.com/8716770/36898985-e6419c2e-1dfb-11e8-8ecc-ddb4f4590049.png)

But, if I filter, it keep showing the total number of pages, but it should only have 1 page

![image](https://user-images.githubusercontent.com/8716770/36899023-1223df00-1dfc-11e8-969f-28beec216b4f.png)
---
## total of filtered records

When i return the total of filtered records it shows no paginator at all
![image](https://user-images.githubusercontent.com/8716770/36899098-584e4f56-1dfc-11e8-80f6-143ac95bf9b6.png)

---

**I think there should be a prop for the total of filtered records e the count be only for de total of records**

**Comment by matfish2** [comment]
The server table is "dumb". It doesn't know the total unless you tell it. Your `count` property, as returned from the server, must reflect the total count before reducing to the current page. The Laravel implementation I've included clearly shows how it's done

**Comment by elton182** [comment]
@matfish2 worked as you said, thanks for the support
