### ISSUE TITLE
When initFilter for Dates is used, the daterange is not displayed in the text

### ISSUE THREAD

**Issue by molerat619** [matfish2/vue-tables-2#447]
- Vue.js version: 2.5.13
- consumed using: Laravel
- relevant code: 

```
initFilters: {
	order_date_time: {start: moment().startOf('month'), end: moment().endOf('month')}
}
```
The filtering process itself works absolutely fine. The only problem is, that the filter text and the daterangepicker do not reflect the initialFilters.

1. It still shows "Filter by column_name" (in german) - I am not using slots, it's the simple column with headings setup, but using the texts option to translate all fields. IMO this should show the range that the table is being filtered by (like it does when you manually pick a date range):
![image](https://user-images.githubusercontent.com/3458576/36941398-a57f7aca-1f5a-11e8-804e-b89a18d85845.png)

2. When you open the daterangepicker, it shows "today" as selected instead of the range that is set in the initFilters-options.
![image](https://user-images.githubusercontent.com/3458576/36941405-de09501e-1f5a-11e8-9aa4-c55ef6ad6dc5.png)

But still, the correct date range is being sent to the backend.
![image](https://user-images.githubusercontent.com/3458576/36941415-17554b70-1f5b-11e8-9b08-0fa717340785.png)

**Comment by molerat619** [comment]
Works great now, thanks.

**Comment by kylepinheiroinmar** [comment]
@molerat619 What ended up being the solution to make the daterangepicker show the initial values? I have run into the exact same issue.
