### ISSUE TITLE
can't use the table

### ISSUE THREAD

**Issue by mohsenpayro** [matfish2/vue-tables-2#448]
- Vue.js version: 2.5.13
- consumed using: (webpack/eslint/autoprefixer/bootstrap-vue/vue-loader)
- FULL error message (including stack trace): options is not defined  / useVuex is not defined / theme is not defined / template is not defined
- relevant code: Vue.use(ClientTable, [options = {}], [useVuex = false], [theme = 'bootstrap3'], [template = 'default'])
- steps for reproducing the issue: import server and client table with Event like explained in the docs and then use them with Vue.use() ( ps: i didn't forgot to import Vue )

after installing the package through npm i can't use the table because of the error i mentioned above.
any ideas what's wrong?

**Comment by matfish2** [comment]
> Vue.use(ClientTable, [options = {}], [useVuex = false], [theme = 'bootstrap3'], [template = 'default'])


This is the format **for documentation purposes only**
You shouldn't use it like that in your code, as it is invalid JavaScript.
Instead:
```js
Vue.use(ClientTable) // and any other parameters if they are different than the default.
```
