### ISSUE TITLE
Default customFilters value and Column naming

### ISSUE THREAD

**Issue by jkehler** [matfish2/vue-tables-2#45]
- Vue.js version: 2.1.6
- consumed using: webpack

First of all this is a nice little library you've made. I have 2 issues that I'm not sure how to solve. I'm hoping you could provide some insight on how I might solve it.

1. I am using the customFilters with Vuex to pass in an advanced JSON filter to the server. The problem is that I want to set a default value here that is used **before** the table is loaded. What it seems to do now is it will load all of my records as soon as the table mounts, and then after it will have to query a 2nd time when i set the custom filter. Is there any way to pass in a default customFilter value that will be used on the initial table mount?

2. It seems columns can only be defined using an array mapped to the data. However, is it possible to set the names directly? Eg. ```columns: [{ name: 'id', title: 'User ID' }]```

Thanks again for this library!

**Comment by matfish2** [comment]
1. Check out the `initFilters` option
2. Columns are required. Heading are not. Therefore heading are declared in a separate option.

**Comment by rezadaulay** [comment]
How to set initFilters ?
