### ISSUE TITLE
"ReferenceError: moment is not defined", when i use toMomentFormat

### ISSUE THREAD

**Issue by hackmigo** [matfish2/vue-tables-2#450]
- Vue.js version: 2.1.0
- consumed using: webpack
- FULL error message (including stack trace):
```
[Vue warn]: Error in mounted hook: "ReferenceError: moment is not defined"
found in
---> <ClientTable>

```
- relevant code:
 ```
options:{
  dateColumns:[ 'last_login','reg_date' ],
  toMomentFormat: 'YYYY-MM-DD',
   .....
}
```

I do not know whether it is my grammatical mistakes, if wrong, please tell me, plz

**Comment by matfish2** [comment]
You need to import moment globally


Sent from my Samsung device

-------- Original message --------

**Comment by hackmigo** [comment]
Thank you. when i change `require('moment');` to `window.moment = require('moment');`  It's work.  
and .... i have another problem now. 

below is my setting for date filter 
```
filterable: ['member','last_login'],
dateColumns:['last_login','reg_date' ],
datepickerOptions:{
   locale: { cancelLabel: 'Clear' },
   showDropdowns: true
},
```
also import daterangepicker globally.

click the filter field, nothing happened.

**Comment by matfish2** [comment]
See #445
