### ISSUE TITLE
Hiding global search input doesn't work

### ISSUE THREAD

**Issue by sergiocastrovale** [matfish2/vue-tables-2#452]
I'm using v1.3.1 and I'm trying to disable any sort of filtering in my table. Following the docs, I've tried to do it in two ways:

1. filterable: []

Search bar shows up just like with filterable: true.

2. Filterable: false

Search bar shows up for a second, then it's hidden.

My question is - why the flickering? Shouldn't the search bar be _removed_ from the markup instead of being just hidden via CSS? Is there any way to solve this?

**Comment by matfish2** [comment]
The search bar **is** removed from the markup. There shouldn't be a flicker nor can I see one on my end.
I have fixed the empty array behaviour

**Comment by sergiocastrovale** [comment]
@matfish2 after updating to v1.3.61, everything seems to be working as expected. Thanks for the quick reply!
