### ISSUE TITLE
Ignore certain part of table

### ISSUE THREAD

**Issue by molerat619** [matfish2/vue-tables-2#454]
Hey there,

how can I have this following table which should sort, filter and paginate the lower part (as it is existing data), but ignoring the upper part (where new entries will be added).

The upper part should not be touched by sort, filter or paginate, only the lower part.

![image](https://user-images.githubusercontent.com/3458576/37153770-19b57e5e-22de-11e8-8e22-11b43190311d.png)

**Comment by matfish2** [comment]
You can use the `beforeBody` or (`prependBody`) slot to add independent rows at the beginning of the table. However, this content is completely up to you to maintain (e.g you can't use `templates` to render the content)

**Comment by molerat619** [comment]
Thank you @matfish2 . I have tested that quickly with a simple datatable and it worked. I will try it again with that more complex table on Monday. Until then, this can be closed :)

**Comment by molerat619** [comment]
That worked fine, thank you!
