### ISSUE TITLE
Server vs client side table 

### ISSUE THREAD

**Issue by McGittyHub** [matfish2/vue-tables-2#457]
I’m currently using Server side table in a very customized environment. I’m manually refreshing the table when searchdata changes and using a custom request function. 

While this works as expected. The code has some smells that I would like to avoid. Like accessing table by ref. 

Can I use client side table instead and still do sorting, filtering and pagination on the server side?

**Comment by matfish2** [comment]
> Can I use client side table instead and still do sorting, filtering and pagination on the server side?

Why would you want to do that? Client table by definition doesn't need the server. Once it received the initial dataset it is completely autonomous and independent. Also, how would this solve your "code smells"? (accessing a table by ref is IMHO *not* a code smell. It is the straight forward way to call table methods. You can always create a wrapper function on your parent if you find yourself calling those methods in multiple places)

**Comment by McGittyHub** [comment]
I guess it’s a matter of maintainability. Having extra boilerplate code to avoid ‘magic’ is going to make it easier to maintain down the road, and with different developers taking over eventually. 

I would also like to keep the data in a store and maybe do some temporary caching etc. Generally just more control of fetching and retrieving data.

**Comment by matfish2** [comment]
The question seems too generic for me, and I don't fully understand the issue, but I'll try to donate my five pence. 
A client table should be used for relatively small datasets (say up to 20,000 records). If this is the size of your dataset using client table will save you all the server side work of implementing pagination, sorting, filtering etc, and will allow much more flexibility in terms of manipulating the dataset on runtime. There is no support for a "hybrid" server-client table.

**Comment by McGittyHub** [comment]
I definitely want server side filtering/sorting/pagination. This is already done and not an issue. Everything is working currently with server side table. Just looking at ways to improve code quality.. guess I’ll stick to server side table for now.

**Comment by matfish2** [comment]
Maybe I can be more helpful if you paste some code
