### ISSUE TITLE
Filter exactly by...

### ISSUE THREAD

**Issue by molerat619** [matfish2/vue-tables-2#458]
- Vue.js version: 2.5.13
- consumed using: Laravel

I have set an initFilter of the `order_id` column in a task-table to a given id (let's say 1). In the database, I have only 6 entries (tasks) that go to order_id == 1. But since the query is using `LIKE` I get all other results that contain (or at least start with) a 1.

How can I set the filter to filter **exactly** by 1, not only *like*

**Comment by matfish2** [comment]
This issue is not related to the client. You need to modify the server code to use exact comparison. The default Laravel implementation uses `LIKE` for open text queries and `=` for list queries (i.e if you include the column in the `listColumns` option).

**Comment by molerat619** [comment]
Alright, thank you. Should I post that anywhere here for other people to use? I want to implement something for relationships as well, but I think I saw something around here already.

**Comment by matfish2** [comment]
Sure. If you think it might be useful to others, and doesn't just answer your particular needs, you are welcome to send any improvements you made.

**Comment by molerat619** [comment]
So I used https://github.com/matfish2/vue-tables-2/pull/169 to get the relationships working and I added an extra parameter to the construct that takes an array of fields that should be handled with `=` instead of `LIKE` (only for string-like values though). This is my working class now:

```
class EloquentVueTables implements VueTablesInterface
{
	public function get($model, array $fields, array $with = [], array $mustEquals = [])
	{
		extract(request()->only(['query', 'limit', 'page', 'orderBy', 'ascending', 'byColumn']));

		$data = (empty($with))? $model->select($fields) : $model->select($fields)->with($with);

		if (isset($query) && $query) {
			$data = $byColumn == 1 ?
				$this->filterByColumn($data, $query, $mustEquals) :
				$this->filter($data, $query, $fields, $mustEquals);
		}

		$count = $data->count();

		$data->limit($limit)
			->skip($limit * ($page - 1));

		if (isset($orderBy)):
			$direction = $ascending == 1 ? 'ASC' : 'DESC';
			$data->orderBy($orderBy, $direction);
		endif;

		$results = $data->get()->toArray();

		return [
			'data' => $results,
			'count' => $count];
	}

	protected function filterByColumn($data, $queries, $mustEquals)
	{
		return $data->where(function ($q) use ($queries, $mustEquals) {
			$queries = json_decode($queries);

			foreach ($queries as $field => $query):
				if (is_string($query)) {
					if(in_array($field, $mustEquals)){
						$q->where($field, '=', $query);
					}else{
						$q->where($field, 'LIKE', "%{$query}%");
					}
				} else if(is_bool($query)){
					$q->where($field, $query);
				}else {
					$start = Carbon::createFromFormat('Y-m-d H:i:s', $query -> start)->startOfDay();
					$end = Carbon::createFromFormat('Y-m-d H:i:s', $query -> end)->endOfDay();

					$q->whereBetween($field, [$start, $end]);
				}
			endforeach;
		});
	}

	protected function filter($data, $query, $fields, $mustEquals)
	{
		return $data->where(function ($q) use ($query, $fields, $mustEquals) {
			foreach ($fields as $index => $field):
				$method = $index ? 'orWhere' : 'where';

				if(in_array($field, $mustEquals)){
					$q->{$method}($field, '=', $query);
				}else{
					$q->{$method}($field, 'LIKE', "%{$query}%");
				}

			endforeach;
		});
	}

```

I will be thankful for any improvements.
