### ISSUE TITLE
how to use `bus` when only use precompiled version

### ISSUE THREAD

**Issue by popozhu** [matfish2/vue-tables-2#46]
- Vue.js version: 2.x
- consumed using: only include the precompiled version `dist/vue-tables.min.js` using `<script>` tag , 
- FULL error message (including stack trace):
- relevant code: `var bus = require('vue-tables-2/lib/bus');`
- steps for reproducing the issue:

Hi, I'm here asking for some help or tips...

First of all, I don't use vuex, and only use `dist/vue-tables.min.js` with a `<script>` tag.

when I use the events in vue-tables-2, such as custom filters, I have no idea how to connect to the `bus` in the vue-tables-2 via `$refs` , just like your way: 
```
var bus = require('vue-tables-2/lib/bus');
```

Thanks for your time~

**Comment by matfish2** [comment]
I was quite reluctant to add a precompiled version to begin with, and as you can see it is not even documented. 
 I need to figure out how to export the event bus in the precompiled version.
If you are using a module bundler I don't see any reason to use the precompiled file.
