### ISSUE TITLE
Unable to use a custom requestFunction on a ServerTable 

### ISSUE THREAD

**Issue by sergiocastrovale** [matfish2/vue-tables-2#460]
Hi, first of all thanks a lot for this package, it's awesome.

I need to migrate a previously ClientTable into a ServerTable and I'm having trouble understanding how to use a custom request function with my data.

This was how I was getting all the data before:

```
fetchInvoices () {
      // Calls mydomain.com/api/invoices (GET)
      return api.invoices({
        success: response => {
          this.total = response.pagination.total // pagination holds next, prev, total etc.
          this.tableData = response.data.result // My result set
        },
        fail: error => {
          console.log(this.errorAPI(error, 'errors'))
        }
      })
    }
```

the `api` holds all the needed axios methods, and this works fine; all the invoices were added to `this.tableData`.

However, I don't see how to incorporate this into `requestFunction(data)`. My idea was to try and just pass along the method, but this obviously doesn't work:

```
      requestFunction: (data) => {
        return this.fetchInvoices()
      },
      responseAdapter: (response) => {
        return { data: response.results, count: response.pagination.total }
      }
```

Also, I don't understand the purpose of a (mandatory) url prop when we're customizing the way our request is handled in `requestFunction()`.

Any help would be appreciated.

**Comment by matfish2** [comment]
The request function should just return the promise, **without the success handler**. When the request is successful, a `then` or `done` method is called, at which point the plugin takes over and parses the response.

The `url` prop was created long before this plugin had a custom request function. I think it makes sense to keep it mandatory, as in most cases, even when using a custom request function, it will still be used (e.g: `myFancyAjaxLibrary.get(this.url)`. In the minority of cases where it isn't, it still serves as good documentation to tell other developers what is the endpoint of this table :)

**Comment by sergiocastrovale** [comment]
I see - too bad we can't customize the endpoint entirely instead of just customizing what the promise will be. In the end, because of this, we're probably going to have to ditch the package on this project as we can't really change the way these responses are built now.

As for the url parameter, I think we'd be better of just making it optional - having an irrelevant and not used parameter just adds redundancy and confusion when we are building custom handlers. Unless we keep the parameter to actually define the route we're going to call on our custom handler itself, but then it's not custom anymore :-)

**Comment by matfish2** [comment]
You CAN customize the entire endpoint. `requestFunction` allows you to use your own ajax package, and set your own headers. You can use `requestAdapter` to mould your request to the format expected by the server, and `responseAdapter` to mould the response to the format expected by the package. Is there anything else not covered by the abovementioned?

As for the `url` prop, making it optional for an edge case like yours, seems problematic as I still have to enforce this parameter for the majority of use cases. I will see if I can implement some conditional require.

**Comment by sergiocastrovale** [comment]
Our current API structure is centralized in an `api.js` file that, given a route, deals with the whole axios request. So, we're not doing the usual

```
       axios.get(url, {
            params: data
        }).catch(function (e) {
            this.dispatch('error', e);
        }
```

but this instead (all api calls return a success/fail):

```
api.invoices({
    success: response => {
    },
    fail: e => {
    }
})   
```

It's a pretty big app and we're currently in no position to change this workflow, and creating "manual" axios.get calls just so that we could return just the promise itself would make things less ... organized. I'm not seeing any way to make it work with the package (and that's obviously not the package's fault) - do you have any ideas?

**Comment by gtarsia** [comment]
@matfish2 I don't think it's an edge case at all. 
I have a component that reuses this table. Sometimes source url changes and I also do some "post processing" on this using other external data. I could go around changing `url` and then create a `responseAdapter` to do this "post processing", but I would very much rather have the entire logic in my component including all the differents `url` instead of having them set in the html accross different views. 
That just makes things hard to track.

The most sensible thing IMHO would be to either use `url` or `requestFunction` and erroring if both are defined.
