### ISSUE TITLE
how to pass nested array inside the vue table 2

### ISSUE THREAD

**Issue by jayanthanantharapu** [matfish2/vue-tables-2#461]
- Vue.js version: 2
- input: `{
	"id": "0001",
	"type": "donut",
	"name": "Cake",
	"ppu": 0.55,
	"batters":
		{
			"batter":
				[
					{ "id": "1001", "need": "Regular" },
					{ "id": "1002", "need": "Chocolate" },
					{ "id": "1003", "need": "Blueberry" },
					{ "id": "1004", "need": "Devil's Food" }
				]
		},
	"topping":
		[
			{ "id": "5001", "type": "None" },
			{ "id": "5002", "type": "Glazed" },
			{ "id": "5005", "type": "Sugar" },
			{ "id": "5007", "type": "Powdered Sugar" },
			{ "id": "5006", "type": "Chocolate with Sprinkles" },
			{ "id": "5003", "type": "Chocolate" },
			{ "id": "5004", "type": "Maple" }
		]
}`
- output: `['type', 'name', 'batter_type', 'topping_type']`

**Comment by matfish2** [comment]
Use the `templates` option:

```js
templates:{
   myColumn(h, row) {
         // "massage" your data and return a string
}
}
```
