### ISSUE TITLE
getOpenChildRows() doesn't work with child_row scoped slot

### ISSUE THREAD

**Issue by skazi0** [matfish2/vue-tables-2#464]
- Vue.js version: 1.3.41
- consumed using: webpack
- FULL error message (including stack trace):
`[Vue warn]: Error in render: "Error: vue-tables-2: Child row undefined or not a component"`
- relevant code:

```
<template>
    <v-client-table ref="table" v-bind:data="data" v-bind:columns="columns" v-bind:options="options">
      <template slot="child_row" slot-scope="props">
        child stuff
      </template>
      <template slot="name" slot-scope="props">
        <button v-on:click.stop="toggleChildRow(props.row)">{{isChildRowOpen(props.row)}}</button>
        {{ props.row.name }}
      </template>
    </v-client-table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      columns: ['name'],
      options: {
      },
      data: [{id: 1, name: 'c1'}, {id: 2, name: 'c2'}],
    };
  },
  methods: {
    isChildRowOpen(row) {
      // assume child closed before ref is defined
      if (!this.$refs.table)
        return false;
      return this.$refs.table.getOpenChildRows().includes(row.id);
    },
    toggleChildRow(row) {
      this.$refs.table.toggleChildRow(row.id);
    },
  },
}

</script>

<style lang="scss">
</style>
```
- steps for reproducing the issue:
click the buttons

**Comment by skazi0** [comment]
My current workaround is to use `return this.$refs.table.openChildRows.includes(row.id);` directly but this is not a documented property so would be good to fix `getOpenChildRows()`.

**Comment by matfish2** [comment]
This is intended behaviour. Get open child rows, is returning the child row **components**, not just the ids. This can't be done unless the child row is, well, a component. 
I will add the `openChildRows` data property to the documentation.

**Comment by skazi0** [comment]
@matfish2 thanks for the doc updates!
