### ISSUE TITLE
Setting daterangepicker - range by external button

### ISSUE THREAD

**Issue by 1stkeks** [matfish2/vue-tables-2#466]
I am using the vue-tables-2 with multiple daterangepickers.

My goal is to set the daterange by clicking on a button that is not inside of the daterangepicker-dropdown.

How would I achieve that? There are methods to set the start/end -date of the daterangepicker, but i'd have to call it by its 'id'. Sadly there is no id set for the daterangepickers inside of the vue-table. Is there a way to set the id or maybe to set the daterange directly?
Would the table refresh itself if I'd change the start/end -date?

Thanks for the help!

**Comment by matfish2** [comment]
Use the `setFilter` method
