### ISSUE TITLE
v-server-table, requestFunction, duplicate requests from the URL parameter

### ISSUE THREAD

**Issue by ssurkovs** [matfish2/vue-tables-2#467]
- Vue.js version: 2.5.13
- consumed using: webpack

Hello.

My code:
`<v-server-table :columns="columns" :options="options" url="/fake/url/for/URL/param">
        </v-server-table>`

and 

`...`
`data () {`
`    return {`
`      columns: ['mac', 'int_hostnames', 'int_ips', 'users', 'last_activity', 'vendor'],`
`      options: {`
`        requestFunction: this.$http.post('https://localhost/api/v1.0/hosts', {}),`
`        responseAdapter: (response) => {`
`          console.log(response)`
`          return { data: response.data, count: response.data.length }`
`        },`
`        data: [],`
`        query: {},`
`        limit: 25,`
`        page: 1,`
`        orderBy: 'last_activity',`
`        ascending: 'asc',`
`        byColumn: ''`
`      }`
`    }`
`  }`
`...`

Google Chome show me this:

`vue-resource.esm.js?f3ef:1085 GET http://localhost:8080/null?query=&limit=10&ascending=1&page=1&byColumn=0 404 (Not Found)`
`undefined`

I use parameter "requestFunction" and expect to send one POST-request to the server.

But "URL" is a required parameter, and when I specify it, i see that 2 requests (GET then my POST) are sent to the server, and vue-tables-2 use query result from the URL parameter (GET).
the result of a query from POST ignoring.

Tell me please what I'm doing wrong.

**Comment by gtarsia** [comment]
I think this is related to https://github.com/matfish2/vue-tables-2/issues/460  
@matfish2 can clarify, but I guess there's no way to turn off `url` and just use `requestFunction`.

**Comment by matfish2** [comment]
The request function should be **defined**, NOT called.
So instead of:

```js
requestFunction: this.$http.post('https://localhost/api/v1.0/hosts', {}),
```

Try

```js
requestFunction() {
    return this.$http.post('https://localhost/api/v1.0/hosts', {})
}
```

**Comment by ssurkovs** [comment]
Thank you, it works!
However, your documentation says otherwise...

**Comment by matfish2** [comment]
Where does it say otherwise?

**Comment by ssurkovs** [comment]
![2018-04-28 19 48 04](https://user-images.githubusercontent.com/33671134/39398871-3bb8bcb6-4b1d-11e8-8766-498b826221a2.png)

**Comment by matfish2** [comment]
Yes. I know where the docs are. But how do you see it says otherwise? It's not calling axios directly, but defining a function that will call it when triggered.

**Comment by ssurkovs** [comment]
Oh, ok.
