### ISSUE TITLE
refresh doesnt exist

### ISSUE THREAD

**Issue by kevindesousa** [matfish2/vue-tables-2#468]
- Vue.js version: v2.5.15 
- consumed using: webpack
- FULL error message (including stack trace):
Uncaught TypeError: this.$refs.table.refresh is not a function

- relevant code:
![image](https://user-images.githubusercontent.com/4758092/37534059-f9778daa-2943-11e8-8390-79da37a7581f.png)
![image](https://user-images.githubusercontent.com/4758092/37534079-0b0f0fb6-2944-11e8-8968-ed4a1243575b.png)

**Comment by matfish2** [comment]
I am unfamiliar with the syntax you are using. what does `v-client-table.event-list` translate to?

**Comment by kevindesousa** [comment]
its `pug` => [https://pugjs.org/api/getting-started.html](url)

it's the same like :
```html
<v-client-table class="event-list" ref="table" :columns="columns" :data="events" :options="options">
    <span slot="name" slot-scope="props">
           {{ props.row.name[lang] }}
    </span>
</v-client-table>
```

**Comment by matfish2** [comment]
Oh, I need to see the full code. Where are you calling `this.$refs`. Is it a direct parent of the table?

**Comment by kevindesousa** [comment]
![carbon](https://user-images.githubusercontent.com/4758092/37545785-84333ad6-296a-11e8-8669-0476a3c6c168.png)

**Comment by matfish2** [comment]
You are using the client table. The `refresh` function is for the server table only.

**Comment by kevindesousa** [comment]
Ah, sorry, thank's.

But my real problem is the data on the table  is not updated.. (the data is on a store, you can see on my last screenshots)

**Comment by matfish2** [comment]
Have a look [here](#407)

**Comment by goarun112** [comment]
`this.$refs.vuetable.refresh()` is not working for me I'm using graphql endpoint to the data table.how to `reload()` or `refresh()` the data table

**Comment by Imboga** [comment]
Same issue here. I'm using the beta branch and methods are not working:
`this.$refs.table.refresh is not a function`
`this.$refs.table.getData is not a function`

by using 
```
this.$refs.table.refresh()
this.$refs.table.getData()
```

**Comment by goarun11** [comment]
Hi, @Imboga if you use graphql,
```javascript
 export const apolloClient = new ApolloClient({
  link: authLink.concat(httpLink), 
  defaultOptions: {
    query: {
      fetchPolicy: "network-only"
    }
  }
});
```
try changing fetch policy to network-only

**Comment by goarun112** [comment]
Hi, @Imboga if you use graphql,
```javascript
 export const apolloClient = new ApolloClient({
  link: authLink.concat(httpLink), 
  defaultOptions: {
    query: {
      fetchPolicy: "network-only"
    }
  }
});
```
try changing fetch policy to network-only
