### ISSUE TITLE
first/last page buttons on pagination are disabled

### ISSUE THREAD

**Issue by wysoki89** [matfish2/vue-tables-2#469]
- Vue.js version: 2.5.2
- consumed using: webpack
- FULL error message: no error message
- steps for reproducing the issue: just try to click on first or last page element in pagination. The behaviour is present on https://jsfiddle.net/matfish2/jfa5t4sm/

**Comment by matfish2** [comment]
Those are NOT first and last page buttons. They are chunk paginators. They should be disabled when there are no more chunks to paginate to. First and last button can also be added. See the options table
