### ISSUE TITLE
Styling filter text fields?

### ISSUE THREAD

**Issue by hjoensson** [matfish2/vue-tables-2#470]
Thanks for an amazing table component!

Is there any good way to style the filter input fields?
![image](https://user-images.githubusercontent.com/810193/37564732-2ceb2260-2a9c-11e8-9d46-804ed9a9fbf8.png)

Regards
Henrik

**Comment by matfish2** [comment]
I don't understand the question. Please elaborate.

**Comment by hjoensson** [comment]
I'm sorry if I was unclear. 

I would like to style the "Filter by Name" text and the size of the input field with CSS.

**Comment by matfish2** [comment]
Duplicate of #471
