### ISSUE TITLE
Styling td with CSS?

### ISSUE THREAD

**Issue by hjoensson** [matfish2/vue-tables-2#471]
Is there a way to style the generated td elements with CSS?
I want to right align number columns to make them easier to read.

Like this:
![image](https://user-images.githubusercontent.com/810193/37585517-b18417bc-2b59-11e8-99ef-f21a105271ad.png)

**Comment by hjoensson** [comment]
A workaround to this is something like this:
```
#cost-table td:nth-child(6), #cost-table td:nth-child(7) {
        text-align: right;
}
```

**Comment by matfish2** [comment]
If you mean that you don't want to use pseudo-selectors, you can apply columns classes using the `columnClasses` option
