### ISSUE TITLE
Change row style

### ISSUE THREAD

**Issue by BPLarissa** [matfish2/vue-tables-2#474]
Is there any way of change row background color?

**Comment by matfish2** [comment]
Yes. Check out the `rowClassCallback` option

**Comment by BPLarissa** [comment]
should I do something like this: 
rowClassCallback: function (row) {
         return test
        }

then...
<style>
.test {
background-color: blue;
</style>

because I have already done this and it doesn't work

Thanks a lot for your reply

**Comment by matfish2** [comment]
A. `test` should be a string.
B. You should probably use `important!` to override bootstrap's background.
C. `Doesn't work` is not very helpful. Did you get an error? Was the class applied? Please be more specific.

**Comment by BPLarissa** [comment]
I have already removed 'scoped' from <style scoped> and then it worked! Thanks a lot for your attention!!!! (;

**Comment by matfish2** [comment]
Was just going to write that :)
