### ISSUE TITLE
How asign style to table heading?

### ISSUE THREAD

**Issue by riux** [matfish2/vue-tables-2#475]
I want to assign stylos css only to the header of the table; I've tried with columnsClasses: {}; but he assigns the silly stylo to the th and tr;

**Comment by matfish2** [comment]
Please elaborate. The question is unclear.

**Comment by riux** [comment]
I want to assign stylos css only to the header of the table; I've tried with columnsClasses: {}; but he assigns the silly stylo to the th and tr;

**Comment by matfish2** [comment]
```css
thead .myClass {
  // my styles
}
```
