### ISSUE TITLE
Can I render html source without using jsx?

### ISSUE THREAD

**Issue by minyoungk** [matfish2/vue-tables-2#480]
I have this source.

```
options: {
                templates: {
                    img_src: function (h, row, index) {
                        return '<img src="smiley.gif" alt="Smiley face" height="42" width="42">';
                    }
                }
            }
```

But table shows html string.
How can I return html source?

**Comment by matfish2** [comment]
Yes. Read the documents under `Templates`

**Comment by eleftrik** [comment]
@matfish2 Is there any example? I can't make it work.
I'm using v-server-table component.
Thank you

**Comment by matfish2** [comment]
What did you try? You have 3 options:

1. scoped slots
2. render function (possibly using jsx)
3. vue component (.vue file with a `data` prop)

**Comment by eleftrik** [comment]
I would like to use scoped slots, but I couldn't make it work.
I need to show a column with buttons like 'Edit', 'Delete' and so on

**Comment by matfish2** [comment]
Please paste your code

Sent from Mail for Windows 10

**Comment by eleftrik** [comment]
Another question: can I use scoped slots or vue component with `v-server-table`?

**Comment by AngryElephant** [comment]
Why the issues are closed before get resolved ?
