### ISSUE TITLE
Invalid argument supplied for foreach() - EloquentVueTables.php

### ISSUE THREAD

**Issue by WitekS** [matfish2/vue-tables-2#482]
- Vue.js version: 2.5.16
- consumed using: webpack
the error appears when using EloquentVueTables. I guess the syntax for PHP is incorrect
`if (..)):
      ...
endif;`
[http://php.net/manual/en/control-structures.if.php](url)
and
`foreach (...):
...
endforeach;`
[http://php.net/manual/en/control-structures.foreach.php](url)

**Comment by matfish2** [comment]
The syntax is fine. Without a line number I can only guess that the problem lies with the `$query` variable being received as a string, rather than an array. This should be an easy fix. Add the following after line 15:

```php
$query = is_array($query)?$query:json_decode($query);
```

**Comment by WitekS** [comment]
the error is in line 42 and points to the syntax so I thought it was this.
This is the full message:
`{message: "Invalid argument supplied for foreach ()", exception: "ErrorException", ...}
exception: "ErrorException"
file: "C: \ Users \ switches \ Documents \ WebDev \ l5app \ app \ VueTables.php"
line:42
message:
"Invalid argument supplied for foreach ()"`
and such a request:
`Request URL: http: // l5app / get-connectors? Query =% 7B% 7D & limit = 10 & ascending = 1 & page = 1 & byColumn = 1`

after adding this line as you wrote everything is ok
thank you
