### ISSUE TITLE
Accesing current column in Templates

### ISSUE THREAD

**Issue by rico** [matfish2/vue-tables-2#483]
Hi, maybe I'm missing something in the docs. But is it possible to access the current column name in a template.

Basically something like this:

    export default Vue.extend({
        props: ['data', 'index'],
        template: `<span>{{ formatted }}</span>`,
        computed: {
            formatted () {

                let column = ??? // How do I get the column?

                return DateTime.format(this.data[column])
            }
        }
    });

**Comment by matfish2** [comment]
The current column is already accessible when using scoped slots (`props.column`). Per your request, i've addded a `column` prop to templates using vue components/files.

**Comment by rico** [comment]
Awesome - thank you very much!
