### ISSUE TITLE
filterByColumn input looses focus

### ISSUE THREAD

**Issue by freeman-g** [matfish2/vue-tables-2#484]
- Vue.js version: 2.5.16
- consumed using: webpack
- steps for reproducing the issue:

This jsfiddle reproduces the issue:

https://jsfiddle.net/ddxrpy8w/

- Go to the Country column and type z in the column filter
- Pause for a second for the filter to complete
- The cursor is no longer focused in the filter column for Country

It looks like this might have something to do with pagination. I noticed that when the filter causes pagination to go away, e.g., less rows than 10, then the filter input looses focus.

I haven't found the issue yet in the source code though.

Thanks

![image](https://user-images.githubusercontent.com/495886/38105344-c6f7bf10-3359-11e8-840d-42b6494a8782.png)

**Comment by molerat619** [comment]
I can confirm that observation. In the beginning it seemed to work on my setup, but not on my colleague's. Now I tested it again (paying more attention to @freeman-g 's assumption) and I could observe the same behavior on my setup as well.

**Comment by molerat619** [comment]
I have opened this issue a few days ago and it also seems to be related to the same problem. https://github.com/matfish2/vue-tables-2/issues/481

**Comment by matfish2** [comment]
It seems like solving #496 fixed this too.

**Comment by freeman-g** [comment]
@matfish2 - yes, that commit fixed this issue too, thanks for this great component!
