### ISSUE TITLE
bootstrap3 theme not being applied

### ISSUE THREAD

**Issue by DrCol** [matfish2/vue-tables-2#485]
I am using Vue2 with `webpack` to make a grid, but the bootstrap3 theme is not being applied to my grid.

    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vue-tables-2": "^1.4.0"

There are no error messages.

`index.js`:

    import {ServerTable} from 'vue-tables-2'
    import UserGrid from '@/components/UserGrid'
    
    Vue.use(ServerTable, {}, false, 'bootstrap3', 'default')
    Vue.use(Router)

    export default new Router({
      mode: 'history',
      routes: [
        {
          path: '/login',
          name: 'Login',
          component: Login
        },
        {
          path: '/user',
          name: 'UserGrid',
          component: UserGrid
        }
      ]
    })
    ...

UserGrid component under `@/components/UserGrid`

    <template>
     <div id="user-grid">
      <v-server-table url="/listing" :columns="columns" :options="options"></v-server-table>
    </div>
    </template>
    
    <script>
    
    import axios from 'axios'
    
    export default {
      name: 'UserGrid',
      data () {
        return {
    ...
    </script>

The core grid displays and my data loads and I have pagination working, but for some reason the bootstrap3 theme isn't there?

I can change `boostrap3` to something arbitrary and it breaks the app, so I know it's finding the theme.

What am I missing?

**Comment by hjoensson** [comment]
DrCol: can you describe what you did to solve this?

/Henrik

**Comment by akhchan99** [comment]
Not sure if this is related, when I upgrade this library from 0.6 to 1.4, all my styling was gone too...then I realized that I have "skin" in my options, which override all the table theme, and "table" isn't listed...then I manually added "table" into "skin" as well, and all the styling is back.
