### ISSUE TITLE
Click per Row and passing data row to function in vue tables-2 ?

### ISSUE THREAD

**Issue by fathan** [matfish2/vue-tables-2#488]
- Vue.js version: 2.5 >
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace): 
- relevant code: 
- steps for reproducing the issue:

hai, I want to mark per row. so, when I click row it leads to a function by sending parameters from the selected row. How to?

**Comment by matfish2** [comment]
Have a look at the `row-click` event
