### ISSUE TITLE
Vuex + preserveState causes duplicate requests when routing 

### ISSUE THREAD

**Issue by basit74** [matfish2/vue-tables-2#491]
I have a product list page, where I am using the vue-table2.

If I navigate through the site, from list to Detail page, to Cart and come back to list page ...

every time the ajax requests will be doubbled. I think that every time the list page is called, the vue-table2 events are initilized again.

Is there any solution fo that?

**Comment by mediaessenz** [comment]
I can confirm this problem.
I use vuex and vue-route. The first time I go to the route with the server-table-component, everything works perfect. After switching to another route and back to the route with the server-table, every ajax call is send twice.
Here are my options:
```
preserveState: true,
saveState: true,
perPageValues: [10, 20, 30],
sortable: ['name', 'years', 'extensions'],
orderBy: {
	column: 'name'
},
pagination: {
	nav: 'scroll'
},
```

**Comment by mediaessenz** [comment]
The problem still exists in version 1.4.32

**Comment by matfish2** [comment]
I am unable to reproduce with the exact relevant settings (`preserveState:true`, `saveState:true`). Just to make sure you are not using some cached version, please check if you have the following code on `created.js:24`:

```js  
if (!self.$store.hasModule(self.name)) {
    self.$store.registerModule(self.name, store);
  }
```

If you do, please also check you have it in your compiled bundle.

**Comment by matfish2** [comment]
I've removed a duplicate `loaded` event in vuex that may cause the problem. Please pull the most recent version and try again.

**Comment by mediaessenz** [comment]
I updated to the latest version (1.4.43) and do not found the file `node_modules/vue-tables-2/compiled/created.js`.
The new compiled version is still not working, but the problems are different from before.
Now (after switching my route and back again), the records per page switch is not working anymore and I also can only switch between page 1 und 2 of a set of 4 pages.

**Comment by matfish2** [comment]
It appears the original problem was fixed, but there is another issue with vuex' state losing reactivity once the component is destroyed. I need to explore this further.

**Comment by matfish2** [comment]
It turns out that even though the component is destroyed, the `getData` method keeps referencing the old instance.

**Comment by mediaessenz** [comment]
After updating to version 1.4.44 of this component, the server table with activated vuex stops working complety.
In the console I get the errors "TypeError: e.allColumns is undefined" and "TypeError: t.$refs.pagination is undefined"

**Comment by matfish2** [comment]
Can't confirm. Mine works as expected. Odd...
