### ISSUE TITLE
feature request: access filtered and/or sorted rows

### ISSUE THREAD

**Issue by abiturma** [matfish2/vue-tables-2#492]
This is a feature request: 

For some use cases, e.g. table footer with sums (per page/per filtered results/total). It would be useful if there was a "clean" way to access the filtered and sorted data in the client table.

Right now I use an event listener on `filter` and pass the table data to `$refs.table.search()` which doesn't seem to be a clean way.  Is there a better and more conceptual way? 

Thanks for your work - it makes vue integration of dynamic tables so much easier (used to use jQuery DataTables before). I totally appreciate it.

**Comment by matfish2** [comment]
> You can access the filtered dataset at any given moment by fetching the filteredData computed property of the table, using ref as a pointer (this.$refs.myTable.filteredData);

**Comment by abiturma** [comment]
Thank you very much for your quick reply. I have seen that, but its not exactly what I looked for. The filteredData property also applies the pagination. I would like to have the data where the filter is applied but the pagination is not yet applied. My use case is a big table and I want to add along a column and display it as:  

sum total: xxx, sum with filter applied: yyy, sum of displayed page: zzz,

**Comment by matfish2** [comment]
I see it was already asked for in #195.
I will strive to add it in the near future.

**Comment by abiturma** [comment]
Ah I see - thank you very much!

Best regards
Aaron
-- 
Dr. Aaron Kunert
abiturma GbR
0179 6140921
www.abiturma.de
aaron.kunert@abiturma.de


Matanya schrieb:

**Comment by matfish2** [comment]
I have added an `allFilteredData` data property
