### ISSUE TITLE
Collapse rows groups

### ISSUE THREAD

**Issue by BPLarissa** [matfish2/vue-tables-2#495]
Is it possible add a collapse property to the groupBy column? I mean, Is it possible collapse the rows group?
There is an example here: https://vladzen.github.io/vue-tables-2-rows-grouping/

**Comment by matfish2** [comment]
Please check out my initial implementation (add `collapseGroups:true` to the `options`). This seems like a feature that can have many options. Let me know you thoughts.

**Comment by BPLarissa** [comment]
Ok!!!! Thank you very much 😄

**Comment by rugged-service** [comment]
This is awesome, can you allow the initial load to show the arrows, and be expanded by default?

**Comment by matfish2** [comment]
I have implemented the request, and consqeuently changed the option name from `collapseGroups` to `toggleGroups`. Please check again.

**Comment by BPLarissa** [comment]
It's wonderful!! Thank you very much (;

**Comment by arjayisidro** [comment]
Hi, how can i change the label for groupBy? thanks
