### ISSUE TITLE
event listener missing on daterangepicker show span/div after empty server response

### ISSUE THREAD

**Issue by dcabanaw** [matfish2/vue-tables-2#496]
- Vue.js version: v2.5.16
- consumed using: webpack (laravel elixir)
- FULL error message (including stack trace): none
- relevant code:

```
<template>
    <v-server-table url="/api/logs" :columns="columns" :options="options">
        <a slot="user" slot-scope="props" :href="'/users/' + props.row.user.id">{{ props.row.user.name }}</a>
        <div slot="child_row" slot-scope="props">
            Testing...
        </div>
    </v-server-table>
</template>

<script>
    import Vue from 'vue';
    import {ServerTable} from 'vue-tables-2';
    Vue.use(ServerTable);
    
    export default {
        data() {
            return {
                columns: ['created_at', 'user', 'message'],
                options: {
                    perPage: 5,
                    perPageValues: [5, 10, 15, 25],
                    skin: "table table-striped table-hover table-condensed",
                    headings: {
                        created_at: 'CreatedAt',
                        user: 'User',
                        message: 'Message'
                    },
                    sortable: ['created_at', 'user'],
                    filterable: true,
                    filterByColumn: true,
                    columnsClasses: {
                        'created_at': 'text-left',
                        'user': 'text-left',
                        'message': 'text-left',
                    },
                    dateFormat: 'YYYY-MM-DD HH:mm:ss',
                    dateColumns: ['created_at'],
                    datepickerOptions: {
                        timePicker: true,
                        timePicker24Hour: true,
                        timePickerIncrement: 5,
                        locale: {
                            format: 'YYYY-MM-DD HH:mm:ss'
                        },
                    },
                    debounce: 750,
                    requestKeys: {
                        query: 'query',
                        limit: 'per_page',
                        orderBy: 'orderBy',
                        ascending: 'ascending',
                        page: 'page',
                        byColumn: 'byColumn'
                    },
                    responseAdapter(resp) {
                        return {
                            data: resp.data.data,
                            count: resp.data.meta.pagination.total
                        }
                    }
                }
            }
        }
    }
</script>
```
- steps for reproducing the issue:
1) Load page with default result set from server
2) Click the span/div to activate daterangepicker for created_at filter
3) Select date range that will return empty data (ie {data: []})
4) After response, the span/div to activate daterangepicker no longer works  (event listener is missing).  Also the date ranges that were selected no longer show and instead shows the default text (ie Filter By...), but the query data is still present when inspected with Vue devtools.

**Comment by dcabanaw** [comment]
After toying with this a bit more, it seems this oddity happens when perPage and perPageValues are set to something other than their default values.

**Comment by dcabanaw** [comment]
Okay so it seems it's not only an empty response, but any result set that has less than the perPage value (default or otherwise) that causes this problem.

**Comment by matfish2** [comment]
I have tracked down the problem to a change in the `count` data property in the `set-data.js` method. It seems it somehow causes a complete recompilation of the table header, which in turn leads to the daterangepicker being destroyed. If you have any other clues that can assist me you are welcome to share them.

**Comment by dcabanaw** [comment]
So after some tinkering around with some modules in the compiled directory, I discovered some odd interaction with the perPage dropdown.  If I modify per-page-values.js to always return true instead of !isLastEntry the the issue goes away

per-page-values.js:

```javascript
"use strict";

module.exports = function (h) {
  var _this = this;

  var perpageValues = [];

  this.opts.perPageValues.every(function (value) {
    var isLastEntry = value >= _this.count;
    var selected = _this.limit == value || isLastEntry && _this.limit > value;
    perpageValues.push(h(
      "option",
      {
        domProps: {
          "value": value,
          "selected": selected
        }
      },
      [value]
    ));
    //return !isLastEntry;
    return true; // "workaround fix"
  });

  return perpageValues;
};
```

This results in the perPage dropdown always being visible though. (which I kinda of prefer to be honest as it showing and not showing moves the table up and down a lot visually).  So somehow when the perPage dropdown is changed all the other table headers get re-rendered?

**Comment by matfish2** [comment]
Great debugging work! I am still not sure why, but it appears that conditionally rendering the table top (the row above the table itself) caused this bug. I have replaced the logic with the softer v-show and it seems to work fine now.
