### ISSUE TITLE
How do I Filter Element texts/labels

### ISSUE THREAD

**Issue by singiankay** [matfish2/vue-tables-2#498]
If I have this slot, how can I filter the text inside the span element?

```
<template slot="so_no" scope="props">
	<span class="badge bg-aqua" v-if="props.row.line_id == client.table.id">
		{{ props.row.so_no }}
	</span>
	<template v-else>
		{{ props.row.so_no }}
	</template>
</template>
```

**Comment by matfish2** [comment]
If "so_no" is an actual column in your dataset and it is defined as filterable (which is the default), then the text filter will filter it.

**Comment by singiankay** [comment]
Sorry, I copy pasted the wrong template. Here is the correct one:

```
<template slot="so_number" scope="props">
	<strong>
		<a @click="setUpdateID(props.row)" v-if="props.row.so_number || props.row.so_number === 0">{{ props.row.so_number }}</a>
		<a @click="setUpdateID(props.row)" v-else>n/a</a>
	</strong>
</template>
```

I tried the filterable in my options object

```
sortable: ['so_number', 'so_date', 'customer_req_delivery_date', 'confirmation_date', 'remarks', 'document_status', 'shipment_status'],
filterable: ['so_number', 'so_date', 'customer_req_delivery_date', 'confirmation_date', 'remarks', 'document_status', 'shipment_status'],
```

remarks, document_status, and shipment status can be filtered. I'm guessing the dates cannot be since they are date objects.
And then this so_number which doesn't work either on filters. Sorting works but it doesn't really sort properly.

**Comment by matfish2** [comment]
I suppose you are using the client table. 
Date fields should be filtered using daterangepicker. See the `dateColumns` option
What exactly doesn't work with "so_number"? Does it not filter at all? Note that the filtering always refers to the **original** data, NOT the template, which is merely presentational. E.g, if you look for "n/a" the filter will NOT return it, even though it is presented in the table.

**Comment by singiankay** [comment]
OMG I'm so bad. Sorry, I forgot that the one I was editing was a server-table. My bad
