### ISSUE TITLE
pagination.edge option is not working

### ISSUE THREAD

**Issue by Sreng-S** [matfish2/vue-tables-2#499]
- Vue.js version:  "^2.5.13"
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace): no errors
- relevant code: 

`import { ServerTable, Event } from "vue-tables-2";`
`Vue.use(ServerTable, {
  sortIcon: {
    base: "fa",
    up: "fa-chevron-up",
    down: "fa-chevron-down",
    is: "fa-sort"
  },
  options: {
    pagination: {
      edge: true,
      chunk:5,
      dropdown:false,
      nav: 'fixed'
    },
  }
});`
- steps for reproducing the issue:

**Comment by matfish2** [comment]
The `options` property is redundant. 
```js
Vue.use(ServerTable, { 
  sortIcon: { 
    base: "fa", 
    up: "fa-chevron-up", 
    down: "fa-chevron-down", 
     is: "fa-sort" },
  pagination: { 
    edge: true, 
    chunk:5, 
    nav: 'fixed' 
  } 
});
```

**Comment by Sreng-S** [comment]
Thanks for your reply. I tried with your comment, I will follow my options, 
```Vue.use(ServerTable, {
  sortIcon: {
    base: "fa",
    up: "fa-chevron-up",
    down: "fa-chevron-down",
    is: "fa-sort"
  },
  perPage: 7,
  // footerHeadings: true,
  highlightMatches: true,
  pagination: {
    chunk: 5,
    edge: true,
    //set dropdown to true to get dropdown instead of pagenation
    dropdown: false
  }
});```

**Comment by matfish2** [comment]
First and Last links are only shown when there is more than one chunk.

**Comment by Sreng-S** [comment]
So there are 2 chunks, I can see. I already read can remove with `edge` option from API doc.
But It's not working on `vue-server-table` now.
