### ISSUE TITLE
Is there a way to set the state (loading, loaded) of the table from outside

### ISSUE THREAD

**Issue by gtarsia** [matfish2/vue-tables-2#501]
I'm using `v-client-table` and getting data remotely on my own.  
The problem is that I don't know how to signal the table that the data is loading (since the loading message doesn't show in the client table), so the first thing that shows up when the table is loading is either "No matching records" (if `:data` was initialized with an empty array) or no table at all with a couple of errors launched (if `:data` was initialized with null/undefined]

I'm aware that If I use `v-server-table` that would make me the message show up. The reason I'm using the client instead, is because I still want to let the sorting and filtering done client side.   

Any idea on how to approach this? 
I imagine something like `this.$children.state = 'loading'` would do the trick, but I'm open to other suggestions.

The API's great btw.

**Comment by matfish2** [comment]
From the docs:

> Important: when loading data asynchronously add a v-if conditional to the component along with some loaded flag, so it will only compile once the data is attached.

Does this help?
