### ISSUE TITLE
Reactivity problem operating table

### ISSUE THREAD

**Issue by kapsoft** [matfish2/vue-tables-2#502]
- Vue.js version: 2

- relevant code:
https://jsfiddle.net/kapsoft/wn2vj3bh/18/

In fiddle example I have a "quantity" number control and a "total" method(that returns quantity*2). 

Changing quantity is not changing total. What am I doing wrong?

Thanks in advance. 

Dean

**Comment by matfish2** [comment]
The data presented is not the original set but rather a computed property (filteredData). Therefore you cannot change the value directly from the template. You can update the original set using an event, sending the (non-zero) index of the row through:
https://jsfiddle.net/whdLsvch/

**Comment by kapsoft** [comment]
Appreciate it! Thanks.

Dean

**Comment by Milkker** [comment]
Thanks for the solution, I met the problem too.
I combine two sample to show how to deal with it, hope it is helpful.
http://jsfiddle.net/qzmvw1dj/
