### ISSUE TITLE
Question: SetFilter (exact match)

### ISSUE THREAD

**Issue by akhchan99** [matfish2/vue-tables-2#503]
Is there anyway to do an exact match on SetFilter?

ie a column with text "abc", "abcd", "abcde", and when setFilter to "abc", only "abc" is shown instead of all 3.

Is it possible to make it do exact match when quoting the text, ie. setFilter('\\'abc\\'')

**Comment by matfish2** [comment]
At the moment it is not possible without using custom filters. I suppose you mean both prograrammatic and user input should be treated the same way. So the consumer would be able to set an `exactMatch` array, in which he'll provide the relevant text columns. Or is it just a one-off use-case?

**Comment by akhchan99** [comment]
My plan was to have just one single Filter box for the whole table, and by entering text in it, (call SetFilter function), perform a general search, and if the text entered is quoted, then do a exact match on any of the columns shown.
