### ISSUE TITLE
Method "orderBy" has already been defined as a data property?

### ISSUE THREAD

**Issue by sergiocastrovale** [matfish2/vue-tables-2#504]
I'm having a very weird issue. I've simplified the usage of the package to its most simple state, the error still happens. Take this example:

**orders.vue**

```
<template>
  <div>
    <item-list :dataItems="[]"></item-list>
  </div>
</template>

<script>
import itemList from './items'

export default {
  components: {
    itemList
  },
  metaInfo: {
    title: 'Order Details'
  }
}
</script>
```

**items.vue**

```
<template>
  <v-client-table :data="dataItems" :columns="['quantity']">
  </v-client-table>
</template>

<script>
export default {
  props: {
    dataItems: Array
  }
}
</script>
```

When I load orders.vue, I get this error: `Method "orderBy" has already been defined as a data property`., pointing at `<v-client-table>`. I don't have any method or variable named orderBy in the whole project, so I'm not sure why this is happening. Any thoughts?

**Comment by matfish2** [comment]
Can you paste the full error stack? What version of vue-tables-2 are you using?

**Comment by matfish2** [comment]
mmm... I do define an `orderBy` data property under `state/data.js`, but no method. Even if you were to define an `orderBy` method it shouldn't collide with my scoped property. I assume you are not using vuex?

**Comment by sergiocastrovale** [comment]
Nope. Just fetching the data on creation and setting it on the component. This is a recent issue, I didn't have any trouble with it in the past.

The weirdest thing is that I don't have anything in my app named orderBy at all, so I'm guessing the conflict would be inside the package itself?

**Comment by matfish2** [comment]
Can you tell me what was the most recent version where you did NOT get this error?

**Comment by Anatolie** [comment]
Also working on this project, facing the same error.

Looks like vue2-filters has an `orderBy` filter as well, likely causing this bug. I'd expect the `orderBy` key to be scoped to the module where it's being defined, but that doesn't seem to be the case. Regardless, it's strange that you aren't defining an `orderBy` method, yet this error still occurs.

To answer your question above - as far as we are aware this error doesn't cause the package to break. However, it does appear in the console if any component with a vue-table is loaded.

**Comment by matfish2** [comment]
> Looks like vue2-filters has an orderBy filter as well, likely causing this bug. I'd expect the orderBy key to be scoped to the module where it's being defined, but that doesn't seem to be the case.


That indeed seems to be the case. On https://github.com/freearhey/vue2-filters/blob/master/src/index.js:20 the author defines a global `orderBy` mixin, which collides with the `orderBy` data property.

**Comment by sergiocastrovale** [comment]
That is indeed the case @matfish2. Thanks for looking into it; we ended up on removing vue2-filters.
