### ISSUE TITLE
[vuex] unknown mutation type: <name>/LOADING

### ISSUE THREAD

**Issue by Denis4yk** [matfish2/vue-tables-2#505]
I'm receiving this at 1.4.44. 

It's a "draft" of the issue. If you aware of this problem, than great. If not, than, I'll supply you with more details. Please, ping me, if you need more input.

**Comment by matfish2** [comment]
No, I am unaware of the problem. Did you provide the required (for vuex) `name` prop?

**Comment by Denis4yk** [comment]
@matfish2 

Yes...ehh....

**Comment by matfish2** [comment]
Thank you. I think I will add some merge functionality to handle this scenario. I will have to be careful not to override existing state though

**Comment by Denis4yk** [comment]
I've changed the name, but this issue is still there. Very strange.

**Comment by Denis4yk** [comment]
@matfish2 

But now I don't understand. Is it possible to use your package with modules. How to extract in a module mutations for your table, for example? Did I overlook it in docs?

**Comment by matfish2** [comment]
The package registers the module itself, provided that is does not exist. So If you don't have a module with the same name as the `name` prop, the package should handle everything itself. You can look at vue-devtools and see the vuex state for yourself.

**Comment by Denis4yk** [comment]
You didn't understand me.

Currently I have a lot of logic "around" your server table. 6 custom filters, bulk actions checkboxes, complex columns, that are consisting of multiple components (dynamic icons, labels, based on the passed data, etc.). 

I'd like to wrap all that stuff into a module. Is there any way to do it, cause now I see, that I can't simply extract proper actions/state/mutations into a module.

**Comment by matfish2** [comment]
You can use a module of your own, that doesn't interfere with the table's module.

**Comment by vesper8** [comment]
I have had this problem for months now, and I do indeed use modules that have the same name as the tables.. so that explains that

**Comment by rSammy** [comment]
So did you get it to work somehow ?

I'm thinking this would be stupid to listen for events to be triggered to trigger manually some vuex actions or mutations since it should already do it from the begining.
