### ISSUE TITLE
Adding columnsDropdown to Table (Bulma skin) causes it to float right

### ISSUE THREAD

**Issue by events-jonas-chrisw** [matfish2/vue-tables-2#506]
Setting columnsDropdown to true =using the Bulma template causes it to float right and push the Record filter right:

![capture](https://user-images.githubusercontent.com/33231747/39580109-44975e70-4ee0-11e8-8535-6c55cb597f8d.PNG)

**Comment by matfish2** [comment]
This is by design. It is floated to the right with all implementations.
