### ISSUE TITLE
remove div.container and div.row before div.VueTables VueTables--client

### ISSUE THREAD

**Issue by djmhdi** [matfish2/vue-tables-2#507]
- Vue.js version: 2.5.16

Hello friends , please i want to remove div.container and div.row before div.VueTables VueTables--client
Please can you help me.

Thank you.

**Comment by matfish2** [comment]
These are part of the template. The can only be removed if you use your own custom template

**Comment by djmhdi** [comment]
Thank you for response , how i can do that ?
