### ISSUE TITLE
How do I customize column headers?

### ISSUE THREAD

**Issue by plutosliu** [matfish2/vue-tables-2#509]
- Vue.js version: 2.5.10
- consumed using: webpack
- FULL error message (including stack trace):

I set headings and headingsTooltips in options but no effect

- relevant code:
`<template>`
`  <div id="people">`
`    <v-client-table :data="tableData" :columns="columns" :options="options">`
`    </v-client-table>`
`  </div>`
`</template>`
`<script>`
`export default {`
`  data() {`
`    return {`
`      columns: ['userName'],`
`      tableData: [],`
`      options: {`
`        headingsTooltips: function(h) { return 'Expanded Title'},`
`        headings: function(h) { return <h2>Title</h2>}`
`      }`
`    }`
`  }`
`}`
`</script>`

**Comment by matfish2** [comment]
You need to specify which heading you are referring to.

.e.g:
```js
{
headingTooltips:{
    title:'Expanded Title'
}
}
```
