### ISSUE TITLE
Can't style my grid to fit the content or a specific column

### ISSUE THREAD

**Issue by IFormiga** [matfish2/vue-tables-2#511]
- Vue.js version: v2.5.16
- consumed using: (browserify/webpack/rollup): webpack

Hello, I read the documentation but I still can't manage to style my own table to fit the content on one specific column. I'm wondering if you have any example code with styling with v-client-table, I didn't manage to find one. Thanks for your time!

This is my code:

https://pastebin.com/6ESa1z0y

**Comment by amitkm2603** [comment]
Have you tried using columnsClasses function?

**Comment by IFormiga** [comment]
After I used deep and columnClasses it worked.
