### ISSUE TITLE
Slots vs ScopedSlots for Heading Slots

### ISSUE THREAD

**Issue by akhchan99** [matfish2/vue-tables-2#512]
I upgraded vue-tables-2 from version 0.6 to 1.4
I realized that the header slot doesn't show anymore, when I debug it.

**$vm0.$slots** shows nothing, but **$vm0.$scopedSlots** shows the corresponding h__XXX slots

but in get-heading.js, its still referencing $slots instead of $scopedSlots

**Comment by matfish2** [comment]
The headings slot used to be a scoped slot but now it is just a normal slot. You need to change your code to reflect that.
