### ISSUE TITLE
Sorting on alphanumberic column not working

### ISSUE THREAD

**Issue by meghaagr24** [matfish2/vue-tables-2#514]
- Vue.js version: 2.5.13
- consumed using: webpack
- steps for reproducing the issue:
If a column has alphanumeric values then sorting on that column doesn't work.
for ex if a column has values [user1,user5,user12,user30] and try to sort the column the result is [user1,user12,user30,user5]

**Comment by jblotus** [comment]
you probably want to implement a custom sort and use a natural-case sorting algorithm.

**Comment by matfish2** [comment]
That's the expected default behaviour. You are sorting strings, not numbers.
As @jblotus commented you can implement custom sorting to match your needs.
