### ISSUE TITLE
Pagination Footer component disappears when filter is active

### ISSUE THREAD

**Issue by mykeels** [matfish2/vue-tables-2#515]
- Vue.js version: 2.4.1
- consumed using: webpack
- FULL error message (including stack trace): NONE
- relevant code: I'm not sure
- steps for reproducing the issue: 

  - Load table with more rows than pagination-chunk allows. E.g. 100 rows when pagination is chunked in 15 rows per page
  - Filter by a column
  - The pagination footer component disappears

**Comment by rodrigoroma** [comment]
I think there's a feature that makes the pagination component only appears when there's more than 1 page.

In a similar way, there's a feature that makes the records per page dropdown show only the options with less results per page than the current result set (or make the dropdown desapear if there's only one page).

Can you check if this is your case?

**Comment by matfish2** [comment]
@rodrigoroma is correct.

**Comment by mykeels** [comment]
This isn't my case @rodrigoroma ... I'm Sorry for replying late.

The filtered data has more than 1 page, and the pagination component is hidden.

### For more context

The data is loaded asynchronously when the filter is activated. 

The data comes from an API endpoint served by Laravel. It uses pagination. The pagination component is supposed to show the actual number of pages returned by the pagination metadata. I use stub data to fill up the array to simulate that data in other pages exist.

However, the pagination component disappears until I set the `count` property on the `ClientTables` component via `this.$refs` to the actual number of elements in the `tableData` array.

**Comment by matfish2** [comment]
Please share the relevant code
