### ISSUE TITLE
Updating ClientTable data is not maintaining date format

### ISSUE THREAD

**Issue by gdhnz** [matfish2/vue-tables-2#516]
VueJS v2.5.16

When updating the data for a ClientTable, the date display is not the format set using `dateFormat`.

https://jsfiddle.net/w46pjfvy/2/

**Comment by matfish2** [comment]
That's expected behaviour. You must convert your dates to moment objects before passing a new dataset to the component. `toMomentFormat` does the work for you initially, but not for any subsuquent changes to the dataset.

**Comment by chippindale** [comment]
I know this is expected behaviour, but I have run into the issue and pre formatting the data repeatedly isnt the nicest solution. Im happy to implement this in a MR if you point me in the right direction @matfish2.
