### ISSUE TITLE
Trigger a "server-table" render request manually.

### ISSUE THREAD

**Issue by theharshin** [matfish2/vue-tables-2#518]
- Vue.js version: 2.5.16
- consumed using: webpack
- FULL error message (including stack trace): No Error
- relevant code:
- steps for reproducing the issue:

"Server Table" sends a request to given URL as soon as the component is mounted.
In my case, I want to set an `initlFilter` which I get from an ajax response.
But before it comes, the request is sent by 'Server Table'.

Can we disable automatic rendering & do it manually?

**Comment by amitkm2603** [comment]
The table can be forced to refresh the data using "refresh" function. Example:

this.$refs.table.refresh();

I am not sure if there is an option to prevent data request on load. But you can try having the url empty initially and setting it once the filter is loaded. For that you can use "requestFunction".
