### ISSUE TITLE
[Question] Listening to template component events

### ISSUE THREAD

**Issue by jsodeman** [matfish2/vue-tables-2#52]
The docs example for using a component for a template shows an event being handled in the component ("erase()").

I need to handle the event on the component that the table is inside, so 2 levels up. How do you listen for a component's events and emit them on to the table's parent component?

**Comment by matfish2** [comment]
use [`this.$emit`](https://vuejs.org/v2/api/#vm-emit). Then listen for the event on the component.

E.g

```js
this.$emit('event');
```

```html
<my-component @event="doSomething()"></my-component>
```

**Comment by georaldc** [comment]
I'm a bit confused but how/where would one attach the event handler? I currently have a global buttons component that has a link in it that emits an event on click, but I am not sure where to handle it. Parent code looks like this ('buttons' is the name of the component that defines the buttons template and contains the link above with the click/emit event)

```
columns: ['column1', 'column2', 'buttonsColumn'],
options: {
    templates: {
        buttonsColumn: 'buttons'
     }
}
````

**Comment by dipu-bd** [comment]
I am facing the same problem here
