### ISSUE TITLE
Get applied filters & URL with query string parameters in the server-table.

### ISSUE THREAD

**Issue by theharshin** [matfish2/vue-tables-2#525]
- Vue.js version: 2.5.16
- consumed using: Webpack

How can I get list of all the filters which are applied to server-table? 
It should include, pagination, sorting, custom filters & query parameters.
It would be also great if I can directly get the URL with query string parameters.
I've tried getting filters from 'refs' object but the filters are scattered in diffrenet objects.
I don't know if there is any better way to achieve this.
Thanks.

**Comment by matfish2** [comment]
The `loading` event sends through all of the request data.
