### ISSUE TITLE
Date formatting not being honoured

### ISSUE THREAD

**Issue by scottjo** [matfish2/vue-tables-2#528]
- Vue.js version: 2.5.16
- consumed using: webpack

Hi

I am trying to use the component to show some data with date columns. My table is defined as:

`
data() {

            return {
                columns: [
                    'dcm_linkto',
                    'dcm_ts',
                    'dcm_data',
                    'dcm_active',
                    'action',
                    'complete'
                ],
                options: {
                    sortable: [],
                    filterable: [],
                    headings: {
                        'dcm_linkto': 'Customer UID',
                        'dcm_ts': 'Date Time',
                        'dcm_data': 'Note',
                        'dcm_active': 'Urgent',
                        'action': 'Action',
                        'complete': 'Complete'
                    },
                    toMomentFormat: 'YYYY-MM-DD HH:mm:ss',
                    dateFormat: window.options.dateFormat,
                    dateColumns: [
                        'dcm_ts'
                    ],
                    templates: {
                        action: ActionWidget,
                        complete: CheckedWidget
                    }
                },

            }

        },
`

Note that I am setting the dateFormat from a global window var that evaluates to a string "Do MMM Y". Everything seems to compile correctly, no warnings etc. When I call up the component I get the following error message

> vue-tables-2: non-iterable data property. Expected array, got object. Make sure that your response conforms to the expected format, or use the 'responseAdapter' option to match the currently returned format
> module.exports @ apply-filters.js:22
> module.exports @ filtered-data.js:35
> get @ vue.common.js:3144
> evaluate @ vue.common.js:3251
> computedGetter @ vue.common.js:3509
> (anonymous) @ rows.js:11
> module.exports @ default.js:101
> (anonymous) @ template-compiler.js:44
> Vue._render @ vue.common.js:4546
> updateComponent @ vue.common.js:2779
> get @ vue.common.js:3144
> run @ vue.common.js:3221
> flushSchedulerQueue @ vue.common.js:2983
> (anonymous) @ vue.common.js:1839
> flushCallbacks @ vue.common.js:1760
> Promise.then (async)
> microTimerFunc @ vue.common.js:1808
> nextTick @ vue.common.js:1852
> queueWatcher @ vue.common.js:3070
> update @ vue.common.js:3211
> notify @ vue.common.js:699
> reactiveSetter @ vue.common.js:1016
> proxySetter @ vue.common.js:3302
> (anonymous) @ EditRequest.vue:100
> Promise.then (async)
> getRequest @ EditRequest.vue:97
> mounted @ EditRequest.vue:88
> callHook @ vue.common.js:2923
> insert @ vue.common.js:4160
> invokeInsertHook @ vue.common.js:5962
> patch @ vue.common.js:6181
> Vue._update @ vue.common.js:2662
> updateComponent @ vue.common.js:2784
> get @ vue.common.js:3144
> Watcher @ vue.common.js:3133
> mountComponent @ vue.common.js:2797
> Vue.$mount @ vue.common.js:8542
> Vue.$mount @ vue.common.js:10941
> VERSION @ data-request-admin.js:93
> __webpack_require__ @ bootstrap d7e98ad5dbaba4226df7:19
> Object.defineProperty.value @ data-request-admin.js:47597
> __webpack_require__ @ bootstrap d7e98ad5dbaba4226df7:19
> (anonymous) @ bootstrap d7e98ad5dbaba4226df7:62
> (anonymous) @ bootstrap d7e98ad5dbaba4226df7:62

What am I doing wrong? When I inspect the input data the format seems to be what I expect = a date string in the correct format. If I replace my window.options.dateFormat with a hardcoded string such as "YYYY" all is fine. I just get the year displayed. Any thoughts / advice would be gratefully received. 

Jon

**Comment by matfish2** [comment]
Form the error you are getting I gather than you are using the server component.
On the server component both `toMomentFormat` and `dateFormat` are irrelevant.
It is up to you to return the correct date format (or use a template to modify it), and filter the data.
