### ISSUE TITLE
add checkbox to header

### ISSUE THREAD

**Issue by kife-design** [matfish2/vue-tables-2#53]
Is there a possibility to add a component to a header label?

I have a table, and the first column is a checkbox, so you can select a set of rows and perform an action to them. I would like to add a "select all" checkbox in the header but i dont see how i can do this. Can anyone help me with this?

**Comment by jayarc** [comment]
I've been experimenting with ways to do this with templates. So far I have an implementation that shows the checkboxes but unfortuanately does not correctly move them on sorting.

**Comment by matfish2** [comment]
I've add a possibility to pass a function to render dynamic HTML:

```js
headings:{
   title: function(h) {
return <h6><input type="checkbox"/>Title</h6>
}
}
```

**Comment by dpacmittal** [comment]
How do I handle events on clicking the heading checkbox?

**Comment by freeman-g** [comment]
@dpacmittal 

Here's how I'm handling events.  

I have the template v-modeled to a selected property:

```
         <v-client-table ref="myGrid" :data="tableData" :columns="myColumns">
            <template slot="selected" scope="props">
              <div>
                <input v-model="props.row.selected" type="checkbox">
              </div>
            </template>
          </v-client-table>
```

I have a selectAll method that sets the underlying property:

```     
       selectAll() {
        let length = this.tableData.length
        for (let i = 0; i < length; i++) {
            this.tableData[i].selected = true
        }
      },
```

Once the data is set in the underlying property, Vue's reactivity two-way binds to the checkbox on each row.

Later if I want to access those selected members to do something, e.g., delete them, I use the ref:

```
      deleteSelected() {
        if (this.$refs.myGrid) {
          let filteredData = this.$refs.myGrid.filteredData
          let length = filteredData.length
          for (let i = 0; i < length; i++) {
            if (filteredData[i].selected) {
              this.delete(filteredData[i])
            }
          }
        }
      }
```

**Comment by freeman-g** [comment]
@dpacmittal 

Here's how I'm handling events.  

I have the template v-modeled to a selected property:

```
         <v-client-table ref="myGrid" :data="tableData" :columns="myColumns">
            <template slot="selected" scope="props">
              <div>
                <input v-model="props.row.selected" type="checkbox">
              </div>
            </template>
          </v-client-table>
```

I have a selectAll method that sets the underlying property:

```     
       selectAll() {
        let length = this.tableData.length
        for (let i = 0; i < length; i++) {
            this.tableData[i].selected = true
        }
        // Unfortunately, Vue's reactivity does not seem to work.
        // so I maniupate the array as a workaround to force a rerender
        this.exit.tableData.push({})
        this.exit.tableData.splice(-1, 1)
      },
```



Later if I want to access those selected members to do something, e.g., delete them, I use the ref:

```
      deleteSelected() {
        if (this.$refs.myGrid) {
          let filteredData = this.$refs.myGrid.filteredData
          let length = filteredData.length
          for (let i = 0; i < length; i++) {
            if (filteredData[i].selected) {
              this.delete(filteredData[i])
            }
          }
        }
      }
```

**Comment by techytuppers** [comment]
@dpacmittal and @matfish2 - any advice on how to link the toggling of the heading checkbox to the selectAll method? I'm finding that I can't add "@click="selectAll" to the JSX used for the heading content.

**Comment by jeff-pang** [comment]
following up on the @freeman-g 's example. an alternative to the render function `selected` is to replace it using scope-slot like this

``` html
<!-- checkbox for each row-->
<template slot="selected" slot-scope="props">
            <input type='checkbox' id='checkbox' v-model='props.row.isChecked'>
</template>
<!-- checkbox for each header (prefix column name with h__-->
<template slot="h__selected" slot-scope="props">
            <input type='checkbox' id='checkbox' @click='selectAll()'>
</template>
```
define a variable to toggle check/uncheck states. in my example i use `isRead`

``` javascript
selectAll() {
     let length = this.tableData.length
     this.isRead=!this.isRead;

     for (let i = 0; i < length; i++) {
         this.tableData[i].isRead=this.isRead;
     }
}
```

**Comment by singhabahu** [comment]
@jeff-pang @freeman-g @matfish2 I've been trying to add a checkbox for the table header but below code didn't work. However code to add checkbox to each row works fine.

```HTML 
<template slot="h__selected" slot-scope="props">
     <input type='checkbox' id='checkbox' @click='selectAll()'>
</template>
```

any idea where I made the mistake?

Here's my code

```javascript
{
      tableColumns: [
        "check",
        "Name",
        "WindowId",
        "Enabled",
        "Duration",
        "Description"
      ],
      tableData: [],
      tableOptions: {
        headings: {
          Name: "Name",
          WindowId: "Window ID",
          Enabled: "Status",
          Duration: "Duration",
          Description: "Description"
        },
        sortable: ["Name", "WindowId", "Enabled", "Duration", "Description"],
        filterable: ["Name", "WindowId", "Enabled", "Duration", "Description"]
}
```

This is how I render my table

```HTML
<template slot="h__check" slot-scope="props">
     <input type='checkbox' id='checkbox' @click='selectAllAtOnce()'>
</template>
```

**Comment by JonathanLouw** [comment]
@singhabahu I know its been a while but maybe this will help someone else, if you leave out the slot-scope attribute it should work:

```
<template slot="h__check">
     <input type='checkbox' id='checkbox' @click='selectAllAtOnce()'>
</template>
```

**Comment by singhabahu** [comment]
@JonathanLouw thanks for the input. will look into this when I get a free time.

**Comment by ChetnaGupta** [comment]
How can we add checkboxes to each row ? Apparently below code doesnt work for me
`<template slot="selected" slot-scope="props">
            <input type='checkbox' id='checkbox' v-model='props.row.isChecked'>
</template>`

**Comment by songoo** [comment]
JonathanLouw - Tnx much that one helped , seems 'h__' slot still do not like slot-scope="props" .

**Comment by hansa0712004212** [comment]
Well, I have able to add checkbox on column header, and select/deselect all checkboxes in rows.
No the problem I got is,
When I click on headerRow checkbox, sorting happens.
How to avoid that?

**Comment by hansa0712004212** [comment]
Thanks everyone.
Well I was able to add checkbox in header row as Select/Deselect All option for rows.

Btw, my problem is,
I want to use select all on filtered results only.
Or I want to select Row checkboxes when select HeaderRow checkbox for filtered/currently visible results on table only.

**Comment by andikajayaw** [comment]
> Thanks everyone.
> Well I was able to add checkbox in header row as Select/Deselect All option for rows.
> 
> Btw, my problem is,
> I want to use select all on filtered results only.
> Or I want to select Row checkboxes when select HeaderRow checkbox for filtered/currently visible results on table only.

Can I see your code for Header checkbox to select all/deselect all the rows? Thank you.

**Comment by yasoza** [comment]
After banging my head on the wall for 4 hours, I finally found this thread. slot-scope dont work with h__ slots. 

``` 
              <template
                  v-for="column in columns"
                  :slot="`h__${column}`"
                >
                  <div
                    :key="column"
                    v-html="options.headings[column]"
                    @click="clickhandler($event,column)"
                  />
                </template>
```

**Comment by hoai** [comment]
Hi, 
My solution is working. maybe this is help other.
Please see it.
https://gist.github.com/hoai/dc37116f6a17a45232647dcfe8090e51

**Comment by SauceTV** [comment]
The header on my checkbox does not update with the "allSelected" variable. The only way to fix it that I found was to use a ref on the header and change the ".checked" var to true or false. The problem is that vue doesnt like when you change the prop directly.

HTML:
```
<v-client-table :columns="['name', 'select']" :data="products" :options="table.options" :theme="table.theme" class="dataTable p-0 m-0 w-100">
      <div slot="h__select" style="float: right">
            <b-form-checkbox @change="cart.selectedProducts = selectAll()" color="success" style="float: right"
                                          v-model="allSelected"/>
      </div>
      <div slot="select" slot-scope="props" style="float: right">
            <b-form-checkbox v-model="cart.selectedProducts" :value="props.row._id" color="success"
                                          style="float: right" />
      </div>
</v-client-table>
```

Vars:
```
data: () => {
      return {
            products: {
                  {name: "socks", _id: 1},
                  {name: "shirt", _id: 2},
                  {name: "pants", _id: 3},
            },
            cart:  {
                  selectedProducts: [],
                  ...  // Other cart Data
            },
            allSelected: false,
            ...  // Other Page Data
      }
}
```

Watchers:
```
watch: {
      selectedProducts: {
            deep: true,
            handler() {
                  let all = this.products.every(product => {
                        return this.cart.selectedProducts.includes(product._id);
                  }
                  if (all && !this.allSelected) {
                       console.log("change to true")
                        this.allSelected = true;
                  } else if (!all && this.allSelected) {
                       console.log("change to false")
                        this.allSelected = false;
                  }
            }
      }
}
```

Methods:
```
methods: {
      selectAll() {
            return  JSON.parse(JSON.stringify(this.allSelected ? this.products.map(_ => _._id) : []));
      }
}
```
