### ISSUE TITLE
Can't set `style` of some rows.

### ISSUE THREAD

**Issue by mapcic** [matfish2/vue-tables-2#530]
Hi. I have the problem with setting `style` of certain rows.

In `options` I can set `rowClassCallback`, but I can't  set `style` of row ( `<tr>`) instead of `class`. I can't find the way how set style for someone rows.

**Motivation:**
I use API, that sends `baground-corol` for any states. One is configured on server and have different values for different users. Some companies want one colors, another want another colors.

**Comment by matfish2** [comment]
The `style` attribute is not supported.
 
Why not use the API data in conjunction with your own custom classes?

E.g if the API returns `color:red`, you can set a `.red` class:

```css
.red {
  background:red;
}
```
