### ISSUE TITLE
Custom filter with component's "Debounce"

### ISSUE THREAD

**Issue by theoarena** [matfish2/vue-tables-2#531]
- Vue.js version: 2.x
- consumed using: webpack
- FULL error message (including stack trace):
- relevant code:

Hi @matfish2! 
I'd like to know if the method `setFilter(query)` uses the same "Debounce" logic as the built-in filter method.

I have: 
my template
```
 <div id="inputfilter">
   <input type="text" name="global-search" v-on:input="generateQueryString" v-model="query_string">
 </div>
 <div id="list-vue">
  <v-server-table url="{{ $api }}" :columns="columns" :options="options" ref="listTable"> 
(...)
```

```
var inputfilter = new Vue({
  el: "#inputfilter",
  data: {
    query_string: ""
  },
  methods:{
    generateQueryString: function(){
      list.$refs['listTable'].setFilter(this.query_string);  
    }
  }
});
```

It works fine. 'generateQueryString' is being called, but the **setFilter** method makes a request for every key hit (v-on:input). Is it expected to work like that? 
When using the built-in filter input, it sounds like the requests are made with a 500 milliseconds debounce time (as written in options section).

Is this the best way to implement a custom search input? Is there a way for me to use the component's built-in debounce logic?

Thanks! =)

**Comment by matfish2** [comment]
`debounce` is only used when the filter is set by a UI event, to determine when the user has finished typing his query. When using `setFilter` programatically it doesn't make sense to set a debounce; i.e if you explicitly call `setFilter` it means you want it to run _now_ with the input you have passed.

In your case. where you are using `setFilter` in response to a UI event, it is up to you to wrap the `generateQueryString` method with `debounce`
