### ISSUE TITLE
Problem with styling ClientTable

### ISSUE THREAD

**Issue by bbogda** [matfish2/vue-tables-2#532]
- Vue.js version: 2.5.10
- consumed using: webpack 3.10.0
- FULL error message (including stack trace):
`vue-tables-2: Template "element-ui" does not exist render`
- relevant code:
```
import Element from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'

import '@/styles/index.scss' // global css
import { ClientTable } from 'vue-tables-2' // Vue-Tables-2

Vue.use(Element, {
  size: 'medium', // set element-ui default size
})

// Vue Tables 2
Vue.use(ClientTable, {}, false, 'theme-chalk', 'element-ui')
```
- steps for reproducing the issue: ...

When set: 
`Vue.use(ClientTable)`
without theme and template got unstyled table:
![vue-tables-2](https://user-images.githubusercontent.com/39616051/40542085-e4976f42-601e-11e8-82ec-93e414dbbee3.jpg)

Is there way to style local ClientTable maybe some style template just for simple styling?

Thanks for vue-tables-2 it's smart one ;)

**Comment by matfish2** [comment]
As documented `ui-element` is not included in the currently supported themes. 
You can copy a theme file from the `themes` folder, modify it to your needs, and pass it to the constructor.
