### ISSUE TITLE
Possible conflict using vue-tables-2 with other components in slot (e.g., vue-strap)

### ISSUE THREAD

**Issue by dbezborodovrp** [matfish2/vue-tables-2#533]
- Vue.js version: `"vue-tables-2": "^1.4.50"`
- consumed using: NPM

I am trying to use vue-tables-2 with a tooltip component from [wffranco/vue-strap](https://github.com/wffranco/vue-strap).

The tooltip component works perfectly on its own, but when I try to include it within a table row slot, the tooltip does not appear. There is a conflict between vue-tables-2 and the tooltip component from vue-strap, but I have no idea what it could be. It is almost as if vue-tables-2 is greedily taking possession of the DOM and not allowing other components to manipulate its own elements (but I am not sure about that.)

```
Vue.component('tooltip', require('vue-strap/src/Tooltip.vue'));

template:
    <v-client-table :columns="table.columns" :data="table.data" :options="table.options">
        <div slot="foo" slot-scope="props">
            <tooltip placement="right" content="test">
                <button class="btn btn-default">Test</button>
            </tooltip>
        </div>
    </v-client-table>
```

**Comment by ixperiencenl** [comment]
Because the slots are generated dynamically (and as I presume, after the tooltip is initialized), I think it's a loading issue.  Maybe it's needed to re-initialize after the load?
```
Event.$on('vue-tables.loaded', function (data) {
    // Do something
});
```

**Comment by matfish2** [comment]
No conflict. It's a css issue.

```
tr td span{
  position:relative;
}
```
