### ISSUE TITLE
Vue-table-2 can't handle an array full of getters and setters?

### ISSUE THREAD

**Issue by driekus77** [matfish2/vue-tables-2#535]
- Vue.js version:

>     "vue": "^2.5.16",
>     "vue-loader": "^15.2.1",
>     "vue-router": "^3.0.1",
>     "vue-tables-2": "^1.4.50",
>     "vue-template-compiler": "^2.5.16",
>     "vuelidate": "^0.7.2",
>     "vuex": "^3.0.1",
>     "vuex-map-fields": "^1.2.3"

- consumed using: (browserify/webpack/rollup)

>     "compression-webpack-plugin": "^1.1.11",
>     "webpack": "^4.8.3",
>     "webpack-cli": "^2.1.4",
>     "webpack-hot-middleware": "^2.7.1"

- FULL error message (including stack trace):
No error message. Table shows correct number of rows but these rows itself are empty when using an array full of getters and setters.
The same array without the getters and setters works fine.
I create these array full of getters & setters using "vuex-map-fields". Already issued a ticket on there github but they don't know Vue-tables-2 so hopefully you can help me towards the right solution.
https://github.com/maoberlehner/vuex-map-fields/issues/27

- Why using vuex-map-fields anyway?
Because its creating a kind of proxy in front of the Vuex state. I use this for both tracking changes and validating anything that the UI missed. Because of that I'm using Vuex in strict mode!
This means that when I don't use the array full of getters & setters I get mutation warnings. 

- relevant code:
See jsfiddle link beneath.
If you switch in the computed part:

```
  computed: {
        ...mapTodoFields({
        todos: 'todos',
      }),

      ...mapTodoMultiRowFields(
        { mtodos: 'todos' }
      )
  },
```
mapTodoFields ==> todos and mapTodoMultiRowFields ==> mtodos;  Result => works 👍
mapTodoFields ==>ptodos and mapTodoMultiRowFields ==> todos; Result => does not work 👎

So to be clear: vue-map-fields is mapping one on one with ...mapTodoFields(...) and the getters & setters are added using ...mapTodoMultiRowFields(...)!

- steps for reproducing the issue:
https://jsfiddle.net/y5w72x87/35/

Thanks for any help and keep up the good work with Vue-tables-2!

Kind regards,

Henry

**Comment by matfish2** [comment]
If you look at the data you are passing in the Chrome console you will note that the properties are non enumerable (it is signified by a lighter pinkish hue). Since the package accesses the properties by iteration, it is understood why it cannot detext those properties.
See: https://stackoverflow.com/questions/29821843/what-is-the-significance-of-faded-properties-when-using-console-dir-in-chrome-de

**Comment by matfish2** [comment]
We are closing this issue becausae we beleive it had been resolved.
If you think it should be reopened please comment below.
