### ISSUE TITLE
Avoid forcing colspan in Child rows to reuse the columns on the v-client-table

### ISSUE THREAD

**Issue by seblucas** [matfish2/vue-tables-2#536]
Hi,

That's more of RFC or a feature request but I'll still send the relevant part of the issue template : 

- Vue.js version:
2.5.13
- consumed using: (browserify/webpack/rollup)
Webpack

When you use Child row, this plugin create a new `tr` with a `td colspan="X" ` (with X being the total number of columns of your table including the column to show/hide child rows). That's perfectly fine if you want to show a brand new component but in my case I want to keep that same columns as the main table (the background color will be different). I can try to reuse the same column size but I often have a pixel difference in the column size.

AFAIK, there's no way to include the child component in the `tr` and let the component handle the `td` and the colspan, isn't it ? Does anybody had the same problem before and is there a workaround ?

Thanks in advance and thanks for this great plugin.

**Comment by mbokil** [comment]
I have run into a similar problem as @seblucas. I need to toggle a row but keep the same column structure as the parent row. I am looking for a way to control the colspan like a colspan property for child rows.

**Comment by ggirodda** [comment]
I also added childRowTr because I needed multiple lines toggle
