### ISSUE TITLE
Stuck on loading with no errors

### ISSUE THREAD

**Issue by gergo2007** [matfish2/vue-tables-2#544]
- Vue.js version: 2.5.16
- consumed using: webpack
- FULL error message (including stack trace): no error message
- relevant code:

In my view i have: 
`<div id="coins"> <v-server-table url="http://localhost/api/coins" :columns="columns" :options="options"></v-server-table> </div>`

My data is:

`
        data: {
            columns: ['name'],
            options: {
            requestFunction: function(data) {
                return axios.get(this.url).catch(function (e) {
                    this.dispatch('error', e);
                }.bind(this));
            }
        }
    }
`

Api returns: 

`return \App\Coin::where('is_available', 1)->paginate();`

My response adapter:

`responseAdapter: function (resp) {
        return {
            data: resp.data.data,
            count: resp.data.total
        }
    }`

The table is showing that its loading but i get no errors.

I have also copied the code from https://jsfiddle.net/matfish2/js4bmdbL/, and its doing the same thing

**Comment by matfish2** [comment]
What response do you get form the server?

**Comment by gergo2007** [comment]
https://gyazo.com/3e90344484a8433171d4057d29614a5b

**Comment by matfish2** [comment]
Can you console.log `resp` in the response adapter? I want to see if it is called.
If not, remove you request function and check again.

**Comment by gergo2007** [comment]
resp in response adapter:

https://gyazo.com/d0a8ef003e90fdf81cb5d17cece23505

**Comment by matfish2** [comment]
Can you log `data` on `compiled\methods\set-data.js:8`?

**Comment by gergo2007** [comment]
data in set-data.js:

https://gyazo.com/c3de0d04e92cb35d506b8f8f636e325e

**Comment by matfish2** [comment]
Alright, let's keep going down the rabbit hole.
log `this.data` on line 10 of the same file.

**Comment by gergo2007** [comment]
this.data was also fine, will send a screenshot in 10 minutes

**Comment by gergo2007** [comment]
this.data and this.count logged:

https://gyazo.com/87c0385ec075ef30559c96f07db9e424

https://gyazo.com/5cbafec94cdf0d1693d1c2ea9f0db4e5

**Comment by matfish2** [comment]
Please look at vue dev tools and see if `data` and `count` are assigned their respective values. I assume you are not using Vuex.

**Comment by gergo2007** [comment]
Im not using vuex.

Components is empty:

https://gyazo.com/a0ef276f304daf91737608c774272c9e

There are 2 events:

https://gyazo.com/8a221d504972801e0bc27dda215519f8

Seems like the url here is wrong? I have a localhost url: https://gyazo.com/86e2d9b8a40aac013ebbc18cc5bd71f4
 
Or that is different url?

**Comment by matfish2** [comment]
No. The URL is fine, and as we saw it returns the expected dataset.
I find it weird though that `Components` are empty. Can you try to close and reopen the console?

It seems to me like a reactivity issue, because `this.data`  and `this.count` are assigned correctly.
Can you console.log `this.count` on `compiled\modules\rows.js:17`.
It should initially show 0, but when the response is assigned it is suppused to rerender with the new count.

**Comment by gergo2007** [comment]
_this.count:

https://gyazo.com/0dc4dd5fa6427465511adb5700751ef4

Not sure why components is empty, i have tried to close and reopen, same thing.

**Comment by matfish2** [comment]
Well, then reactivity is also ok. 
You need to keep logging after the `if` statement the returns the "no results" html. 
On the second render, when the count not zero, it should continue all the way to the end and return the `rows` variable, at which point your table should be displayed. I can only assume that it doesn't get there for some reason.

**Comment by gergo2007** [comment]
I have figured it out, by default in Laravels app.blade.php there is:


    
    <script src="{{ asset('js/app.js') }}" defer></script>

Which messed up vue js.

Thank you for helping and sorry for wasting your time!
