### ISSUE TITLE
childRow :  How it work ?

### ISSUE THREAD

**Issue by Soulnianfo** [matfish2/vue-tables-2#545]
Hi, can you help me ?
I have create a component chilaRow.vue which content two button and I import it in other component and make something that : 

import childrow from './childRow'
data(){
options:{
          childRow` : 'childrow'
}
}
but I saw just a row display and nothing inside.

**Comment by matfish2** [comment]
We were unable to reproduce this issue, using the details that you have provided.
It would be best if you could provide us with more details and relevant code, and create a fiddle demonstating the issue.
