### ISSUE TITLE
Empty query on initial loading of the table since v1.3.41

### ISSUE THREAD

**Issue by gergo2007** [matfish2/vue-tables-2#546]
Hello

I just noticed that the query is empty on initial load since v1.3.41.

Is it possible to still send the query somehow with the new version on initial load?

Thank you!

**Comment by gergo2007** [comment]
Using version 1.3.32 initial load params:

https://gyazo.com/dfa3f73c51004797e69aee92060580a9

Version 1.3.41 or newer:

https://gyazo.com/9e81302fc777173b024950260b806d25

**Comment by gergo2007** [comment]
Working version:

https://jsfiddle.net/s58h6uex/

New version that has this issue:

https://jsfiddle.net/wjLup57n/2/

**Comment by gergo2007** [comment]
Im not referring to initFilters, im referring to the query being empty in the new version (https://gyazo.com/8541ab2070649e4697659b9f2ca8a2fc)  vs sending whats in the filterable ( https://gyazo.com/7279234ba547fa7fa539fb3d7ababab1 ) 

With the new version if i set initFilters: {'name': ''} thats also ignored.

**Comment by matfish2** [comment]
Oh. now I see. 
Yes, the new version ignores empty filters, as they don't serve any purpose on the server side, AFAIK.
Can you explain the logic behind the need for empty filters?

**Comment by gergo2007** [comment]
I have a trait that filters by the params sent.
If i send company.name it splits it by the dot and uses the first part to load the relationship even if the filter is empty.

**Comment by matfish2** [comment]
I've add a `sendEmptyFilters` option. Defaults to `false`

**Comment by gergo2007** [comment]
Thank you!
