### ISSUE TITLE
rowClassCallback not called after click

### ISSUE THREAD

**Issue by seivad** [matfish2/vue-tables-2#549]
- Vue.js version: ^2.5.7
- consumed using: webpack

```
rowClassCallback: function (row) {
                        console.log("Row:", row.id)
                        return row.active ? 'success' : '';
                    }
```

```
rowClicked(data) {
                console.log("Data Row:", data)
                data.row.active = true
                this.$store.dispatch('selectProduct', data.row)
            }
```

The issue is that the rowClassCallback never get's fired again from the rowClicked() function. So although all the items i've got have an active: false property on them, when they change to true by data.row.active = true, it never calls and doesn't update the row. 

Can you please advise how this works? It isn't clear in the documentation nor in prior Issues that I've looked at.

**Comment by matfish2** [comment]
Are you using the client or server component? With or without vuex?
The original row is only passed down in the client component, and even then only when there is a unique identifier (defaults to `id`, which you seem to have)

**Comment by making3** [comment]
Same here, unless I'm using it wrong (which might be the case).

* Vue.js version: 2.5.16
* Using webpack (3.12.0 currently)
* Not using Vuex.
* Using server component.
* 'id' is available on the row data (and is unique).

Table:

    <v-server-table class="pagination" :url="apiUrl" :columns="columns" @loading="loadingData" @loaded="doneLoading" @row-click="rowClick" :options="options">
        
 
Vue Data:

    options: {
        // Other stuff
        rowClassCallback: function (row) {
            return row.selected ? 'info' : '';
        }
    }

Vue Methods:

    rowClick(row) {
        row.selected = true;
    }

`rowClick` is fired every time I click on a row. `rowClassCallback` is fired on initialization only. Is that expected?

**Comment by matfish2** [comment]
Client side fiddle: https://jsfiddle.net/jfa5t4sm/2666/
Server side fiddle: https://jsfiddle.net/js4bmdbL/300/

**Comment by making3** [comment]
@matfish2 Thanks for the help, C was my problem, which I should be able to deal with now, though I'm not sure what @seivad's specific issue was (fiddles should help).

**Comment by kawasilewska** [comment]
@seivad I've had the same problem as you. 
Solution what helped me was to use `watch` section instead of `computed` and for each entry in the array I was creating a new object based on entry fields.

So, in your example you should have:
-  `arrayProducts` field in the vue `data` section,
-  watch for `this.products`:
```
watch: {
    products(value) {
        this.arrayProducts = value.map(product => {
            return {
                ...product fields,
                id: 'a unique identifier of a product row', <- very important
                active: false
            }
        }
    }
}
```
