### ISSUE TITLE
How do you rename columns without affecting the data?

### ISSUE THREAD

**Issue by Msolda1** [matfish2/vue-tables-2#550]
I read through the documentation several times but sorry if I missed it. Everything is working great except I am fetching data using Axios and the data consists of objects. I want to display values in the tables and I can only show them when I write the full object notation for example:
columns: ['shipping_address.first_name']

And then the column on the table winds up showing "Shipping address.first name" when I want it to just show First Name. I tried {'First Name': 'shipping_address.first_name'}, I tried filters, and I tried to use some of the built in options like columnsClasses and initFilters.

On a similar note, is there a way to join columns together? For example if I wanted to display shipping_address.first_name and shipping_address.last_name together in the same column with the header "Name." I am using Vue 2 inside a Laravel project with Eloquent.

**Comment by matfish2** [comment]
A. use the `headings` option.
B. Yes. Use [Templates](https://github.com/matfish2/vue-tables-2#templates)
