### ISSUE TITLE
ref is undefined

### ISSUE THREAD

**Issue by dermansi** [matfish2/vue-tables-2#551]
Hey, beginner question here:

The ref of my table is undefined.

On my table i have ref="table"

mounted() {
  console.log(this.$refs); // lists me table
  console.log(this.$refs.table); // lists me undefined
}

Do you know the reason for this?

Thanks for your work
Manuel

**Comment by matfish2** [comment]
This is a generic Vue question. As such please ask your question in a dedicated forum.
