### ISSUE TITLE
pagination broken (even in sample?)

### ISSUE THREAD

**Issue by fabsenet** [matfish2/vue-tables-2#552]
I have several issues with the pagination:

1. The "last" page button is never clickable: 
![grafik](https://user-images.githubusercontent.com/2065705/41900804-088b1f02-791f-11e8-8d60-aa51a16b44d3.png)
1. The texts for first/last are not changeable.
1. Setting edge:false or true has absolutely no effect.

See it here: 
https://jsfiddle.net/jfa5t4sm/2791/
this is basically your demo with minor modification, see below.

## List form:
- Vue.js version: 2.5.8
- consumed using: jsfiddle
- FULL error message (including stack trace): no
- relevant code:
```js
      texts: {
        count: '{from}. bis {to}. Datensatz von {count} werden angezeigt.|{count} Datensätze|Ein Datensatz', //works
        first: 'Erster', //works NOT
        last: 'Letzter', //works NOT
      },
      pagination: {
        edge: true //setting this true or false makes NO difference
      }
```
- steps for reproducing the issue: 
 - https://jsfiddle.net/jfa5t4sm/2791/
 - click last button and observe no change

**Comment by matfish2** [comment]
It is not broken.
When you have only one chunk the first and last links are not presented.
Try setting the `pagination.chunk` option to 2 and see how it works

**Comment by add1ct3dd** [comment]
Following on from this, if there are not enough pages to use the chunks, why are they being displayed?

First/Last are only shown when there are enough pages that you cannot view them all in the list, so why are we showing chunks when there are < 10 pages?

Sorry to comment on an old issue, it seemed to make more sense than opening a new one currently.
