### ISSUE TITLE
Column Visibility, hide column on init

### ISSUE THREAD

**Issue by vstruhar** [matfish2/vue-tables-2#559]
Is it possible to hide a column(s) on page load?
Went through the documentation a few times and I still can't figure it out.

I have tried to use:
```
columnsDisplay: {
    order_id: 'mobile',
}
```
It works, but then the column **will show up on mobile** which is not desirable.

**Comment by MatiasOlivera** [comment]
You must use a logical operator (`min`, `max ` or `not`) as a prefix of the device type. You can use `not_mobile `or `min_tablet`.

**Comment by vstruhar** [comment]
Thanks for the reply Matias. I know that I can use logic operators, but the idea is to **hide a column on every device on page load**. Sorry, maybe my description wasn't clear.

**Comment by francislavoie** [comment]
@vstruhar you can bind to the `columns` parameter, and update the columns array as you please. If the column isn't in the array, it isn't rendered.

**Comment by theharshin** [comment]
I too need this kind of option. Some columns are not always required to show at initial. But we need to give the option to enable it whenever required. 
The current configuration is like we'll show all the columns, the user will hide which is not required.
@vstruhar did you find any proper solution/hack?

**Comment by vstruhar** [comment]
I didn't find any solution for this, still showing all columns on table load.

But I'm using the solution described [here](https://github.com/matfish2/vue-tables-2/issues/304#issuecomment-340190104) when I need to show/hide for example some admin specific columns.

**Comment by eddivalen** [comment]
Hey  @vstruhar , please could you share how do you solve this issue?  I want to hide a column by a condition

**Comment by vstruhar** [comment]
@eddivalen Sure, it's really simple, here is what I did:
`<v-server-table ref="table" :columns="columns" :options="options" :name="name" class="has-bulk-selection">`
I removed/added item to `columns` array when needed:
`mounted() {
     // hide admin column
     if (!this.isAdmin) {
          this.columns.splice(this.columns.findIndex(column => column == 'checkbox'), 1);
     }
},`

**Comment by alexander-wecode** [comment]
For anybody looking for a solution.
I found a toogleColumn() function directly on the `v-server-table` component that worked for me and still keeps the column in the dropdown.

`<v-server-table ref="table" :columns="columns" :options="options" :name="name" class="has-bulk-selection">
`

```
mounted() {
     // hide desired column
     const serverTableRef = this.$refs.table;
     serveTableRef.toggleColumn(column_to_hide);
}
``
`

**Comment by matfish2** [comment]
solved by `visibleColumns/hiddenColumns` options
