### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by eleftrik** [matfish2/vue-tables-2#560]
How about localization? I can't find anything in the documentation. If think a hint in the documentation would be really appreciated.
Thank you

**Comment by matfish2** [comment]
look at the `headings` option

**Comment by eleftrik** [comment]
I know, with `headings` option I can translate column names.
What about other labels, such as `Showing x to y of z records`, `Filter` , `Records`, etc.?
There is no mention in the README.md.
Thanks

**Comment by matfish2** [comment]
There is. Look at the `texts` option

Sent from Mail for Windows 10

**Comment by eleftrik** [comment]
Thank you @matfish2, I see there is the `texts` option, but which are the keys?
I guessed I can use texts: `{count: 'Showing 1 to 25 of 200 records'}`, but I don't know how to replace values

**Comment by matfish2** [comment]
As mentioned in the docs you should use the [defaults](https://github.com/matfish2/vue-tables-2/blob/master/lib/config/defaults.js) file as guidance

**Comment by eleftrik** [comment]
Thank you so much.
