### ISSUE TITLE
Additional Examples

### ISSUE THREAD

**Issue by 19peaches** [matfish2/vue-tables-2#561]
Just a suggestion, it would be useful if you would create some in depth examples that implement more options. Your current example has virtually nothing configured.

I absolutely love this package, but it takes forever to figure out how to implement anything, some of the instructions just point in circles and provide no definable answers.

I appreciate all the hard work you put into this, thank you so much.

**Comment by matfish2** [comment]
I hear what you are saying and I think it is a valid point. 
I will strive to enrich the example in the near future. Of course, if you or anyone else want to chip in and create an alternative/extended full blown fiddle, that would be great.

>  some of the instructions just point in circles and provide no definable answers

I would appreciate it if you could expand on your comment, so I could try and improve documentation.
