### ISSUE TITLE
How do you pass options when using CDN ?

### ISSUE THREAD

**Issue by sobiero** [matfish2/vue-tables-2#568]
How do you pass the options below when using CDN ? I want to use bootstrap4

Vue.use(ClientTable, [options = {}], [useVuex = false], [theme = 'bootstrap3'], [template = 'default']);

- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

**Comment by rSammy** [comment]
Hello,

You can use table like this 

`<v-client-table :data="users" :columns="columns" :options="options"></v-client-table>`
```
 data() {
            return {
                data : [{id:1, name:'Test'}],
                columns: ['id', 'name'],
                options: {
                    theme: 'bootstrap4',
                    template: 'default',
                    headings: {
                        id: 'ID',
                        name: 'Name'
                    },
                },
```
