### ISSUE TITLE
Pagination isn't reset when applying custom filter with client side table

### ISSUE THREAD

**Issue by kelchm** [matfish2/vue-tables-2#57]
Vue.js version: 2.1
consumed using: (browserify/webpack/rollup): webpack
FULL error message (including stack trace): N/A
relevant code: N/A
steps for reproducing the issue:
Client-Side Table
Switch to a page X (other than 1)
Add filter to the table which filters out most rows
Records won't be shown, since the table will still be on page X

This is an identical issue to #36, but the fix in #37 only applied to the server side component.

**Comment by fernandoherlo** [comment]
After this commit, if use vue-tables-2 + vue-router and switch routes in the app, the customfilters are register more than one time, and "setPage" gives a error. I solve this, adding before "bus.$on"...
`bus.$off('vue-tables.filter::' + filter.name)` in _lib/methods/register-client-filters.js_

Excuse my bad English!

**Comment by awmottaz** [comment]
I am having the same issue as @fernandoherlo. Has there been any more development on this?
