### ISSUE TITLE
Adding a tooltip to each row

### ISSUE THREAD

**Issue by boriskogan81** [matfish2/vue-tables-2#571]
Vue.js version: 2.5.16
consumed using: (browserify/webpack/rollup): Webpack (via Vue-CLI 3)

How can I add a tooltip with row information? I'd like to use the Bootstrap Vue tooltip module, which targets parent elements either by id or by ref-can I add either one to each row programatically?

**Comment by newuser** [comment]
Well,  I see only dirty way to fix in sources of the library : 
rows.push(<tr class={rowClass} key=
in modules/rows.js.
There are slots for columns but no slot for row.
