### ISSUE TITLE
Client side filtering with nested tableData

### ISSUE THREAD

**Issue by gergo2007** [matfish2/vue-tables-2#581]
Hello

I have a tableData with nested data, i want to create a custom filter for the nested data. 

So i have:

    customFilters: [{
        name: 'role.title',
        callback: function (row, query) {
            console.log(row.role[0].title == query);
            return row.role[0].title == query;
        }
    }]

If i type in my filter, i can see in the console 2 of them are True but nothing shows up in the table.

Example:

https://jsfiddle.net/xa0kqh2b/

Is this a bug or am i doing something wrong?

Thank you!

**Comment by kife-design** [comment]
I have the same problem. Some rows return true, but the resultset is empty in the table

**Comment by lukedanielson** [comment]
I can't get the emitter to fire, even though it doesn't report an error:

This is executed:
```js
Event.$emit('vue-tables.filter::jlee_mode', mode);
```

But the custom filter callback never fires, nor reports an error.

options:
```js
customFilters: [
    {
        name: 'jlee_mode',
        callback: function(row, query) {
            // debugger;
            console.log('custom filter jlee_mode callback', query)
            if (query === -1) {
                return true;
            }
            return row.name[0] == query
        },
    }   
]
```

Any ideas?

**Comment by KaiOelfke** [comment]
I had the same problem with a simple age range custom filter. Debugging confirmed that my filter callback function is correctly returning different booleans. Also the rows were filtered. However after this custom filtering a standard text filter removed all rows.

1. The user selects an option from the list filter e.g. 0 - 30 years with `id: 'young'`
2. My custom filter callback function receives the query variable with string 'young' and filters the rows
3. A text filter filters all rows for 'young' and there is no match

If I use a string like `id: '1'` for age 0 - 30 I actually get some results like 16 years as the text filter matches here, however all rows with ages of 0-9 and 20-30 don't appear.

As a temporary workaround I added the following code to `/methods/client-search.js` to return the data earlier without further filtering. But this breaks multi column filtering so it's not a solution. Basically columns with custom filters should only use the custom filter and no other text filter.

```
var filterData = filterByCustomFilters(data, this.opts.customFilters, this.customQueries);
if (filterData.length != data.length) {
    return filterData
}
```

**Comment by KaiOelfke** [comment]
I changed my workaround so that multi column filtering works. I am not an experienced JavaScript dev so it can be done cleaner probably. Basically if the current column is a custom filter column the standard filtering is skipped as custom filtering happens before.  In `/methods/client-search.js`:

```js
var data = filterByCustomFilters(data, this.opts.customFilters, this.customQueries);
if (!totalQueries) return data;
return data.filter(function (row, index) {
  found = 0;
  this.filterableColumns.forEach(function (column) {
    if (this.opts.customFilters.every(function (customFilter) {
      return customFilter.name == column
    })) {
      found++;
      return;
    }
  ...
  }
}
```
