### ISSUE TITLE
Date format not working

### ISSUE THREAD

**Issue by jakobeissler** [matfish2/vue-tables-2#582]
- Vue.js version: 2.5.13
- consumed using: (webpack)
- FULL error message (including stack trace): None
- relevant code:

**Template:**
`<v-client-table  :data="resultados" :columns="columnas" :options="opcionesTabla"></v-client-table>`

**Vue instance:**
```
data: function() {
		return {
			columnas: ['a', 'b', 'c'],
			resultados: {
                                "a": 'test',
                                "b": 'test',
                                "c": "2018-07-01T04:00:00Z"
                        },
			opcionesTabla: {
				dateColumns: ['c'],
				dateFormat: 'DD MM YYYY h:mm a',
				toMomentFormat: 'YYYY-MM-DD HH:mm',
				theme: 'bootstrap4',
				template: 'default',
				useVuex: false,
				headings: {
					a: 'A',
					b: 'B',
					c: 'C'
				}
			}
		}
	}

```

**main.js file:**

```
import { ServerTable, ClientTable, Event } from 'vue-tables-2';
Vue.use(ClientTable);
```

**index.html file:**

```
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
    <div id="app"></div>
    <!-- built files will be auto injected -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
  </body>
```

- steps for reproducing the issue:

Running this code on my installation wil not work. It shows the table and seach filter but date is not formatted. No errors in console.

I've checked: typeof $().daterangepicker in console and i get: function

**Comment by jakobeissler** [comment]
I just realized, sorting also isn't working, no icons are displayed. Search filters work ok.

**Comment by MatiasManevi** [comment]
Have the same problem and found the solution [here](https://github.com/matfish2/vue-tables/issues/138l) hope it helps

**Comment by MatiasManevi** [comment]
Have the same problem and found the solution [#138](https://github.com/matfish2/vue-tables/issues/138) hope it helps
