### ISSUE TITLE
Slot in thead?

### ISSUE THREAD

**Issue by eyylen** [matfish2/vue-tables-2#587]
- Vue.js version: 2.5.13

Is it possible to add a slot inside the thead, e.g. prependHeader or similar?
I would like to add an extra tr inside the thead with colspans to group my columns.

<img width="437" alt="2018-08-16" src="https://user-images.githubusercontent.com/37864214/44196835-4fe0a700-a13d-11e8-85a8-61159162763d.png">

**Comment by sanaani** [comment]
I could really use this one in my project.
