### ISSUE TITLE
pagination.edge nonfunctional, doesn't produce first/last page buttons.

### ISSUE THREAD

**Issue by Santboi** [matfish2/vue-tables-2#590]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

**Comment by valantonini** [comment]
I am having the same issue. Is this a bug or do I need additional configuration options? I can't find the rendering of first and last buttons in the code.

**Comment by JoeZ99** [comment]
same here. when I set, 
`paginaton: {chunk: 22, edge: true}` 
I got chunks of 22 items in pagination, but no "first" and "last" links
