### ISSUE TITLE
How insert background to scoped slot

### ISSUE THREAD

**Issue by riux** [matfish2/vue-tables-2#593]
how insert background to cell
                ``` <template slot="name" slot-scope="props" >
                            <div class="cover">
                               <p>{{props.row.name}}</p>
                            </div>
                        </template>```

**Comment by ixperiencenl** [comment]
I would do this with CSS via the rowClassCallback:
`rowClassCallback: function(row) {
                            return 'cssName';
                    }`
and set the background via CSS.
