### ISSUE TITLE
Template HTML not rendering inside table

### ISSUE THREAD

**Issue by BrianEstrada** [matfish2/vue-tables-2#6]
**- Vue.js version:** 2.0
**- consumed using:** WebKit
**- FULL error message (including stack trace):** [![Capture.png](https://s10.postimg.org/xqxe32gux/Capture.png)](https://postimg.org/image/qnpingbf9/)
**- relevant code:** http://pastebin.com/Vg3z8Z0k  
I'm not sure whats going on but for some reason the html inside the table isn't being rendered or processed.

**Comment by matfish2** [comment]
You are passing templates the way it is done on the VueJs 1 package.
Follow the instruction in the `Templates` section of the docs for THIS package.
