### ISSUE TITLE
Feature request to add tutorial on how to create a new custom theme.

### ISSUE THREAD

**Issue by Vad1mo** [matfish2/vue-tables-2#601]
I would like to create a custom theme to adapt it to my surrounding style. with custom search and pagination. So far I can see I need to create a new theme to change the styling and structuring. There have been already requests #538 and #440 however there is no tutorial or more documentation on that. I also would volunteer to test it.  

![image](https://user-images.githubusercontent.com/1492007/45907778-98a11500-bdf9-11e8-9933-f664713d96ae.png)

**Comment by dhornbein** [comment]
If someone could explain it to me I'd be happy to write the documentation. I'm too much of a novice to be able to figure it out on my own... :(

**Comment by JiriFurda** [comment]
bump

**Comment by laudaikinhdi** [comment]
Please help me custom theme

**Comment by zyuhel** [comment]
It it isn't a tutorial, but [this fiddle](https://jsfiddle.net/matfish2/jfa5t4sm/7564/) from #673 helped me a lot.
