### ISSUE TITLE
Add number row

### ISSUE THREAD

**Issue by MitjaC** [matfish2/vue-tables-2#603]
I have server side set up and it works, it shows data, sort and filter both work. Now I am showing usernames and their points. What I want to add is one additional row that would contain numbers from 1 to N, where N is number of users. In jquery datatables library there was a special function for that, as far as I know there isn't anything like that so I am looking for a solution to accomplish that

**Comment by molerat619** [comment]
You have to use `slots` and the `props.index` property to achieve that.

**Comment by dneykov** [comment]
Using `props.index` returns negative indexes. Can anyone help with that? using `v-server-table` with limit 20.
Indexes start from -19,-18 and so on...

Thanks.

**Comment by lastlink** [comment]
`props.index` doesn't seem to pull anything for me. even when trying in this fiddle https://jsfiddle.net/mwetu3ab/ inside the child row slot `test:{{props.index}}`
