### ISSUE TITLE
how to add two buttons in same column

### ISSUE THREAD

**Issue by Sakthi002** [matfish2/vue-tables-2#604]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:
![same](https://user-images.githubusercontent.com/35330401/45941017-ec7a4c80-bff9-11e8-9278-33b9f19e584f.PNG)

**Comment by matfish2** [comment]
Have you read the [Templates](https://github.com/matfish2/vue-tables-2#templates) section?

**Comment by Sakthi002** [comment]
can u give one example code for two buttons

**Comment by matfish2** [comment]
```vue
<v-client-table>
<template slot="actions" slot-scope="{ row }">
<button @click="edit(row.id)">Edit</button>
<button @click="erase(row.id)>Delete</button>
</template>
</v-client-table>
```

**Comment by Sakthi002** [comment]
tanq sir..,
