### ISSUE TITLE
Pagination showing error

### ISSUE THREAD

**Issue by Sakthi002** [matfish2/vue-tables-2#608]
![page12](https://user-images.githubusercontent.com/35330401/46017867-24ff5080-c0f6-11e8-84ed-c965cb97e2f5.PNG)
but i gave correct path.
i am getting this error
![log](https://user-images.githubusercontent.com/35330401/46008701-16f00680-c0db-11e8-84d5-0bc60275a212.PNG)
![page](https://user-images.githubusercontent.com/35330401/46010774-6c2f1680-c0e1-11e8-8e26-bddeba3b0715.PNG)
![page1](https://user-images.githubusercontent.com/35330401/46010781-705b3400-c0e1-11e8-9b8c-dc9c0115c3f0.PNG)

**Comment by gamma1210** [comment]
May I know how you solved this?
