### ISSUE TITLE
Daterangepicker for Date Filter Not Working

### ISSUE THREAD

**Issue by forddyce** [matfish2/vue-tables-2#61]
- Vue.js version: 2.1.8
- consumed using: (browserify/webpack/rollup) browserify
- FULL error message (including stack trace): no error, just nothing happen when I click the date filter
- relevant code:
```
var tableColumns = ['name', 'created_at', 'company_count', 'action']
var options = {
  pagination: {
    dropdown: true,
    chunk: 10
  },
  filterByColumn: true,
  texts: {
    limit: 'Records: '
  },
  dateColumns: ['created_at'],
  datepickerOptions: {
    showDropdowns: true
  },
  orderBy: {
    column: 'created_at',
    ascending: false
  },
  filterable: ['name', 'created_at'],
  sortable: ['name', 'created_at'],
  debounce: 1000,
  headings: {
    name: 'Name',
    created_at: 'Date Created',
    company_count: 'Total Companies'
  },
  skin: 'table table-vue table-striped table-bordered table-hover',
  templates: {
    action: function (h, row) {
      return <div class="btn-group">
        <show-link id={row.id} module="industry"></show-link>
        <edit-link id={row.id} module="industry"></edit-link>
        <delete-link id={row.id} module="industry" table={this.$refs.listTable}></delete-link>
      </div>
    }
  }
}
```
- steps for reproducing the issue:
Firebug didn't even show any error. And when I go to 

> lib/methods/init-date-filters.js

And try to:
```
that.opts.dateColumns.forEach(function(column) {
     el =  $(that.$el).find("#VueTables__" + column + "-filter");
     console.log(el); // try to find if el is the right one
     ..bla,bla,bla
}
```
It didn't even show in console.

And I make sure the daterangepicker is in right order, I tried to make a sample input elsewhere and the daterangepicker on that input works.

Any suggestion?

**Comment by forddyce** [comment]
[SOLVED] I can't put name as one of the column, now that's weird.

**Comment by fabriciofs** [comment]
@forddyce I have the same problem, what exactly did it do?

**Comment by vkumarsi1** [comment]
Still date field is not coming as filterable. please suggest to fix

**Comment by matfish2** [comment]
https://github.com/matfish2/vue-tables-2/issues/445#issuecomment-369975272
