### ISSUE TITLE
Abruptly stopped working

### ISSUE THREAD

**Issue by cotein** [matfish2/vue-tables-2#610]
First, sorry by my english.

My component is this:

<code>

    <div>
        <v-client-table
            ref="expirablelist"
            :columns="columns"
            :data="rows"
            :options="options"
        >

            <div slot="child_row" slot-scope="props">
                <span><strong>Comentario:</strong></span><span>{{props.row.comment}}</span>
            </div>

            
            <template slot="number" slot-scope="props">
                <div>{{props.index}}</div>
            </template>
        </v-client-table>
    </div>

<code>

import Multiselect from "vue-multiselect";
import busVue from "../../extras/eventBus.js";
import Collection from "collectionsjs";
import DateManipulation from '../../../js/extras/classes/DateManipulation';

export default {
    components: { Multiselect },
    props: ['api_token'],
    data() {
        return {
                columns: [
                    "number",
                    "name",
                    'apply_to',
                    'days_for_alarm',
                    "expire_at",
                    'time_to',
                    'status',
                    'edit',
                    'delete'
                ],
                rows: [],
                options: {
                    perPage: 15,
                    perPageValues: [10, 25, 50, 100],
                    headings: {
                        number: "N°",
                        name: "Vencimiento",
                        apply_to : 'Aplica a',
                        days_for_alarm: "Avisar a partir",
                        expire_at: "Vence el",
                        time_to : 'Falta',
                        status : 'Estado',
                        edit: "Editar",
                        delete: "Eliminar",
                    },
                /*  rowClassCallback(row) {
                    return (!row.valid)?'alert-danger':''; 
                }, */
                    templates: {
                        status: 'status-cell',
                        edit: 'button-edit-cell',
                        delete: 'button-trash-cell',
                    },
                    columnsClasses: {
                        number : 'text-center',
                        days_for_alarm : 'text-center',
                        expire_at : 'text-center',
                        time_to : 'text-center',
                        apply_to : 'text-left',
                        status : 'text-center',
                        edit : 'text-center',
                        delete : 'text-center',
                    },
                sorteable: ["number", 'name'],
                filterable: ["number", 'name']
            }
        };
    },
    methods: {
        getData() {
            let $vm = this;
            $vm.$http.get("/api/expirable/company").then(
                function(response) {
                    console.log(response);
                    $vm.rows = response.body;
                },

                function(response) {
                    console.log(response);
                }
            );
        }
    },
    computed: {},
    mounted() {
        let $vm = this;

        Vue.http.interceptors.push((request, next) => {
        request.headers.set("Authorization", "Bearer " + $vm.api_token);
        next();
        });

        $vm.getData();
    }
};

</code>

But now dosen't works anymore.
**TypeError: "_vm.props is undefined, can't access property "row" of it"**
Anybody help me, please?

**Comment by molerat619** [comment]
Please reformat your code so it is readable. It will be easier for people to help you.
