### ISSUE TITLE
ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by omayhemo** [matfish2/vue-tables-2#612]
- Vue.js version:
latest
- consumed using: (browserify/webpack/rollup)
parcel
- FULL error message (including stack trace):
ReferenceError: $ is not defined
    at before-destroy.js:25
    at Array.forEach (<anonymous>)
    at VueComponent.module.exports (before-destroy.js:24)
    at callHook (vue.runtime.esm.js:2917)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js:2696)
    at destroy (vue.runtime.esm.js:4174)
    at invokeDestroyHook (vue.runtime.esm.js:5739)
    at invokeDestroyHook (vue.runtime.esm.js:5744)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:6077)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js:2719)
- relevant code:
`<button slot="Edit" slot-scope="props" class="fa fa-edit" v-on:click="edit(props.row.Id)">EDIT</button>`

...

```
methods: {
      edit(id) {
        console.log("edit click: " + id)
        this.$router.push({ path: '/edit/' + id})
      }
    },
```

- steps for reproducing the issue:
Clicking the edit button causes vue-tables-2 to blow up.  Apparently you're using jQuery?

**Comment by omayhemo** [comment]
Only happens if I use a datecolumn.  Probably missing the date component.  Closing

**Comment by lucianobosco** [comment]
So in order to enable datepicker filter in a Vue project we have to import JQuery globally? Odd and ugly...

**Comment by matfish2** [comment]
@lucianobosco please keep it civil. I welcome any suggestions, but there is a way to pass constructive criticism without using this kind of language. 

To the matter at hand, including jquery+daterangepicker+moment, or any other heavy third-party plugin which is only sometimes used (such as axios), would have made the compiled package very large. I am sure there is a better solution, that doesn't require those packages to be present in the window scope, and you are welcome to suggest it below.
