### ISSUE TITLE
Add warning to documentation regarding saveState

### ISSUE THREAD

**Issue by molerat619** [matfish2/vue-tables-2#613]
When you enable saveState, it works great. But you have to be careful with future changes. 

For example, I added a new column with a filter to my existing table. But I could never see the filter - I assume, because saveState was active. Once I cleared that from my local storage, the filter was displayed.

I suggest to add a warning in the documentation, as this has been at least the second time that I have spent 30 minutes trying to find the issue with my table setup.

**Comment by events-jonas-chrisw** [comment]
broke lots of stuff for users here too.... things go awry if they already have a localstorage variable stored, and you change the filter structure of the table... :-(

**Comment by events-jonas-chrisw** [comment]
fixed it...

i now grab the version number from package.json and send that as a value to the name prop on the table. Works a treat.....
