### ISSUE TITLE
"row-click"-Event does not return the original data object representing that row

### ISSUE THREAD

**Issue by katebe** [matfish2/vue-tables-2#62]
- Vue.js version: 2.1.8 (vue-tables-2 version 0.2.77)
- consumed using: webpack
- relevant code: see commit https://github.com/matfish2/vue-tables-2/commit/13187833780694022760eec86b2dcd0b35e19d73
- steps for reproducing the issue:
  - create a row listener
  - change attributes of the row in the listener -> changes are not reflected in table

I think this problem comes from commit https://github.com/matfish2/vue-tables-2/commit/13187833780694022760eec86b2dcd0b35e19d73 by cloning the original data. Maybe you could store a reference to the original object in the clone and pass the original one to the listener?

BTW: Thanks for your great library :)

**Comment by forddyce** [comment]
I think VueJS version < 2 won't work with vue-tables-2? Shouldn't you use: https://github.com/matfish2/vue-tables ?

**Comment by katebe** [comment]
I edited my post... I have entered the version of vue-tables-2 I am using instead of the VueJS version. Sorry

**Comment by forddyce** [comment]
Did you use the server component one? How about `refresh` method, did it work? @katebe

**Comment by katebe** [comment]
I am using the client table. If I change my bound data inside my Vue component, the table updates directly. But not with the row listener. I am using a workaround now where I look up the correct entry in my bound data by an ID I have on each row and then edit that object.

**Comment by forddyce** [comment]
@katebe would love to see some code.

**Comment by matfish2** [comment]
Unfortunately I must clone the data in order to avoid changing the original data set when the user filters the data. The side-effect is that you cannot change to row directly from the callback. A possible solution would be to hunt down the original row and pass it to the callback instead of the cloned one. However, this solution requires a unique id for each row.

**Comment by katebe** [comment]
How about this:

Change the cloning part inside "computed/filtered-data.js" to:
```javascript
var data = clone(this.tableData);
for (var i = 0; i < this.tableData.length; i++) {
  data[i].$originalData = this.tableData[i];
}
```
And then inside "template/rows.jsx" modify the event handler to `on-click={that.rowWasClicked.bind(that, row.$originalData)}`

Maybe there are still more method calls (like the rowClassCallback) where you would pass the original object?!

--

@forddyce
I made an simple example:
```javascript
<template>
  <div>
    <v-client-table :data="data" :columns="columns" @row-click="changeData"></v-client-table>
  </div>
</template>
<script lang="babel">
  export default {
    data: function () {
      return {
        data: [{name: 'Test'}],
        columns: ['name']
      }
    },
    methods: {
      changeData: function (row) {
        row.name = 'Test changed' // expected to work, but does not
        // this.data[0].name = 'Test changed' // works
      }
    }
  }
</script>
```

**Comment by matfish2** [comment]
@katebe, looping through all the data on every single re-evaluation seems wasteful, when it is only necessary once a row was clicked.
