### ISSUE TITLE
What if data json has a dot in key naming?

### ISSUE THREAD

**Issue by ihoro** [matfish2/vue-tables-2#627]
Hello,

I have data like `[ { ‘Dim.A’: 1, ‘Dim.B’: 2 }, { ‘Dim.A’: 10, ‘Dim.B’: 20}, …]`. I’ve tried to refer it as `columns: [ ‘Dim.A’, ‘Dim.B’ ]`, but it doesn’t work, and it looks obvious due to it’s a notation for nested objects.

Is there support of such cases?

**Comment by gitBC** [comment]
Hello Ihoro, I also use names along these lines. You'll need to use the scoped slots to get them into place.

Everywhere you refer to them you will need to encapsulate them in quotes, including in places like columns, sortable, columnClasses.


**Ultimately, this was the key discovery for me:**
<span slot="Dim.A" slot-scope="props">{{ props.row['Dim.A'] }}</span>

**Comment by gitBC** [comment]
I'm finding that this does however currently [cause a problem](#630) with daterangepicker via the dateColumns option as of v1.4.70

**Comment by ihoro** [comment]
Hi gitBC,

Thanks, with slots it works. But yes, it would be better to have this ability without special dancing :) Thanks for your attention!

**Comment by matfish2** [comment]
Problem is that using dot notation has a special meaning, namely nested column data.
