### ISSUE TITLE
Vuetable display wrongly when data has html tag

### ISSUE THREAD

**Issue by vicnoob** [matfish2/vue-tables-2#628]
- Vue.js version:  Vue 2.5
- consumed using: webpack

When data in table has html, its display Unescaped html

Behavior:

![image](https://user-images.githubusercontent.com/17595317/48458724-11b95900-e7fa-11e8-9dd7-70c5926ca8b4.png)

Expect:

Display: ` <strong> Fullname2 </strong>`

**Comment by matfish2** [comment]
As documented this is expected behavior. Use templates to render HTML in your cell
