### ISSUE TITLE
ServerTable: Cancel pending request when another is initiated

### ISSUE THREAD

**Issue by AuditeMarlow** [matfish2/vue-tables-2#633]
I'm using the ServerTable component in combination with Axios, and would very much like to cancel any pending requests when a new one is initiated. Following the docs, I can override how requests are handled using the `requestFunction` data prop. Following the [Axios docs](https://github.com/axios/axios#cancellation), I'm setting up a cancel token with Axios as followed:

```javascript
requestFunction(data) {
    const CancelToken = axios.CancelToken
    const source = CancelToken.source()

    return axios.get(this.url, {
        cancelToken: source.token,
        params: data,
    }).catch(function (thrown) {
        if (axios.isCancel(thrown)) {
            console.log('Request canceled', thrown.message)
        } else {
            this.dispatch('error', thrown)
        }
    }.bind(this))
}
```

However, it is lost upon me how to approach actually cancelling any pending requests. Can anyone point me in the right direction?

**Comment by TheStoof** [comment]
https://github.com/axios/axios#cancellation

```
// cancel the request (the message parameter is optional)
source.cancel('Operation canceled by the user.');
```

**Comment by Milkker** [comment]
Thanks for @AuditeMarlow 's idea, I met the same problem too.
I resolve it by create cancelToken and add it to table, every request start check the cancelToken, if exists I will cancel it.
```javascript
requestFunction: function (data) {
  var table = this;

  if (table.cancel)
    table.cancel.cancel();

  table.cancel = axios.CancelToken.source();

  return axios.get(this.url, {
    cancelToken: table.cancel.token,
    params: data
  }).then(function (response) {
    //to avoid canceled request let the table lock in loading...
    table.loading = false;
    return response;
  }).catch(function (e) {
    if (axios.isCancel(e)) {
      console.log('Request canceled', e.message)
    } else {
      this.dispatch('error', e)
    }
  }.bind(this));
}
```

But If vue-table-2 can provide draw counter, let data always follow the max draw response, it would be easier.
Just like [jquery datatable's draw parameter](https://datatables.net/manual/server-side)
@matfish2

**Comment by Imboga** [comment]
Hi! Any updates about this? Looks interesting when "Next" pagination button is clicked several times

**Comment by matfish2** [comment]
Added axios auto cancel for pending requests when new request is sent to private repo

**Comment by matfish2** [comment]
Added to private repo: `useDrawCounter` option

**Comment by Imboga** [comment]
> Added to private repo: axios auto cancel for previously pending requests when new request is sent

Will this be merged in next release?
