### ISSUE TITLE
Unable to add a class to the selected row

### ISSUE THREAD

**Issue by jkwilloch** [matfish2/vue-tables-2#636]
- Vue.js version: 2.5.16

I have been having a lot of issues with getting the **rowClassCallback** method, in combination with the **row-click** event to dynamically change the class of a row element.
I have looked through issue #371 #598 or #236 for help, but still can't get it to work.

What i am trying to accomplish is to select a row, and have it's class change so i can set a background-color for the currently selected row. 
I am able to use the **rowClassCallback** to set the row classes when the table is first created, based on an variable on the row object. 
I am also able to use the **row-click** event to change the same variable from **true** to **false** (or the other way around). But this does not initiate a class-change on the row, even when calling the **rowClassCallback** function with the new row.

This is the code i have. I am using **Vue-Property-Decorator** and **Typescript**. So the syntax might be slightly off from the norm. 

```html
<v-client-table
        v-if="myObjectList.length > 0 && showObjectList" // Hides the table if there is no data present 
        v-on:row-click="rowSelected"
        :data="myObjectList" 
        :columns="columns"
        :options="tableOptions">
</v-client-table>
```
 ```ts
columns = [ ... ] 
tableOptions = {
        sortable: [],
        perPage: 5,
        perPageValues: [],
        filterable: false,
        pagination: { 
            nav: 'scroll'
        },
        uniqueId: 'customRowId', // A unique id-variable on the row object
        rowClassCallback(row: myRowObject){
            if(row.active)
            return 'activeRow'
            else
            return ''
        }
    };


rowSelected(emitObject: TableEmitObject){
        emitObject.row.active = !emitObject.row.active; // Simply toggles the variable, for testing.
        this.tableOptions.rowClassCallback(emitObject.row);
}
```
TableEmitObject is simply an interface to allow Typescript to know what objects i'm working with.
```ts
import { MyRowObject } from '@/interfaces';
export interface TableEmitObject{
    event: string,
    row: MyRowObject
}
```

```css
.activeRow {
  background-color: black !important;
}
```

With this setup, when i click a row, i can go into **vue-dev-tools** and see that the **active** variable changes inside the **computed/filteredData** object for that row. The constructed DOM element does however not change, and no new class gets added to the selected row.

**Comment by ETSmukesh** [comment]
I'me also facing the same issue, anybody helps me out.

**Comment by sahilxjain** [comment]
You can use key on v-client-table and update the key
