### ISSUE TITLE
Feature Request: filter icon in table header

### ISSUE THREAD

**Issue by ivar-os** [matfish2/vue-tables-2#638]
- Vue.js version: 2.5
- consumed using: (browserify/webpack/rollup): Webpack
- FULL error message (including stack trace): no error -> Feature Request
- relevant code:
- steps for reproducing the issue: see screenshot

Thanks for this great software. We have a feature request: allow filtering on a column level, where the filter is positioned in the header of the table (compare sorting). See screenshot. Thanks in advance.

![screenshot 2018-11-29 16 46 13](https://user-images.githubusercontent.com/44036196/49233652-b8a31500-f3f6-11e8-94d1-170482dc8722.png)

**Comment by gitBC** [comment]
@ivar-os If you're just looking to provide a fancy icon, or even attach an event to it there are two options for this. 

1. Scoped slot
```
//note this should be based on your column name h__{column} and overrides the options.headings value
      <span slot="h__sourceList">
          Source List <i class="fas fa-filter" @click="someFunction"></i>
      </span>
```
2. JSX compiled html as is mentioned in the headings section of the docs
