### ISSUE TITLE
Class Bind to a scoped slot for matfish2/vue-tables-2

### ISSUE THREAD

**Issue by catheibasilio** [matfish2/vue-tables-2#641]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

My goal is to add a condition if that `Math.sign(props.row.unrealisedPL ) < 0)` then change background color of that TD column via a class.

here's my code snippet 
```javascript
      <v-client-table
            v-if="tableData.length > 0 && tableData"
            :data="tableData"
            :columns="columns"
            :options="options"
            :columnsClasses="columnsClasses"
          >
          <template slot="mfpl" scope="props">
             <div  :class="{'text-danger': (Math.sign(props.row.unrealisedPL ) < 0),
              'text-success': (Math.sign(props.row.unrealisedPL ) > 0)}">
                {{ props.row.unrealisedPL  }}
            </div>
          </template>
          </v-client-table>```

but this doesn't work.  please help

**Comment by gitBC** [comment]
There shouldn't be a need to pass the columsClasses prop like that.

To style my columns I use a scoped slot like so:

In your case...
//Changing the background color of mfpl slot but then displaying  props.row.unrealisedPL
//If you want the background of unrealisedPL  to change, change the name in slot=
                <span slot="mfpl" slot-scope="props"
                      :class="getNegativeValueClass(props.row.unrealisedPL )">
                    {{ props.row.unrealisedPL }}
                </span>
methods() {
  getNegativeValueClass(value) 
  {
    return ( Math.sign(value< 0) ) ? 'text-danger' : 'text-success';
  }
}
