### ISSUE TITLE
pagination: { edge: false } doesn't hide buttons

### ISSUE THREAD

**Issue by skironDotNet** [matfish2/vue-tables-2#642]
pagination.edge | Boolean | Show 'First' and 'Last' buttons | pagination: { edge: false }

added `pagination: { edge: false }` and 'First' and 'Last' buttons are still visible
tried this property in `options` and outside `options` as per https://github.com/matfish2/vue-tables-2/issues/499 and no difference

**Comment by gitBC** [comment]
I also tested and couldnt seem to get this to work. I do notice however, that the arrows get a disabled class. You should be able to target these via css.
```
.VuePagination__pagination-item-prev-chunk.disabled,
.VuePagination__pagination-item-next-chunk.disabled {
    display: none;
}
```

**Comment by MrJuanVilla** [comment]
@gitBC @skironDotNet  You might be misunderstanding, 'First' and 'Last' buttons are not the same as double arrows '<<' and '>>' which is next and prev chunk.
First and Last are buttons with literally the word 'First' or 'Last', in this case `pagination: { edge: false }` is the option that disable those once.

Double arrows show when `pagination: { nav: 'fixed' }`, and works along with 'pagination: { chunk: 10 }' and is for navigation between pages. If you have 30 pages, your bottom bar will show **page numbers** ( ie. 1,2,3,4.... { chunkSize } ) and when you click double arrows it will get you do the next set of **pages** ( ie. 11,12,13...{ chunkSize *2 } ) but this is not the 'Last' page you could get.

The only way to remove the double arrows, you need to change to `pagination: { nav: 'scroll' }`.
