### ISSUE TITLE
columnsDropdown is not working if custom filters are present

### ISSUE THREAD

**Issue by sanugstanly** [matfish2/vue-tables-2#644]
`columnsDropdown` is working perfect if there is no custom filters are present 

But if there is some custom filters are present `columnsDropdown` not working as expected

Error: I have some fields with dynamic dropdown filters as custom filters, while toggling the columns in dropdown some of the filters are missing which are actually selected columns. Also its misplacing the filters to some other columns as well

Am attaching screenshots below

This screenshot is before adding column visibility

<img width="1403" alt="screen shot 2018-12-16 at 8 52 01 pm" src="https://user-images.githubusercontent.com/14848762/50057009-ca661580-0175-11e9-8053-3cbd12ad806a.png">

After adding column visibility
<img width="1456" alt="screen shot 2018-12-16 at 8 52 21 pm" src="https://user-images.githubusercontent.com/14848762/50057023-ea95d480-0175-11e9-861b-43dca2590198.png">

Please Help

**Comment by matfish2** [comment]
Fixed
