### ISSUE TITLE
Child row update data

### ISSUE THREAD

**Issue by Samtronic** [matfish2/vue-tables-2#645]
Hi !
I need when open child_row, do a http request and update child row data with response. I need to update all object.  What is the best way to proceed to return the information in the child row when you open a child row.

Thanks Steven

**Comment by Samtronic** [comment]
I find a other solution with a button in action with metod 'this.$refs.table.toggleChildRow(row.id)'.
But it is possible to hide the child row toggler column.

Thanks Steven

**Comment by matfish2** [comment]
set `showChildRowToggler` to `false`
