### ISSUE TITLE
columnsDropdown - jumps

### ISSUE THREAD

**Issue by litan1106** [matfish2/vue-tables-2#648]
- Vue.js version: 2.5.17
- consumed using: webpack 4
- FULL error message (including stack trace): no error
- relevant code: https://jsfiddle.net/39xyzgm7/
- steps for reproducing the issue:
1. create a client table with columnsDropdown: true
2. place the vue table in the bottom of the page.

when the vue table is in the bottom of the page, it jumps when you click an dropdown item.

**Comment by GitOkaKaz** [comment]
i also want to solve this issue. is someone capable of helping us with this?

**Comment by MortallyRoasted** [comment]
Change the dropdown `hrefs` to `#/` instead of `#`

**Comment by GitOkaKaz** [comment]
thanks, that works!

**Comment by jotefer** [comment]
For me it worked to change `href` attribute from `#` to `javascript:void(0)`
