### ISSUE TITLE
thead fixed

### ISSUE THREAD

**Issue by andresRiosC** [matfish2/vue-tables-2#651]
- Vue.js version: 2.5.21
- consumed using: webpack (laravel mix)
- FULL error message (including stack trace):  n/a
- relevant code: n/a

Good afternoon, I have the need to leave the thead fixed without damaging the functionality of the filters.

![image](https://user-images.githubusercontent.com/15206514/50710083-fb7c8c00-1037-11e9-865c-4670d4540470.png)

**Comment by gitBC** [comment]
Here is an option I used: https://medium.com/@vembarrajan/html-css-tricks-scroll-able-table-body-tbody-d23182ae0fbc

**Comment by matfish2** [comment]
I prefer @gitBC solution to cumbersome meddling with the HTML

**Comment by matfish2** [comment]
added option stickyHeader to private repo
