### ISSUE TITLE
Clearing all column filters and reload data

### ISSUE THREAD

**Issue by kife-design** [matfish2/vue-tables-2#652]
Hi,

I have a table that has column filtering. The filtering is done server-side and is using vuex to manage the data.

Is there an easy way to easy clear all column filters and reload the data? I searched for it in the docs but couldnt find anything.

**Comment by TheStoof** [comment]
There doesn't seem to be an API for it, or at least not an easy function to clear all filters. However, you can do the following:

```
for (var key in this.$refs['table'].query) {
    this.$refs['table'].query[key] = '';
}
this.$refs['table'].refresh();
```

**Comment by mtereschenko** [comment]
This solution works for me. 

```
<button @click="resetFilter"> Clear </button>

resetFilter() {
                let values = {};
                for (const column of this.options.filterable) {
                    values[column] = null
                }
                this.$refs.vtable.setFilter(values);
                this.$nextTick(() => {
                    this.$refs.vtable.refresh()
                })
            },
```
