### ISSUE TITLE
headingsTooltips in options  no effect

### ISSUE THREAD

**Issue by Sakthi002** [matfish2/vue-tables-2#655]
this.options = {

				headings: {

					category: 'Category',

					subject : 'Subject',

					sender_mail: 'Sender mail',

					reciever_mail: 'Reciever mail',

					referee_id : 'Referee id',

					referee_type : 'Referee type',

					created_at: 'Created At',

					action: 'Action'
				},

				headingTooltips:{
				    category:'Expanded Title'
				},

**Comment by wonkenstein** [comment]
Did you fix this?

I had the same problem too and then realised in options it should be `headingsTooltips` not `headingTooltips` that you have in your options code.

Changing that should bring up tooltips on the headings from the title attribute.

```
this.options = {
    headings: {
	category: 'Category',
	subject : 'Subject',
	sender_mail: 'Sender mail',
	receiver_mail: 'Receiver mail',
	referee_id : 'Referee id',
	referee_type : 'Referee type',
	created_at: 'Created At',
	action: 'Action'
    },
    headingsTooltips:{
        category:'Expanded Title'
},
```
