### ISSUE TITLE
webpack build failed: can't resolve math.random in 'randomatic' module

### ISSUE THREAD

**Issue by samteb** [matfish2/vue-tables-2#656]
- Vue.js version: 2.5
- consumed using: webpack 2.6
- FULL error message (including stack trace):

```
ERROR in ./~/randomatic/index.js
Module not found: Error: Can't resolve 'math-random' in 'C:\Users\97254\Documents\Projects\analytics-dashboard\node_modules\randomatic'
 @ ./~/randomatic/index.js 12:17-39
 @ ./~/fill-range/index.js
 @ ./~/expand-range/index.js
 @ ./~/braces/index.js
 @ ./~/micromatch/lib/utils.js
 @ ./~/micromatch/index.js
 @ ./~/filter-array/index.js
 @ ./~/array-intersection/index.js
 @ ./~/vue-tables-2/compiled/methods/has-date-filters.js
 @ ./~/vue-tables-2/compiled/mixins/methods.js
 @ ./~/vue-tables-2/compiled/table.js
 @ ./~/vue-tables-2/compiled/v-client-table.js
 @ ./~/vue-tables-2/compiled/index.js
 @ ./src/main.js

  Build failed with errors.
```

- relevant code:

```
import {ClientTable} from vue-tables-2
Vue.use(ClientTable)
```

- steps for reproducing the issue:

My project works well as expected until I try to import vue-tables-2 and use it as a plugin. My build fails because of 'randomatic'.
I am trying to fix it for 5hours now. Please help me.

**Comment by yinteman** [comment]
because  the dependency package  --"math-random@1.0.1"   has error. you can update "math-random".
add the following codes  to the  package.json.
`"resolutions": 
    "math-random": "1.0.4"
  }`

**Comment by samteb** [comment]
I am sorry. This issue was resolved in fact. Thanks.

**Comment by yinteman** [comment]
could you  please tell me the method you use ?
