### ISSUE TITLE
VueServerTable Handle 4xx and 5xx errors

### ISSUE THREAD

**Issue by TomHart** [matfish2/vue-tables-2#661]
Would it be possible for the vue-server-table to be able to handle 4xx and 5xx errors, maybe letting the user define messages by response code?

Alternatively, is there a way to set the tables message? So I could do something like 

                    requestFunction: function (data) {
                        return axios.get(this.url, {
                            params: data
                        }).catch(function (e) {
                            switch (e.request.status) {
                                case 403:
                                    this.$refs['myTable'].showMessage('Sorry, this is forbidden');
                                    break;
                                default:
                                    this.dispatch('error', e);
                                    break;
                            }
                        }.bind(this));
                    },

**Comment by TheStoof** [comment]
Sounds like a nice feature request. I noticed that you can define options.texts.loading for a loading message, so perhaps it's best to allow there to be a loading/error message template or scope that way it can be handled outside the logic of Vue Tables. The dispatch here can simply pass the error object up where you can handle the complex logic by listening to the 'error' channel in the Vue Tables 2 bus.

**Comment by TheStoof** [comment]
OK, so this is a **hack** in the sense that it's overloading the 'loading' text. I think there should be an error state to the table that is displayed when loading fails for any reason.

`
export default {
    data: () => ({
        columns: [],
        options: {
            texts: {
                loading: 'Loading...'
            }
        }
    }),
    mounted() {
        Event.$on('vue-tables.error', (e) => {
            this.options.texts.loading = 'An error!';
        });
        Event.$on('vue-tables.loading', (e) => {
            this.options.texts.loading = 'Loading...';
        });
    }
}
`

**Comment by TheStoof** [comment]
I've been trying to add an error state, but the design seems centered around keeping data around until it is replaced. When initially loading, my changes can display a custom error message. However, when data is present, there has to be a decision to drop the existing data and display the error inline or don't display it at all.

Alternatively, I would recommend using the vue-tables.error and vue-tables.loading events and use something like SWAL2 to tell the user that data is being loaded or when a request has errored out.

**Comment by matfish2** [comment]
Added to private repo
