### ISSUE TITLE
Highlight not working in Scoped slots 

### ISSUE THREAD

**Issue by luchorengo** [matfish2/vue-tables-2#662]
Highlight is not working when using scoped slots. Is there a native way to detect the matched text and add the ```<b></b>``` tag?

```
<div slot="dni" slot-scope="props">
        {{ props.row.dni == null ? '' : props.row.dni }}
</div>
```

**Comment by matfish2** [comment]
scoped slots are presentational only, which means they cannot be searched directly on the dataset. This can still theoretically be implemented by rendering the slot during search, but I think it might prove rather heavy on performance. I might add it as an additional `includeSlotsInHighlight` option.
