### ISSUE TITLE
beforeSearch slot

### ISSUE THREAD

**Issue by valantonini** [matfish2/vue-tables-2#667]
- Vue.js version: 2.6.1
- consumed using: webpack
- FULL error message (including stack trace):
- relevant code: #659 
- steps for reproducing the issue: n/a

A beforeSearch slot would be helpful for customisation. I have made the slot in pull request #659. Travis CI build appears to have failed but I don't believe it was due to the changes in the pull request.

**Comment by matfish2** [comment]
Merged. Thanks
