### ISSUE TITLE
perPage option not working

### ISSUE THREAD

**Issue by sebasijan** [matfish2/vue-tables-2#669]
Please check the [sandbox example](https://jsfiddle.net/matfish2/js4bmdbL/) and try changing the `perPage` option, where I would expect the number of items displayed to change accordingly, but nothing appears to happen.

**Comment by matfish2** [comment]
Works

**Comment by Bhavna2207** [comment]
per page option is not working. Whenever the component is mounted it's displaying all the records on the same page.
But whenever the next page is clicked it's taking the per page value and showing that many records on the page.
