### ISSUE TITLE
Feature Request: Custom Sorting Functions

### ISSUE THREAD

**Issue by kelchm** [matfish2/vue-tables-2#67]
It would be great to be able to provide a custom compare function for implementing custom sorting logic on a column.

**Comment by matfish2** [comment]
Can you give an example of custom sorting logic?

**Comment by kelchm** [comment]
@matfish2 I don't have an example offhand, but this is very useful when dealing with sorting complex content. For example, imagine I wanted to allow the sorting of a sparkline (comprised of an array of values) by the average value or the most recent value?

Essentially this would be a hook by which you can provide a function that compares two rows. Griddle has a nice implementation of this that has [two method signatures](https://github.com/GriddleGriddle/Griddle/issues/142#issuecomment-267537931).
