### ISSUE TITLE
columnsDropdown not emitting event on change

### ISSUE THREAD

**Issue by p0psicles** [matfish2/vue-tables-2#671]
- Vue.js version: 2.5.22
- consumed using: (browserify/webpack/rollup) webpack: 4.29.3
- FULL error message (including stack trace): NA
- relevant code: NA
- steps for reproducing the issue: NA

In my use case I have a nested v-client-table structure. Like:

```
<v-client-table ref="table-0" level="1">
    <v-client-table ref="table-0-0" level="2">
    </<v-client-table>
    <v-client-table ref="table-0-1" level="2">
</v-client-table>

<v-client-table ref="table-1" level="1">
    <v-client-table ref="table-1-0" level="2">
    </<v-client-table>
    <v-client-table ref="table-1-1" level="2">
</v-client-table>
```

What i'm trying to accomplish is that when in one table in level 2 i'm using the `columnsDropdown` to display/hide columns. It should also apply that to the other tables in level 2.

I've created something for this using emit/on-sorting for the soring part. And used the method setSorting with $ref to apply to sorting to all "sub" tables.

I'd like to also apply something like this on the columnsDropdown. But I see there arent any events emitted when I change the columnsDropdown value.

Could an on-change/update event be added for this? And also a method added like: `setColumnsDropdown()`
Or is there another solution that could help me with me use case?

**Comment by p0psicles** [comment]
@matfish2 your still invested?

**Comment by matfish2** [comment]
Do you mean an event for when the dropdown is toggled, or for when individual columns are toggled inside the dropdown?

**Comment by p0psicles** [comment]
No idea. My question was from more then half a year ago. In the mean time I've added all the features I needed. You can check if your interested in my fork.

https://github.com/xaksis/vue-good-table/compare/master...p0psicles:master

If you like anything I can help with PR

**Comment by matfish2** [comment]
Nice fork, only not of this repo... :)

**Comment by p0psicles** [comment]
Haha whoops
