### ISSUE TITLE
add class to columnsDropdown button 

### ISSUE THREAD

**Issue by luchorengo** [matfish2/vue-tables-2#672]
Is it possible to add an extra class such "btn-sm" to columnsDropdown button? Also I will need to change the "btn-secondary" class to "btn-primary".
Is there a scoped slot for this that I'm missing?
I did not find any documentation regarding how to customize this button so any help will be appreciated.

Thanks in advance

**Comment by matfish2** [comment]
In the (hopefully) near future I plan to make the components modular and controllable. For the time being, you can write some CSS to style it. Unfortunately, I can't add an option to configure every single class as this will bloat the options to monstrous proportions and will still not allow full-grained control over the UI.
