### ISSUE TITLE
Correct way to pass custom theme

### ISSUE THREAD

**Issue by AngryElephant** [matfish2/vue-tables-2#673]
- Vue.js version: 2
- consumed using: (browserify/webpack/rollup) Webpack
- FULL error message (including stack trace): theme is no a function

I was browsing the issue and a lot of people are asking how to use a custom theme but the issues are closed without proper answer.

As recommended i used one of the template boilerplate from the theme folder.

then i import it 

`var bootstrap4Theme = require('./../config/bootstrap4-theme');
`
and i pass it to the global like this  

`Vue.use(ServerTable, {skin:''}, false, bootstrap4Theme, 'footerPagination');
`
This is not working.

What is the proper way to pass a custom theme ?

And btw the option 'skin' is not working. 

Thank you.

**Comment by matfish2** [comment]
https://jsfiddle.net/matfish2/jfa5t4sm/7564/
