### ISSUE TITLE
Maximum call stack size exceeded with dropdown pagination

### ISSUE THREAD

**Issue by ayhanyunt12** [matfish2/vue-tables-2#675]
- Vue.js version: 2.5.2
- consumed using: webpack
- FULL error message (including stack trace): 
![image](https://user-images.githubusercontent.com/34600087/53730077-ee3d1b80-3e87-11e9-877b-449c6173762c.png)

- relevant code: pagination: {dropdown: true},
- steps for reproducing the issue: I have data with count is over 2.5 million and I want do display pagination as dropdown with perPage value is 25. When I do that I get the related error, is there a way to prevent that or make dropdown lazy loading?

**Comment by matfish2** [comment]
Are you using server or client component?

**Comment by matfish2** [comment]
As this requires - to my understanding - a javascript enhanced select, it is related to the broader #738, which once accomplished should allow swapping UI elements while maintaining functionality.

**Comment by matfish2** [comment]
https://matanya.gitbook.io/vue-tables-2/custom-template-version-2
