### ISSUE TITLE
Server side not respecting axios default options

### ISSUE THREAD

**Issue by ixperiencenl** [matfish2/vue-tables-2#677]
- Vue.js version: 2.6.8
- consumed using: npm webpack
- FULL error message (including stack trace):
Access to XMLHttpRequest at 'http://testdomain.local/data?query=&limit=10&ascending=1&page=1&byColumn=0' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I use Axios as my http library. I load it in using: axios = require('axios');
Right after that, I set the following headers:
``
axios.defaults.headers.common['Authorization'] = 'Bearer ' + APIKEY;
axios.defaults.headers.common['Access-Control-Allow-Origin'] = '*';
``

Using requests outside vue-tables-2 works fine, and the data is being retrieved.
But it looks like vue-tables-2 doesn't respect the default axios settings and makes a new axios instance with empty settings.

When I set the following:
``
requestFunction: function(data) {
            return axios.get(this.url, { 
            params: data, 
            withCredentials: true, 
            headers: {
                'Access-Control-Allow-Origin': '*',
                ' Access-Control-Allow-Credentials' : true <--- see the space? When I remove the space here, I get an error that credentials isn't set?!
            } 
            }).catch(function (e) {
            this.dispatch('error', e);
            }.bind(this))
        },
``

I get the following: 
`` Uncaught (in promise) TypeError: Cannot read property 'data' of undefined ``

Which looks like there's no data prop being passed. But that is not the main issue here. I just want the default axios settings being respected.

Please help me out on this, it causes a big headache.
Big thanks for your repo!

**Comment by matfish2** [comment]
The package doesn't use its own `axios` import, so it entirely relies on the instance available in the window scope, with its default headers and all. I will need to explore and see what the issue might be.

**Comment by ixperiencenl** [comment]
This has something to do with Axios global settings and also Laravel needs to be set correctly to accept the requests.

```axios.defaults.headers["Access-Control-Allow-Origin"] = "*";
    axios.defaults.headers["Cache-Control"] = "max-age=1440";
    axios.defaults.params = {};```

So for now you may close this.
