### ISSUE TITLE
How to get server-side files by composer ?

### ISSUE THREAD

**Issue by imami** [matfish2/vue-tables-2#678]
I get the front-end package for vuejs by `npm install vue-tables-2`,
but what about back-end ?
Can I get `EloquentVueTables.php` and `VueTablesInterface.php` as a package via composer ?

**Comment by AuditeMarlow** [comment]
The documentation provides an example of how to achieve similar results as you would with a client side table. You will have to write your server side implementation yourself.

**Comment by matfish2** [comment]
Or simply copy EloquentVueTables to your project and you have a good starting point
