### ISSUE TITLE
Repalce array-intersection dependency to account for security issue

### ISSUE THREAD

**Issue by jblotus** [matfish2/vue-tables-2#684]
https://nodesecurity.io/advisories/786   

Running an audit, on this dependency chain:  vue-tables-2 > array-intersection > filter-array > micromatch > braces

It looks like the filter-array maintainer does not wish to update that package to use a newer version of micromatch (which depends on the affected "braces" package).

https://github.com/jonschlinkert/filter-array/issues/4

Would it be possible to substitute array-intersection with a different package?

**Comment by matfish2** [comment]
changed intersection package
