### ISSUE TITLE
SBA registered vue component error rendering

### ISSUE THREAD

**Issue by cristian-balan** [matfish2/vue-tables-2#686]
Hello matfish2,
I need your help for a particular issue.
I have a Vue.js component "App" with "vue-table-2". The "App" works fine into a Spring boot application.
But if I try to register the component to a SpringBootAdmin from de.codecentric (version 2.1.3), the rendering doesn't work anymore, the problem is a conflicts with "vue-table-2". 
If I remove the "import {ClientTable} from 'vue-tables-2'" the App can register itself as view to the SBA and works fine, but of course without the vue table.

Do you have any ideea where could be the problem ?
Thank you & Best regards, 
Cristian

- Vue.js version: 3.4.0
- consumed using: (browserify/webpack/rollup)

- FULL error message (including stack trace):
TypeError: t is undefined vue.runtime.esm.js:5046
use VueJS
e906 index.js:30
    e906 viewRegistry.js:38

- relevant code: here just the relevant code part of my "main.js"
```
import {ClientTable} from 'vue-tables-2';
Vue.use(ClientTable);
SBA.use({
  install({viewRegistry}) {
    viewRegistry.addView({
      name: 'app',  //<1>
      path: '/app', //<2>
      component: app, //<3>
      label: 'App', //<4>
      order: 1000, //<5>
    }); 
  }
});
```

**Comment by matfish2** [comment]
Sorry, I'm unfamiliar with SBA. Maybe someone here can help?
