### ISSUE TITLE
ServerTable: Error in created hook: "TypeError: this.getData(...).then is not a function"

### ISSUE THREAD

**Issue by toudidel** [matfish2/vue-tables-2#687]
- Vue.js version: 2.6.10

```
    <v-server-table :columns="columns" :options="options">
      <template slot="action" slot-scope="props">
        <div>
          <b-btn variant="outline-info mr-2" class="btn-xs" @click.prevent="edit(props.row)">edit</b-btn>
          <b-btn variant="outline-danger" class="btn-xs" @click.prevent="remove(props.row)">remove</b-btn>
        </div>
      </template>
    </v-server-table>
```

I have problem with ServerTable and requestFunction providing some data.
I've received ann error:

```
[Vue warn]: Error in created hook: "TypeError: this.getData(...).then is not a function"
found in

---> <ServerTable>
      <HelloWorld> at src/components/HelloWorld.vue
        <App> at src/App.vue
          <Root>
warn @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620
```

requestFunction gets the data from simple [service](https://github.com/toudidel/vuetable/blob/master/src/api/my.service.js) which mocks the data:
`
requestFunction: function(data) {
          return MyService.getAll()
        },
`

MyService:
```
export default {
    getAll() {
        return {
            data: [
                {
                    "id": 1,
                    "name": "foo",
                },
                {
                    "id": 1,
                    "name": "bar",
                }],
            count: 2
        }
    }
}
```

To reproduce bug I make small demo application: https://github.com/toudidel/vuetable

**Comment by matfish2** [comment]
Thing is getData always expects a response from `axios/jquery/vue-resource` which all return promises. So if you change your service to return promise, rather than plain array, it should be fine. Though I am not sure entirely sure why you need to mock server.

**Comment by jauharfuadi54** [comment]
> * Vue.js version: 2.6.10
> 
> ```
>     <v-server-table :columns="columns" :options="options">
>       <template slot="action" slot-scope="props">
>         <div>
>           <b-btn variant="outline-info mr-2" class="btn-xs" @click.prevent="edit(props.row)">edit</b-btn>
>           <b-btn variant="outline-danger" class="btn-xs" @click.prevent="remove(props.row)">remove</b-btn>
>         </div>
>       </template>
>     </v-server-table>
> ```
> 
> I have problem with ServerTable and requestFunction providing some data.
> I've received ann error:
> 
> ```
> [Vue warn]: Error in created hook: "TypeError: this.getData(...).then is not a function"
> found in
> 
> ---> <ServerTable>
>       <HelloWorld> at src/components/HelloWorld.vue
>         <App> at src/App.vue
>           <Root>
> warn @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620
> ```
> 
> requestFunction gets the data from simple [service](https://github.com/toudidel/vuetable/blob/master/src/api/my.service.js) which mocks the data:
> `requestFunction: function(data) { return MyService.getAll() },`
> 
> MyService:
> 
> ```
> export default {
>     getAll() {
>         return {
>             data: [
>                 {
>                     "id": 1,
>                     "name": "foo",
>                 },
>                 {
>                     "id": 1,
>                     "name": "bar",
>                 }],
>             count: 2
>         }
>     }
> }
> ```
> 
> To reproduce bug I make small demo application: https://github.com/toudidel/vuetable

Cant open your github
