### ISSUE TITLE
Feature request: hide column on init

### ISSUE THREAD

**Issue by fasterlars** [matfish2/vue-tables-2#688]
Hiding a column by default, but still available in the columnsDropdown list, would be a simple and very nice feature.
It´s also requested in these threads: https://github.com/matfish2/vue-tables-2/issues/559 https://github.com/matfish2/vue-tables-2/issues/105
Is it possible this will be implemented at some point?
I know the columnsDisplay mobile/tablet workaround is possible in some cases, but it isn´t optimal.
Great table overall though! :)

**Comment by ray007** [comment]
And maybe also have an option for columns which must not be hidden?

**Comment by matfish2** [comment]
Added the mutually exclusive options `visibleColumns` and `hiddenColumns`
