### ISSUE TITLE
is it possible to get the index on row-click ?

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#689]
currently when using the row-click event, you receive the mouse event and the whole row. But I would like to access the index. Meaning, if clicking the 3rd row on page 1 then I would get an index of 3, and if clicking the 1st row on page 2 (Assuming 20 records per page) then the row index would be 21

Or at the very least if I could get the index of that page, and also access to the paginator from within the row-click then I could do my own calculation.

**Comment by seuaCoder** [comment]
Currently we don't have any way to get the index on click ?
