### ISSUE TITLE
No matching any row, detecting no moment object on daterangepicker

### ISSUE THREAD

**Issue by MatiasManevi** [matfish2/vue-tables-2#691]
- Vue.js version: 2.6.6
- Vue-table-2 version: 1.4.70
- consumed using: webpack 4.29.6
- FULL error message: nothing
- relevant code:
```
data(){
	return{
		columns: ['id', 'name', 'phone', 'email', 'created_at'],
		options: {
			filterByColumn: true,
		        perPage: 15,
			perPageValues: [],
			texts: {
				page: "Pagina:",
				filter: "Filtrar:",
			        filterBy: 'Filtrar por {column}',
			        limit: 'Limite',
       			       count: 'Mostrando de {from} a {to} de {count} registros|{count} regitros|Un registro'	
			},
			dateColumns: ['created_at'],
			templates:{
				created_at(h, row) {
				     return moment(row.created_at).format('YYYY-MM-DD HH:mm:ss');
			        }
			},
			dateFormat: 'YYYY-MM-DD HH:mm:ss',
			toMomentFormat:  'YYYY-MM-DD HH:mm:ss',
			datepickerOptions: {
				showDropdowns: true,
				autoUpdateInput: true,
				locale:{
					cancelLabel: 'Limpiar',
					applyLabel: 'Aplicar'
				},
			},
			pagination: {chunk: 5, dropdown: false},
			filterable: ['name','phone','email', 'created_at'],
			sortable: ['name','phone','email', 'created_at'],
			headings: {
				name: 'Nombre',
				phone: 'Telefono',
				email: 'Email',
				created_at: 'Fecha',
				id: 'ID',
			},
		}
	}

}
```
- steps for reproducing the issue:
I assume that im having the same problem than this [issue#401](https://github.com/matfish2/vue-tables-2/issues/401).. but not sure if is the same problem in the deep.

I have correctly imported jQuery + moment + daterangepicker.

I have rows that match what im searching, but nothing is returned. So, I dive in the code and found that in the client-search.js file the `foundMatch ` function never receives a moment object when filtering by date ranges.

```
if (['string', 'number', 'boolean'].indexOf(typeof value === 'undefined' ? 'undefined' : _typeof(value)) > -1) {
    value = String(value).toLowerCase();
}
```
This above lines are the first ones on foundMatch function and always execute with true on the IF when Im filtering by date ranges. I figure out that value variable is always a string like "2019-04-12 17:05:02" and not a moment object. And, if is not a moment object will never execute the lines of code that filter date ranges.

What Im doing wrong?

Thanks in advance

**Comment by MatiasManevi** [comment]
More context info:

I put this line

`value = moment(value);`

right after this line 

`value = this._getValue(row, column);`

on the filterable columns loop  `this.filterableColumns.forEach(function (column) {`

And everything work!! .. But this not ideal because I have another columns that are not dates.

I did this just to know if the type of my date column should be Moment Object in this function to work properly. Something between this filter loop and my App is wrong, or maybe just in my App, I appreciate your help

**Comment by MatiasManevi** [comment]
There is still no answer to this problem. I have fought for 2 days with this bug. I just relax and forget about it on the weekend, and in those bright moments of relaxation is where I glimpse a way to make it work without having to touch the plugin.

I'm using Vuex. Within the mutation where I set my list of records, I map each record so that the fields that are dates are converted to moment objects. Done!, I can keep moving forward.
```
_set_clients: (state, clients) => {
	clients = clients.map((client) => {
		client.created_at = moment(client.created_at);
		client.updated_at = moment(client.updated_at);
		return client;
	});

	state.clients = clients;
}
```
The rest of the plugin works very well, congratulations!

**Comment by matfish2** [comment]
Are you saying that `toMomentFormat` doesn't work? Anyway, this option is just a helper to transform all dates to moment. As you realized this can be easily done on the dataset before passing it to the plugin,

**Comment by maxkdev** [comment]
Just add `transformDateStringsToMoment()` into `table-data.js` like this:
```
module.exports = function () {
  if (this.opts.toMomentFormat) this.transformDateStringsToMoment();
  return this.data;
};
```
Bingo!

**Comment by matfish2** [comment]
@maxkdev that will trigger the conversion every time the data is changed. What's needed is only the initial transformation of date strings to moment objects, which is already called in `v-client-table.js`
