### ISSUE TITLE
Question - Select2 as filter in header

### ISSUE THREAD

**Issue by laravelbap** [matfish2/vue-tables-2#692]
Hi,
Great library. Almost everything works without problems.

I have small question: Is it possible to use select2 (for example https://vue-multiselect.js.org) in header filters? 
I have select filters in header but with 30+ records in select filter, it's hard to find the proper one to filter. If Yes. How can do this?

**Comment by laravelbap** [comment]
Solved using custom filters, custom slots and https://vue-multiselect.js.org/

for future readers:
1.  install vue-mutltiselect

2. add custom header filter

```
<div slot="filter__user">

 <vue-multiselect 
   :options="config.users" 
   :searchable="true" 
   :show-labels="false" 
   @input="refreshTable"
   label="text" 
   track-by="id" 
   v-model="filters.user_id"
  ></vue-multiselect>
</div>
```
3. add render 

```
 <div slot="user" slot-scope="props">
   {{ props.row.user != null ? props.row.user.name : '' }}
 </div>
```

4. use request adapter

```
requestAdapter: (data) => {
                        if (this.filters.user_id) {
                            data.query.user_id = String(this.filters.user_id.id);
                        } else {
                            delete data.query.user_id;
                        }

                        return data;
                    },
```

**Comment by matfish2** [comment]
Good solution. Might add a more streamlined way to do this
