### ISSUE TITLE
pagination: { edge: true, nav: 'scroll' } doesn't update page number buttons

### ISSUE THREAD

**Issue by equus52** [matfish2/vue-tables-2#694]
With option pagination: { edge: true, nav: 'scroll' }, First/Last buttons doesn't update page number buttons.

- steps for reproducing the issue:

1. Add edge option to [fiddle](https://jsfiddle.net/matfish2/jfa5t4sm/) and Run
```
pagination: {
  edge: true,
  nav: 'scroll',
  chunk: 2
}
```

2. Push Last button and push First button

**Comment by matfish2** [comment]
Fixed in vue-pagination-2. reinstall dependecies
