### ISSUE TITLE
Limit and pagination 

### ISSUE THREAD

**Issue by SouadAli10** [matfish2/vue-tables-2#696]
Hello, 
Thank you for this repo it's great. I am using the server side table and utilizing api calls I want to use the pagination to change so for example when I set initial limit at 10 when I chose pagination 2 it would send an api call where the limit is 20 for example how can I do that?

**Comment by DoubleB123** [comment]
If I'm understanding right that isn't how pagination should work. You don't want it to return 20 items when you go to page 2. You want it to return 10 each time, but the offset in the query would change. You would probably just want your backend to calculate the offset from the page and limit and then use the limit and calculated offset in your query.
