### ISSUE TITLE
How to put custom class on childrows?

### ISSUE THREAD

**Issue by fasterlars** [matfish2/vue-tables-2#697]
I use rowClassCallback for ordinary rows, which works great:

```
 rowClassCallback(row) {
          return row.active ? "active" : "";
        },
```

 But it doesent seem to trigger for childrows. So is this, or a similar official solution, possible/available? Or do I need to go css hacking? :/

**Comment by matfish2** [comment]
Do you mean the same class which is applied to the main row should be applied to the child? Or Maybe `{class}--child-row`?
