### ISSUE TITLE
Feature Request: td classes and styling

### ISSUE THREAD

**Issue by vincemukiiri** [matfish2/vue-tables-2#700]
I'd like to be able to add a class to a td element directly based on the data of the element. For example, I have a column called balance and I'd like to add a red background if its value is less than zero. At the moment, you can do something similar with scoped-slot templates like so
```
<template slot="balance" slot-scope="props">
  <div :class="{'table-danger': props.row.balance <= 0}">
    {{ props.row.balance }}
  </div>
</template>
```
by wrapping the content with a div and applying the class to the div. However I'd rather apply the class directly to the td element for cleaner styling since the example above applies a padding to the td before the red div. 

An idea is to be able to apply the class like this
```
<template slot="balance" slot-scope="props" :class="{'table-danger': props.row.balance <= 0}">
  {{ props.row.balance }}
</template>
```
without the need for a wrapping element.

Related issues are #471 #348

**Comment by matfish2** [comment]
https://github.com/matfish2/vue-tables-2#cells-conditional-styling
