### ISSUE TITLE
Is it possible to make columns re-sizable by dragging them

### ISSUE THREAD

**Issue by srdmathur** [matfish2/vue-tables-2#702]
- Vue.js version: 2.x.x
- consumed using: webpack
- FULL error message (including stack trace): There is no error message. Its a query.
- relevant code:
- steps for reproducing the issue:

**Comment by ixperiencenl** [comment]
For anyone using an older version and upgrading now. This can cause issues on iphones not wanting to horizontally scroll anymore. You need to add resizableColumns: false to your options to fix this issue
