### ISSUE TITLE
It is possible to use the client-table loading data from the server and with useVuex = true??

### ISSUE THREAD

**Issue by GusTejada** [matfish2/vue-tables-2#704]
"vue": "^2.6.10",
"vue-router": "^3.0.3",
"vue-tables-2": "^1.4.70",
"vuex": "^3.0.1"

hello good, thank you very much for the table vue 2, excellent work, use the client table to load data from an external api, the table has a name as the doc says, I use useVuex = true, the table does not paint records, with useVuex = false works fine, can not use client table with external data and use vuex ??

**Comment by matfish2** [comment]
Fixed
