### ISSUE TITLE
Get Data or count in Scoped Template

### ISSUE THREAD

**Issue by kushalbacancy** [matfish2/vue-tables-2#706]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

Hi, is it possible to use the `data` or `count` inside the template scoped?
In my case, I need to use the data or count inside the template scoped, 

```
<v-server-table ref="floorTable" :url="route('floor.index', {building_id: $route.params.id})" :columns="columns" :options="options">
   <template slot="action" slot-scope="props">
      <button class="action-btn btn-edit" @click="edit(props.row.id)"><i class="fa fa-pencil "></i></button>
      <button class="action-btn btn-times" @click="remove(props.row.id)"><i class="fa fa-times"></i></button>
      <button class="action-btn btn-angle-up" @click="shiftOrder(props.row.id,'up')" ><i class="fa fa-angle-up"></i></button>
      <button class="action-btn btn-angle-down" @click="shiftOrder(props.row.id,'down')"><i class="fa fa-angle-down"></i></button>
    </template>
 </v-server-table>
```
In above code I want `count` in `<template slot>`  section.

**Comment by luchorengo** [comment]
It would be nice to know how to grab the responseAdapter data out from the function. In my case, I need to return an additional value from my backend controller to be shown at the top table.
I'm currently using:
`<div slot="beforeFilter" >
    <span class="font-weight-bold">Total: ${{ total_receipts }}</span>
</div>`
where total_receipts is a value returned from controller. Any idea how to proceed?

**Comment by matfish2** [comment]
@kushalbacancy, do you mind explaining why you need to access `data` and `count` in the template? While I can pass those to the scoped slot as additional data, it seems very wasteful to pass this data to each row, especially in the case of the `data` property.

**Comment by matfish2** [comment]
closed for inactivity
