### ISSUE TITLE
[HowTo] add "summary" attribute and <caption> tag to <table>

### ISSUE THREAD

**Issue by sreenadh** [matfish2/vue-tables-2#711]
Is it possible to add either <caption> tag or "summary" attribute to the table as recommended by Siteimprove Accessibility Checker?

**Comment by sreenadh** [comment]
Thank you 🙂 
Any upcoming release or should I change to dev-master in package.json

#736 is also a accessibility change

**Comment by matfish2** [comment]
There is a new release. Will tale care of #736 as well.
