### ISSUE TITLE
I do i change the name field "filter" and "search query"

### ISSUE THREAD

**Issue by Matemare** [matfish2/vue-tables-2#714]
Hi matfish2 i would like to translate all the fields genereted on vuetable2 filter block.
i try to put this code on page where vuetable-2 is inserted:
        texts: () => {
          return {
            count: "Showing {from} to {to} of {count} records|{count} records|One record",
            first: 'First',
            last: 'Last',
            filter: "Filter:",
            filterPlaceholder: "Search query",
            limit: "Records",
            page: "Page:",
            noResults: "No matching records",
            filterBy: "Filter by {column}",
            loading: 'Loading...',
            defaultOption: 'Select {column}',
            columns: 'Columns'
          }
        },

But nothing work if i try to change some fields.
Can you please advice me how to chage this fields?

Thanks in advance

**Comment by joelmandell** [comment]
Hi,

You have to define an property on the data object that is passed to the prop options on the table component.![bild](https://user-images.githubusercontent.com/109020/61774041-5324ee00-adf6-11e9-9789-c6b3287794ce.png)

![bild](https://user-images.githubusercontent.com/109020/61773986-3dafc400-adf6-11e9-8af6-b96e0d672ca3.png)

**Comment by Matemare** [comment]
@joelmandell joelmandell 
Thanks for your answer but they wont to change dinamically when i change the language...

**Comment by joelmandell** [comment]
Okay,
Check this https://jsfiddle.net/b6uywrpv/
In that example I set the options.texts with Object.assign when doing a change on a select option.
