### ISSUE TITLE
Upload to cdnjs

### ISSUE THREAD

**Issue by Rickvanderwaal** [matfish2/vue-tables-2#715]
We are using LibMan for restoring packages in our project. This client side package manager does have three providers:
* cdnjs
* unpkg
* local filesystem

We use the 'unpkg' provider to get vue-tables-2 but this provider is very unreliable. Can you please upload vue-tables-2 to the cdnjs provider? It's as easy as create a pull request in the cdnjs repository.

**Comment by matfish2** [comment]
https://github.com/cdnjs/cdnjs/pull/13531
