### ISSUE TITLE
toggle single child row

### ISSUE THREAD

**Issue by lastlink** [matfish2/vue-tables-2#716]
- Vue.js version: 2.6.10
- consumed using: webpack
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

when I click on the + -  on the left column all the child rows for every row expand. I'd prefer to have a single one expand.

**Comment by matfish2** [comment]
Form the docs:

> When using the childRow option you must pass a unqiue id property for each row, which is used to track the current state. If your identifer key is not id, use the uniqueKey option to set it.

Does this help?
