### ISSUE TITLE
How to show only specific columns by default from columns array

### ISSUE THREAD

**Issue by Sakthi002** [matfish2/vue-tables-2#718]
**My Columns array**
columns : [ 'name', 'age', 'email', 'phone'],

from this by default i want to show only 2 columns `name, age`,

then in columnsDropdown after i select 'email' i want to show `email` column

**Comment by jblotus** [comment]
You might be able to make tableColumns option read from a computed property.

**Comment by matfish2** [comment]
Did you check the [Columns Visibility](https://github.com/matfish2/vue-tables-2#columns-visibility) section? It shows a dropdown that enables visible columns selection.
