### ISSUE TITLE
Support for CodeIgniter as data backend for Server Tables (example implementation)

### ISSUE THREAD

**Issue by Biktorgj** [matfish2/vue-tables-2#722]
Hi, 

We are using CodeIgniter as the backend for some server side tables with your package. I adapted a small library to be able to use Vue-tables-2 with CodeIgniter & MySQL and I thought it would help others to have some more implementation examples outside of laravel

This library allows both POST and GET requests, and handles ordering, filtering and paging, and it support joins. It might have quite some bugs, though it's working fine (tm) for our use cases. The library is based off another library initially coded for jQuery datatables package.

To use it server side, the user would need to place it in 'application/libraries/Vuetables.php', 

[Vuetables.php.txt](https://github.com/matfish2/vue-tables-2/files/3556658/Vuetables.php.txt)

Here's an example on how to call the library:
```

    $this->vuetables
      ->select('site_members.id, site_members.member_id, family_id, signup_allowed, status, site_membership_discounts.discount_percent')
      ->from('site_members')
      ->join('site_membership_discounts', 'site_membership_discounts.member_id = site_members.id AND year = '.date('Y').'', 'left');
   echo json_encode($this->vuetables->generate('pagedarray'));
  }
```

Hope it helps users using other frameworks out there!

**Comment by matfish2** [comment]
Thanks. If you'd like you can send a PR where you add this implementation alongside the Eloquent one
