### ISSUE TITLE
customize table data

### ISSUE THREAD

**Issue by saranya401** [matfish2/vue-tables-2#724]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:
vue.js  -  >2.6
consumed using :webpack
ISSUE:
I am using v-client-table in that, I will not get data for some keys and which implies its a new user, so in place of that I need to load other component, which gives user to enter data  manually
CODE:
 <v-client-table
            :name="'myClientData'"
            :data="tableData"
            :columns="columns"
            :options="options"
          >
            <span
              slot="Symbol"
              class="float-right"
              slot-scope="props"
            >
              
              <div class="d-block">{{ (props.row.Symbol) }}</div>
            </span>
            <span slot="Account" slot-scope="props">
              <div class="float-right d-block">{{ (props.row.Account) }}</div>
              <br />
            </span>
            <span
              slot="STCapitalGains"
              class="float-right taxImpact"
              v-bind:class="{'loss-red':(props.row.STCapitalGains < 0), 'gain-green':(props.row.STCapitalGains > 0)}"
              slot-scope="props"
            >
              <div class="d-block">{{ (props.row.STCapitalGains) }}</div>
                            <div v-if="(props.row.STCapitalGains === 'n/a')  ? true : props.row.STCapitalGains"></div>

              
            </span>
            <span
              slot="LTCapitalGains"
              class="float-right taxImpact"
              v-bind:class="{'loss-red':(props.row.LTCapitalGains < 0), 'gain-green':(props.row.LTCapitalGains > 0)}"
              slot-scope="props"
            >
              <div class="d-block">{{ (props.row.LTCapitalGains) }}</div>
              <div slot="child_row" slot-scope="props">
                {{ (props.row.LTCapitalGains) }}
    </div>
                            

            </span>
              <span
              slot="OrdinaryDividends"
              class="float-right taxImpact"
              v-bind:class="{'loss-red':(props.row.OrdinaryDividends < 0), 'gain-green':(props.row.OrdinaryDividends > 0)}"
              slot-scope="props"
            >
              <div class="d-block">{{ (props.row.OrdinaryDividends) }}</div>
              
            </span>
              <span
              slot="TaxImpacts"
              class="float-right taxImpact"
              v-bind:class="{'loss-red':(props.row.TaxImpacts < 0), 'gain-green':(props.row.TaxImpacts > 0)}"
              slot-scope="props"
            >
              <div class="d-block">{{ (props.row.TaxImpacts) }}</div>
                            

            </span>
              <span
              slot="RecordDate"
              class="float-right taxImpact"
              v-bind:class="{'loss-red':(props.row.RecordDate < 0), 'gain-green':(props.row.RecordDate > 0)}"
              slot-scope="props"
            >
              <div class="d-block">{{ (props.row.RecordDate) }}</div>
                            

            </span>
            </v-client-table>

**Comment by matfish2** [comment]
Not sure I understood the question. Please clarify. If you want the data to change dynamically just change the data passed to the table on the fly. Vue's reactivity will take care of the rest

**Comment by matfish2** [comment]
closed for inactivity
