### ISSUE TITLE
vue-tables-2 (v-client-table) adding a dropdown in each row. v-model effects all rows

### ISSUE THREAD

**Issue by qadirfarooq** [matfish2/vue-tables-2#725]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:
HI,
Thanks for such a nice component. i am having a little bit of issue when i am adding a drop-down in each row. when the drop-down value changed in one row its effecting all the rows in a grid. i am using the v-model for binding and the value of v-model(NewOverrideStatus)  is picking up the correct value but on its value change its effecting all the rows.  see the template and screen shots before and after. i am new to Vue js and grid so please help. 

        <template slot="statusid" slot-scope="props"  >
          <select id="override" v-model="NewOverrideStatus"  v-on:change="ChangeServiceStatus(NewOverrideStatus,props.row.servicecodeid)"  class="form-control form-control-sm"> 
          
           <option v-for="option in ServiceStatus" v-bind:value="option.id"  :key="option.id">
          <strong>{{ option.text }}</strong>
          </option> 
          </select>
        </template>
 
Before Dropdown changed:

![image](https://user-images.githubusercontent.com/27695273/64207150-45cd3b80-ce59-11e9-9445-3144c03c8d4a.png)

After Dropdown changed: 

changing the value of one dropdown it changed the value of all rows drop down. 
![image](https://user-images.githubusercontent.com/27695273/64207251-7dd47e80-ce59-11e9-83d9-a8bf4c742c1d.png)

**Comment by matfish2** [comment]
I see you are using the same `v-model` data for all rows, so not surprisingly they all change when you select one. You should probably opt for a contextualised model on the dataset itself. so `:value=row.status` should do the trick. Then on change you can detect the row in your dataset and update its status.
