### ISSUE TITLE
How to prevent initial data load (server table)?

### ISSUE THREAD

**Issue by solotony** [matfish2/vue-tables-2#726]
I do not need data to be loaded when table mounted, only after custom filter values inited.

**Comment by jblotus** [comment]
You can probably provide a custom request function that returns your initial dataset, and overwrite that dataset upon subsequent request or set a flag to prevent checking on initial load.

**Comment by solotony** [comment]
Re: [matfish2/vue-tables-2] How to prevent initial data load (server table)? (#726)


Thanks





You can probably provide a custom request function that returns your initial dataset, and overwrite that dataset upon subsequent request or set a flag to prevent checking on initial load.
