### ISSUE TITLE
dynamic column creation and grouping, how?

### ISSUE THREAD

**Issue by syslao** [matfish2/vue-tables-2#728]
- Vue.js version: 2.5.2
- consumed using: (browserify/webpack/rollup) webpack

Hi! big thanks for your work.

I have dataset from api :

`[
    {
        param_id: "9966_48",
        param_name: "param1",
        points: [
            {
                x: "2019-09-14T00:00:21.493",
                y: 0.0
            },
            {
                x: "2019-09-14T00:05:22.623",
                y: 1.0
            },
            {
                x: "2019-09-14T01:05:30.06",
                y: 9.0
            }
        ]
    },
    {
        param_id: "9981_1076",
        param_name: "param2",
        points: null
    },
    {
        param_id: "9966_58",
        param_name: "param3",
        points: [
            {
                x: "2019-09-14T01:00:29.817",
                y: 6.0
            },
            {
                x: "2019-09-14T01:05:30.06",
                y: 0.0
            }
        ]
    },
.....
]`

and i need to create table with format like :

```
data                    |  param1     |  param2       |  param3    | param ...
2019-09-14T00:00:21.493 |  0.0        |               |            |
2019-09-14T00:05:22.623 |  1.0        |               |            |
2019-09-14T01:00:29.817 |             |               |  6.0       |
2019-09-14T01:05:30.06  |  9.0        |               |  0.0       |

```
dates can be the same and it is desirable to combine them

**Comment by matfish2** [comment]
you need to manipulate the dataset before passing it to the table so you'll eventually get:
```
[
 {
   date: '2019-09-14T00:00:21.493',
   param1: 0.0,
   params2: null
}
...
]
```
