### ISSUE TITLE
Initial multi column sorting

### ISSUE THREAD

**Issue by Rickvanderwaal** [matfish2/vue-tables-2#729]
* Vue.js version: 2.5.21
* Vue-tables-2 version: 1.4.70

We are using the server-table with the possibility of sorting mulitple columns. Is there any option to set a default of multiple sorted columns ? Only initial sort by one column is working for us:
```
options: {
  orderBy: {
    column: 'name',
    ascending: true
  }
}
```

**Comment by awulkan** [comment]
I am also interested in knowing if this is possible. I assume that the "Feature request" label means that it's not possible yet.

**Comment by matfish2** [comment]
I am not sure I understand what you mean by "a default of multiple sorted columns". There can only be one primary sorting column, and it is defined using the `orderBy` option you have mentioned.

**Comment by awulkan** [comment]
I believe what is asked for is to be able to sort by multiple columns. For example, first you might sort a list of people by first name, and then you sort it a second time by the last name. So you end up with a list where all the people who have the same first name are sorted alphabetically on their last name instead.

This was just a simple example. In my case I had to implement my own sorting algorithm to sort users projects by username and date of last edit to the projects.

**Comment by matfish2** [comment]
But that's been supported for a while now:
https://github.com/matfish2/vue-tables-2#multiple-sorting

**Comment by Rickvanderwaal** [comment]
You’re right. Sorting on multiple columns is supported and we use it. However there is no option to provide an initial value for multi sorting. 

The following options are available from the documentation:
![DA24F55A-CF4B-4D84-B686-AED3BFCFBBB9](https://user-images.githubusercontent.com/8845169/67903577-3b36d600-fb6c-11e9-8ab4-0558697f1839.jpeg)

Does this clarify the feature ?

**Comment by matfish2** [comment]
I am still not fully sure I understand. The secondary columns are either matching the direction of the primary column or not. You can set this using the `matchDir` property. So I am not sure what you mean by "initial value for multi sorting"? As I said before you can only set one primary sorting column. The rest are derived depending on the logic you defined in multisorting. Maybe an example would help.

**Comment by Rickvanderwaal** [comment]
I want to apply sorting on multiple columns at first page load. When an user enters my webpage the table is default sorted on firstname. The user can use shift + click to sort on lastname too. Is there any option to sort by firstname and by lastname on first page load?

**Comment by matfish2** [comment]
As I said, that's exactly what `multiSorting` is for:
```js
 {
   orderBy:{
    column: 'first_name',
    ascending: true   
   },
   multiSorting: {
        first_name: [
            {
                column: 'last_name',
                matchDir: false / true // depending on whether you want it to match the direction of `first_name` or not
            }
        ]
    }
}
```

The `orderBy` option will trigger an initial primary sort by first name. The `multiSorting` option will then sort by last name as a secondary column. Maybe what causes confusion is that the secondary column sort icon doesn't reflect that it's being sorted?

**Comment by Rickvanderwaal** [comment]
Excuse me, I forgot to mention that we use the server-side datatables. This option is only available for client-side datatables right?

**Comment by matfish2** [comment]
from the docs: 

> On the server component this behaviour is disabled by default because it requires additional server logic to handle the request. To enable it set `serverMultiSorting` to true. The request will then contain a `multiSort` array, if applicable.

**Comment by Rickvanderwaal** [comment]
I agree, i did read this in the documentation. However the multiSort array is not send on initial load. I have set the `serverMultiSorting` to true en filled the `multiSort` array.
I have setup a JSFiddle to show this use case: https://jsfiddle.net/rickwaal/fzvektun/

Am i doing something wrong?

**Comment by Rickvanderwaal** [comment]
@matfish2 please take a look at the last provided jsfiddle?

**Comment by matfish2** [comment]
developer-defined mutisort (as opposed to user-defined by clicking Shift+click) is not sent to the server as it's a constant and thus the server can implement the logic without request parameters. If for some reason you still want to send it you can use the `params` option to do so

**Comment by christopheralert** [comment]
Just for some clarification, I ran into this same issue but was able to work around it.
Naming the column the same as a column in the table data made it not work. Creating a new arbitrary name for it did.

For example, my columns were name and active. I called the multi sort "name" and it would not work. I created an arbitrary name for it, as so, and it worked perfectly:

```
multiSorting: {
                    name_act: [
                    {
                        column: 'active',
                        matchDir: true
                    },
                    {
                        column: 'name',
                        matchDir: true
                    }]
                },
```
