### ISSUE TITLE
How custom templates for full table are supposed to work?

### ISSUE THREAD

**Issue by giraz82** [matfish2/vue-tables-2#73]
- Vue.js version: 2.1.10
- consumed using: (browserify/webpack/rollup) Laravel Mix (Webpack)
- FULL error message (including stack trace): No error, but empty component
- relevant code:
UserTable.vue

![schermata 2017-02-07 alle 11 00 02](https://cloud.githubusercontent.com/assets/5285724/22686504/9f6c9eba-ed24-11e6-9413-a926498c41e5.png)

template.jsx (original file included in the package):
![schermata 2017-02-07 alle 11 01 26](https://cloud.githubusercontent.com/assets/5285724/22686560/d4a19a36-ed24-11e6-877f-89753004dd54.png)

- steps for reproducing the issue:
I copied the file template.jsx from node_modules/vue-tables-2/lib to the path where I have js assets, then I adjusted the require paths to get webpack compilation work right.

After that the component results empty if I check the html, but wit Vue Dev Tools I can see all his properties correctly filled.
![schermata 2017-02-07 alle 10 54 56](https://cloud.githubusercontent.com/assets/5285724/22686308/e4ee4516-ed23-11e6-97c8-b5fb524a4b11.png)

Edit: I replaced code with screenshot because fomatting broke down for some reason..
Thank you.

**Comment by giraz82** [comment]
Ok, this the answer I was searching: [https://github.com/matfish2/vue-tables-2/issues/8](url)

```
var VueTables = require('vue-tables-2');
var custom_template = require('./custom_template.jsx');
Vue.use(VueTables.server, {},
    false,
    custom_template('server')); // OR custom_template('client')
```

I think it would be useful to others to point out this in de docs.

**Comment by hermandinho** [comment]
Hello, i am getting error `React is not defined` after doing this.

**Comment by EmilMoe** [comment]
Not working
