### ISSUE TITLE
Build childrow on the fly

### ISSUE THREAD

**Issue by sdonnet** [matfish2/vue-tables-2#731]
Hi,

I am in the same situation than
[is it possible to have a table as a childRow ?](https://github.com/matfish2/vue-tables-2/issues/90)

I want to build the childtable by an axios query, but I struggle to pass key parameter, as each sub-table data are built from the parent key. How can I link childtable to key of childRow ?

**Comment by sdonnet** [comment]
I found...

Self-documenting :  

- I created a component "ChildTable" with :  
```
<template>
   <v-client-table :data="rows" :columns="columns" :options=":options"></v-client-table>
</template>

<script>
   import ClientTable from 'vue-tables-2';
  export default {
    name: "ChildTable",
    components: {
        ClientTable
    },
    props: {
      childKey: Number,
      columns: Array,
      options: Object,
    }
  }
```

And I consume this component in my main table :  
```
<template>
    <v-client-table ...>
        <template slot="child_row" scope="props">
            <ChildTable :childKey="props.row.<KEY>" :columns="childColumns" :options="childOptions"/>
        </template>
    </v-client-table>
</template>

<script>
import {ClientTable, Event} from 'vue-tables-2';
import ChildTable from '@/components/ChildTable.vue';

export default {
  name: 'MainTable',
  components: {
    ClientTable,
    ChildTable,
    Event,
  },
.../...
}
</script>
```
In data section, you build all arrays for main and child tables.

**Comment by matfish2** [comment]
Note you can also pass a component directly to the `childRow` option. No need to wrap in a slot.
