### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by hellboy81** [matfish2/vue-tables-2#732]
[Which replacement should be used](https://www.npmtrends.com/ag-grid-vue-vs-vuetable-2-vs-vue-tables-2-vs-vue-good-table)

**Comment by ixperiencenl** [comment]
ag-Grid looks very promising. The fact that they both offer a paid and a free version makes sense. It takes time (and obviously money) to create something like this. 
It's unfortunate that @matfish2 probably doesn't have the time to maintain this great package. I still use it with a lot of joy, but it has it's shortcomings and that makes it a bit harder to use

**Comment by matfish2** [comment]
Hey all. Sorry for the long absence. I hope to maintain regularly from now on. Will take some time to get all those issues out of the way, but it should clear up soon
