### ISSUE TITLE
Error with dependency: babel-helper-vue-jsx-merge-props

### ISSUE THREAD

**Issue by tylerscott23** [matfish2/vue-tables-2#734]
Build fails with latest version 1.4.73 and 1.4.80 on dependency missing.  Works fine with 1.4.70.

- Vue.js version: 3.11.0
- consumed using: (webpack)
- FULL error message (including stack trace):
 ERROR  Failed to compile with 1 errors                                                                                                                                                                               10:07:34 AM
This dependency was not found:

* babel-helper-vue-jsx-merge-props in ./node_modules/vue-tables-2/compiled/modules/rows.js

To install it, you can run: npm install --save babel-helper-vue-jsx-merge-props
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
- relevant code: NA
- steps for reproducing the issue: yarn build

**Comment by matfish2** [comment]
I've moved the plugin from dev-deps to deps. can you try again with version 1.4.81?

**Comment by tylerscott23** [comment]
Works now!  Thanks!
