### ISSUE TITLE
Modular table components (pagination, table, dropdown, etc.)

### ISSUE THREAD

**Issue by TheStoof** [matfish2/vue-tables-2#738]
This is a feature request. Your project has been incredibly helpful to projects and it one of the most popular FOSS table components for VueJS. Although we have the ability to change templates or even themes, it is not easily done. Would it be feasible to consider making the pagination, per-page dropdown, search, and other similar elements to be 100% modular so that you could include pagination if desired, per-page, or even the table component.

**Comment by matfish2** [comment]
That's quite a heavy request. Though I definitely see the great benefit of it, I don't know if I'll have the time and resources to implement in the near future.

**Comment by matfish2** [comment]
https://matanya.gitbook.io/vue-tables-2/custom-template-version-2
