### ISSUE TITLE
Accessibility - aria-label in <nav> tag of pagination

### ISSUE THREAD

**Issue by sreenadh** [matfish2/vue-tables-2#739]
How can I add aria-label for 'nav' tag in pagination? I'm using custom template. 

```
Vue.use(ServerTable, {
    columnsClasses: {
        sl: 'text-center',
        actions: 'text-center'
    },
    sortIcon: {
        base: "fa",
        up: "fa-chevron-up",
        down: "fa-chevron-down",
        is: "fa-sort"
    },
    pagination: {
        edge: true,
        chunk: 5,
        nav: 'fixed'
    },
}, false, 'bootstrap4', require('./vue-table-theme'));
```

PS: The table summary and td tabIndex='0' changes worked fine 👍

**Comment by sreenadh** [comment]
@matfish2 is there any workaround which I can try to get this done? like the custom template? or overriding the pagination component for vue-tables.

**Comment by matfish2** [comment]
I can add it to pagination component. Do you want a customizable aria-label, e.g:
``` 
pagination: {
        edge: true,
        chunk: 5,
        nav: 'fixed',
       ariaLabel:'My Own Label'
    },
```

**Comment by sreenadh** [comment]
Yes. a customized aria-label for each table.

**Comment by matfish2** [comment]
sorry, apparently I'm using vue-pagination-2@^1.6 but the most recent version in over 2.0. I can't upgrade to this version without breaking this plugin
