### ISSUE TITLE
Slots for child rows

### ISSUE THREAD

**Issue by hunterway55** [matfish2/vue-tables-2#74]
- Vue.js version: 2.1.0
- consumed using: (webpack)
Propose using slots for child rows

```
 <v-client-table
          :data="tableData"
          :columns="columns"
          :options="options"
          :name="table_name"
          @loaded="onLoaded"
          scope="props">
          <mychild-row name="childrow id="props.childID"><mychild-row>
   </v-client-table>
```

Just a thought??

**Comment by matfish2** [comment]
I've tried to implement something of the sort but hit a problem with passing contextual row data inside the `v-for` loop. If you feel up to the task a PR is most welcome.

**Comment by jiangdi0924** [comment]
@hunterway55  hello , do you know how to add child row  now?

**Comment by hunterway55** [comment]
Hello. We just continued using
```
 options:{
...
childRow: 'row-component'
...
}
```

**Comment by jiangdi0924** [comment]
thank you

2017-07-21 14:48 GMT+08:00 Jonathan allen <notifications@github.com>:

**Comment by Dwood15** [comment]
Is there a working jsfiddle example of using child rows? I'm new to using Vue and haven't been able to figure out what is meant by the partial examples on the tutorial. I can get the main client-datable to work just fine though.

**Comment by matfish2** [comment]
I've added an example usage to the fiddle

**Comment by Dwood15** [comment]
Thanks a million.

**Comment by mandersondesign** [comment]
Not sure if this is the right place, but is there an option to Append the child row toggle, vs prepend it? Love for it to be the last column on the row instead.

**Comment by matfish2** [comment]
Yes, Set the `childRowTogglerFirst` to `false`
