### ISSUE TITLE
Feature request: ServerTable - load page data and total records count separately

### ISSUE THREAD

**Issue by carrotinside** [matfish2/vue-tables-2#741]
Hi,

it would be great to be able on ServerTable set page data and total count separately/subsequently. It speeds up showing page data.
Very often users do not scroll to a pager, so the count is not so important as a data itself. It can be computed in a following request.

Thx

**Comment by matfish2** [comment]
Interesting. However, I am not entirely clear as to when should the count request be sent. I suppose the plugin can wait until the data is populated and then check if the pagination section (i.e empty wrapper) is visible. If so, it will immediately send the count request. If not, it will wait for the pagination wrapper to be present in the viewport and then send the request.

**Comment by carrotinside** [comment]
For us it would be enough to be able set "count" also separately from "setData" method. Someting like setCount ...

We're sending the request for count immediately after page data arrives and than doing little bit complicated logic to avoid pager changing (mainly when user going through pages) by injecting previous count in setData call, and also handling states where concurrently exists new request for data and still does not returns count request from previous data request and so on.
It's not ideal, but it gives us half the time a faster response.

**Comment by matfish2** [comment]
Sounds rather complicated, especially if we consider pagination which requires count to be present immediately (i assume that's what you mean by "avoid pager changing"). 
What you can try is return count 0 from the main request, and then send your own count request when appropriate and update the `count` property on the plugin using `this.$refs`.

**Comment by carrotinside** [comment]
I think I tried set count to 0 in main request, but the table didn't show any data. You're checking count, not data.length for data presence.
And set count directly is possible only in ClientTable, not ServerTable, but maybe I tried it wrong.

**Comment by matfish2** [comment]
as for count check I will change it to consider data.length instead.
count property is available on server table as well, use vue-dev-tools to hunt it down.

**Comment by matfish2** [comment]
Published in 1.5.43

**Comment by carrotinside** [comment]
Super quick fix. I'll try it.
Thank you.

**Comment by jauharfuadi54** [comment]
need full example please

**Comment by carrotinside** [comment]
When I set `this.$refs.myTable.count = 123`, gets an error:
Computed property "count" was assigned to but it has no setter.

Can you add setter for count property?

**Comment by matfish2** [comment]
are you using vuex? `count` is not a computed property normally. It's a data property assigned directly from the response.

**Comment by carrotinside** [comment]
Yes. It seems to set property correctly, but reactivity is missing. The pager is not rendered. After second request (by changed filter) the count is used.

**Comment by matfish2** [comment]
If you are using vuex you should mutate the store `count` property, not the component's computed count

**Comment by carrotinside** [comment]
You're right. I tried it before and it was not possible on server table. I'll check it again.

**Comment by matfish2** [comment]
look at vue dev tools, the component itself is calling a SET_COUNT mutation on the module, Just call the same mutation yourself

**Comment by carrotinside** [comment]
[vuex] unknown mutation type: contactsTable/SET_COUNT

I can see only following mutations in dev tools:
LOADING, SET_DATA, LOADED

For sure, I've tried SET_DATA instead of SET_COUNT and it works.

**Comment by Imboga** [comment]
This is a pretty common issue when you fetch data from huge tables. 
I'm fetching 25 rows from an about 1.5 million records table and the query performance gets destroyed when counting total rows for pagination purposes because of double-querying.
It would be a great improvement to have something like @carrotinside is asking for.
IMO, a good solution could be having the next/prev pagination buttons with no chunks or the need to know the total rows count. Nowadays nobody cares about total records or even moving through specific page numbers. If they want to find something, they just use the table filter.
