### ISSUE TITLE
Server side custom filter

### ISSUE THREAD

**Issue by toudidel** [matfish2/vue-tables-2#743]
I try to implement server side custom filter
According to documentation I emit an event `Event.$emit('vue-tables.filter::filterType', 'MY_FILTER')`

How can I handle this event and refresh data when in options is used function `requestFunction` to get the fresh data?
Where should be defined event handler for event `vue-tables.filter::foo`?

**Comment by matfish2** [comment]
Emitting the event should send an extra param with the name of the filter and the value. Then it is up to you to handle the filtering - using this parameter - on the server-side.

**Comment by toudidel** [comment]
It'd be good but unfortunately no any request is trigerred.

**Comment by matfish2** [comment]
Well, I need to see some code then. I've checked and wasn't able to reproduce the issue

**Comment by toudidel** [comment]
HTML:
>
    <ContentWrapper>
    <div>
        <button type="button" class="btn mr-1 mb-1 btn-primary" @click="applyFilter('EVENT_TODAY')">Today</button>
        <button type="button" class="btn mr-1 mb-1 btn-primary" @click="applyFilter('EVENT_TOMMOROW')">Tomorrow</button>
        <button type="button" class="btn mr-1 mb-1 btn-success" @click="applyFilter('EVENT_ALL')">All</button>
    </div>
    <v-server-table name="events" ref="table" :columns="columns" :options="options" saveState="true">
        <template slot="action" slot-scope="props">
            <div>
                <b-btn variant="outline-info mr-2" class="btn-xs" @click.prevent="edit(props.row)">{{ $t('common.edit') }}</b-btn>
            </div>
        </template>
    </v-server-table>
    </ContentWrapper>

JS:
> 
    import Vue from 'vue';
    import {ServerTable, Event} from 'vue-tables-2';
    import EventService from '@/api/event.service';
    import moment from 'moment'

    Vue.use(ServerTable);

    export default {
        name: "Events",
        components: {ServerTable},

        data() {
            return {
                events: [],
                filterType: 'EVENT_ALL',
                columns: this.getColumns(),

                options: {
                    headings: {
                        startDate: this.$t('model.event.startDate'),
                        finishDate: this.$t('model.event.finishDate'),
                        action: this.$t('common.operations')
                    },
                    requestFunction: function(data) {
                        return EventService.getAllPageable(data)
                    },
                    responseAdapter: function(resp) {
                        console.log('response')
                        return {
                            data: resp.data.content.map(item => {
                                const container = {};

                                container.id = item.id;
                                container.startDate = moment(item.startDate).format('YYYY-MM-DD HH:mm');
                                container.finishDate = moment(item.finishDate).format('YYYY-MM-DD HH:mm');

                                return container;
                            }),
                            count: resp.data.totalElements
                        }
                    },
                    sortable: ['startDate', 'finishDate'],
                    filterable: false,
                    perPage: 20,
                    perPageValues: [],
                    sortIcon: {
                        is: 'fa-sort',
                        base: 'fas',
                        up: 'fa-sort-up',
                        down: 'fa-sort-down'
                    },
                    customFilters: ['filterType']
                }
            }
        },

        methods: {
            getColumns() {
                return ['startDate', 'finishDate', 'patient.name', 'user.name', 'action'];
            },

            edit (row) {
                this.$router.push({name: 'event', params: {patientId: row.patient.id, eventId: row.id}});
            },

            applyFilter(filterType) {
                this.filterType = filterType;
                Event.$emit('vue-tables.filter::filterType', filterType);
                //this.$refs.table.refresh();
            }
        }
    }

**Comment by matfish2** [comment]
The code seems ok. Only thing I see, and not sure if it's related, is that you declare the table locally:
```components: {ServerTable},```
which is unnecessary as it's already declared globally when you register using Vue.use.

**Comment by toudidel** [comment]
OK, thanks. I'll analyze your example.

**Comment by toudidel** [comment]
I've tested some cases. When I use v-server-table like in your example, it works. I mean if I specify `url attribute` with endpoint returnning array in rest.

But it does not work if I don't use `url` and use `requestFunction` to get the data from external REST API.

BTW I use requestFunction to use my common API managment and build valid request containing proper authorization data against my rest api.

**Comment by matfish2** [comment]
I matched the above settings (no `url` + `requestFunction`) and still no luck. can you check if your `requestFunction` is triggered or not:
```  js
requestFunction: function(data) {
  console.log(data);
  return EventService.getAllPageable(data)
},
```

maybe your `EventService` class is blocking the request on account of the extra parameter?

**Comment by toudidel** [comment]
`EventService` works properly.

I found solution and reason why it wasn't working. My code was actually correct.

My table definiotion was:
`<v-server-table name="events" ref="table" :columns="columns" :options="options" saveState="true">`

The only one thing I removed is `name` atteibute. So if I have:
`<v-server-table ref="table" :columns="columns" :options="options" saveState="true">`

it works properly. The reason was `name` attribute but I don't kno why.

**Comment by matfish2** [comment]
I do:
```
Note: If you are using the bus and want the event to be "namespaced", so you can distinguish bewteen different tables on the same page, use the name prop. The event name will then take the shape of vue-tables.tableName.eventName.
```
