### ISSUE TITLE
How to display loader on every call we make to server

### ISSUE THREAD

**Issue by KingmakerNikhil** [matfish2/vue-tables-2#746]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

**Comment by matfish2** [comment]
use the `loading` and `loaded` events to display and hide loader respectively.

**Comment by KingmakerNikhil** [comment]
Where can i call these events. can you show me a example for this.
