### ISSUE TITLE
Child row display problem when <v-client-table> is inside a bootstrap <card>

### ISSUE THREAD

**Issue by oocar** [matfish2/vue-tables-2#747]
Vue.js version: 2

The hidden child row <div slot="child_row" slot-scope="props"> is displayed but **in the first parent column** (instead of spanned in all parent columns)

**Comment by matfish2** [comment]
I need some reproduction code as this is working properly in demo, and also has a passing test. Also, what version of the package are you using?

**Comment by oocar** [comment]
-->    "vue-tables-2": "^1.5.33"

<card>
    <v-client-table ref="vuetable" :data="table_rows" :columns="table_columns"  :options="table_options">
      <div slot="child_row" slot-scope="props">
                <div><b>Text:</b> {{props.row.data.original_text}}</div>
 </v-client-table>
</card>

--> original_text is displayed in a child row but inside the 1st column :(

**Comment by matfish2** [comment]
Can you inspect the child row `td` and see what is the `colspan` set there? (it should be count of table_columns + 1 for the toggler)

**Comment by oocar** [comment]
Yes, the colspan is ok!
Here is the html code, I can't understand ...!

`<td colspan="11" tabindex="0"><div><div><b>Text:</b> ... my text ... </div></div></td>`

**Comment by matfish2** [comment]
Well, if the `colspan` is ok it is probably some CSS issue that you need to figure out

**Comment by oocar** [comment]
I use vue light-bootstrap-dashboard and there was a display:block in **.card.table** scss file.
I removed it and it fixed the problem!
Weird
Thanks
