### ISSUE TITLE
Event Error

### ISSUE THREAD

**Issue by KingmakerNikhil** [matfish2/vue-tables-2#748]
Event.$on is not a function. can you tell me why am i getting this error.

**Comment by matfish2** [comment]
Not without seeing some code

**Comment by KingmakerNikhil** [comment]
mounted: function() {
    Event.$on('vue-tables.loading', function (data) {
        console.log(data)
    });
  },

**Comment by matfish2** [comment]
How do you import the `Event`?

**Comment by KingmakerNikhil** [comment]
I imported like this
import { ServerTable, Event } from 'vue-tables-2'

registered like this
Vue.use(Event)

and using that event in my code 

mounted: function() {
Event.$on('vue-tables.loading', function (data) {
console.log(data)
});
},

**Comment by matfish2** [comment]
`Vue.use(Event)` is redundant

**Comment by KingmakerNikhil** [comment]
How should i use those events?
