### ISSUE TITLE
First and last page buttons

### ISSUE THREAD

**Issue by giraz82** [matfish2/vue-tables-2#75]
In the pagination, "first page" and "last page" buttons are always disabled, even at the bottom of the doc page: [https://jsfiddle.net/matfish2/823jzuzc/embedded/result/](https://jsfiddle.net/matfish2/823jzuzc/embedded/result/)

Is there a way to fix?
Thanx

**Comment by matfish2** [comment]
The double arrow is NOT for first or last page, but for prev and next chunk. if there is only one chunk (less than 11 pages by default) than both will be disabled

**Comment by vesper8** [comment]
@matfish2 it would have been nice if this was configurable. Currently if you have hundreds of pages it's extremely hard to get to the last page

I would have liked a "first and last" page alternative

**Comment by pnutmath** [comment]
What does `pagination.edge` option do? @matfish2, seems it have no effect ("vue-tables-2": "^1.4.70")
