### ISSUE TITLE
How to get row count dislayed?

### ISSUE THREAD

**Issue by oocar** [matfish2/vue-tables-2#750]
I'd like to get the row count displayed at the bottom of the table after an update.

**Comment by matfish2** [comment]
it's already displayed at the bottom as part of pagination

**Comment by oocar** [comment]
but I want to display elsewhere :)

**Comment by matfish2** [comment]
use `refs`. `this.table.$refs.count`

**Comment by oocar** [comment]
You meant this.$refs.table.count ;) thanks
