### ISSUE TITLE
vue-tables-2 >= 1.5.0 interferes with bootstrap-vue select elements

### ISSUE THREAD

**Issue by sebastian-raubach** [matfish2/vue-tables-2#751]
- Vue.js version: 2.6.10
- consumed using: webpack
- FULL error message (including stack trace):
None
- relevant code:
```
<b-form-select v-model="selected" :options="options" multiple/>
<p>{{ selected }}</p>
<v-server-table ... />
```
- steps for reproducing the issue:

Use Bootstrap-Vue and vue-tables-2 (version 1.5.0 or above) in the same project and place a `v-server-table` on the same page as a `<b-form-select>`. The selection of individual items will no longer happen in the select element.
This was working fine with vue-tables-2 < 1.5.0 and I just verified this by downgrading vue-tables-2.

Any idea why this might be happening?

**Comment by matfish2** [comment]
Not sure what can cause it. Can you create a fiddle to reproduce? (you can use the server-side demo as a starting point)

**Comment by matfish2** [comment]
closed for inactivity
