### ISSUE TITLE
Support Vue Fontawesome 5

### ISSUE THREAD

**Issue by MaurizioRicci** [matfish2/vue-tables-2#760]
Using Fontawesome 5 for sort icons [enhancement] #441 - Vue.js version:

If possibile consider adding support to Vue FortAwesome. So in the sortIcon maybe add a template to render the correct icon instead of the class. Something like:
```
sortIcon:{
   up: '<font-awesome-icon icon="sort-up" />'
   down: '<font-awesome-icon icon="sort-down" />'
}
```

**Comment by justice47** [comment]
Why it can't be done with current semantic like so:
```
sortIcon: { 
    base: 'fa', 
    up: 'fa-sort-up', 
    down: 'fa-sort-down'
}
```
?

**Comment by MaurizioRicci** [comment]
> Why it can't be done with current semantic like so:
> 
> ```
> sortIcon: { 
>     base: 'fa', 
>     up: 'fa-sort-up', 
>     down: 'fa-sort-down'
> }
> ```
> 
> (after adding Font Awesome of course)?

I mean to use Vue font awesome which makes you insert icons as <font-awesome-icon/> components. Moreover apparently using Vue FontAwesome you could import only the icons you need.

**Comment by matfish2** [comment]
https://matanya.gitbook.io/vue-tables-2/custom-template-version-2#font-awesome-sort-icon
