### ISSUE TITLE
How to load Multiple Server Tables on Same page

### ISSUE THREAD

**Issue by Bhavini30** [matfish2/vue-tables-2#761]
- Vue.js version:  2.5.17
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace): 
- relevant code:
- steps for reproducing the issue:

**Comment by matfish2** [comment]
What seems to be the problem? You can use as many instances as you want on
the same page.

**Comment by Bhavini30** [comment]
Got it. Thank you.
