### ISSUE TITLE
Problems with slots for overwriting columns

### ISSUE THREAD

**Issue by sdonnet** [matfish2/vue-tables-2#762]
- Vue.js version: 2.6.10
- vue-tables-2 : v1.5.45

I have created a component, over v-client-table, to embed some global behaviours, such as an action column, forms for create/update/delete each row, ...
My component is as follow :  

**MyClientList.vue :**
```
<template>
   <v-client-table :data="rows" :columns="columns" ...>
   </v-client-table>
</template>
```
**And MyExample.vue :**
```
<template>
   <MyClientList ...>
   </MyClientList>
</template>
```
My problem is that I have created a Vue/Child/Grand Child problem, and I am no more able to create/declare slots for overwriting some columns.

My last test is :  

**MyClientList.vue :**
```
<template>
   <v-client-table :data="rows" :columns="columns" ...>
       <p v-for="nestedSlot in nestedSlots" :key="nestedSlots.indexOf(nestedSlot)">
           <template :slot="nestedSlot" slot-scope="props">
             <span>{{ nestedSlot }}</span>
            </template>
         </p>
   </v-client-table>
</template>
```
**and MyExample.vue :**
```
<template>
   <MyClientList nestedSlots="['columnA']" ...>
        <div slot="columnA" slot-scope="props">
           <some-stuff-to-display>{{ props.row.columnA }}</some-stuff-to-display>
        </div>
   </MyClientList>
</template>
```
with of course "columnA" being one column defined in the rows list, and "nestedSlots" an array of slot names to overwrite, and given as prop.

I found the logic by google-ing the problem ("nested slots"), but I am not able to : overwrite one or more columns.

Do I have missed something ?

Sylvain

**Comment by Dakine135** [comment]
I am having the same issue, Is is possible to modify the columns in a nested way from the "Grandparent"?
