### ISSUE TITLE
Crash on v1.5.45

### ISSUE THREAD

**Issue by sdonnet** [matfish2/vue-tables-2#763]
I was 1.5.43 until this afternoon. I used to list data rows in v-client-table with this version.
But I have upgraded to 1.5.45 and my lists crash now :  

<img width="610" alt="Capture d’écran 2019-11-20 à 18 05 48" src="https://user-images.githubusercontent.com/7150014/69260777-b5350a80-0bc0-11ea-80ae-e88441763af5.png">

I have downgraded to 1.5.43 and re-upgraded to 1.5.45, and that's clear : .43 is OK, .45 is KO.
I have not yet analyzed more.

**Comment by matfish2** [comment]
Are you using a custom template? I've added a class to the generic filter
input field

**Comment by matfish2** [comment]
please try the new version (1.5.46). I've added an existence check for the generic filter element.

**Comment by sdonnet** [comment]
Ok for me. No more errors.
Thanks a lot !
