### ISSUE TITLE
Using InitFilters and filterByColumn generates query param

### ISSUE THREAD

**Issue by mapelli0** [matfish2/vue-tables-2#766]
If I add a custom filter
customFilters: ['statementDate']
and set
initFilters: {statementDate: this.statementDate.format('DD/MM/YYYY')}

the generated param list is
?query%5BstatementDate%5D=22%2F11%2F2019&limit=10&ascending=1&page=1&byColumn=1&statementDate=22%2F11%2F2019

while not using initFilters the generated param list is
?limit=10&ascending=1&page=1&byColumn=1&statementDate=

**Comment by matfish2** [comment]
Unable to reproduce. Custom filters are sent as independent params, whether you set an initial value or not: https://jsfiddle.net/matfish2/cafn602o/

**Comment by mapelli0** [comment]
Sorry about that,
I didn't mention that the customFilter is for a column already in the table.

https://jsfiddle.net/mapelli0/c0mgrxua/2/

**Comment by matfish2** [comment]
I see it's always there as an independent query param regardless of `initFilters`. It just adds it to the "native" query as well when the filter has a value.
I suppose I can remove for native query filters that are not included in `filterable` array.
Or maybe just include all custom filters under `query`? Not sure.

**Comment by mapelli0** [comment]
I think the query param shouldn't be there, but that is just my opinion, also i need to check but if you emit the filter event, the named param changes but the query param does not
