### ISSUE TITLE
Order of elements is reversed after using GroupBy keywords in the Options 

### ISSUE THREAD

**Issue by zzscie** [matfish2/vue-tables-2#767]
- Vue.js version:2.6.1
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

[sample](https://jsfiddle.net/c4v0b97t/16/)
slightly change the 'code' Attr. in data for groupBy testing. vue-table-2 provide a format that in which every element is push into the right group  and right order in the first Time, 
And then click the 'Rs' group row,
'AE' group will show on the screen, but with reversed order

|United Arab Emirates| 
  | Ukraine |   
  | Uganda |  
  | Tuvalu| 
can elements still listed in ascending order in the group with group also in  ascending order?

**Comment by matfish2** [comment]
Unable to reproduce:
![Screenshot_4](https://user-images.githubusercontent.com/1510460/71163074-0a624b80-2255-11ea-826a-ef5c38fddcff.png)
