### ISSUE TITLE
child_row with uniqueKey on structured object doesn't work

### ISSUE THREAD

**Issue by oocar** [matfish2/vue-tables-2#768]
Example my object is { "a":"1", "b":{"c":2, "d":3 }

I want child_row on item "c".
What I did: I put "uniqueKey" option to "b.c"
Result : all the children open when I click on a +row :(

To me, "uniqueKey" works only with attributes **at the root of the objet**.

**Comment by matfish2** [comment]
`uniqueId` doesn't work with dot notation. it should be present at the root level
