### ISSUE TITLE
Back to page the query should same 

### ISSUE THREAD

**Issue by priyeshvadhiya** [matfish2/vue-tables-2#769]
How can I add **URL** parameters to  page, so that multiple filtering and page could be specified in URL, so that going back from other page wouldn't reset these params of last opened  page.

**Comment by matfish2** [comment]
did you try the `saveState` option?

**Comment by priyeshvadhiya** [comment]
@matfish2  yes, i have tried a lot. can you please give me an example.

**Comment by priyeshvadhiya** [comment]
@matfish2  I have try with **saveState** it is store in local storage but, custom filter did'd wok
