### ISSUE TITLE
Having trouble implementing save state

### ISSUE THREAD

**Issue by siddharthghedia** [matfish2/vue-tables-2#770]
relevant code: 

     options: {
        perPage: 10,
        pagination: {
          chunk: 6,
          edge: false
        },
        preserveState: false,
        useVuex: false,
        saveState: true,
        theme: 'bootstrap4',
        template: 'default',
        orderBy: {
          ascending: false,
          column: 'created_at'
        },
        sortIcon: {
          base: 'fa',
          up: 'fa-sort-asc',
          down: 'fa-sort-desc',
          is: 'fa-sort'
        },
        footerHeadings: true,
        headings: {
          selected: function(h) {
            return h('input', {
              attrs: {
                type: 'checkbox',
                id: 'selectAllCheckbox'
              },
              on: {
                click: e => {
                  this.selectAll(e.srcElement.checked)
                }
              },
              ref: 'selectAllCheckbox'
            })
          },
          language: function() {
            let availableLangulagefr = ''
            let availableLangulageen = ''
            let availableLangulagede = ''
            if (this.languageFilter !== 'fr') {
              availableLangulagefr = (
                <li>
                  <a href="#">
                    <img
                      src="https://d1vfyhy3c09bht.cloudfront.net/img/french.png"
                      class="flagIcon"
                    />
                  </a>
                </li>
              )
            }
            if (this.languageFilter !== 'en') {
              availableLangulageen = (
                <li>
                  <a href="#">
                    <img
                      src="https://d1vfyhy3c09bht.cloudfront.net/img/english.png"
                      class="flagIcon"
                    />
                  </a>
                </li>
              )
            }

            if (this.languageFilter !== 'de') {
              availableLangulagede = (
                <li>
                  <a>
                    <img
                      src="https://d1vfyhy3c09bht.cloudfront.net/img/german.png"
                      class="flagIcon"
                    />
                  </a>
                </li>
              )
            }
            return (
              <ul class="language_flages">
                {availableLangulagefr}
                {availableLangulageen}
                {availableLangulagede}
              </ul>
            )
          },
          title: 'Name',
          addresses: 'Location',
          categories: 'Categories',
          region: 'Regions',
          created_at: 'Posted',
          action: 'Action'
        },
        perPageValues: [],
        requestFunction: this.getListing,
        responseAdapter: ({ data }) => {
          this.countFr = data.count_by_lang.frTotal
          this.countEn = data.count_by_lang.enTotal
          this.countDe = data.count_by_lang.deTotal
          return data
        },
        sortable: ['title', 'addresses', 'created_at'],
        filterable: ['title', 'addresses'],
        customFilters: ['category', 'date', 'type']
      },

`Error`
![Screenshot from 2019-12-04 17-42-41](https://user-images.githubusercontent.com/5723637/70141657-8be6a500-16bd-11ea-9a40-16593bbcae81.png)

I'm trying to constantly save table state in localStroage.
There are multiple custom filters, click on custom filter it's not working.
when back to this page it should initialised with localStroage data.
Thanks.

**Comment by matfish2** [comment]
I am unable to reproduce. 
From the error message you're getting it seems like the problem is that the `currentState` var is `null` for some reason. Can you add `console.log(currentState)` to both the `try` and `catch` blocks in `compiled/update-state.js`?

**Comment by siddharthghedia** [comment]
okay, will update that. another problem is when i put name props then custom filter didn't work.

**Comment by matfish2** [comment]
From Docs:

> Note: If you are using the bus and want the event to be "namespaced", so you can distinguish between different tables on the same page, use the `name` prop. The event name will then take the shape of `vue-tables.tableName.eventName`.

**Comment by siddharthghedia** [comment]
okay, thank you.
