### ISSUE TITLE
Custom Request Cancellation Error

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#771]
- Vue.js version: 2.6.10
- consumed using: webpack
- FULL error message (including stack trace):
```
ScsApp.js?id=635af55e08cd11bfbeb3:230459 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at VueComponent.responseAdapter (ScsApp.js?id=635af55e08cd11bfbeb3:230459)
    at Store.undefined (ScsApp.js?id=635af55e08cd11bfbeb3:233541)
    at wrappedMutationHandler (ScsApp.js?id=635af55e08cd11bfbeb3:247435)
    at commitIterator (ScsApp.js?id=635af55e08cd11bfbeb3:247101)
    at Array.forEach (<anonymous>)
    at ScsApp.js?id=635af55e08cd11bfbeb3:247100
    at Store._withCommit (ScsApp.js?id=635af55e08cd11bfbeb3:247231)
    at Store.commit (ScsApp.js?id=635af55e08cd11bfbeb3:247099)
    at Store.boundCommit [as commit] (ScsApp.js?id=635af55e08cd11bfbeb3:247044)
    at VueComponent.commit (ScsApp.js?id=635af55e08cd11bfbeb3:233780)
```

this error points this this file:
get-response-data.js:
```javascript
'use strict';

module.exports = function (response) {

  if (typeof axios !== 'undefined' && typeof response !== 'undefined') return response.data;

  return response;
};```

- steps for reproducing the issue:
First off, thank you so much for the hard work on this table!
Secondly, thank you for allowing a custom request function.
I used this custom request function to create a way to cancel older data requests:
```javascript
requestFunction: function (data) {
                        cancel && cancel();

                        return axios.get(this.url, {
                            params: data,
                            cancelToken: new CancelToken(function executor(c) {
                                // an executor function receives a cancel function as a parameter
                                cancel = c;
                            })
                        }).catch(function (e) {
                            this.dispatch('error', e);
                        }.bind(this));
                    }
```

When the old request is cancelled, the response is undefined. Since you want to receive an axios promise, I can't intercept this on my side. I'd like to see something that either ignores the cancelled request or bypasses it.
Something like this:
```javascript
'use strict';

module.exports = function (response) {

  if (typeof axios !== 'undefined' && typeof response !== 'undefined') return response.data;

  if (typeof response === 'undefined') return {data: []};
  
  return response;
};
```

**Comment by matfish2** [comment]
Please try again with version 1.6.12

**Comment by scs-ben** [comment]
This is resulting in a `Uncaught (in promise) TypeError: Cannot read property 'data' of undefined`

**Comment by scs-ben** [comment]
I am having a hard time tracing down where exactly this is a problem but I can still forego the error by modifying `compiled\methods\get-response-data.js`

**Comment by matfish2** [comment]
Does this happen on the initial request?

**Comment by scs-ben** [comment]
Yes, I have 3 requests on load, 2 are cancelled and the 3rd goes through. I get 2 errors in the console for the 2 cancelled requests.

**Comment by matfish2** [comment]
I suspect this might be specific to initial request. On `compiled/v-server-table.js` can you check what `this.getData(true)` returns? Does it return a promise? is it resolved by the `then` method? is `this.setData(response)` being called? If so, what is the value of `response` in it? You can see the first row in `set-data` should abort if the response if undefined.

**Comment by scs-ben** [comment]
I get the error on each cancelled requests.

The `vue-server-table.js` getData(true) is only returning when on initialization.
The method in `get-data.js` returns with `response` as `undefined` on each call.

**Comment by scs-ben** [comment]
I made these changes to keep the table in "Loading" without errors:
v-server-table.js:
```js
if (this.opts.sendInitialRequest) {
        this.loadState();
        this.getData(true).then(function (response) {
          if (typeof response !== 'undefined') {
            this.setData(response);
            this.loading = false;
          }

          if (this.hasDateFilters()) {
            setTimeout(function () {
              this.initDateFilters();
            }.bind(this), 0);
          }
        }.bind(this));
      }
```

and get-data.js:
```js
  return promise.then(function (response) {
    if (typeof response !== 'undefined') {
      return this.setData(response);
    } else {
      return false;
    }
  }.bind(this));
```

**Comment by matfish2** [comment]
Thanks. I've added those changes to 1.6.13

**Comment by scs-ben** [comment]
Great, thanks! Having the ability to cancel requests saves this table for us. Super stoked.

Do you have a donation page?

**Comment by matfish2** [comment]
I've added a Sponsor button. Thanks!
