### ISSUE TITLE
Custom template(Top pagination) not working

### ISSUE THREAD

**Issue by siddharthghedia** [matfish2/vue-tables-2#772]
- Vue.js version: 
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:

     'use strict'
      const _merge = require('merge')

      const _merge2 = _interopRequireDefault(_merge)

       function _interopRequireDefault(obj) {
            return obj && obj.__esModule ? obj : { default: obj }
      }

       module.exports = function(h, modules, classes, slots) {
        const filterId = 'VueTables__search_' + this.id
        const ddpId = 'VueTables__dropdown-pagination_' + this.id
        const perpageId = 'VueTables__limit_' + this.id
        const perpageValues = require('vue-tables-2/compiled/modules/per-page-values').call(
          this,h)

       const genericFilter = this.hasGenericFilter
          ? h('div', { class: 'VueTables__search-field' }, [
           h(
             'label',
             {
            attrs: { for: filterId },
            class: classes.label
          },
          [this.display('filter')]
        ),
        modules.normalFilter(classes, filterId)
      ])
       : ''

      const perpage =
      perpageValues.length > 1
      ? h('div', { class: 'VueTables__limit-field' }, [
          h('label', { class: classes.label, attrs: { for: perpageId } }, [
            this.display('limit')
          ]),
          modules.perPage(perpageValues, classes.select, perpageId)
        ])
      : ''

      const dropdownPagination =
      this.opts.pagination && this.opts.pagination.dropdown
      ? h('div', { class: 'VueTables__pagination-wrapper' }, [
          h(
            'div',
            {
              class:
                classes.field +
                ' ' +
                classes.inline +
                ' ' +
                classes.right +
                ' VueTables__dropdown-pagination',
              directives: [
                {
                  name: 'show',
                  value: this.totalPages > 1
                }
              ]
            },
            [
              h(
                'label',
                {
                  attrs: { for: ddpId }
                },
                [this.display('page')]
              ),
              modules.dropdownPagination(classes.select, ddpId)
            ]
          )
        ])
      : ''

      const columnsDropdown = this.opts.columnsDropdown
      ? h('div', { class: 'VueTables__columns-dropdown-wrapper' }, [
        modules.columnsDropdown(classes)
      ])
      : ''

      const footerHeadings = this.opts.footerHeadings
       ? h('tfoot', [h('tr', [modules.headings(classes.right)])])
        : ''

       const shouldShowTop =
         genericFilter ||
         perpage ||
         dropdownPagination ||
         columnsDropdown ||
         slots.beforeFilter ||
         slots.afterFilter ||
         slots.beforeLimit ||
         slots.afterLimit

          const tableTop = h(
           'div',
           {
            class: classes.row,
             directives: [
              {
              name: 'show',
              value: shouldShowTop
           }
         ]
       },
        [
        h('div', { class: classes.column }, [
        h(
          'div',
          {
            class:
              classes.field +
              ' ' +
              classes.inline +
              ' ' +
              classes.left +
              ' VueTables__search'
          },
          [slots.beforeFilter, genericFilter, slots.afterFilter]
        ),
           h(
          'div',
          {
            class:
              classes.field +
              ' ' +
              classes.inline +
              ' ' +
              classes.right +
              ' VueTables__limit'
          },
          [slots.beforeLimit, perpage, slots.afterLimit]
        ),
        dropdownPagination,
        columnsDropdown
      ])
        ]
       )

      return h('div', { class: 'VueTables VueTables--' + this.source }, [
       tableTop,
        slots.beforeTable,
        h('div', { class: 'header_pagination' }, [
          modules.pagination(
        (0, _merge2.default)(classes.pagination, {
          wrapper:
            classes.row + ' ' + classes.column + ' ' + classes.contentCenter,
          nav: classes.center,
          count: classes.center + ' ' + classes.column
          })
        ),
        modules.dropdownPaginationCount()
        ]),
        h('div', { class: 'table-responsive' }, [
         h(
          'table',
          {
          class:
            'VueTables__table ' +
            (this.opts.skin ? this.opts.skin : classes.table)
         },
         [
          h('thead', [
            h('tr', [modules.headings(classes.right)]),
            slots.beforeFilters,
            modules.columnFilters(classes),
            slots.afterFilters
          ]),
          footerHeadings,
          slots.beforeBody,
          h('tbody', [
            slots.prependBody,
            modules.rows(classes),
            slots.appendBody
          ]),
          slots.afterBody
        ]
      )
      ]),
       slots.afterTable,
        modules.pagination(
       (0, _merge2.default)(classes.pagination, {
        wrapper:
          classes.row + ' ' + classes.column + ' ' + classes.contentCenter,
        nav: classes.center,
        count: classes.center + ' ' + classes.column
        })
      ),
      modules.dropdownPaginationCount()
       ])
        }

I am trying to set page from `saveState` all the data was set as expected but only top pagination is not set when returning back to main page, (bottom pagination is working as expected.)

Image: 
![Screenshot from 2019-12-06 18-00-53](https://user-images.githubusercontent.com/5723637/70323294-6dfe7900-1852-11ea-894e-7eeee010a63a.png)

**Comment by matfish2** [comment]
Setting pagination programmatically currently works on a per-component basis. I am in the process of creating a new templating engine that would solve this issue and allow a less cumbersome way for creating custom templates. In the meantime, you can get the current page value from the saved state object (look at localStorage) and manually set the page on top pagination based on unique ref :`this.$refs.table.$refs.pagination2.setPage(page)`. Somewhat hacky but should work

**Comment by siddharthghedia** [comment]
If i modify the custom template then got this error: 
![Screenshot from 2019-12-09 15-09-11](https://user-images.githubusercontent.com/5723637/70424816-00db2580-1a96-11ea-936e-dc1d23870dcd.png)

**Comment by matfish2** [comment]
Sorry, I can't help with debugging custom templates. Once you change the code you are in the best position to debug
