### ISSUE TITLE
Input type number keep changing value after one click on spinner

### ISSUE THREAD

**Issue by ionutraducanu** [matfish2/vue-tables-2#773]
I have used your demo fiddle to show the bug. https://jsfiddle.net/pbfo1sk0/

It happens only in Chrome, please try clicking on the up arrow and see how the value keep changing until you take the mouse from there.

From what I have been able to debug it has something with the mouseup listener added by the table in resizeable-columns.js

Thank you!

**Comment by matfish2** [comment]
Thanks for reporting the issue. Should be fixed now

**Comment by ionutraducanu** [comment]
@matfish2 Awesome, thank you!
