### ISSUE TITLE
setData called 2 times

### ISSUE THREAD

**Issue by ionutraducanu** [matfish2/vue-tables-2#776]
Hello @matfish2 , I updated to the latest version to have 'fix #773' and now I have the following issue because of #771 (https://github.com/matfish2/vue-tables-2/commit/3883dc97e7a61c53b81b12e1d137547852bb553b) 

I am using a custom function for responseAdapter() and it is called twice.

In compiled/v-server-table.js and lib/v-server-table.js **this.setData(response)** is called twice and is crashing my code.

I have removed one of the this.setData and this.loading and the everything works.
Can you, please, remove the double call? 

Thank you,
Ionut

**Comment by matfish2** [comment]
Thanks for reporting the issue. Can you try again with 1.6.16 please?

**Comment by ionutraducanu** [comment]
@matfish2  you are simply the best! thank you so much!
