### ISSUE TITLE
Server Table Shows Loading after Loaded

### ISSUE THREAD

**Issue by scs-ben** [matfish2/vue-tables-2#777]
My server table will sometimes show loading when the result from the server came back with no data.

**Comment by matfish2** [comment]
which version of the package are you using? might be related to the fixed #776

**Comment by scs-ben** [comment]
I'm using version 1.6.16

I am using the custom requestFunction, however, the response is not being cancelled. It's just a standard data: [], count: 0

**Comment by matfish2** [comment]
mmm. That's odd. There is a call to `this.loading = false` right after `setData` on initial request (v-server-table.js:73). Can you please add `console.log` at the beginning of the function (before `if (typeof response === 'undefined') return;`)  to see what `response` equals?

**Comment by scs-ben** [comment]
For me, I only get 1 output right when page loads. This function is never called a second time.

```
created: function created() {
      if (!this.opts.requestFunction && !this.url) {
        throw 'vue-tables-2: you must provide either a "url" prop or a custom request function. Aborting';
      }

      _created(this);

      if (!this.vuex) {
        this.query = this.initQuery();
        this.initOrderBy();
        this.customQueries = this.initCustomFilters();
      }

      if (this.opts.sendInitialRequest) {
        this.loadState();
        this.getData(true).then(function (response) {
          console.log(response);
          if (typeof response === 'undefined') return;
```

**Comment by scs-ben** [comment]
I'm assuming that in general the "Loading" page is overwritten by the actual data but `loading = false` seems to never be set?

**Comment by scs-ben** [comment]
I can resolve the problem by adding a `this.loading = false;` to `get-data.js`

```js
  var promise = this.sendRequest(data);
  if (promiseOnly) return promise;
  return promise.then(function (response) {
    if (typeof response !== 'undefined') {
      this.loading = false;
      return this.setData(response);
    } else {
      return false;
    }
  }.bind(this));
};
```

**Comment by matfish2** [comment]
Loading state should be handled by the first call.
I guess for some reason the handler is skipped in your case (the only reason i can think of is an undefined response, as this is the only barrier).
However, since you say this fixes the issue I'll add it, if only temporarily

**Comment by scs-ben** [comment]
the response can't be undefined to get to that stage, so for some reason the setData isn't setting the loading state properly

**Comment by matfish2** [comment]
Did you try the new version? Was the issue fixed?

**Comment by scs-ben** [comment]
Yes, the table now shows "No matching records"
