### ISSUE TITLE
resetQuery() throws error

### ISSUE THREAD

**Issue by byrd1089** [matfish2/vue-tables-2#778]
- Vue.js version: 2.x
- consumed using: webpack
- FULL error message: "0 is read only"

I'm using the server table with my own filter input in the application nav bar.  
When the user clears the input, I'd like to clear the table. 

I thought resetQuery() would do this but it is throwing the above error.

**Comment by matfish2** [comment]
Thank you for reporting this issue. Please try again with version 1.6.18
