### ISSUE TITLE
vue-bootstrap-datetimepicker not working inside v-server-table

### ISSUE THREAD

**Issue by mostafalaravel** [matfish2/vue-tables-2#780]
Hello , 

I try to use vue-bootstrap-datetimepicker inside the server table  but it not working : the date table is shown but without CSS and not on a right position !

````

                    <v-server-table :columns="columnCompetences" :options="options" :show-pagination="false"
                                    v-bind:ref="'wheel_'+wheel.id"  @loaded="onLoaded"
                                    v-bind:url="'/api/competences?wheelId='+wheel.id">
                        <span slot="status" slot-scope="{row}">
					        <i :class="statusColor(row)" aria-hidden="true" class="fa fa-stop"></i>
                                <date-picker :config="beginDateOptions" autocomplete="off"

                                             placeholder="Select date"
                                ></date-picker>
                        </span>
````
BUT :  if I put the  `vue-bootstrap-datetimepicker` outside of the  `<v-server-table ` it works without issues !

inside table, (without CSS)
![image](https://user-images.githubusercontent.com/25288712/70797847-a7c90580-1da5-11ea-87e7-c2e6aedd21af.png)

outside table : (no issue)
![image](https://user-images.githubusercontent.com/25288712/70797899-d050ff80-1da5-11ea-9826-112ee8ef098b.png)

**Comment by matfish2** [comment]
The package offers you the platform for including vue-compiled templates. The visibility of the compiled HTML is beyond the scope of this package. 
From the images attached I see that even inside the table you have CSS applied to the picker. You might need to tweak it to match the context in which it is rendered in the DOM,
