### ISSUE TITLE
Is there a way to capture the query (client-side)

### ISSUE THREAD

**Issue by tspeciale-jc** [matfish2/vue-tables-2#782]
- Vue.js version: latest
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace): No error
- relevant code: Unsure
- steps for reproducing the issue: N/A

We are hoping to capture user queries in a database.  Is there a way to retrieve the query that a user types into there?

**Comment by matfish2** [comment]
`this.$refs.myTable.query`

**Comment by tspeciale-jc** [comment]
Apprecaite it @matfish2.  Is this documented anywhere or...maybe a much more ignorant Vue question, but is `this.$refs` the way to access any parent component?

**Comment by matfish2** [comment]
Hi, It's not documented, but maybe I'll add it somewhere... 
You can read about refs here: https://vuejs.org/v2/api/#ref. They are basically handles by which you can catch any child component to fetch a property or run a method
