### ISSUE TITLE
querySelector is not a function

### ISSUE THREAD

**Issue by ochanje210** [matfish2/vue-tables-2#787]
- Vue.js version: 2.5.13
- consumed using: webpack
- FULL error message (including stack trace): There was no explicit error message. However, I have found that `this.$el.querySelector` is `undefined` from `set-filters-dom.js`.
- relevant code:
```js 
var el = this.$el.querySelector('.VueTables__search__input');
```
from set-filters-dom.js
- steps for reproducing the issue:
use version: 2.0.0-beta-1
render v-server-table

(it works from version 1.6.16)

**Comment by matfish2** [comment]
Unable to reproduce. At which point are you getting the `querySelector is not a function`?
