### ISSUE TITLE
Module not found when using vuex and vue-router [BUG]

### ISSUE THREAD

**Issue by lucianobosco** [matfish2/vue-tables-2#788]
I'm using the vuex feature. 
```
Vue.use(ServerTable, {}, true, 'bootstrap4')
```

My table name is `catalog_list` and it's using `preserveState: true,`
```
<v-server-table name="catalog_list" :columns="headers" :options="options">
```
I've created a vuex module `catalog_list` which is imported in my main store
```
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

import catalog_list from '@/components/products/store/catalog_list.js'

export const store = new Vuex.Store({

    modules: {
        catalog_list,
    },
})
```
My vuex module has some dummy content for testing purposes
```
const catalog_list = {

    namespaced: true,

    state: {
        test: 'lorem',
    },

    getters: {
        test: state => {
          return state.test
        }
    },
}

export default catalog_list
```
When loading the component for the first time, the `test` property is mapped correctly and it's shown in my component. Also, in my dev-tool I can see the getter `catalog_list -> test: "lorem"`
```
<template>

    <div>
        {{ test }}
        
        <v-server-table
            name="catalog_list"
            :columns="headers"
            :options="options">
        </v-server-table>
    </div>

</template>

<script>

import { mapState } from 'vuex'

export default {
    name: 'product-table-component',

    data() {
        return {
            headers: ['id', 'name','type','price','status','actions'],
            options: {
                preserveState: true,
                
                requestFunction: function (data) {

                    // Request
                    return axios.get('/products', {
                        params: data
                    }).catch(function (e) {
                        this.dispatch('error', e)
                    }.bind(this))

                }.bind(this),

                responseAdapter: function(resp) {
                    // Format response
                    var data = this.getResponseData(resp)
                    let array = Object.values(data.data)
                    // Return data to table
                    return { data: array, count: data.count }
                }
            }
        }
    },

    computed: {
        ...mapState('catalog_list',['test'])
    },
}
</script>
```
The issue comes when I navigate to another route and get back to the table component. I see these messages:
`Unregister module: catalog_list`
`Register module: catalog_list`
then the `LOADING`, `SET_DATA` and `LOADED` mutations occurs.

But finally, I get an error:
**`[vuex] module namespace not found in mapState(): catalog_list/`**

It looks like the unregister event is destroying my custom module but never registering again..
Any clue about how to solve this?

EDIT: I found out that state is preserved, but getters are not.

**Comment by matfish2** [comment]
module should not be unregistered at all when `preserveState` is set to `true`. I wasn't able to reproduce the issue

**Comment by polosson** [comment]
Hi!  
Since [this merge](https://github.com/matfish2/vue-tables-2/pull/793) and version `1.6.24`, a new issue appeared: when I navigate to another route, then come back to the route where there is the table component, a warning appear in console:

```
[vuex] state field "MyTable" was overridden by a module with the same name at "MyTable"
```

Where `MyTable` is the `name` prop passed to the component. And, the behavior of this table becomes weird, specially with pagination and other data changes... Rendering is not correct.

If I revert the changes of [this commit](https://github.com/matfish2/vue-tables-2/pull/793/commits/11203ddab03e74dbfda676323d30580cc5b43396) everything works fine again. Maybe we should reconsider this fix? And make further tests to fix the OP issue correctly?  
Thanks! :smiley:

**Comment by matfish2** [comment]
Serves me right for merging a PR so haphazardaly... I rolled back the change, Still unable to reproduce the original issue though
