### ISSUE TITLE
Vue $refs points to wrong object (refresh is not a function)

### ISSUE THREAD

**Issue by ianfoulds** [matfish2/vue-tables-2#789]
- Vue.js version: 2.6.11, vue-tables-2 version: 2.0.0-beta.1
- consumed using: webpack
- When attempting to call published vue-tables-2 methods via this.$refs some methods (refresh) are not found. If the $children property is inspected on the $ref.xxx object the table can be found at position 0 which does contain all the published methods and plenty more.

The only published methods on the this.$refs.xxx element are:
getOpenChildRows
getResponseData
setFilter
setOrder
setPage
toggleChildRows

```
<template>
    <div id="app" class="mt-3">
        <v-server-table ref="table" :url="serviceUri" :columns="tableColumns" />
    </div>
</template>

<script>

import Vue from 'vue';
import {ServerTable, Event} from 'vue-tables-2';

Vue.use(ServerTable, {}, false, 'bootstrap4');

export default {

    data() {
        let serviceUri = "/webapi/surveys";
        return {
            serviceUri: "/webapi/surveys",
            tableColumns: [ 'name', 'description' ],
        };
    },

    mounted() {
        // Very weird, the actual table item is a child!!
        if (this.$refs.table.$children.length) {
            let table = this.$refs.table.$children[0];
            table.refresh();
        }
    }, 
}
</script>

```
- steps for reproducing the issue:
If you use the above code you can access the refresh() function, but if you try this.$refs.table.refresh() it will fail as the method does not exist.

**Comment by matfish2** [comment]
Fixed. Please download latest version (2.0.0-beta.2)
