### ISSUE TITLE
Error in adding custom columns

### ISSUE THREAD

**Issue by lkho** [matfish2/vue-tables-2#79]
- Vue.js version: 2.1.10
- consumed using: webpack
- FULL error message (including stack trace):

```
vue-tables-2: Undeclared template. All templates must be declared in the 'columns' prop. TypeError: Cannot create property '[object Object]' on string 'data[0].__actions'
    at VueComponent.set$1 [as $set] (http://localhost:8080/app.js:5939:14)
    at VueComponent.<anonymous> (http://localhost:8080/app.js:45346:14)
    at Array.forEach (native)
    at VueComponent.<anonymous> (http://localhost:8080/app.js:45345:26)
    at Array.forEach (native)
    at VueComponent.module.exports (http://localhost:8080/app.js:45343:15)
    at VueComponent.boundFn [as addCustomColumns] (http://localhost:8080/app.js:5227:12)
    at VueComponent.module.exports (http://localhost:8080/app.js:45907:8)
    at VueComponent.boundFn [as setData] (http://localhost:8080/app.js:5226:14)
    at VueComponent.<anonymous> (http://localhost:8080/app.js:46582:14)
```

- relevant code:
`vue-tables-2\lib\methods\add-custom-columns.js`
```javascript
module.exports = function () {

  try {
    this.data.forEach(function (row, index) {

      this.customColumns.forEach(function (custom) {
        // this line is not calling $set() with correct parameters, it should be
        // this.$set(this.data[index], custom, this.opts.templates[custom]);
        this.$set('data[' + index + '].' + custom, this.opts.templates[custom]);
      }.bind(this));

    }.bind(this));
  } catch (e) {
    console.error(`vue-tables-2: Undeclared template. All templates must be declared in the 'columns' prop.`, e);
  }
}
```
- steps for reproducing the issue:
add any custom columns

**Comment by matfish2** [comment]
This is a custom error letting you know that you must declare templates in
the columns prop

**Comment by lkho** [comment]
but `this.customColumns` is computed from `vue-tables-2\lib\computed\custom-columns.js`:
```javascript
import diff from '../helpers/array-diff'

module.exports = function() {
      return diff(this.templatesKeys, this.Columns);
}
```
where this.Columns is
```javascript
    computed:{
      Columns: function() {
        return this.columns;
      }
    }
```

so if i declare custom columns in both templates and columns prop then `this.customColumns` becomes empty?

BTW the above error is caused by wrong parameters, if I change the line to the suggested one the error is gone. Maybe that's because of the change of the $set() method signature from the previous Vue versions.

**Comment by lkho** [comment]
i think this is just a migration issue:
https://vuejs.org/v2/api/#vm-set
https://v1.vuejs.org/api/#vm-set

**Comment by matfish2** [comment]
You are right. Some of the custom columns logic is redundant and is basically a residue from v1. I will remove it.

**Comment by achchu93** [comment]
For anyone who is struggling with this issue can be recover with one solution. I too had this issue. then what i did is i just put the custom column name in the column property. Then it went away. I have used Vue2.

             `columns :['code', 'name', 'start_date', "Actions"],
                 module :{
                     id : "",
                     code : "",
                     name : "",
                     start_date : "",
                },
                tableOptions:{
                    templates: {
                        Actions: (h, row) => {
                            return <form-actions onDelete={ this.openIt } onEdit={ this.editIt }></form-actions>;
                        }
                    }
                },`

Credit goes to @shakee93 . He showed me the solution.

**Comment by matfish2** [comment]
From the docs:

> Templates must be declared in the columns prop

**Comment by achchu93** [comment]
@matfish2 yeah, it is in the doc. But you know, it didn't throw an error when i used it normally. First i didn't declared it in the columns prop. It was fine until i create multiple tables. But suddenly it came once i created my 4th table. So i just posted this to anyone who can come up with this error. All are not experts. So this will be helpful to newbies.
