### ISSUE TITLE
Adding listColumns in options changes the value of the data in the row.

### ISSUE THREAD

**Issue by vincemukiiri** [matfish2/vue-tables-2#797]
- Vue.js version: 2.6.10
- Vue Tables version: 2.0.0-beta.3
- consumed using: webpack

- steps for reproducing the issue:
In the example below, the value `props.row.active` changes from 1/0 to 'active'/'inactive'.
```
data: {
  columns: [
    'name',
    'active'
  ],
  data: [
    { name: 'Joe', active: 1 },
    { name: 'Jane', active: 0}
  ],
  options: {
    listColumns: {
      active: [
        {
          id: '1',
          text: 'active'
        },
        {
          id: '0',
          text: 'inactive'
         }
      ]
    }
  }
}
```
This behaviour is different from the previous version of vue-tables-2 where the value would remain the same as initially provided and then one could change what value is displayed using column templates.

**Comment by matfish2** [comment]
Thank you for the report. Should be fixed now (v2.0.2)
