### ISSUE TITLE
Custom filter column does not work in mounted

### ISSUE THREAD

**Issue by alexsantm2019** [matfish2/vue-tables-2#799]
Hi everyone,
I have a vue-tables which works normally, but the custom filter does not. I had created a select filter using filter__{column}, but when the screen render, my select does not work. It only works when I click in a row select (which I created to delete multiple rows)

This is my screen when I render:
![Screenshot_1](https://user-images.githubusercontent.com/48456214/74686420-7d2d6b80-519f-11ea-8441-0c13e1faac99.png)

When I click in any select from the left, my select works
![Screenshot_2](https://user-images.githubusercontent.com/48456214/74686421-7dc60200-519f-11ea-98b6-6c41f5ca365c.png)

This is my full code:

<template>

    <div class="container" ref="content">
        
        <div class="row justify-content-center">
            {{conditionalMetadata}}
            <v-client-table :columns="columns" :data="rowdata" :options="options" id ="table_atc" 
                ref="table-empresa" class="w-100">

                    
                        <div slot="child_row" slot-scope="props" class="row p-4 bg-black" >   
                                                   
                            
                            <div class="col-lg-12">
                                <div v-if= "props.row.serDescription">
                                    <strong><h5>Service Description:</h5></strong>
                                    {{props.row.serDescription}}
                                </div>
                                <div v-else class="text-center">
                                    <h5>No Interactions</h5>
                                </div>
                            </div>                        
                            
                            
                        </div>
                    

                    
                    
                    

                            
                            <template slot="serGroup" slot-scope="props"  >
                                <div class="text-center align-middle">
                                    <div v-if="props.row.serGroup==1">
                                        <div>Service</div>                             
                                    </div>
                                    <div v-else>
                                        <div>Installation</div>                             
                                    </div>                            
                                </div>
                            </template>
                            

                            
                            <template slot="serVessel" slot-scope="props"  >
                                <div class="text-center align-middle">
                                    <div v-if="props.row.serVessel==0">
                                        <div class="alert alert-danger">NO</div>                             
                                    </div>
                                    <div v-else>
                                        <div class="alert alert-success">YES</div>                             
                                    </div>                            
                                </div>
                            </template>
                            

                            
                            <template slot="serDeck" slot-scope="props"  >
                                <div class="text-center align-middle">
                                    <div v-if="props.row.serDeck==0">
                                        <div class="alert alert-danger">NO</div>                             
                                    </div>
                                    <div v-else>
                                        <div class="alert alert-success">YES</div>                             
                                    </div>                            
                                </div>
                            </template>
                            

                            
                            <template slot="serCabin" slot-scope="props"  >
                                <div class="text-center align-middle">
                                    <div v-if="props.row.serCabin==0">
                                        <div class="alert alert-danger">NO</div>                             
                                    </div>
                                    <div v-else>
                                        <div class="alert alert-success">YES</div>                             
                                    </div>                            
                                </div>
                            </template>
                                                        

                            
                                    <template slot="actions" slot-scope="props"  >
                                        <div class="text-center align-middle">
                                            
                                            <a  :href="goToEdit(props.row.serId)"
                                                class="btn btn-outline-primary btn-sm"
                                                data-toggle="tooltip" data-placement="top" title="Edit">
                                                <i class="fa fa-edit"></i>
                                            </a>                             
                                        </div>
                                    </template>

                                    
                                        
                                        <template slot="selected" slot-scope="props">
                                            <div class="text-center">
                                                <input type="checkbox" v-model="selectedIds" @click="select" :value="props.row.serId">        
                                            </div>
                                        </template>                                        
                                             

                                        <div slot="beforeTable" class="mb-2 botonDeleteAll" v-if="selectedIds.length>0">
                                            <button type="button" class="btn btn-sm btn-danger" @click="deleteAll()"><i class="fas fa-trash"></i> Delete All <span class="badge badge-light">{{this.selectedIds.length}}</span></button>
                                        </div>    

                                        
                                        <div slot="filter__selected" class="text-center p-1">                                                              
                                            <input type="checkbox" v-model="allSelected">
                                        </div>   
                                         
                                    

                            

                    
                    
                    

                        
                        
                        
                                                          
                                <div slot="filter__serGroup" >                  
                                    <select 
                                            id="serGroup" 
                                            name="serGroup" 
                                            @change="searchByServicesMetadata($event)" 
                                            class="form-control"
                                            v-model="keywordServicesMetadata">
                                        <option value="">Select Group</option>
                                        <option
                                            :value="ser.id"
                                            :key="ser.id"
                                            v-for="ser in servicesMetadata">
                                            {{ ser.name }}
                                        </option>                                        
                                    </select>
                                </div>
                                

                                                       
                                <div slot="filter__serVessel"> 
                                    <select 
                                            id="serVessel" 
                                            name="serVessel" 
                                            @change="searchByConditionalVesselMetadata($event)" 
                                            v-model="keywordConditionalMetadata"
                                            class="form-control">
                                        <option value="">Select Group</option>
                                        <option
                                            v-for="con in conditionalMetadata"
                                            :value="con.id"
                                            :key="con.id">
                                            {{ con.name }}
                                        </option>
                                    </select>      
                                </div>
                                

                                                       
                                <div slot="filter__serDeck"> 
                                    <select 
                                            id="serDeck" 
                                            name="serDeck" 
                                            @change="searchByConditionalDeckMetadata($event)" 
                                            v-model="keywordConditionalMetadata"
                                            class="form-control">
                                        <option value="">Select Group</option>
                                        <option
                                            v-for="con in conditionalMetadata"
                                            :value="con.id"
                                            :key="con.id">
                                            {{ con.name }}
                                        </option>
                                    </select>      
                                </div>
                                      

                                                       
                                <div slot="filter__serCabin"> 
                                    {{conditionalMetadata}}<br>
                                    {{this.conditionalMetadata}}<br>
                                    <select 
                                            id="serCabin" 
                                            name="serCabin" 
                                            @change="searchByConditionalCabinMetadata($event)" 
                                            v-model="keywordConditionalMetadata"
                                            class="form-control">
                                        <option value="">Select Group</option>
                                        <option
                                            v-for="con in conditionalMetadata"
                                            :value="con.id"
                                            :key="con.id">
                                            {{ con.name }}
                                        </option>
                                    </select>  
                                </div>

                                                                                            

                                

                        
                        
                                            

                </v-client-table>

        </div>
    </div>
</template>
```
<script>
    /* *** SERVICES *** */
        import ServiceServices from '../../../services/service/ServiceServices.js';
        import Conf from './../../../services/conf'
    /* *** SERVICES *** */
   
    import {ServerTable, ClientTable, Event} from 'vue-tables-2';
    Vue.use(ClientTable);

    /* *** MENSAJE TOAST *** */
    import CxltToastr from 'cxlt-vue2-toastr'
    import 'cxlt-vue2-toastr/dist/css/cxlt-vue2-toastr.css';
    Vue.use(CxltToastr)
    var toastrConfigs = {
        position: 'top right',
        showDuration: 8000,
        progressBar: true,
    }
    Vue.use(CxltToastr, toastrConfigs)
    /* *** FIN MENSAJE TOAST *** */
    
    export default {
        name:'indexservice',        
        data(){
            return {
                rowdata: [],                
                servicesMetadata: [],
                conditionalMetadata: [],
                keywordServicesMetadata:'',
                keywordConditionalMetadata:'',
                allSelected: false,
                selected: [],
                selectedIds: [],                
                keywordConfirmationDate:'',
                options: {
                            uniqueKey:'serId',
                            // rowClassCallback(row) {
                            //     // Da color a toda la fila de acuerdo a una condicion
                            //     return row.decStatus==0 ? 'alert alert-danger' : 'alert alert-success';
                            // },      
                            clientMultiSorting:true,             
                            highlightMatches: true,
                            sortable: true,
                            editable: true,
                            striped: true,
                            columnsDropdown: false,
                            footerHeadings:true,
                            //perPage:2,
                            texts: {
                                filter: "Filter:",
                                filterBy: 'Filter by {column}',
                                count:'Showing {from} to {to} of {count} records|{count} records|One record ',
                                limit:"Records:",
                                page:"Page:",
                                noResults:"No matching records",
                                loading:'Loading...',
                                defaultOption:'Select {column}',
                                columns:"Columns",
                            },
                            filterByColumn:true,                         
                            //groupBy :'vslName',
                            noDataMsg: 'No data to show',
                            customFilters: [
                                {
                                    name: "filterByServicesMetadata",
                                    callback: function(row, query) {
                                        return row.serGroup == query;
                                    }
                                }, 
                                {
                                    name: "filterByConditionalVesselMetadata",
                                    callback: function(row, query) {
                                        return row.serVessel == query;
                                    }
                                }, 
                                {
                                    name: "filterByConditionalDeckMetadata",
                                    callback: function(row, query) {
                                        return row.serDeck == query;
                                    }
                                }, 
                                {
                                    name: "filterByConditionalCabinMetadata",
                                    callback: function(row, query) {
                                        return row.serCabin == query;
                                    }
                                },                                                                                                 
                            ],
                            //customFilters:['producto'],
                            //initFilters:{tarPeriodo: '2001'},
                            //toMomentFormat: true,
                            emptyResultsMsg: 'No results for this filter',
                            noDataMsg: 'No data to show',
                            loadingMsg: 'Loading ...',
                            perPageValues: [5, 10,25,50,100,200,300],
                            sortIcon: {
                                base: 'fa',
                                up: 'fa fa-angle-up',
                                down: 'fa fa-angle-down'
                            },
                            collapseGroups:true,
                            preserveState: true,
                            //skin: "table table-striped table-bordered table-hover table-sm table-fixed",
                            skin: "table table-striped table-bordered table-hover table-sm table-fixed",
                            perPage: 10,
                            orderBy: { ascending:true },
                            childRowTogglerFirst:true,
                            //footerHeadings: true,
                            pagination: {
                                chunk: 10,
                                dropdown: false,
                                nav: 'fixed',
                                edge: true,
                                align:'center',
                            },
                            headings: {
                                selected:'',
                               serGroup:'Group',                            
                               serName:'Service Name',
                               serDescription:'Service description',
                               serVessel:'Service for Vessel?',
                               serDeck:'Service for Deck?',
                               serCabin:'Service for Cabin?',
                               serIcon:'Icon',
                            },
                            filterable: [
                                //'serGroup',
                                'serName',
                                //'serDescription',
                                //'serVessel', 
                                //'serDeck',
                                //'serCabin',
                                //'serIcon',
                            ],                            
                },
                columns: [
                   'selected',
                   //'decId',
                   'serGroup',
                   'serName',
                   //'serDescription',
                   'serVessel', 
                   'serDeck',
                   'serCabin',
                   //'serIcon',
                   'actions'
                ],                
            }
        },

        watch: {
            allSelected: function () {
                this.selectAll()
            }
        },        

        methods: {
            goToEdit(id){
                let server = Conf.server 
                let ruta = "service/" + id + "/edit";
                return ruta;
            },

            // Metodos para seleccionar varios registros y eliminar
                selectAll: function() {
                    this.selectedIds = [];

                    if (this.allSelected) {
                        for (let i in this.rowdata) {
                        this.selectedIds.push(this.rowdata[i].serId);
                        }
                }
                },
                select: function() {
                    this.allSelected = false;
                },
                deleteAll() {                
                    if (confirm("Would you like to delete selected items?")) {
                        let data =this.selectedIds;
                        ServiceServices.deleteAll(data).then((response) => {

                            // Mensaje de confirmación
                            this.$toast.success({
                                title:'Success',
                                message:'Row(s) deleted successfully',
                                progressBar:true,
                                position: 'top right',
                                showDuration:2000,
                                timeOut: 2500
                            });
                            // Fin Mensaje de confirmación

                            this.selectedIds= [];
                            this.getAll();
                        }).catch((error) => {
                            console.log("Error al eliminar: " + error);
                            //console.log(error.response);
                        });
                    }
                },                
            // Fin Metodos para seleccionar varios registros y eliminar
            
            getAll() {
                    ServiceServices.getAll().then((response) => {
                        this.rowdata = response.data.data;
                    }).catch((error) => {
                        console.log("Error: " + error);
                    });
            },     
            
            getServicesMetadata() {
                    ServiceServices.getServicesMetadata().then((response) => {
                        this.servicesMetadata = response.data.data;
                    }).catch((error) => {
                        console.log("Error: " + error);
                    });
            }, 
            getConditionalMetadata() {
                    ServiceServices.getConditionalMetadata().then((response) => {
                        this.conditionalMetadata = response.data.data;
                    }).catch((error) => {
                        console.log("Error: " + error);
                    });
            },

            /**** Filtros personalizados *** */

                searchByServicesMetadata(event) {
                    this.keywordServicesMetadata = event.target.value;
                    Event.$emit("vue-tables.filter::filterByServicesMetadata", this.keywordServicesMetadata);
                },
                searchByConditionalVesselMetadata(event) {
                    this.keywordConditionalMetadata = event.target.value;
                    Event.$emit("vue-tables.filter::filterByConditionalVesselMetadata", this.keywordConditionalMetadata);
                },                
                searchByConditionalDeckMetadata(event) {
                    this.keywordConditionalMetadata = event.target.value;
                    Event.$emit("vue-tables.filter::filterByConditionalDeckMetadata", this.keywordConditionalMetadata);
                }, 
                searchByConditionalCabinMetadata(event) {
                    this.keywordConditionalMetadata = event.target.value;
                    Event.$emit("vue-tables.filter::filterByConditionalCabinMetadata", this.keywordConditionalMetadata);
                },                                 

            /**** Fin Filtros personalizados *** */            
            
        },        

        mounted() {
            this.getServicesMetadata();
            this.getConditionalMetadata();
            this.getAll();


            
        }
    }
</script>
```

**Comment by matfish2** [comment]
Since you are populating `servicesMetadata` on mounted using an ajax request it stands to reason that your select will be initially empty until the response is assinged to the variable. You can make mounted `async` and add `await` to all requests in mounted. Then use some `loading` flag to indicate the table is ready to be rendered, and add a `v-if=loading` on the table component.

**Comment by kalex375** [comment]
Faced with the same problem. Inputs do not get update value from outside
