### ISSUE TITLE
Programmatic updates for all state

### ISSUE THREAD

**Issue by seaneagan** [matfish2/vue-tables-2#80]
- Vue.js version: 2.0.1

Most if not all of the table state can be _initialized_ programatically via the "options" interface, but AFAICT, only `page` (via `setPage()`) can be _updated_ programatically.  For example I am wanting to support browser history as the user updates table fields like the query, limit (page size), and sort column and direction.  But there is no way to update these fields on route change (due to browser navigation).  Ideally it would be nice to be able to set all fields in a single call so as not to trigger reactivity multiple times.

Or maybe there is a better way to do this already?

**Comment by matfish2** [comment]
Well, if you are using Vuex then the state is completely exposed to your store. Otherwise you can dive in using `ref` and manipulate the desired properties. I will probably add more setters in the near future.
