### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by KingmakerNikhil** [matfish2/vue-tables-2#801]
How can i add a tooltip to the data showing in the datatable?

**Comment by KingmakerNikhil** [comment]
<div v-for="column in columns" :key="column" :slot="column" slot-scope="props" class="tooltip">
          <span class="tooltip tooltiptext">{{'MEHMET' + props.row.bene_first_name}}</span>
        </div>
Is there something wrong in this code?

**Comment by matfish2** [comment]
Use the `templates` option
https://matanya.gitbook.io/vue-tables-2/templates

**Comment by KingmakerNikhil** [comment]
Templates works only for one column at a time, in my case columns are not static, columns change according to the data. i need to set tooltip for every cell in my page.
