### ISSUE TITLE
Can't change the sort direction programmatically

### ISSUE THREAD

**Issue by jamie-pi** [matfish2/vue-tables-2#802]
- Vue.js version: 2.6.10
- consumed using: webpack

We are looking to be able to change the sort direction and column programmatically using the server side version of the table. Is this possible at the moment?

We are able to use the transform to change the AJAX request to get the correct response from the server, but there doesn't seem to be a way in the docs to update the UI in the table to show the correct sort direction and column.

We've tried changing the 'orderBy' object in the transform method, but it doesn't seem to update the UI. Thanks in advance!

**Comment by matfish2** [comment]
```js
this.$refs.[myTable].setOrder(column, isAsc)
```

**Comment by jamie-pi** [comment]
Thank you, that works. I was hoping there would be a way to only update the UI without firing a new AJAX request, but I can find a workaround using this.
