### ISSUE TITLE
Editable row: [Vue warn]: Missing required prop: "data"

### ISSUE THREAD

**Issue by rollinstar** [matfish2/vue-tables-2#806]
- Vue.js version: 2.6.10
- consumed using: webpack
- FULL error message (including stack trace):
```
[Vue warn]: Missing required prop: "data"
[Vue warn]: Error in render: "TypeError: Cannot read property 'filter' of undefined"
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'filter' of undefined
```
- relevant code:
```
<v-client-table :columns="columns" v-model="data" :options="options">
    <div slot="name" slot-scope="{row, update, setEditing, isEditing, revertValue}">
        <span @click="setEditing(true)" v-if="!isEditing()">
            <a>{{row.name}}</a>
        </span>
        <span v-else>
            <input type="text" v-model="row.name">
           <button type="button" class="btn btn-info btn-xs"
                                    @click="update(row.name); setEditing(false)">Submit</button>
           <button type="button" class="btn btn-default btn-xs"
                                    @click="revertValue(); setEditing(false)">Cancel</button>
        </span>
    </div>
</v-client-table>
```
- steps for reproducing the issue:

I am trying to make a editable row table. I declared `v-model` instead of `prop` and `editableColumns: ['name']` into the options. But it doesn't work. Could please see it? What is the wrong?

**Comment by xsHaDoWnx** [comment]
```<v-client-table :columns="columns" :data="YouData" :options="options">```

**Comment by matfish2** [comment]
@xsHaDoWnx he should use `v-model`, not `data`, for the edited data to sync up with the original dataset, @rollinstar I was unable to reproduce. What version of the package are you using?

**Comment by rollinstar** [comment]
@matfish2 I'm using version 1.4.70.

**Comment by matfish2** [comment]
editable rows are not supported in this version. Please update to the latest version (or at least to latest before 2.0)
