### ISSUE TITLE
ServerTable $refs.table.data is undefined

### ISSUE THREAD

**Issue by webdevnerdstuff** [matfish2/vue-tables-2#808]
- Vue.js version: 2.6.10
- vue-tables-2 version: 2 and above
- consumed using: webpack
- FULL error message (including stack trace): n/a
- relevant code: $refs.table
- steps for reproducing the issue:

1. Have a v-server-table
2. Load data via `@loaded`
3. After the table has loaded with data populating the table the `$refs.table` object does not container `$refs.table.data` and equals undefined.

I'm not sure if this is something that changed from version 1 to version 2 of the plugin. I couldn't find anything in the documentation that it did. Perhaps I missed it?

This does not have data:
```javascritpt
this.$refs.table.data
```

This does load data
```javascript
Event.$on('vue-tables.loaded', function (data) {
    // data is returned
});
```

**My current fix**

To fix the issue I reverted back to version 1.6.18 of vue-tables-2, and the data is there like it should be and is back to working perfectly.

**Comment by webdevnerdstuff** [comment]
@matfish2 Did you close this because it was fixed in a new release?

**Comment by matfish2** [comment]
Yes
