### ISSUE TITLE
ServerTable $refs.table.getData is not a function

### ISSUE THREAD

**Issue by Cristianmg6** [matfish2/vue-tables-2#812]
- Vue.js version: 2.5.17
- consumed using: webpack
- FULL error message (including stack trace):
TypeError: _this.$refs.table.getData is not a function
    at VueComponent.<anonymous> (app.js:2107)
- relevant code:

```html
<v-server-table ref="table" :columns="columns" :url="url" :options="options">
	<template :slot="column" v-for="column in editable_columns"  slot-scope="props">
		<input type="text" class="form-control" :value="props.row[column]" :placeholder="labels[column]" @focusout="updateField(column, props.row, $event)">
	</template>
</v-server-table>
```

```javascript
this.$http.post(
	route(this.route_update_field),
	{field: field, id: row[this.pk], value: value},
	{
		headers: {
			'x-csrf-token': document.head.querySelector('meta[name=csrf-token]').content
		}
	}
).then(response => {
	this.$refs.table.getData();
	if(response.ok){
		//toast success
	}else{
		//toast error
	}
}).catch(error => {
	//toast error
	console.log(error);
}).finally(() => {
	this.processing = false;
});
```
Hello,
I'm using ServerTable and I need to reload Data preserving current filters on custom method.
I've tried to use getData() method, but console returns error.
Using refresh() method instead works correctly, but losing current filters.

I've been searching in other issues but I don't know how to fix this.
Thank you in advance.

**Comment by iamsajithk** [comment]
I am also facing this issue. .refresh() is working but .getData() is not working. As per the documentation the correct function I need is .getData(). When I consoled the this.$refs.table there is no such method exists in that.
