### ISSUE TITLE
vue-tables.row-click doesn't fire in 2.x versions

### ISSUE THREAD

**Issue by brettpappas** [matfish2/vue-tables-2#816]
- Vue.js version: any 2.x.x 
- consumed using: webpack
- FULL error message (including stack trace): no event emitted when clicking on rows other than `focusChanged`
- relevant code: `@row-click`
- steps for reproducing the issue: add `@row-click="onRowClick"` to `v-client-table` and check console. You also cen verify by using Vue DevTools.

I was able to take the same code and just swap out the version to 1.6.18 and previous and it works as expected.

**Comment by matfish2** [comment]
Unable to reproduce with the latest version. There is a passing test for this event which runs as part of CI. 
![Screenshot 2020-04-09 00 58 09](https://user-images.githubusercontent.com/1510460/78837766-6831c380-79fd-11ea-9039-7f0bcfead20f.png)

**Comment by brettpappas** [comment]
Just found a different plugin that was calling Vue.mixin() that registered a global click function that stopped propogation and prevented `@row-click`. Still not sure why it only affected that particular event when others continued to work like filter event, and why it didn't affect 1.x.x versions.
