### ISSUE TITLE
Expansion the groupBy functionality

### ISSUE THREAD

**Issue by PadusSofija** [matfish2/vue-tables-2#819]
Hi. Thank you for the library. 
I would like to ask you if it is possible to add a groupBy for multiple fields. 
Example:
Let's assume we have a table with fields: Country, City, Street, ...
As a result, we would like to have all the data grouped by Country and then inside each country grouped by the city. After the selection of both county and city, the rows can be shown. 
![exPNG](https://user-images.githubusercontent.com/14282837/79350809-96a12880-7f40-11ea-96a4-47bfb6e12574.PNG)

**Comment by matfish2** [comment]
Added to the private repo
