### ISSUE TITLE
issue with dependency: babel-helper-vue-jsx-merge-props

### ISSUE THREAD

**Issue by vinayakkulkarni** [matfish2/vue-tables-2#823]
- Vue.js version: 2.6.11
- consumed using: (browserify/webpack/rollup): webpack
- FULL error message (including stack trace): 
![Screenshot from 2020-04-20 12-27-20](https://user-images.githubusercontent.com/19776877/79723159-e85fff00-8302-11ea-950e-853d9eb4b7fa.png)
- steps for reproducing the issue: basic example

**Comment by MaurizioRicci** [comment]
Yes me too, i came here for this kind of problem.

**Comment by matfish2** [comment]
I've moved this dependency from dev to dependencies. Please try again now

**Comment by vinayakkulkarni** [comment]
Can confirm, version `2.0.20` solves the issue :)
