### ISSUE TITLE
In which format have I to return data to vue-tables-2 with Server Table

### ISSUE THREAD

**Issue by sergeynilov** [matfish2/vue-tables-2#824]
Hello,
In my vue/cli 4 / Bootstrap 4.3 app I use vue-tables-2 and reading Server Table
implementation here https://matanya.gitbook.io/vue-tables-2/server-table

from server side(laravel 6) I return :

```
        return response()->json([
            'data'                 => $activityLogs,
            'count'                => $activity_logs_count
        ], 200);

```
and in console I see returned data : https://imgur.com/a/2iGUfKS

But in the console I have errors :
```
vue-tables-2: invalid 'count' property. Expected number, got undefined
...
set-data.js?7175:11 count equals undefined
...
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: props.data.forEach is not a function"
...
found in
---> <RLTableBody>
       <VtTableBody>
       
vue.runtime.esm.js?2b0e:1888 TypeError: props.data.forEach is not a function
    at _default (VtTableBody.js?1a4e:36)
                        

```             
I suppose that problem in format of returned data.
In vue file I have :

        <div id="activity_logs_data_table">
            <v-server-table :url="apiUrl + '/activity-logs-filter'" :columns="columns" :options="tableOptions">
            </v-server-table>
        </div>
   ...
 
                tableOptions: {
                    // see the options API
                    requestFunction(data) {
   
                        this.is_page_loaded = false
                        let credentialsConfig= JSON.parse(JSON.stringify(settingCredentialsConfig))
                        credentialsConfig.headers.Authorization = 'Bearer ' + this.$parent.$parent.currentLoggedUserToken
                        return axios.get(this.url, {
                            params: data
                        }, credentialsConfig ).catch(function (error) {
                            console.log('requestFunction error::')
                            console.error(error)
                        })

                    } // requestFunction: (data) => {
                },
...
 
```
    "axios": "^0.19.0",
    "vue": "^2.6.10",
    "vue-tables-2": "^2.0.14" 

```
Which must be valid format for returned data?

Thanks!

**Comment by matfish2** [comment]
Is `axios` available on the `window` scope? If not, the package will assume the data in directly on the response object, whereas in `axios` it is on `response.data`.
This can be fixed in two ways:
a. make `axios` available to the `window` scope
b. write a `responseAdapter` (see options API)

**Comment by sergeynilov** [comment]
Thanks!
Looks like setting axios available on the window scope:
```
<script>
    import axios from 'axios'
    window.axios = axios

```Helped me!
