### ISSUE TITLE
Slot for all headings?

### ISSUE THREAD

**Issue by add1ct3dd** [matfish2/vue-tables-2#825]
Hi,

Sorry this is less of an issue but more of a struggle finding it in the documentation or understanding the code...

I understand you can template out slots for specific headings in your table (for example if you have an ID column, you can template the ID heading), that's fine. Is there a way to generically template all headings, without using the templates (I don't want to add custom templates when we use the component in multiple datatables, and this slot editing would only apply to one)? Hopefully this makes sense, and I've just missed the slot scope for it!

Thanks!

Matt

**Comment by matfish2** [comment]
You can wrap the table with your own wrapper component which declares those heading templates, and use this wrapper instead of the core table component

**Comment by add1ct3dd** [comment]
> You can wrap the table with your own wrapper component which declares those heading templates, and use this wrapper everywhere instead of the core table component

Ok cheers I'll take a look!

**Comment by add1ct3dd** [comment]
I've just taken a look now, that seems to make sense, but how do I make use of both grids throughout the project?

The examples in the docs instantiates it like so:

```
Vue.use(ClientTable, {}, false, 'bootstrap3', {
    sortControl: MySortControl
});
```

But then how do I continue using the base grid in other areas of the application? It seems the examples only cover using one or the other, not both? 

Thanks!

**Comment by matfish2** [comment]
The two components are independent. You just register both (call Vue.use twice, once with ClientTable and once with ServerTable)

**Comment by matfish2** [comment]
What do you mean by "both grids"?

**Comment by matfish2** [comment]
If you mean the grid without the wrapper, just use v-client-table and not your wrapped version

**Comment by add1ct3dd** [comment]
> If you mean the grid without the wrapper, just use `v-client-table` and not your wrapped version

Sorry maybe it's my lack of understanding, or lack of explanation. Let me see if I can explain it better!

```
Vue.use(ClientTable, {}, false, 'bootstrap3', {
});

Vue.use(ClientTable, {}, false, 'bootstrap3', {
    sortControl: MySortControl
});
```


If I declare it as above, I have access to <v-client-table> in my components, but if I declare it twice (one stock, one with my custom templates), how do I then differentiate between both to make use of them?

**Comment by matfish2** [comment]
Unfortunately, you can't declare it twice. You can only register the component once with or without template overrides. Is there a reason you would want two different templates in the same app?

**Comment by add1ct3dd** [comment]
> Unfortunately, you can't declare it twice. You can only register the component once with or without template overrides. Is there a reason you would want two different templates in the same app?

Essentially different functionality. So, for the grids I currently have the stock templates work fine and everything works as expected.

With the new grid, we have user actions in & around the grid that would change a status icon in the column heading (essentially like a validation icon). The problem I have is I can't do this via slot scopes because the grid data is variant/user defined, so we don't have fixed columns. I did see in docs/other issues in github that you can template specific columns as below:

```
<template slot="h__selected" slot-scope="props">
            <input type='checkbox' id='checkbox' @click='selectAll()'>
```

But I couldn't see how I could target 'every' header via a slot template and add my own stuff into it.

Hopefully those use cases make more sense in my quest to be able to modify table headings on the fly :D

**Comment by matfish2** [comment]
You can use v-for to target all headers dynamically:

```html
<template :slot="`h__${header}`" slot-scope="props" v-for="header in headers">
            <input type='checkbox' id='checkbox' @click='selectAll(header)'>
</template>
```

**Comment by add1ct3dd** [comment]
> You can use v-for to target all headers dynamically:
> 
> ```
> <template :slot="`h__${header}`" slot-scope="props" v-for="header in headers">
>             <input type='checkbox' id='checkbox' @click='selectAll(header)'>
> </template>
> ```

I didn't even think of that...! Thank you so much, problem solved :)
