### ISSUE TITLE
I got 401 error from request in vue-tables-2 with Server Table

### ISSUE THREAD

**Issue by sergeynilov** [matfish2/vue-tables-2#826]
Hello!
In my vue/cli 4 app I got 401 error from request in vue-tables-2 with Server Table.
I make :

```
    <div id="activity_logs_data_table">
        <v-server-table :url="apiUrl + '/adminarea/activity-logs-filter'" :columns="columns" :options="tableOptions">
        </v-server-table>
    </div>
    ...
            tableOptions: {
                // see the options API

                requestFunction(data) {
                    let credentialsConfig= JSON.parse(JSON.stringify(settingCredentialsConfig)) // Setting Bearer token
                    credentialsConfig.headers.Authorization = ' Bearer ' + this.$parent.$parent.currentLoggedUserToken

                    return axios.get(this.url, {
                        params: data
                    }, credentialsConfig ).catch(function (error) {
                        console.log('requestFunction error::')
                        console.error(error)
                    })

                } // requestFunction: (data) => {
            }, // tableOptions: {

```

And in browser checking the request I see Bearer token in different format, I expect : https://imgur.com/a/Y3xsZuW

Running the same url in other page( without vue-tables-2  ) :

I recieve data from the server :

```
            this.credentialsConfig.headers.Authorization = 'Bearer ' + this.currentLoggedUserToken
            // Request URL: http://local-ctasks-api.com/api/adminarea/activity-logs-filter?query=&limit=10&ascending=1&page=1&byColumn=0
            axios.get(this.apiUrl + '/adminarea/activity-logs-filter?query=&limit=10&ascending=1&page=1&byColumn=0', this.credentialsConfig)
                .then(({ data }) => {
                    console.log('/adminarea/activity-logs-filter data::')
                    console.log(data)

                    this.activityLogsRows = data.data
                })
                .catch(error => {
                    this.showPopupMessage('Settings Editor', error.response.data.message, 'warn')
                })

```
and in browser I see Authorization in Bearer Format: https://imgur.com/a/iBjnf4D

Are the some additive options missed ?

Thanks!

**Comment by matfish2** [comment]
This question does not seem related to the package. It's a server-side issue (could be that you need to send other headers from the client, but you already know how to do that

**Comment by sergeynilov** [comment]
I edited my original post : I had invalid code blocks , now to links to imgur are visible.
1) Printscreen is request of vue-tables-2 with Server Table
I pay attention that “Bearer ” token is not visible there, but 
in requestFunction I send “Bearer ” token 
`    credentialsConfig.headers.Authorization = ' Bearer ' + this.$parent.$parent.currentLoggedUserToken
`and it does not work

2) Running the same url in other page( without vue-tables-2 ) it works ok
and in Printscreen of this request I see “Bearer ” token.

I think that is the issue. If vue-tables-2 with Server Table has 
support of “Bearer ” token ? I read API and do not remember such option...

**Comment by matfish2** [comment]
This is an axios issue. Vue-tables does not intervene with the request parameters. I managed to send headers using it as the second parameter. Please check your code.

**Comment by sergeynilov** [comment]
From API doc:
```
options: {
    requestFunction: (data) => {
        return axios.get(this.url, {
            params: data
        }).catch(function (e) {
            this.dispatch('error', e);
        });
    }
}

```
 second parameter is object with keys. I see 1 key “params”.
 Which key must have my credentialsConfig param ?
