### ISSUE TITLE
Access to the options inside scoped templates

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#827]
Hi, @matfish2 ! You've done a tremendous work implementing the scoped templates system! 

But I have a question: is there any opportunity to get access to the options object inside templates component? I have a lot of custom implementations based on them and sometimes it is really useful to throw some additional options to the templates. For example, I have complicated logic of no-data message, which requires some data from the higher level components. In earlier versions I used to get it from the options object. And know I feel some pain using structures like `ctx.parent.$parent.$parent.$parent`. I appreciate all the things you've already done and are going to do to develop this brilliant component.

**Comment by matfish2** [comment]
Thank you for your kind words. Per you request, I have added an `opts` property to all of the components.

**Comment by VladZen** [comment]
Great! Thx! You're awesome!
