### ISSUE TITLE
Change focus to next row

### ISSUE THREAD

**Issue by theveloped** [matfish2/vue-tables-2#829]
First, great work on vue-tables-2! It seems to have a massive amount of options and is very wel implemented. 

I'm a bit at a loss how to approach performing operations on the DOM based on the row position and order. At the moment I have a table with input fields in one of the rows, I would however like to move the focus to the input field in the next row. Is there any way to get the data and row/cell DOM elements based on the row index?

**Comment by matfish2** [comment]
It sounds like you can use tabIndex for that. You can disable the table tabbing by setting `tabbable` to `false`

**Comment by theveloped** [comment]
Thank you for the quick reply! Didn't know about the tabbable option. For now I'm using a `ref` on the input cell based on the `data.index` and `data.column` fields like so:

```
<template slot="quantity" slot-scope="data">
    <input type="number" 
        :ref="data.column + data.index.toString()" 
        v-model.number="data.row.quantity" 
        v-on:keyup.enter="nextCell(data)">
</template>
```

The method `nextCell` is then specified as below to change the focus to the next cell in the same column. It's a very specific use case but on the off chance someone is looking to do something similar this might help.

```
nextCell (data) {
  var nextCellRef = data.column + (data.index + 1).toString()
  if (this.$refs[nextCellRef] != undefined) {
    this.$refs[nextCellRef].focus()
  }
},
```
