### ISSUE TITLE
Using tableHeading template and header slots (h__xyz) together leads to  "TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by samuelmoser** [matfish2/vue-tables-2#830]
I'm using the  VtTableHeading as a startpoint for customizing the header: https://github.com/matfish2/vue-tables-2/blob/master/templates/VtTableHeading.vue
 
`Vue.use(ClientTable, {}, false, 'bootstrap3', {
  tableHeading: MyTableHeading
})`

If I try to overwrite one table header with
`<div slot="h__selected">`

I get the following error:

`vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property '_renderProxy' closes the circle"
found in
---> <MyTableHeading> at src/components/commons/table/MyTableHeading.vue
       <RLTableHeading>
         <VtTableHeading>
           <RLHeadingRow>
             <VtHeadingsRow>
               <RLTableHead>
                 <VtTableHead>
                   <RLTable>
                     <VtTable>
                       <RLClientTable>
                         <VtClientTable>`

**Comment by VladZen** [comment]
Have the same problem, but when I set th template as function like
```
const headings = {
  ip: function (h) {
    return <span>
      IP
      <small class="no-bold">
        Use this IP in domain's A entry
      </small>
    </span>
  }
}
```

**Comment by VladZen** [comment]
@samuelmoser 
The reason for that is incorrect attempt to render `props.heading`, which is presented as `vnode`. I worked around it, changing `VtTableHeading` template as following:
```
<span class="VueTables__heading"
          :title="props.title">
      <template v-if="typeof props.heading === 'string'">
        {{ props.heading }}
      </template>

      <vnodes :vnodes="props.heading"
              v-else />
</span>
```

and don't forget to define `vnodes` component:
```
vnodes: {
      functional: true,
      render: (h, ctx) => ctx.props.vnodes
}
```
