### ISSUE TITLE
Divide header in multiple rows

### ISSUE THREAD

**Issue by igorizviekov** [matfish2/vue-tables-2#831]
Is there a way to divide selected columns in the header into few separate rows?
<img width="448" alt="Screen Shot 2020-05-05 at 15 18 42" src="https://user-images.githubusercontent.com/56380850/81065212-b72b2580-8ee3-11ea-8c57-9cbccdd68b6a.png">

**Comment by matfish2** [comment]
At the moment there is no designated option for this. You can use the `prependHead` slot to add an additional row for grouping columns. Granted it will not handle ungrouped columns - such as `head 3` in your example - by applying rowspan=2, but it's close enough.

**Comment by igorizviekov** [comment]
I'll try that, thanks!
