### ISSUE TITLE
Virtual Pagination - Implemented for server table?

### ISSUE THREAD

**Issue by jeffcj** [matfish2/vue-tables-2#835]
- Vue.js version: 2.6.11
- consumed using: webpack
- FULL error message (including stack trace): N/A
- relevant code: N/A
- steps for reproducing the issue: N/A

Using (premium) version 2.0.24. It looks like virtual "infinite scroll" pagination is only implemented in v-client-table. If I'm correct, is the same functionality planned for v-server-table?

**Comment by matfish2** [comment]
Hi, you are indeed correct. Server-side virtual pagination wasn't implemented yet. I plan to add it shortly (hopefully this week). I'll update here once it is deployed. Thank you for your patience.

**Comment by matfish2** [comment]
I have added the functionality. It doesn't require any change to your server-side code. Let me know if you need further assistance.

**Comment by jeffcj** [comment]
Pagination seems to work as expected. Thanks! Having some challenges getting sticky headers to work, but I will investigate further on my side.

**Comment by matfish2** [comment]
I think the problem with sticky headers is related to resizable columns. Can you try and disable them and see if that works? (` resizableColumns: false,`)

**Comment by jeffcj** [comment]
You are correct. When resizableColumns: false it works as expected. When resizableColumns: true the th gets set to position: relative instead of position: sticky.

**Comment by matfish2** [comment]
Pushed a fix. Should work now even with resizeable columns
