### ISSUE TITLE
Using Tailwind Theme Configuration - Table Header Styling will be ignored

### ISSUE THREAD

**Issue by samuelmoser** [matfish2/vue-tables-2#838]
I'm using Tailwind (in the paid table version) and want to style the header like this:

```import defaultTailwind from 'vue-tables-2/compiled/themes/tailwind'

const vueTableStyleOptions = () => {
  return {
    ...defaultTailwind(),
    td: 'px-4 py-2',
    th: 'bg-black'
  }
}
export default vueTableStyleOptions
```

then the `<th>` has empty class attributes:
![image](https://user-images.githubusercontent.com/31036187/82789515-b47c7a00-9e6a-11ea-9f23-b8a9a320186f.png)

**Comment by matfish2** [comment]
Thank you for reporting the issue. It has been fixed. Please pull the latest version
