### ISSUE TITLE
Add custom attribute in TAG <td>

### ISSUE THREAD

**Issue by klebermachado** [matfish2/vue-tables-2#839]
Hi,
I need to create a custom attribute for the TAG <td>, but I haven't found any way to do this.
See what I want to reproduce:
```
<tbody>
    <tr>
        <td data-label="Name">Jhon</td>
        <td data-label="Age">18</td>
        <td data-label="City">New York</td>
    </tr>
</tbody>
```

Is this possible?

**Comment by matfish2** [comment]
You can achieve this using a [custom template](https://matanya.gitbook.io/vue-tables-2/custom-template) for the [VtTableCell](https://github.com/matfish2/vue-tables-2/blob/master/templates/VtTableCell.vue) component.

**Comment by matfish2** [comment]
Pull the latest version. The you can achieve this using a [custom template](https://matanya.gitbook.io/vue-tables-2/custom-template) for the [VtTableCell](https://github.com/matfish2/vue-tables-2/blob/master/templates/VtTableCell.vue) component:

```vue
<template>
    <td :tabindex="props.tabIndex" :class="props.classes" :data-label="props.opts.headings[props.column]">
        <vnodes :vnodes="props.content"/>
    </td>
</template>

<script>
    export default {
        name: "MyTableCell",
        props: ['props'],
        components: {
            vnodes: {
                functional: true,
                render: (h, ctx) => typeof ctx.props.vnodes === 'object' ? ctx.props.vnodes : [ctx.props.vnodes]
            }
        }
    }
</script>
```
