### ISSUE TITLE
Method "setLimit" is missing from ServerTable (Licensed Version)

### ISSUE THREAD

**Issue by ollieBaker** [matfish2/vue-tables-2#840]
- Vue.js version: 2.6.11
- consumed using: Webpack via Vue CLI
- FULL error message  
TypeError: this.$refs.table.setLimit is not a function
- relevant code:
this.$refs.table.setPage(1) //OK
this.$refs.table.setLimit(1) //Fails

- steps for reproducing the issue:
As above

The method [described here](https://matanya.gitbook.io/vue-tables-2/methods) setLimit is missing from the object exposed through a ref. The methods setPage, setOrder etc are all present. 

Is this by design? Is there another way to programatically set the page size / limit?

**Comment by matfish2** [comment]
Thanks for the bug report. Please try with the latest version (2.0.29)

**Comment by ollieBaker** [comment]
Thanks for fixing. Can you update the version on xscode? That's where I am installing from since I bought my license through there. The site says `Last release: about 2 months ago (v2.0.15)` so it's a bit out of date.

**Comment by matfish2** [comment]
I think their stats aren't up-to-date. Anyway, I've just pushed the latest to the private repo and synced it in XSCODE. please try to pull the latest and lmk if you experience any issues

**Comment by ollieBaker** [comment]
`2.0.29` is installing now and the fix works. Thanks for your quick response.
