### ISSUE TITLE
Empty skin option

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#841]
Hi, @matfish2 ! I found out that there is no possibility to set skin option as empty string to reset basic css classes. I guess [that is why](https://github.com/matfish2/vue-tables-2/blob/45a076486ae192c27bca8e3f02b252370b09e45d/lib/components/renderless/RLTable.js#L10)

**Comment by matfish2** [comment]
I think the idea was to deprecate the skin option, as the theme's `table` property already covers it. If you'll reset the skin to an empty string and modify the theme's `table` property you'll be able to apply your classes. I'd love to hear suggestions on how to tackle this more elegantly
