### ISSUE TITLE
override default filter with custom filter

### ISSUE THREAD

**Issue by jtyagi** [matfish2/vue-tables-2#846]
- Vue.js version: 2.6.11
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:
Is there a way to override the default filter (or search algorithm) with a custom filter(search algorithm). Because when I am adding the custom filter, the Custom filter is not getting all the values I think the default is applied first then only which values pass through the default filter comes to the custom filter.

**Comment by matfish2** [comment]
Did you look here: https://matanya.gitbook.io/vue-tables-2/client-table/filtering-algorithm?
