### ISSUE TITLE
Is sorting/grouping algorithm possible similar to the filtering algorithm?

### ISSUE THREAD

**Issue by theveloped** [matfish2/vue-tables-2#848]
I'm wondering if it is possible to sort and group a client table based on values that are not directly in available in the data structure. This seems possible for filtering using [a custom filtering algorithm](https://matanya.gitbook.io/vue-tables-2/client-table/filtering-algorithm) and I'm wondering if there is something similar for sorting and grouping.

**Comment by matfish2** [comment]
did you look at custom sorting: https://matanya.gitbook.io/vue-tables-2/custom-sorting?

**Comment by theveloped** [comment]
This is perfect! Not sure how I missed this. A similar feature for grouping would also be super useful.
