### ISSUE TITLE
Is it possible to customize the Controls Row?

### ISSUE THREAD

**Issue by danegigi** [matfish2/vue-tables-2#849]
Hey @matfish2,

Nice vue plugin. But I find it hard to customize the table especially the Controls Row at the very top of the table.
Is there a way to disable it so I can create a new custom set of controls? I saw that there's an option for beforeTable which will add additional row below the Controls row for me to put in some custom actions. I just find it unclean having 2 rows of controls if I could fit everything in one row. 

Thanks

**Comment by matfish2** [comment]
You can use a [custom template](https://matanya.gitbook.io/vue-tables-2/custom-template) to remove the controls row. Edit [VtDataTable](https://github.com/matfish2/vue-tables-2/blob/master/templates/VtDataTable.vue)
