### ISSUE TITLE
Sorting bug

### ISSUE THREAD

**Issue by gkurdej** [matfish2/vue-tables-2#85]
- Vue.js version: 2.1
- consumed using: webpack
- FULL error message (including stack trace): nothing
- relevant code:
- steps for reproducing the issue:

Open page with table and click first column to revert sort order. Sort order reverted. Now you cannot revert it again. Vuex ascending property is fixed to false. You can sort by other columns, but ascending is always false. If first sorting click is for other column, bug doesn't appear at all. Bug is only for Vuex version.

**Comment by matfish2** [comment]
I followed your scenario to the letter but couldn't replicate this bug. Can you post a link to a reproduction of the bug?
