### ISSUE TITLE
Documentation: child row docs use old slot scope syntax

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#850]
- Vue.js version: 2.6
- consumed using: webpack
- no error message

In the docs about Child Rows, an old and deprecated slot-scope syntax is used. https://matanya.gitbook.io/vue-tables-2/child-rows
The first example should be this:

```diff
- <template slot="child_row" scope="props">
+ <template v-slot:child_row="props">
  <div><b>First name:</b> {{props.row.first_name}}</div>
  <div><b>Last name:</b> {{props.row.last_name}}</div>
</template>
```

It seems most examples use older syntax ;-)

**Comment by matfish2** [comment]
Thank you. Fixed
