### ISSUE TITLE
Documentation: CONTRIBUTING.md file missing

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#851]
In the README there is a broken link to CONTRIBUTING.md. I was looking for ways to contribute to the documentation :)
It's best CONTRIBUTING.md contains some starting points, guidelines or tips 👍

**Comment by matfish2** [comment]
Thank you. I've added the CONTRIBUTING file. Feel free to add any data you deem helpful and I'll merge your PR
