### ISSUE TITLE
Unchecking / hiding columns breaks VtSortControl index

### ISSUE THREAD

**Issue by kirkbross** [matfish2/vue-tables-2#852]
- Vue.js version: **Demo Codepen**
- consumed using: -
- FULL error message (including stack trace): **No Error**
- relevant code: **VtSortControl & VtTableHeading**
- steps for reproducing the issue: 

1. Go to the below fork of the Codepen demo
2. Click the Columns dropdown
3. Uncheck "View Record" and close the Columns dropdown.
4. Click to sort the "Created At" column and watch the "Updated At" column sort icon toggle.

Depending on how many columns you hide, that's how many columns offset the "active" sort icon will be. I'm not sure where to address this, in the sort component or upstream.

[CODEPEN](https://jsfiddle.net/kirkbross/r9u7h0fs/)

**Comment by matfish2** [comment]
Thank you for the report. Should be fixed now

**Comment by kirkbross** [comment]
> Thank you for the report. Should be fixed now

Yep. Many thanks!
