### ISSUE TITLE
Client table disables multimedia keys (Browser_back and Browser_forward)

### ISSUE THREAD

**Issue by kevintechie** [matfish2/vue-tables-2#854]
- Vue.js version: Nuxt 2.13.3
- consumed using: (browserify/webpack/rollup) nuxt plugin
- FULL error message (including stack trace): no error message
- relevant code: see vue-tables-2 demo site
- steps for reproducing the issue:

1. Go to vue-tables-2 demo site: https://jsfiddle.net/matfish2/jfa5t4sm/
1. Hover mouse over demo table area (not any of the code areas)
1. Press the mouse's back button (use a mouse w/ multimedia back button functionality such as Logitech M705)
1. Notice nothing happens
1. Hover over code area and press mouse's back button
1. Notice the browser navigates to previous page

On a standard website (i.e. not on JSFiddle), this behavior completely disables the multimedia back and forward buttons for every other page on the website after navigating to a page that contains the v-client-table -- even after navigating away from the page with the problematic component.

I have not specifically tried this with the server table, but assume it displays the same behavior.

**Comment by kevintechie** [comment]
It looks like the bug is caused by the `preventDefault()` call on the `mouseup` event listener on the document.  https://github.com/matfish2/vue-tables-2/blob/351a5c4c7b877d1058200dd6896c884ddefc9c4d/lib/helpers/resizeable-columns.js#L65

**Comment by kevintechie** [comment]
This is a serious bug for anyone that uses assistive technology that relies on the browser to see button 3 (Browser_Back) and 4 (Browser_Forward) to navigate the web.

**Comment by kevintechie** [comment]
Closed w/o comment? Is this fixed? Will it be fixed?

**Comment by matfish2** [comment]
It was fixed. Look at the close message. It references a commit

**Comment by kevintechie** [comment]
Got it. Missed the commit id on my phone. Sorry. Thanks.
