### ISSUE TITLE
Vuejs 3 compatibility?

### ISSUE THREAD

**Issue by vincent-lu** [matfish2/vue-tables-2#855]
Hi sorry if this question has already been answered. Does anyone know what's the current state of the compatibility with vuejs 3?

Thanks!

**Comment by bjerh** [comment]
Any comments on this? :-)

**Comment by matfish2** [comment]
Working on it. Turns out to be more complicated than I thought.

**Comment by matfish2** [comment]
vue3 version now available for subscribers

**Comment by hisuwh** [comment]
Will v3 always be subscribers only or is this just an initial thing?

**Comment by caseroft** [comment]
Hello, I add myself to the question, is version 3 always going to be premium? I use it in an open source project and I am in love with it and I don't want to change it. but i need to migrate to vue3
