### ISSUE TITLE
How to Reset Client Table to Initial State

### ISSUE THREAD

**Issue by 19peaches** [matfish2/vue-tables-2#858]
- Vue.js version: 2.6.11
- consumed using: webpack
- FULL error message (including stack trace): no error message
- relevant code: 

My table is being used to display search results from a remote API within a Bootstrap Modal. When the user closes the modal, I need to empty or otherwise reset the entire table back to it's initial state. Search result data is passed in as a prop, then the prop is reset to any empty array. I am calling:

```
this.$refs.table.resetQuery()
```

which does reset the Filter ... but NOT the pagination. When the modal is reopened and a search is run, the pagination shows negative values and there is no current page set.

```
Showing -99 to 0 of 208 records
```

- steps for reproducing the issue:

1. Begin with empty table
2. Fill table with results array
3. empty table data array
4. Fill table with new results array
5. pagination shows errors

Is there a method or a reliable way to functionally reset the table to initial render?

**Comment by Silverhawk83** [comment]
I have the same problem.

**Comment by DaxtonChen** [comment]
I have the same problem.

**Comment by matfish2** [comment]
Seems like the most simple solution would be to use a v-if flag on the table and set it to false when the modal is closed. This way the whole component will re-render when the modal is opened the next time

**Comment by 19peaches** [comment]
@matfish2 

I tried that first, doesn't do the trick.

**Comment by sahilxjain** [comment]
@matfish2 @19peaches I have the same issue and your solution worked for me using v-if to re render whole component. For me that tricked worked by using a timeout of 1 millisecond

**Comment by matfish2** [comment]
Yes, as @sahilxjain pointed out you may need to use a timeout (can be 0) or `this.$nextTick`

**Comment by washu** [comment]
the issue continues i had to put a :key property to get it to reset. seems like there is a watch somewhere
