### ISSUE TITLE
Question: What is the best way to style the checkbox of the selectable tablerow

### ISSUE THREAD

**Issue by samuelmoser** [matfish2/vue-tables-2#869]
I have no idea how to style the checkbox. There is no template to use...

**Comment by matfish2** [comment]
I will add the select row template to the private repo. In the mean time you can use : `tr td:first-child input`

**Comment by matfish2** [comment]
Added `VtRowSelector` to the `templates` folder. Also, note the `td` already has a `VueTables__select-row ` class which you can use as an anchor.
