### ISSUE TITLE
Question: Tailwind Theme configuration: table

### ISSUE THREAD

**Issue by samuelmoser** [matfish2/vue-tables-2#871]
where should the table-auto be placed on the table? I can't find it in the dom...
![image](https://user-images.githubusercontent.com/31036187/90483006-665ad800-e134-11ea-82c9-72810d8b403a.png)

**Comment by samuelmoser** [comment]
Its working on the server table, but not on the client table...

**Comment by matfish2** [comment]
`table-auto` is applied to the `table` element on both the server and the client table (they are using a common component)

**Comment by samuelmoser** [comment]
hm, very strange I can't find table-auto on the <table>...

**Comment by samuelmoser** [comment]
and all classes there won't be applied

```
import defaultTailwind from 'vue-tables-2/compiled/themes/tailwind'

const vueTableStyleOptions = () => {
  return {
    ...defaultTailwind(),
    table: 'bg-green'
  }
}
```
bg-green won't be applied...

**Comment by matfish2** [comment]
Just tested your code and `bg-green` is applied as expected. Obviously it overrides the default classes for the table element. If you want those applied as well you need to add them explicitly.

**Comment by samuelmoser** [comment]
If I use the VtTable template: 
```
<template>
    <table v-bind="props.tableAttrs">
        <caption v-if="props.caption">{{props.caption}}</caption>
        <vt-table-head/>
        <vnodes :vnodes="props.slots.beforeBody"/>
        <vt-table-body ref="vt_table_body"/>
        <vnodes :vnodes="props.slots.afterBody"/>
    </table>

</template>

<script>
    import VtTableHead from 'vue-tables-2/compiled/components/VtTableHead'
    import VtTableBody from 'vue-tables-2/compiled/components/VtTableBody'

    export default {
        name: "MyTable",
        props: ['props'],
        components: {
            VtTableHead,
            VtTableBody,
            vnodes: {
                functional: true,
                render: (h, ctx) => ctx.props.vnodes
            }
        }
    }
</script>

```
in the props.attribute is only
```
class: "VueTables__table class-from-skin-option"
summary: false
```
there is no bg-green at all.

**Comment by samuelmoser** [comment]
I don't know from where the class should come from...

**Comment by samuelmoser** [comment]
I found it.
Theme and Skin don't go well together, if I don't set the skin option, it will work...
because of this:
```
"class": "VueTables__table ".concat(this.opts().skin ? this.opts().skin : this.theme.table)
```

**Comment by matfish2** [comment]
Thanks for debugging. I will remove the skin option as it should be deprecated, and the theme's table property should be used instead
