### ISSUE TITLE
Accessing licensed version with npmrc

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#872]
A feature request: 
My coworker messaged me the license we purchased today, but I am wondering if we could use our `.npmrc` for accessing the private version of the package instead of adding a (not-versioned) git repository in our `package.json`. Is that possible?

**Comment by matfish2** [comment]
Hello. Thank you for purchasing the licensed version. As for your question, the premium package is not currently licensed in npm, as this is unsupported by xs:code (through which the purchase was made). I will pass on your request to the xs:code team and ask them to try and come up with a solution.

**Comment by cmitz** [comment]
> I will pass on your request to the xs:code team and ask them to try and come up with a solution

Thanks, that's all I wanted!
