### ISSUE TITLE
Feature request: select-all improvements

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#873]
- Vue.js version: 2.6.11
- consumed using: webpack
- FULL error message (including stack trace): not relevant
- relevant code: 
```
selectable: {
  mode: 'multiple',
  only: row => {
    // complex logic to determine of row was visible in the first place
  }
},
```

I am implementing a "select multiple" feature in a heavily filtered table. I would like to be able to select all, and that works. However, also the filtered out (an thus not visible) rows are selected. I would like only the visible rows to be selectable with the select-all function.

My current workaround is quite cumbersome and relies on the `selectable.only` option, replaying all existing filters on the current row. It's kind of slow. And probably prone to errors.

- Could we have a way to "select all" on just the visible rows?
- Extended: could we have a way to select all, but only on the current page?

## Possible solutions:

- passing some row metadata to the `only` function, like `only(row, metadata)` where metadata is `{ visible: true, onThisPage: false }`
- extra option, `selectable.selectAllMode: '[all|filtered|page]'` where `all` is default, and options can be combined?

**Comment by matfish2** [comment]
Selecting all rows outside of the filtered dataset is a bug. I will fix and add select current page only functionality. When it comes to the server table this is the only available option as the other rows are unknown, so I'm assuming you are referring to the client table.

**Comment by matfish2** [comment]
Fixed. Select now applies only to filtered data. In addition, I've added the selectAllMode option you suggested. By default, it is set to `all` (i.e all filtered). Set to `page` to select only the current page.
