### ISSUE TITLE
Bug: Deselecting row when using uniqueKey option does not work

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#875]
- Vue.js version: 2.6.11
- consumed using: webpack
- FULL error message (including stack trace): _No error message_
- relevant code: Check this [Gist](https://gist.github.com/cmitz/3145374a5b885b02bacf80394209e210)

### Explanation

When using `uniqueKey` and `selectable.mode: 'multiple'` as option, deselecting a row does not work. I believe it is because there is a not-dynamic check on `id` instead of evaluating what uniqueKey is.

Solution:

```diff
- this.selectedRows.filter(R => R[id] !== row.id)
+ this.selectedRows.filter(R => R[id] !== row[id])
```

> The gist also contains a customFilter and initialFilter, but that was not relevant after all :)

**Comment by matfish2** [comment]
Thank you for reporting and debugging, I have fixed the issue in the private repo. Please pull the latest.
