### ISSUE TITLE
feature request: programmatically focus on filter input

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#876]
I'd like to programmatically `focus()` on the filter input for a better UX in our app. We have a pretty specific use-case where we swap the displayed table but keep the "GENERIC" filter value. 

Possible solutions would be providing a `$ref` value for us to call `focus()` on, or a `focusOnFilter()` method on `$refs.table`.

**Comment by matfish2** [comment]
Added. Use as follows:
```js
this.$refs.myTable.$refs.genericFilter.focus()  // or blur
```

**Comment by cmitz** [comment]
Dude, that was fast! Absolutely wild. Thanks! 🚤
