### ISSUE TITLE
Add Loading/Loaded events to Client Table (Feature Request)

### ISSUE THREAD

**Issue by Rykono** [matfish2/vue-tables-2#877]
I apologize for the lack of structure in my message. I am currently trying out the virtual pagination. When the table is loading more rows, it is not obvious to an end user exactly what is happening. I was hoping to be able to use the loading and loaded events to add a spinner to the table, but loading more rows does not trigger those events. 

Is there another way to implement this? or is this intended?

Otherwise - Feature Request -> Virtual Pagination to trigger loading events when loading more rows. 

Thanks!

**Comment by matfish2** [comment]
Unable to reproduce, as you can see in the attached screenshot both events are fired upon intersection with the pagination observer.
![Screenshot 2020-09-20 14 11 24](https://user-images.githubusercontent.com/1510460/93709983-91798280-fb4b-11ea-8602-5e15aaca6e7c.png)

**Comment by Rykono** [comment]
I apologize, my table is a client table, on this table it has a decent amount of data in it, and takes about 1-2 seconds before the next section loads when scrolling, or possibly because buttons or picture thumbnails are also on the table? I understand if this not possible since it a client table, but thank you for your time for looking at this.

**Comment by matfish2** [comment]
Added loading and loaded events to Client table.

**Comment by Rykono** [comment]
Thanks!
