### ISSUE TITLE
Feature Request - Programmatically Selectable Rows

### ISSUE THREAD

**Issue by Rykono** [matfish2/vue-tables-2#878]
The main use case im am trying at the moment, is i do not like the extra column for the selectable feature. Would rather use onRowClick to be able to select a row, and use css styling to show it selected. Being able to programmatically select the rows, would allow this simple modification, I assume if im able to hide the select column. 

Im sure there are also some other use cases for this as well, like selecting multiple based on filters.  (AKA select all rows with dates older than, etc.)

Thanks!

**Comment by matfish2** [comment]
Added. Please see docs: https://matanya.gitbook.io/vue-tables-2/selectable-rows

**Comment by Rykono** [comment]
Thanks!

**Comment by Rykono** [comment]
Hello, 

I was just trying to implement the programmatic selectable rows. Everything is working for me except selected rows do not have the class 'Vuetables__row--selected'.  All functions are working as expected, selectRow, selectRows, unselect, selectAll, reset, and retrieving the selected rows with no errors. But im just not getting a class change on the row. Is there anything im missing or possible bug?

Also up to you, if you do resetSelectedRows() when no rows are selected comes back with error. Cannot set property checked of null. Handled on my side.

**Comment by matfish2** [comment]
Thanks for your feedback. I'll fix the resetSelectedRows() issue

**Comment by matfish2** [comment]
hmmm. I was unable to reproduce. Called on client table with no selected rows.
