### ISSUE TITLE
Missing , in options API documentation

### ISSUE THREAD

**Issue by thepill** [matfish2/vue-tables-2#88]
- Vue.js version: -
- consumed using: -
- FULL error message -
- relevant code:
```
texts:{
count:'Showing {from} to {to} of {count} records|{count} records|One record',
filter:'Filter Results:',
filterPlaceholder:'Search query',
limit:'Records:',
noResults:'No matching records',
page:'Page:' // for dropdown pagination, 
filterBy: 'Filter by {column}' // Placeholder for search fields when filtering by column
loading:'Loading...', // First request to server
defaultOption:'Select {column}' // default option for list filters
}
```

- steps for reproducing the issue:

1. https://jsfiddle.net/matfish2/823jzuzc/embedded/result/

2. option `texts`

3. Missing `,`:

page:'Page:'`, `// for dropdown pagination, 
filterBy: 'Filter by {column}'`,` // Placeholder for search fields when filtering by column

**Comment by matfish2** [comment]
Fixed
