### ISSUE TITLE
Feature request: specific styling for whole column

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#882]
I'd like to style a whole column a little differently when it's sorted, but currently there is no way for `cellStyles` to determine if the column it's in is sorted (at least I don't think so). 

In HTML + CSS we could style using `<col>` elements above `thead`, like this: https://quirksmode.org/css/css2/columns.html
Would that be a useful addition?

**Comment by matfish2** [comment]
Please see the new `addSortedClassToCells` boolean option. When set to true all cells will have a class indicating column and sort direction

**Comment by cmitz** [comment]
Sweet, thanks!
