### ISSUE TITLE
How to set v-client-table pagination page value always 1 ?

### ISSUE THREAD

**Issue by Hajakutbudeen** [matfish2/vue-tables-2#883]
- Vue.js version:
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

Vue 2.0
webpack

<img width="1058" alt="Screen Shot 2020-09-20 at 1 38 20 PM" src="https://user-images.githubusercontent.com/63705818/93709402-9556d600-fb46-11ea-8456-8e3d96243116.png">

I am using also custom filter table outside every time filter change its load new data when data is empty then pagination -> page value going to 0.  i need to set that value always 1

How to do that ?

Please advise Thank you

**Comment by matfish2** [comment]
```js
this.$refs.$myTable.setPage(1)
```

**Comment by Hajakutbudeen** [comment]
Thank you so much !!!

**Comment by Hajakutbudeen** [comment]
this.$refs.myTable.setPage(1) this code works for me, myTable without $, :) Thank you
