### ISSUE TITLE
Filter not working when using CDN 

### ISSUE THREAD

**Issue by Chaitwo** [matfish2/vue-tables-2#886]
- Vue.js version: 2.6
- consumed using: CDN
- FULL error message (including stack trace): No Error
- relevant code: Used the same code from Demo ( https://jsfiddle.net/matfish2/jfa5t4sm/ )

Filter, Pagination are not working

**Comment by matfish2** [comment]
The demo code IS using the CDN version. Can you link to a fiddle/codepen that demonstrates the issue?

**Comment by Chaitwo** [comment]
@matfish2 Sorry, totally my bad I've messed up the CDN references on my end. now that I've tried it on Codepen it's working as expected. Thank you for the quick reply.

 Here is the reference 

https://codepen.io/Chaitwo/pen/gOrEmeQ
