### ISSUE TITLE
Nested Row in Vue Table 2

### ISSUE THREAD

**Issue by Hajakutbudeen** [matfish2/vue-tables-2#887]
- Vue.js version: 2
- consumed using: (browserify/webpack/rollup): browserify
- FULL error message (including stack trace): no error
- relevant code: 
- steps for reproducing the issue:

i have parameter like this:
{
name: father
age: 30
country: usa
        child: {
                  name: son
                  age: 10
                  country: usa
                  }
}

i need to display like this: 

name | age | country    //title

father | 30  | usa         //row
son     | 10  | usa         //row

please advise

**Comment by matfish2** [comment]
You can't divide one data object into two presentational rows (except by using a [child row](https://matanya.gitbook.io/vue-tables-2/child-rows)).
To achieve the desired presentation you will have to mold your data to fit your needs (i.e split the object into two) and pass the result to the table.
