### ISSUE TITLE
Slot, perpage dropdown not showing when data array count is less then perPage options

### ISSUE THREAD

**Issue by TusharJoy** [matfish2/vue-tables-2#888]
My options as follows 
options: {
        filterable: true,
        columnsDropdown: false,
        addSortedClassToCells: true,
        pagination: {
          edge: false
        },
        perPage: 5,
      }

So when i got 2/3 rows slot and perpage variable dropdown is not showing

**Comment by matfish2** [comment]
That is the default behavior. To Override set  `alwaysShowPerPageSelect` to `true`

**Comment by TusharJoy** [comment]
nah not working

**Comment by TusharJoy** [comment]
I have injected  alwaysShowPerPageSelect: true in global option config still no result

**Comment by matfish2** [comment]
Fixed and added to docs
