### ISSUE TITLE
Grouping rows

### ISSUE THREAD

**Issue by mosinve** [matfish2/vue-tables-2#89]
In my project i needed to be able to group rows. I made some editions to source template files to add this functionality. 
Need advice on how to make them compatible with main branch. 
I want to have my own edits and to have possibility to update core files from this repo.

**Comment by tksumanth1994** [comment]
@mosinve did you happen to find any workaround for this? I'm stuck at the same place. Need group by feature in vue-tables-2.

**Comment by mosinve** [comment]
Yep, i made it by custom template
