### ISSUE TITLE
cannot toggle child row with this.$refs.myTable.toggleChildRow(1) according the doc

### ISSUE THREAD

**Issue by silvesterwali** [matfish2/vue-tables-2#890]
- Vue.js version:2x with cdn
- consumed using: (browserify/webpack/rollup) 
- FULL error message (including stack trace): vue.js:1897 TypeError: Cannot read property 'toggleChildRow' of undefined
hi guys ....
i just use the doc on https://matanya.gitbook.io/vue-tables-2/child-rows . 
when i use the toggle child row i just get error like above please help me

**Comment by matfish2** [comment]
you need to set your own ref on the table. `myTable` is just an example

**Comment by silvesterwali** [comment]
thanks so much @matfish2  i have to read carefully your documentation ....
