### ISSUE TITLE
ServerTable show loading if sendInitialRequest set to false

### ISSUE THREAD

**Issue by ybenhssaien** [matfish2/vue-tables-2#891]
- Vue.js version: 2.6.10
- vue-tables-2 version : 1.4.70
- FULL error message (including stack trace): there is no error
- relevant code: no code
- steps for reproducing the issue:
1. Set options to :
```javascript
      options: {
        sendInitialRequest: false,
        texts: {
          loading: 'Chargement en cours...',
        },
      },
```
2. Reload page

# Result :
- There is no request to the server as expected => 👍 
- Still showing the loading message `Chargement en cours ...` while there is no request sent ! 👎 
![image](https://user-images.githubusercontent.com/7301643/94819161-38d59f80-03ff-11eb-90ca-f702374abcd7.png)

# Suggestion
- Add a text option to set custom message in case `sendInitialRequest` set to `false`

# Example
```javascript
      options: {
        sendInitialRequest: false,
        texts: {
          noRequest: 'Please choose at least one filter to fetch results',
        },
      },
```

**Comment by matfish2** [comment]
Thanks for reporting. Should work now
