### ISSUE TITLE
[Question] Access to savedState

### ISSUE THREAD

**Issue by akdasa** [matfish2/vue-tables-2#892]
Good getlocaltime()!

Is it possible to access savedState to populate the value for a custom filter component?

```html
<v-server-table>
  <div
      v-for="(filterModel, key, idx) in options.filtersModel"
      :key="idx"
      :slot="`filter__${key}`"
  >
      <custom-component
          :value="getSavedFilterValueFromLocalstorage(key)"
      />
  </div>
</v-server-table>
```

I found an ugly solution:
```js
getSavedFilterValueFromLocalstorage(key) {
    const savedFilterValue = localStorage["vuetables_" + this.name];
    if (savedFilterValue) {
        const parsedFilterValue = JSON.parse(savedFilterValue);
        const value = parsedFilterValue?.query[key];
        return value;
    }
}
```

Is it possible to make it more clear/not so ugly?

**Comment by matfish2** [comment]
It may be ugly but it's pretty much what I would do behind the scenes. I am less inclined to add it to the package unless others show interest as well.

**Comment by akdasa** [comment]
Ok, thanks. How to trigger "save filters in local storage" events?

Here is a case:
1. I change the value in my custom component.
2. I change the value in any standard filter component.
3. Everything works fine. But if I skip step 2 then the value from my custom component would not be saved in localStorage.

**Comment by matfish2** [comment]
Are you using the event bus to throw a `vue-tables.filter::myFilter` event? the triggered method calls `updateState` (see `register-server-filters.js`)
