### ISSUE TITLE
Using alwaysShowPerPageSelect ignores perPage property

### ISSUE THREAD

**Issue by lucianobosco** [matfish2/vue-tables-2#893]
Fixed and added to docs

_Originally posted by @matfish2 in https://github.com/matfish2/vue-tables-2/issues/888#issuecomment-700731852_

When using `alwaysShowPerPageSelect: true,` the dropdown selected value is always the first option, ignoring the `perPage` property value used.
Tested by declaring `perPage` property globally or locally within the component. Also, I'm using `saveState: true`.

FYI:
Package version: `"vue-tables-2": "^2.1.44",`

**Comment by matfish2** [comment]
Thanks for reporting. Should work in version 2.1.45

**Comment by lucianobosco** [comment]
Hey Matanya, 
It's working fine when no custom template is used but not with `VtPerPageSelector`.
Since I need to add some additional bootstrap classes to the dropdown container I've made use of the custom template following the sample in https://github.com/matfish2/vue-tables-2/blob/master/templates/VtPerPageSelector.vue.

```
<template>
        <div class="VueTables__limit-field px-4 pt-3 pb-0">
            <label :class="props.labelClass" :for="`VueTables__limit_${props.id}`">
                {{props.display('limit')}}
            </label>
            <select :id="props.selectAttrs.id"
                    :class="props.selectAttrs.class"
                    :value="props.selectAttrs.value"
                    @change="props.selectEvents.change">
                <option v-for="val in props.perPageValues" :value="val" :key="val">{{val}}</option>
            </select>
        </div>
</template>

<script>
export default {
    name: 'MyPerPageSelector',
    props: ['props']
}
</script>
```
I'm guessing that you forgot to update the sample code. I see that you have changed this jsx a few hours ago
https://github.com/matfish2/vue-tables-2/blob/master/lib/components/VtPerPageSelector.jsx but the template seems to be outdated.

So far I can see `perPage: "25"` in localStorage but the dropdown is always `10` as the default value.
BTW, I've manually deleted the content from local storage and refreshed the page to regenerate values.

```
perPageValues: [10, 25, 50, 100],
alwaysShowPerPageSelect: true,
perPage: 25,
saveState: true,
```
As I see this could be related just to documentation. Any chance to get the updated template structures no matter the content exposed here? https://github.com/matfish2/vue-tables-2/tree/master/templates

Also please note that I've added the `:key=""` property in the `<option></option>` tag to avoid EsLint compiling error `Elements in iteration expect to have 'v-bind:key' directives`

Thanks again for your hard work on maintaining this package!

**Comment by matfish2** [comment]
Template updated
