### ISSUE TITLE
Selected row frame

### ISSUE THREAD

**Issue by samtronic10** [matfish2/vue-tables-2#894]
What is the best way to change to change the color of selected border row
Thanks

**Comment by matfish2** [comment]
As stated in the docs selected rows (tr) have an additional `VueTables__row--selected` class which you can use to style them

**Comment by Samtronic** [comment]
I tried this class but I can't display the background or the border.
.VueTables__child-row-toggler {
    width: 16px;
    height: 16px;
    line-height: 16px;
    display: block;
    margin: auto;
    text-align: center;
    cursor: pointer; // Steven
}

.VueTables__child-row-toggler--closed::before {
    content: "+";
}

.VueTables__child-row-toggler--open::before {
    content: "-";
}

.VueTables__row--selected {
    background-color: blue;
    background-color: red;
}

but only the class VueTables__row--selected does not work.

Thanks

**Comment by matfish2** [comment]
Try to apply the styling to the `td`:

```css
.VueTables__row--selected td {
background-color: blue;
}
```

**Comment by Samtronic** [comment]
Doesn't seem to work

**Comment by matfish2** [comment]
When you inspect the `tr` element is the `VueTables__row--selected` class present on selected rows?

**Comment by Samtronic** [comment]
No it's not present
