### ISSUE TITLE
[Question] Only relate custom filter to a corresponding table

### ISSUE THREAD

**Issue by nicholasturk** [matfish2/vue-tables-2#895]
I am using vue-tables to generate multiple tables on one page. Currently I'm using a customer filter and doing something like this:

      filterDiff(choice){
         vtEvent.$emit('vue-tables.filter::git', choice);
      }

But this will apply to every vue-table currently rendered on the page. Is there a way I can relate this to a corresponding table?

Thanks.

**Comment by matfish2** [comment]
See comment here: https://matanya.gitbook.io/vue-tables-2/events:

If you are using the bus and want the event to be "namespaced", so you can distinguish between different tables on the same page, use the name prop. The event name will then take the shape of vue-tables.tableName.eventName

**Comment by nicholasturk** [comment]
Thanks!
