### ISSUE TITLE
How to attached context-menu to the entire row?

### ISSUE THREAD

**Issue by ken8806** [matfish2/vue-tables-2#896]
- Vue.js version: 2.14.3
- consumed using: (webpack)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

Hi, I can attached a context menu to a column slot but I would like to attach on the whole row - how can I go about this?

Regards
Kenneth

**Comment by matfish2** [comment]
I am not sure I understand the scenario, but if you mean that a row click should display a menu which is defined on a column template, I'd suggest setting some sort of `menuOpen` flag on the row and toggling it using the `row-click` event. Then on your template, you'll add a `v-show="row.menuOpen"`
