### ISSUE TITLE
how to show loading, when changing pages in vue-server-table.

### ISSUE THREAD

**Issue by Denis-String** [matfish2/vue-tables-2#897]
- Vue.js version: ^2.6.11
- consumed using: Webpack
- FULL error message (including stack trace): none
- relevant code:
- steps for reproducing the issue:

Current behavior:
When used ``v-server-table`` in the first render of the table shows the loading, but when you change to another page, the loading does not show.

Expected behavior:
When you change to another page, show loading until the table receives the data.

Example:
https://codepen.io/Dnis/pen/mdEdmEr?editors=1010

**Comment by matfish2** [comment]
The table treats initial loading differently to subsequent requests. 
On initial loading when the table has no knowledge of the data, we show a loading message.
On subsequent requests use the `loading` and `loaded` events to indicate loading as you please.

**Comment by Denis-String** [comment]
> A tabela trata o carregamento inicial de maneira diferente das solicitações subsequentes.
> No carregamento inicial, quando a tabela não tem conhecimento dos dados, mostramos uma mensagem de carregamento.
> Em solicitações subsequentes, use os eventos `loading`e `loaded`para indicar o carregamento como desejar.

How I can set the loading status in the table?
I tried to use loading, which already exists in the table.
I made ``this.$refs.myTable.$refs.table.loading = true``
but the table has not changed to the loading status.

Do I need to create a loading? or I can already use the existing one?

**Comment by matfish2** [comment]
You don't create a loading status yourself. There are events thrown when the table is loading and loaded respectively.
https://matanya.gitbook.io/vue-tables-2/events
