### ISSUE TITLE
Error when rendering component

### ISSUE THREAD

**Issue by pedrogadino** [matfish2/vue-tables-2#9]
**- Vue.js version:** v6.6.0
**- consumed using:** webpack

When I try to use the template property in options, i got this error:
**[Vue warn]: Error when rendering component <client-table>**

**- relevant code:** http://pastebin.com/hfsPtGN9

When I remove the template property from options, works as expected.
I miss something?

**Comment by matfish2** [comment]
Yes. You are using v1 syntax. Please read the docs for this version.
As a side note, `delete` is a reserved word in JavaScript.

**Comment by ryanrca** [comment]
There is no "Vue.js version: v6.6.0"

**Comment by pedrogadino** [comment]
Sorry, vue.js version: 2.0

I make this changes: http://pastebin.com/cWuwXKMb
Exactly like the documentation says. Still not working.

Where my syntax is wrong?

**Comment by matfish2** [comment]
Please paste the full error stack, as requested in the issue template.
