### ISSUE TITLE
Serial index and pagination problem.

### ISSUE THREAD

**Issue by rofequl** [matfish2/vue-tables-2#900]
- "vue": "^2.6.12",
- "vue-tables-2": "^2.1.46",
- "vuex": "~3.5.1"
- "@coreui/coreui": "^3.3.0",

Sometime show this type of error. when I came again this page it's all right.
```
<div id="people" class="dataTables_wrapper no-footer my-5">
      <v-client-table :data="Object.values(subsubcategoryList)" :columns="columns" class="text-center"
                      :options="options">
        <div slot="serial" slot-scope="props">
          {{ props.index }}
        </div>

        <div slot="action" slot-scope="props">
          <CButtonGroup size="sm" class="mx-1">
            <CButton color="secondary" @click="openModalEdit(props.row)">
              <font-awesome-icon icon="edit"/>
            </CButton>
            <CButton color="secondary" @click="deleteSubcategory(props.row.id)">
              <font-awesome-icon icon="trash-alt"/>
            </CButton>
          </CButtonGroup>
        </div>
      </v-client-table>
    </div>
```

![issue](https://user-images.githubusercontent.com/26442131/96402144-f7aeff00-11f6-11eb-841c-f4ae934c4bab.png)

**Comment by matfish2** [comment]
I'm going to need more info in order to debug it as I can't reproduce with normal settings. It seems like something in the code is setting the page to 0. You can follow the `page` property on devtools and see when this happens.

**Comment by Funkyerdodder** [comment]
I also have the similar problem
![image](https://user-images.githubusercontent.com/21053450/98821258-2a0ddf80-23e4-11eb-8945-4da15bab8919.png)

**Comment by matfish2** [comment]
@Funkyerdodder are you also using vuex?

**Comment by rofequl** [comment]
When page load my data was empty, subsubcategoryList = []
that's why its count 0 we face this problem.
So I put a dummy data just like subsubcategoryList = [{}], so its not starting count in 0, my problem are fixed.
I think you should fixed this issue.

**Comment by matfish2** [comment]
I pushed a possible fix (wasn't able to reproduce). Please check and let me know if it worked (I believe the issue only occurs with vuex + async table population)

**Comment by matfish2** [comment]
Pushed another fix, forcing page to be above 0, Closing.
