### ISSUE TITLE
how to close all open toggle child row  v-client-table 

### ISSUE THREAD

**Issue by silvesterwali** [matfish2/vue-tables-2#901]
- Vue.js version: 2^*
- consumed using: (browserify/webpack/rollup) using cdn version
- FULL error message (including stack trace):
- relevant code: 

before running methods this.$refs.myTable.toggleChildRow(id)
i want to close all the open togle before .so i only open one childrow toggle

![image](https://user-images.githubusercontent.com/40487188/96829530-706ac100-146c-11eb-8cd6-d39384d4c0d5.png)

- steps for reproducing the issue:

how to close old open toggle child row before new toggle row is toggled

**Comment by matfish2** [comment]
This should work (see devtools if it doesn't, and look for `openChildRows`)
```js
this.$refs.myTableRef.$refs.table.openChildRows = [];
```

**Comment by silvesterwali** [comment]
ok thank you @matfish2  this is working

**Comment by sunmingtao** [comment]
I was going to ask why `this.$refs.myTableRef.openChildRows` always resolves to `undefined`. Now I came to know it should be `this.$refs.myTable.$refs.table.openChildRows`. Thank you.
