### ISSUE TITLE
Is list columns filtering broken?

### ISSUE THREAD

**Issue by alex-muntean** [matfish2/vue-tables-2#903]
- Vue.js version:
2.5.8
- consumed using: (browserify/webpack/rollup)
webpack
- FULL error message (including stack trace):
no error
- relevant code:
https://jsfiddle.net/nz862h3x/
- steps for reproducing the issue:
It seems that filtering the second column will bring up no results.
I have followed the example here: https://matanya.gitbook.io/vue-tables-2/list-filters
Thanks

**Comment by matfish2** [comment]
you id needs to match the data
https://jsfiddle.net/matfish2/1tjbaezc/
