### ISSUE TITLE
Multiple condition for 'cellClasses'

### ISSUE THREAD

**Issue by shern91** [matfish2/vue-tables-2#904]
I need to styling my column cell for different condition. 

Example.

`cellClasses:{
  balance: [
    {
        class:'low-balance',
        condition: row => row.balance < 100
    }
  ]
}`

The above example is only styling the row while the balance is less than 100. What if I have multiple condition like while balance is equal to 0 is showing 'zero-balance ' class, balance less than 100 showing 'low-balance' class, balance more than 1000 showing 'sufficient-balance' class. How do I do that? Thank in advance.

**Comment by matfish2** [comment]
Simply add more classes, and make sure the conditions are mutually exclusive.

```js
cellClasses:{ balance: [ { class:'low-balance', condition: row => row.balance < 100 && row.balance>0 }, { class:'zero-balance', condition: row => row.balance === 0 } ] }
```

**Comment by shern91** [comment]
> Simply add more classes, and make sure the conditions are mutually exclusive.
> 
> ```js
> cellClasses:{ balance: [ { class:'low-balance', condition: row => row.balance < 100 && row.balance>0 }, { class:'zero-balance', condition: row => row.balance === 0 } ] }
> ```

Ok. Thank you very much.
