### ISSUE TITLE
Its possible to get input values in free version?

### ISSUE THREAD

**Issue by osmelg** [matfish2/vue-tables-2#905]
Hello. I want to know if its possible to insert a input in a column and get the row modified using the free version? is there any example on how to do this using custom templates?
`<client-table :templates="thetemplate"></client-table>`
And data
`data(){
return{
        thetemplate: {
          thecolumn: (h, row) => <input v-model={this.selected} type='text' value={row.name} class="input"/>,
        },
}
}`

**Comment by matfish2** [comment]
https://matanya.gitbook.io/vue-tables-2/client-table/editable-cells

**Comment by osmelg** [comment]
Thank you for the response, but that example is to use it on slots, and i need to use in templates, i cant figure it out how to update a row and get row updated

**Comment by matfish2** [comment]
a. that's not the syntax for javascript templates (`templates` is not a prop, but an option)
b. templates only pass the row. Changing it to pass all props would present a breaking change, so I am reluctant. 
Why can't you use scoped slots?

**Comment by osmelg** [comment]
Is ok for you if i explan it via email?
