### ISSUE TITLE
No results row template's `props.getMessage`

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#908]
- Vue.js version: 2.6.12
- consumed using: webpack
- FULL error message (including stack trace):
![](http://joxi.ru/12MBqyxslJ47oA.jpg)

Hi, @matfish2 ! There is something wrong, while trying to change NoResultsRow template. Logging `this.props` inside created hook in your [basic template](https://github.com/matfish2/vue-tables-2/blob/master/templates/VtNoResultsRow.vue#L5) shows following:

![](http://joxi.ru/Vrw34GeU7qK5yr.jpg)

Seems like `getMessage` wasn't provided inside the appropriate [renderless component](https://github.com/matfish2/vue-tables-2/blob/master/lib/components/renderless/RLNoResultsRow.js#L5).

**Comment by matfish2** [comment]
Thanks for reporting. Fixed. Should be:  {{props.display(props.message)}}
