### ISSUE TITLE
Error using component with Vue 2.0.7

### ISSUE THREAD

**Issue by afucher** [matfish2/vue-tables-2#91]
- Vue.js version: 2.0.7
- consumed using: (browserify/webpack/rollup): webpack
- FULL error message (including stack trace):[Vue warn]: Failed to mount component: template or render function not defined. 
(found in component <v-client-table>)
warn @ build.js:9074
Vue._mount @ build.js:10735
Vue$3.$mount @ build.js:14533
Vue$3.$mount @ build.js:16860
init @ build.js:11055
createComponent @ build.js:12607
createElm @ build.js:12550
createChildren @ build.js:12658
createElm @ build.js:12583
createChildren @ build.js:12658
createElm @ build.js:12583
patch @ build.js:13001
Vue._update @ build.js:10770
(anonymous) @ build.js:10744
get @ build.js:10207
Watcher @ build.js:10199
Vue._mount @ build.js:10743
Vue$3.$mount @ build.js:14533
Vue$3.$mount @ build.js:16860
init @ build.js:11055
(anonymous) @ build.js:11209
createComponent @ build.js:12607
createElm @ build.js:12550
createChildren @ build.js:12658
createElm @ build.js:12583
createChildren @ build.js:12658
createElm @ build.js:12583
patch @ build.js:13001
Vue._update @ build.js:10770
(anonymous) @ build.js:10744
get @ build.js:10207
Watcher @ build.js:10199
Vue._mount @ build.js:10743
Vue$3.$mount @ build.js:14533
Vue$3.$mount @ build.js:16860
init @ build.js:11055
createComponent @ build.js:12607
createElm @ build.js:12550
patch @ build.js:13038
Vue._update @ build.js:10770
(anonymous) @ build.js:10744
get @ build.js:10207
Watcher @ build.js:10199
Vue._mount @ build.js:10743
Vue$3.$mount @ build.js:14533
Vue$3.$mount @ build.js:16860
initRender @ build.js:11471
Vue._init @ build.js:11851
Vue$3 @ build.js:11898
(anonymous) @ build.js:8542
__webpack_require__ @ build.js:556
fn @ build.js:87
(anonymous) @ build.js:588
__webpack_require__ @ build.js:556
(anonymous) @ build.js:579
(anonymous) @ build.js:582

- relevant code: 
        <div id="people">
            <v-client-table :data="data" :columns="columns" :options="options"></v-client-table>
        </div>
 data: function(){
            return {
                data: [{name:'teste'}],
                columns: ['name'],
                options: {
      sortable: ['option']
    }
- steps for reproducing the issue: Just try to use the component

**Comment by matfish2** [comment]
Both components have a `render` function. I suspect that you are missing a render function in your own code.
