### ISSUE TITLE
Vue-Tables-2 Pro calls `getRequestParams` twice

### ISSUE THREAD

**Issue by jssullivan** [matfish2/vue-tables-2#910]
- Vue.js version: 2.6, Vue-Tables-2 Pro 2.1.50
- consumed using: (browserify/webpack/rollup): webpack
- FULL error message (including stack trace): Unexpected Behavior
- relevant code: `get-data.js` L8-12, remove L12 (Vue Table 2 Pro, the open source repo doesn't have this bug).
- steps for reproducing the issue: 
1. In Vue Tables 2 Pro create a request adapter, have it return undefined,
2. Add a debugger to your request adapter,
3. See that `parameters` is correct the first time, but on the second erroneous call its the return value from the first call (in this case undefined)

**Comment by matfish2** [comment]
Thanks for reporting. Fixed.
