### ISSUE TITLE
how to use custom search component on v-table-2

### ISSUE THREAD

**Issue by silvesterwali** [matfish2/vue-tables-2#911]
- Vue.js version: 2x^
- consumed using: (browserify/webpack/rollup)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:
i want replace it with my own component .How to do that ?
![image](https://user-images.githubusercontent.com/40487188/100957545-a1eba780-3555-11eb-83be-ad140a9536d2.png)

**Comment by matfish2** [comment]
Option A: https://matanya.gitbook.io/vue-tables-2/custom-template swap VtGenericFilter
Option B: set `filterable` to false, and use [custom filters](https://matanya.gitbook.io/vue-tables-2/custom-filters) and the `beforeFilter` [slot](https://matanya.gitbook.io/vue-tables-2/slots)

**Comment by silvesterwali** [comment]
thank's @matfish2  this very usefull

**Comment by azeos** [comment]
I'm sorry to comment on a closed issue, but it seems to be the correct one.

I need the global search to ignore accents. I went with the "Option A", replacing "VtGenericFilter". But I'm not sure how to replace the "search" function with my own.

How can I replace the global search function? Or where can I see the code of the default one?

Thanks!
