### ISSUE TITLE
Update all filters at the same time (limit, page, sorting and params) at the same time

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#912]
Hi @matfish2 ! 

I have a specific case in my current project. I made behavior when all the params are being saved in location url as GET-params like `?limit=10&page=1&createdRange=2020-11-26T12%3A00%3A00%2B03%3A00,2020-12-03T11%3A59%3A59%2B03%3A00&ascending=1&orderBy=firstName` to share the link between different users on the exact state of table. It works fine during initializing, but when I'm going back or forward in history I want params to be reinitialized. I'm using vue-router with history mode set on. Technically I know how to implement it using URL watch, but I don't know any API of tables that allows me to set all the things at the same time. There are different things like `setOrder`, `setPage` etc, but does the tables plugin have a method to update all the things at the same time?

**Comment by VladZen** [comment]
I can send all the params to request, but it doesn't reflect in the view (ordering, pagination, limit for ex) are new according to the response but stays the same in the view (chosen pagination, limit or ordering icon). It could be solved with additional parameter to like `setPage(1, false)`, where `false` means `do not reload`

**Comment by matfish2** [comment]
https://matanya.gitbook.io/vue-tables-2/server-table/setting-multiple-request-parameters

Please let me know if it works as expected

**Comment by VladZen** [comment]
great! checking... let you know if something goes wrong or say "thx" and close the issue if it will be okay)

**Comment by VladZen** [comment]
`setCustomFilters(params)` unfortunately is not available =( it's not a big deal, cause I change params using updating of `options.params` but keeping you informed
![](http://joxi.ru/ZrJNlxjsw76dzr.jpg)

**Comment by matfish2** [comment]
Thanks for debugging. Can you please try again now?

**Comment by VladZen** [comment]
Sure, pulling new version...

**Comment by VladZen** [comment]
Everything is working! You're the best! Thx for the greatest product!
