### ISSUE TITLE
Table is not updated after setLoadingState(false)

### ISSUE THREAD

**Issue by eddivalen** [matfish2/vue-tables-2#918]
- Vue.js version: 2.1.6.11
- consumed using: (browserify/webpack/rollup): webpack
- steps for reproducing the issue:

I use this method to use the asynchronous loading to fetch the data from a GraphQL API, just like it says on the [docs](https://matanya.gitbook.io/vue-tables-2/client-table/asynchronous-loading)

But the pagination is not working, once the GraphQL query has finished and the new array is ready, I call my method to update the status to false, but I just get an empty table  "No matching records"

```  
methods: {
 changeStateVueTable(state){
      let self = this
      self.$refs.table.setLoadingState(state)
    },
    .
    .
}
```

The only way that I fixed this issue before, was by putting a condition to not show the table while the query is loading, @matfish2 any idea on how to solve this? I would like to avoid using the condition, so the table can get a better UI, hiding and showing the table through pagination isn't nice.

**Comment by matfish2** [comment]
Unable to reproduce: https://jsfiddle.net/matfish2/7h0n4acg/2/

**Comment by eddivalen** [comment]
@matfish2   It's hard to replicate my issue on a jsFiddle, but what I can see on the VtClientTable component is the _allFilteredData_ array is not getting updated, is there a manual way to force it and get the new data from the props?

![2020-12-18 19_03_05-DevTools - localhost_8080_](https://user-images.githubusercontent.com/8193094/102668973-bb9b0a80-4163-11eb-846f-750a5620392a.png)

**Comment by eddivalen** [comment]
Sorry @matfish2, I fixed my issue, I was trying to call these methods on the result function from Apollo
```
this.$refs.table.setLoadingState(false)
this.$refs.table.setPage(this.page)
```
So I had to put it after that function and now it's working
