### ISSUE TITLE
Import custom templates not working gives out blank template

### ISSUE THREAD

**Issue by maisnamraju** [matfish2/vue-tables-2#92]
- Vue.js version: 2.1.0
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace): No erros whatsoever
- relevant code:
![screen shot 2017-02-25 at 4 27 49 pm](https://cloud.githubusercontent.com/assets/2786378/23330586/867361e4-fb77-11e6-9d52-67d685b2b024.png)
![screen shot 2017-02-25 at 4 27 34 pm](https://cloud.githubusercontent.com/assets/2786378/23330587/8e383012-fb77-11e6-8f70-14eaefdd70b1.png)
![screen shot 2017-02-25 at 4 32 33 pm](https://cloud.githubusercontent.com/assets/2786378/23330615/0fb277c4-fb78-11e6-9419-710f7fc72707.png)

![screen shot 2017-02-25 at 4 31 42 pm](https://cloud.githubusercontent.com/assets/2786378/23330610/ea165594-fb77-11e6-86a7-8b4f50913a81.png)

- steps for reproducing the issue:
As mentioned in the docs, I copied the `template.js` file and the content inside the template folder and imported the template, while rendering the template gives out a blank page. It works well without the custom template 

I have tried with renaming the file extensions as well but they didn't work, the return function inside the main template is not called at all and I don't get any errors for the same.

**Comment by matfish2** [comment]
The template is a function, and should be called with the `source` param:

```
Vue.use(ClientTable,{}, false, TableTemplate('client'))
```

I will add it to the docs
