### ISSUE TITLE
How to set all filtering algorithm to case insensitive as default?

### ISSUE THREAD

**Issue by ahmad-fauzan458** [matfish2/vue-tables-2#921]
I know we can use something like this on each of column for case insensitive filter:
```
filterAlgorithm: {
  column(row, query) {
      if (row.column) {
          return ((row.column).toLowerCase()).includes(query.toLowerCase());
      }
  }
}
```

But it's too tiring to make changes for every column, do you have any parameter to make all filter algorithm case insensitive by default?

**Comment by matfish2** [comment]
But it already **is** case insensitive https://jsfiddle.net/matfish2/fb4qhps5/1/

**Comment by ahmad-fauzan458** [comment]
oh i see, seems like someone in my team overriding it somewhere so it's not case insensitive anymore, thanks.
