### ISSUE TITLE
Custom VtColumnsDropdown causes "TypeError: Converting circular structure to JSON"

### ISSUE THREAD

**Issue by tankbusta** [matfish2/vue-tables-2#922]
- Vue.js version: 2.6.11
- consumed using: webpack via vue-cli (not ejected)

I'm attempting to create a custom columns dropdown but I'm getting `TypeError: Converting circular structure to JSON` similar to #830. I'm using the subscribers version, so I copied `templates/VtColumnsDropdown.vue` to my source tree. 

The code snippet below `./ColumnsDropdown` is a 1:1 copy of `templates/VtColumnsDropdown.vue`
```
import Vue from 'vue'
import { ServerTable, ClientTable } from 'vue-tables-2'
import ColumnsDropdown from './ColumnsDropdown'  

Vue.use(
  ServerTable,
  {
    sortIcon: tableIcons
  },
  false,
  'bootstrap4',
  {
    columnsDropdown: ColumnsDropdown 
  },
)
```
This can be reproduced without any changes to the template. The culprit is the call to `props.getHeading(column)`  https://github.com/matfish2/vue-tables-2/blob/master/templates/VtColumnsDropdown.vue#L20

**Comment by matfish2** [comment]
I am unable to reproduce. Tried both free and premium versions
