### ISSUE TITLE
Toggle All Groups?

### ISSUE THREAD

**Issue by karmanbadhesha** [matfish2/vue-tables-2#925]
I know how to toggle an individual group, but is it possible to loop through all props and call the toggleGroup method on each one so I can collapse/expand all groups in one click?

**Comment by matfish2** [comment]
You can manipulate to `collapsedGroups` array (`this.$refs.myTable.$refs.table.collapsedGroups`). 
To collapse all, push all group values to this array. To expand all empty the array.

**Comment by karmanbadhesha** [comment]
perfect thank you!
