### ISSUE TITLE
how to use heading in nested array?

### ISSUE THREAD

**Issue by Kneotrino** [matfish2/vue-tables-2#927]
- Vue.js version: 2.6.12
- consumed using: (webpack)
- FULL error message (including stack trace):
Syntax Error: Unexpected token, expected "," (63:31)

> 63 |                     employeeDto.employeeId : 'Employee ID',
     |                                ^
  64 |                     temperature: 'Body temperature',
  65 |                     inputDate: 'Input Date'
  66 |                 },
- relevant code:
`
columns: ['#', 'employeeDto.employeeId','employeeDto.fullName', 'inputDate','actions'],
            options: {
                headings: {
                    employeeDto.employeeId : 'EmployeeID',
                    employeeDto.fullName : 'fullName',
                    temperature: 'Body temperature',
                    inputDate: 'Input Date'
                }
            },
`

**Comment by matfish2** [comment]
sourround by single quotes: `'employeeDto.employeeId':'EmployeeID'`
