### ISSUE TITLE
seting count index on options.texts.count does not have any effects. 

### ISSUE THREAD

**Issue by PEscar** [matfish2/vue-tables-2#928]
- Vue.js version: 2.6.12
- consumed using: (browserify/webpack/rollup) https://cdnjs.cloudflare.com/ajax/libs/vue-tables-2/2.1.1/vue-tables-2.min.js
- no error message
- relevant code:
texts: {
         count: 'Mostrando {from} a {to} de {count} resultados|{count} resultados|Un resultado'
}
- steps for reproducing the issue:

Change de text of 'count' index (options -> texts -> count for something like in the example.

OBS: If i change de default options in src by the same string, it works !
But changing de label in execution time (not from default options in src) not

**Comment by matfish2** [comment]
Unable to reproduce (used exact CDN link as above). How are you passing options to the component? Please share the relevant code.
![2021-01-28](https://user-images.githubusercontent.com/1510460/106109353-1ad03f80-6152-11eb-92bc-2b0d209fe046.png)
