### ISSUE TITLE
Failed for prop "value"

### ISSUE THREAD

**Issue by VictorLessa** [matfish2/vue-tables-2#929]
- Vue.js version: 2 CLI: 4
- consumed using: (browserify)
- FULL error message (including stack trace): 
Invalid prop: custom validator check failed for prop "value"
vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: custom validator check failed for prop "value".

found in

---> <Pagination>
       <RLPagination>
         <VtPagination>
           <RLClientTable>
             <VtClientTable>
               <Dashboard>
                 <App> at src/App.vue
                   <Root>

**Comment by matfish2** [comment]
Please include all relevant code. There isn't enough data for me to debug
