### ISSUE TITLE
Compatible with webpack2 / vuecli?

### ISSUE THREAD

**Issue by vincent-lu** [matfish2/vue-tables-2#93]
- Vue.js version: 2.2.1
- consumed using: (browserify/webpack/rollup) webpack2 (vue-cli webpack template)
- FULL error message (including stack trace):
```
bus.js?440b:5 "var bus = new Vue();"

Uncaught TypeError: Vue is not a constructor
    at eval (eval at <anonymous> (app.js:1026), <anonymous>:5:11)
    at Object.<anonymous> (app.js:1026)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at eval (eval at <anonymous> (app.js:1571), <anonymous>:3:11)
    at Object.<anonymous> (app.js:1571)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at eval (eval at <anonymous> (app.js:1564), <anonymous>:5:16)
    at Object.<anonymous> (app.js:1564)
```
- relevant code:
This line of code `var bus = new Vue();` in `vue-pagination-2/compiled/bus.js` is causing `Vue is not a constructor` error under webpack2.

Note the same code works with older version of vue-cli webpack projects (that used webpack 1).

**Comment by matfish2** [comment]
Can you `console.log(Vue)` in `bus.js` and post the result?

**Comment by vincent-lu** [comment]
Thanks @matfish2 . This is what I got from `console.log(Vue)`. Let me know if you need me to expand anything.
<img width="1254" alt="screen shot 2017-02-27 at 17 19 41" src="https://cloud.githubusercontent.com/assets/390546/23350794/1b78dc7a-fd11-11e6-91c3-5b988db4fb75.png">

**Comment by matfish2** [comment]
Hmm. As you can see `Vue` itself is contained in the `default` property instead of being exposed at the root level. I will have to look into it.

**Comment by vincent-lu** [comment]
Not a problem @matfish2 thanks.

**Comment by matfish2** [comment]
As it turns out there is some inconsistency in the way `exports.default` is parsed. I have replaced it with ES6 syntax (`export default` and `import` rather than `exports.default` and `require`). Please pull the new version and try again. I believe you will now get an error for the next module which uses  the `require` syntax. If this turns out to be the case I will have to go over the package and replace all the "require"s

**Comment by vincent-lu** [comment]
After the update I'm getting the exact same error. (deleted node_modules and rerun `yarn` to be sure).

Current versions:
Vue: 2.2.1
Webpack: 2.2.1
Vue-tables-2: 0.4.52
Vue-pagination-2: 0.2.7

Perhaps it's because the error occurs at `vue-pagination-2/compiled/bus.js` but the update made is only in `vue-tables-2`?

**Comment by matfish2** [comment]
You are right. I've updated the pagination plugin as well. Please try again and keep me posted.

**Comment by vincent-lu** [comment]
Getting this:
```
vuex.js?286c:8

Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.eval (eval at <anonymous> (app.js:1578), <anonymous>:15:16)
    at eval (eval at <anonymous> (app.js:1578), <anonymous>:43:30)
    at Object.<anonymous> (app.js:1578)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at eval (eval at <anonymous> (app.js:1564), <anonymous>:6:17)
    at Object.<anonymous> (app.js:1564)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at eval (eval at <anonymous> (app.js:1032), <anonymous>:1:21)
```

Line 8 of `node_modules/vue-pagination-2/compiled/state/vuex.js`, `var name = this.for;`

**Comment by matfish2** [comment]
@vincent-lu, That would be great.

**Comment by vincent-lu** [comment]
It's here:

https://github.com/vincent-lu/vue-tables-demo

I just quickly created a repo haven't thoroughly tested it (README contains basic info to get you started), but I got it to the point basically it produces the same error reported here https://github.com/matfish2/vue-tables-2/issues/93#issuecomment-283190833

The error occurs as soon as I run `import { ClientTable } from 'vue-tables-2'` .

If it runs into error because I forgot config something apologies in advance and just let me know I will fix it.

**Comment by matfish2** [comment]
Found it. in your `webpack.base.conf.js` you have:

```js
 {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules(?!\/(vue-tables-2|vue-pagination-2))/
  }
```

This is not only redundant, because the package is precompiled, and no longer requires any transforms, but is also the cause of the error you are getting.
I removed it, restarted the server, and voila.

**Comment by vincent-lu** [comment]
Yeah nice thanks @matfish2.

All works without jsx transform now.

Confirmed working with the following stack:

- Vue 2.2.1
- Webpack 2.2.1
- Project created via vue-cli's latest webpack template
- Vue-tables-2 0.4.53
- Vue-pagination-2 0.2.72

No longer need to modify the following files originally created by vue-cli:

- /build/webpack.base.conf.js
- /.babelrc

And no longer need the following packages:

- babel-plugin-syntax-jsx
- babel-plugin-transform-vue-jsx
