### ISSUE TITLE
How to specify ajax library

### ISSUE THREAD

**Issue by hisuwh** [matfish2/vue-tables-2#932]
- Vue.js version: 2.6.12 (2.1.80 if you mean vue-tables-2 version)
- consumed using: webpack

Your docs says "supports jQuery, axios and vue-resource" but I can't see anywhere in the documentation that specifies how to configure this.  I have both vue-resource and axios being used in my application currently as I'm refactoring from the former to the latter.  vue-tables-2 seems to be preferring vue-resource so I want to know if I can tell it to use axios instead?

**Comment by matfish2** [comment]
There is currently no option to specify ajax library. The package scans for vue-resource, axios or jquery in this order of precedence, and uses the first package it encounters

**Comment by hisuwh** [comment]
Considering vue-resource is no longer the recommended approach perhaps this order should be changed (I realise this would be a breaking change).  Or the alternative is to have the ability to set your own preference as I described so people migrating away from vue-resource can do so for vue-tables-2.

**Comment by hisuwh** [comment]
The code here seems to check axios first: https://github.com/matfish2/vue-tables-2/blob/master/lib/methods/send-request.js
Is this not the correct file?
