### ISSUE TITLE
StickyHeader defaults to white background

### ISSUE THREAD

**Issue by Rykono** [matfish2/vue-tables-2#933]
- Vue.js version: Vue2
- consumed using: (browserify/webpack/rollup): webpack
- FULL error message (including stack trace): none
- relevant code: stickyHeader: true
- steps for reproducing the issue: set stickyHeader to true.

The default white background on the stickyHeader is conflicting with dark theme on website. 

Thanks!

**Comment by matfish2** [comment]
Thanks for reporting this. I have added a `stickyHeaderBackground` option, which defaults to `white`, to maintain backward compatibility. You can either set your own color or set it to an empty string to remove the `background` rule altogether.
