### ISSUE TITLE
Table overlaying dropdown (z-index)

### ISSUE THREAD

**Issue by viniciussvl** [matfish2/vue-tables-2#935]
Hello how are you?
I am trying to open a dropdown within the table, but the table is overlapping this dropdown, how can I do to resolve this? I have already tried to use a z-index class: 99999; in the dropdown, but I was not successful.

![overlay](https://user-images.githubusercontent.com/23041126/109849726-78174f00-7c30-11eb-9bb3-77e22d33dd5e.PNG)

My Slot:
`  

                        <div slot="actions" slot-scope="props">
                            <b-dropdown 
                                split
                                split-variant="primary-dark" 
                                size="sm" 
                                class="m-2">

                                <b-dropdown-item @click="sell(props.row.id)"><i class="fa fa-shopping-cart"></i> Sell</b-dropdown-item>
                                <b-dropdown-item @click="singleSplit(props.row.id)"><i class="fa fa-columns"></i> Split</b-dropdown-item>
                            </b-dropdown>
                        </div>`

**Comment by spacewaffle** [comment]
This isn't a z-index issue. This is a dom scope issue. Because your dropdown is inside the table header, it cannot display itself outside of the bounds of the table. I've solved this in the past by giving my table a minimum height and making sure any dropdowns that come from it are shorter than the min height of the table.

**Comment by viniciussvl** [comment]
This css worked for me. For those with the same problem try this:

```
.table-responsive, .table {
    overflow-y: visible !important;
}
```
