### ISSUE TITLE
remove rows in the table (like filtering) is very slow (vue.teardown)

### ISSUE THREAD

**Issue by MosheL** [matfish2/vue-tables-2#937]
- Vue.js version:  2.6.11.  tried also 2.4.1, 2.5.22
- consumed using: webpack
- FULL error message (including stack trace): this is not an error, but a slow $destroy.
- relevant code:
- steps for reproducing the issue: 
Display a table with v-server-table and some rows,  then filter the rows.
the server time is fast. the client is very slow (also on fast computers).

why?
When we remove a Component from the page, it need to remove the watcher on fields and deps.
this loop can run 10-15K times, as count of (fields+rows))^2.

from Vue.js code:
```

Watcher.prototype.teardown = function teardown () {
  if (this.active) {
    // remove self from vm's watcher list
    // this is a somewhat expensive operation so we skip it
    // if the vm is being destroyed.
    if (!this.vm._isBeingDestroyed) {
      remove(this.vm._watchers, this);
    }
    var i = this.deps.length;
    while (i--) {
      this.deps[i].removeSub(this);
    }
    this.active = false;
  }
};

removeSub: ...

Dep.prototype.removeSub = function removeSub (sub) {
  remove(this.subs, sub);
};

```

`this.subs` length is 1782 for the vm of the table in this example (100 rows, 8 columns).
and for any row  and field. 

What I tried:
- tried to make the object with rows static (`Object.freeze()`)
- I tried to fix it on my custom fields so I was created them as a `functional`. 
   this was help as they also does the problem, but the main problem is the table itself.
- I tried to use an older version of the vue-tables, like  2.1.x or 2.0.x.  same problem.

Stack trace for example:

teardown (VM6765 vue.runtime.esm.js:4604)
Vue.$destroy (VM6765 vue.runtime.esm.js:3981)
destroy (VM6765 vue.runtime.esm.js:3156)
invokeDestroyHook (VM6765 vue.runtime.esm.js:6104)
patch (VM6765 vue.runtime.esm.js:6457)
Vue.$destroy (VM6765 vue.runtime.esm.js:3995)
destroy (VM6765 vue.runtime.esm.js:3156)
invokeDestroyHook (VM6765 vue.runtime.esm.js:6104)
invokeDestroyHook (VM6765 vue.runtime.esm.js:6109)
patch (VM6765 vue.runtime.esm.js:6457)
Vue.$destroy (VM6765 vue.runtime.esm.js:3995)
destroy (VM6765 vue.runtime.esm.js:3156)
invokeDestroyHook (VM6765 vue.runtime.esm.js:6104)
patch (VM6765 vue.runtime.esm.js:6457)
Vue.$destroy (VM6765 vue.runtime.esm.js:3995)
destroy (VM6765 vue.runtime.esm.js:3156)
invokeDestroyHook (VM6765 vue.runtime.esm.js:6104)
removeVnodes (VM6765 vue.runtime.esm.js:6120)
updateChildren (VM6765 vue.runtime.esm.js:6225)
patchVnode (VM6765 vue.runtime.esm.js:6309)
patch (VM6765 vue.runtime.esm.js:6472)
Vue._update (VM6765 vue.runtime.esm.js:3942)
updateComponent (VM6765 vue.runtime.esm.js:4060)
get (VM6765 vue.runtime.esm.js:4473)
run (VM6765 vue.runtime.esm.js:4548)
flushSchedulerQueue (VM6765 vue.runtime.esm.js:4304)
(anonymous) (VM6765 vue.runtime.esm.js:1979)
flushCallbacks (VM6765 vue.runtime.esm.js:1905)
Promise.then (async)
timerFunc (VM6765 vue.runtime.esm.js:1932)
nextTick (VM6765 vue.runtime.esm.js:1989)
queueWatcher (VM6765 vue.runtime.esm.js:4396)
update (VM6765 vue.runtime.esm.js:4538)
notify (VM6765 vue.runtime.esm.js:731)
reactiveSetter (VM6765 vue.runtime.esm.js:1056)
proxySetter (VM6765 vue.runtime.esm.js:4625)
module.exports (set-data.js:7)
eval (get-data.js:23)
Promise.then (async)
module.exports (get-data.js:20)
search (server-search.js:59)
module.exports (server-search.js:50)
later (index.js:27)
setTimeout (async)
debounced (index.js:38)
eval (search.js:23)
keyup (filterWDate.vue?./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options:22)
invokeWithErrorHandling (VM6765 vue.runtime.esm.js:1853)
invoker (VM6765 vue.runtime.esm.js:2178)
original._wrapper (VM6765 vue.runtime.esm.js:6907)

**Comment by MosheL** [comment]
some example of the problem in other forum:

https://forum.vuejs.org/t/having-some-confusing-performance-issues-related-to-component-teardown/93081/7

**Comment by matfish2** [comment]
I wonder if this is an example where good coding practices don't pay off... Prior to v2 of the plugin, there was but one large table component. v2 introduced a more modular approach that allows the consumer to easily swap components and control the UI. I didn't know this could have such a dramatic effect on performance (due to `tearDown` and `destroy` of multiple components). I am open to suggestions, as I am not sure what can be done to by-pass the issue, without restructuring the entire code and losing precious functionality.

**Comment by MosheL** [comment]
OK. I was tested some of my old websites. I was used (2018) the v1 and it much faster.

what about the  Vue 3 version? the changed the way watchers was working. maybe it will be better.

**Comment by matfish2** [comment]
The vue 3 version is out, but it's available for subscribers only. I will label this "help wanted", maybe someone has an idea

**Comment by MosheL** [comment]
I know about the subscribers, I am just interesting to test if they (Vue) or you  solve the problem in this version.
Maybe you can test it.

**Comment by MosheL** [comment]
I found a solution for my-side  components. I  created them as `functional`. functional components does not has a  state so they do not need to be  `treardown`.

Maybe you can make your side components as s functional only.  If you will fix half of them we will get the 1/4 of the problem.

**Comment by matfish2** [comment]
Thank you for exploring this. By "side components" do you mean the ones that start with Vt? (i.e those who render the data passed from the components that start with RL)

**Comment by MosheL** [comment]
I do not see the Vt components in the `teardown`.
I can see the RL.

For example, this is some of the items I found from the `teardown` process via breakpoint :

breakpoint position: `Watcher.prototype.teardown` function
```
>> this.deps.length 
43
>> this.deps[1].subs.length
517

>> var counts = {};
>> this.deps[1].subs.map(f=> f.vm.$options._componentTag).forEach(function(x) { counts[x] = (counts[x] || 0)+1; });

{
"r-l-server-table":11,
"v-server-table":1,
"r-l-table":1,
"r-l-table-head":1,
"r-l-headings-row":1,
"r-l-table-heading":10,
"r-l-sort-control":10,
"r-l-filters-row":1,
"r-l-text-filter":7,
"undefined":5,
"r-l-list-filter":3,
"r-l-table-body":1,
"r-l-pagination":1,
"r-l-table-row":22,
"r-l-table-cell":440,
"r-l-no-results-row":2
}

```
We loop over  43 * 517 items again and again. this is the slow process.

So the main problem is the  `r-l-table-cell`, but any component you can make a functional will help.
