### ISSUE TITLE
Incorrect row index on pages

### ISSUE THREAD

**Issue by carrotinside** [matfish2/vue-tables-2#939]
- Vue.js version: 2.6.12
- vue-tables-2 version: 2.2.0
- consumed usin: webpack

After update from 1.6.25 to 2.2.0 version we noticed that number of row (index) starts in every page from 1.
Before update it worked correctly.

e.g.
`<template v-slot:NumberRow="list">{{ list.index }}.</template>`

Thank you

**Comment by matfish2** [comment]
Thanks for reporting, Fixed in 2.2.1
