### ISSUE TITLE
methods/send-request.js jQuery get return a String

### ISSUE THREAD

**Issue by smalllazypig** [matfish2/vue-tables-2#94]
line 16  
` if (typeof $ != 'undefined') return $.get(this.url, data).fail(function (e) {`
return a json String

`config/defaults.js line 54 responseAdapter: function responseAdapter(resp) {`
resp.data will be undefined

**Comment by matfish2** [comment]
Unable to reproduce. I am getting a json object.
Maybe your server code returns an entity which in unparsable as json?

**Comment by smalllazypig** [comment]
VueResource parse correct
May be $.getJSON is better

**Comment by matfish2** [comment]
Good idea. Let me know if it worked.
