### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by VDVT** [matfish2/vue-tables-2#942]
I have received an issue when I using v-client-table and try change data of table with length items less than current page activated.
![image](https://user-images.githubusercontent.com/18101217/113322085-754a6f80-933e-11eb-91d9-b8cec1cea69c.png)

**Comment by VictorLessa** [comment]
I have the same error

**Comment by matfish2** [comment]
When you reduce array size you need to set page to 1, or to a page within
the range first. Use the setPage method
