### ISSUE TITLE
StickyHeader not working with premium version

### ISSUE THREAD

**Issue by vincent-lu** [matfish2/vue-tables-2#943]
- Vue.js version: 3
- Consumed using: webpack
- FULL error message (including stack trace): n/a
- Relevant code:
```javascript
options: {
    stickyHeader: true,
}
```
- Steps for reproducing the issue:
Using v-tables-3 @ 0.3.0, when I set `stickyHeader` to `true`, the `th.VueTables__sortable ` elements shows having `style="position: sticky;"` (instead of `position: relative`) but as I scroll the table the header does not get stuck.
Additionally if I set `stickyHeaderBackground: "red"` nothing happens.

**Comment by matfish2** [comment]
Thank you for reporting. Fixed in version 0.3.1. Please confirm

**Comment by vincent-lu** [comment]
Hey @matfish2 thanks for the quick response, really appreciate it.

BTW it seems the styling used to achieve the sticky header effect really doesn't like any overflow styling.

After update to 0.3.1, this works:
```html
<v-server-table url="/products" ...>
```

But this breaks it:
```html
<div style="overflow: auto">
    <v-server-table url="/products" ...>
</div>
```

BTW @matfish2 I want to make some meager donation to this project for all the benefit I've gotten from your project over the years, what is the best way to go about this?

**Comment by matfish2** [comment]
> BTW it seems the styling used to achieve the sticky header effect really doesn't like any overflow styling, even if applied to the parent (or grand parents) of the vue table itself.

I am open to suggestions, but I believe that's more of a CSS issue, seeing as I am simply using `position:sticky`

> BTW @matfish2 I want to make some meager donation to this project for all the benefit I've gotten from your project over the years, what is the best way to go about this? (can I just buy Support Hour from your xscode page?)

Yes, I think purchasing a support hour would be the easiest way. I really appreciate it. Thank you!

**Comment by vincent-lu** [comment]
Yeah not a problem mate purchase a support hour.

As for the css interaction with `overflow` it doesn't bother me (yet) so I will leave it be for now.

Thanks again.
