### ISSUE TITLE
Incomplete template?

### ISSUE THREAD

**Issue by karmanbadhesha** [matfish2/vue-tables-2#945]
- Vue.js version: 2.6.12

Hello matfish2,

I had sent an email to you  but perhaps you missed it.

I am attempting to use the VtTableBody custom template and am having with the grouping as it is still listed as TODO.
However, in the compiled js code there is grouping there. 

Thanks,
Karman

**Comment by matfish2** [comment]
Hi, @karmanbadhesha. Yes, I remember when converting the templates from `jsx` to `vue` for consumer override I ran into some problem (can't remember exactly what) when converting the grouping component. You can see in the template line 35 a comment to that effect. I will have another look to try and add this functionality

**Comment by karmanbadhesha** [comment]
Thanks for the reploy @matfish2. Yes I am using the premium
