### ISSUE TITLE
Slow browser performance with EditableCells

### ISSUE THREAD

**Issue by vincent-lu** [matfish2/vue-tables-2#946]
- Vue.js version: 3
- consumed using: webpack
- Vue-tables version: 0.3.4

Hi I've implemented the EditableCells feature outlined here (https://matanya.gitbook.io/vue-tables-2/client-table/editable-cells), here is an example of such implementation:

```vue
<template>
  <v-client-table
    :data="table.data"
    :columns="table.columns"
    :options="table.options"
    @input="(e) => (table.data = e)"
    @update="updateTable"
  >
    <template #title="{ row, update }">
      <input
        v-model="row.title"
        type="text"
        @update:modelValue="update"
      />
    </template>
  </v-client-table>
</template>

<script>
import { reactive } from "vue";

export default {
  const table = reactive({
    data: [
      {
        id: 1,
        name: "John",
        title: "Foo bar",
      },

       {
        id: 2,
        name: "Tom",
        title: "Hello world",
      },
    ],
    columns: ["id", "name", "title"],
    options: {
      editableColumns: ["title"],
    },
  });

  const updateTable = (data) => axios.put("/people", data); // simple example, actual code has debounce on this

  return {
    table,
    updateTable,
  };
};
</script>
```

The above code works fine and send the PUT request to my API endpoint just fine.

However when the `table.data` contains moderate to large amount of rows and columns (in my case, about 10 columns and 7000 rows). Typing in the `<input type="text">` become very slow. To an extent this is normal since we have a large amount of event listeners.

But if I swap out the EditableCells implementation from `vue-tables` with my own simple @update funtion on the `<input type="text">`, the browser performance becomes much more tolerable.

This change includes:

- Removes `editableColumns: ["title"]` from options
- Change `@update:modelValue="update"` to `@update:modelValue="() => myUpdate(row)"`
- Add `myUpdate` function:
```
const myUpdate = (row) => axios.put("/people", row); // again, just example actual code does debounce on this
```

So it seems the event chains implemented in `vue-tables` EditableCells is less performant.

So is it possible to address this performance issue to make it at least as performant as the simpler implementation above? Or even better is there room to improve performance via some sort of Javascript event delegation, or Vuejs watch?

Again thanks for your time.

**Comment by matfish2** [comment]
1. As far as I can see, your current code doesn't use the editable cells' functionality, i.e it doesn't update the original dataset, so performance is not comparable.
2. For using the original update function to update data on-they-fly using an input element, I can add a `debouncedUpdate` function, which should significantly improve performance.

**Comment by vincent-lu** [comment]
Hmmm I'm not sure what you refer to as my current code. In my production initially I used editable cell but I want to make input faster so I experimented with my own code that doesn't use vue-table's built-in editable cells feature.

I don't think it's the lack of debouncing is the cause of the slowdown, because even with debounce in my `updateTable`, the key up on input is still slow.

My guess is the editable cells have a chain of emit/events to something like:
- **input @update:modelValue > vue-table > my updateTable function**

If I turn off `editableColumns: ["title"]`, and change `@update:modelValue="update"` to `@update:modelValue="() => myUpdate(row)"`, it's faster and basically the emit never reach `<v-client-table>`. So the flow of events becomes
- **input @update:modelValue > my myUpdate function**

So the difference between those two is the faster method never reach `<v-client-table>`'s `@input` or `@update` event.

I have two ideas:

1. **Delegate listener to a `<form>` wrapper**: when editable cells is enabled, wrap the whole table with a `<form>` element, and add a `@input` listener to it, the `event.target.value` should give us the updated value, and we just need to supply the `index` to the `<input>` to know which row is updated. See this example:
```vue
<template>
    <form @input="changed">
      <input
        v-for="(row, index) in mydata"
        :key="row.id"
        v-model="row.name"
        :index="index"
        column="name"
        type="text"
      />
    </form>
</template>

<script>
export default {
  setup() {
    const mydata = reactive([
      { id: 1, name: "foo" },
      { id: 2, name: "bar" },
    ]);
    const changed = (event) => {
      const newValue = event.target.value;
      const index = event.target.attributes.index.value;
      const column = event.target.attributes.column.value;

      // so we know mydata[index][column] changed to newValue
    };

    return {
      mydata,
      changed,
    };
  },
};
</script>
```

The event delegation in above code may help with the performance, perhaps even throw a configurable throttle on the `<form @input>` event? (https://lodash.com/docs/4.17.15#throttle)

2. **The other idea is use vuejs deep watcher** (https://v3.vuejs.org/guide/migration/watch.html#overview), since we are already using v-model which will update the array looped by `v-for`. In my above example the `name` value of the `mydata` array will change on key up without any custom update function.

Obviously those two are just ideas and they need to fit in with vue-table's own implementation and data struture. So I hoping you can shed some light on the best direction here.

I also appreciate the fact that trying to improve browser performance of large table & input fields can be tedious, so thanks again for your time and patience.

**Comment by matfish2** [comment]
> So the difference between those two is the faster method never reach <v-client-table>'s @input or @update event

But that's exactly the event that updates the data and is emitted by the `update` function provided to the slot, What I meant is that the code you shared does not update the table data, and in fact **does not use the editable cells functionality at all**. This is based on the your `updateValue` code:
```
const myUpdate = (row) => axios.put("/people", row); // again, just example actual code does debounce on this 
```
Unless you are also updating the original data passed to the table in this function, I don't see how it will change the original data array passed to the table.



The slowness you were referring to stems IMO from the update function being called on every keystroke. Since this function loops through the entire dataset in order to update it, it is expectedly slow. I have added a `deboundedUpdate` function to v0.3.5. 
Can you please try using it and let me know if you are still experiencing slow performance:
```html
<template #title="{ row, debouncedUpdate }">
      <input
        v-model="row.title"
        type="text"
        @update:modelValue="debouncedUpdate"
      />
    </template>
```

**Comment by vincent-lu** [comment]
Hey thanks @manandhar I gave `debouncedUpdate` a ago and the keypress is still slow (`update` starts to get slow on keydown, `debouncedUpdate` starts to get slow on keyup).

I did some performance measurement with Chrome DevTools, on table with 9 columns and about 7000 rows.

This is when using the Editable Cells `update` call:
![vue-tables update](https://user-images.githubusercontent.com/390546/116326225-46250200-a807-11eb-8878-d8cf2dd0126d.png)

This is when using the new Editable Cells `debouncedUpdate` call:
![vue-tables debouncedUpdate](https://user-images.githubusercontent.com/390546/116326247-53da8780-a807-11eb-9a02-f423d261b106.png)

And this is just simply change `@update:modelValue="update"` to `@update:modelValue="() => myUpdate(row)"`:
![vue-tables simple](https://user-images.githubusercontent.com/390546/116326298-72d91980-a807-11eb-806d-038d6ddf4bd9.png)

I also tried to use `<form>` wrapper idea and simply add only 1 event listener on the `<form>` (wrapped outside of `<v-client-table>`), the code is simply:
```vue
<template>
  <form v-else @input="myinput"> // the only event listener we have
    <v-client-table
      :data="table.data"
      :columns="table.columns"
      :options="table.options"
    >
      <template #bin_location="{ row, index }">
        <input
          v-model="row.bin_location"
          type="text"

          :index="index" // without vue-tables help we need this to locate the actual changed row in myinput function
          column="bin_location" // help to determine the changed column
        />
      </template>
    </v-client-table>
  </form>
</template>
```
and this is the best performance wise:
![vue-tables form input](https://user-images.githubusercontent.com/390546/116327053-39a1a900-a809-11eb-8b00-598b0be503c7.png)

I'm wondering if you can let `<v-client-table>` emit a `input` event with the actual `row` data (and perhaps optionally the column is updated, the`oldValue` and `newValue`) so I don't have to find the actual changed row via `event.target.attributes.index.value`?

Thanks again.
