### ISSUE TITLE
'Per page' selected value not equal to actual number of rows after refresh using saveState

### ISSUE THREAD

**Issue by hiddejansman** [matfish2/vue-tables-2#949]
- Vue.js version: 2.6.12
- consumed using: webpack
- vue-tables-2 version: 2.2.1
- steps for reproducing the issue:

1. Create server table with (minimal) options:
```javascript
options: {
  saveState: true,
  perPage: 25,
  perPageValues: [5, 10, 15, 25, 50, 100]
}
```
You should see '25' selected as default value for the 'per page'-dropdown.
2. Select for example '10' in 'per-page' dropdown. The table should show 10 rows now.
3. Refresh page.
4. You should still see 10 rows, but the selected value in dropdown is '5' instead of '10'.

When I inspect the state in localStorage, the 'perPage' value is being stringified. This might be the reason why the selected dropdown option is not displaying this value. After changing "10" to 10 manually and refreshing the page, the value in the 'per page'-dropdown is correctly set to 10, according to the number of rows.

Initial state:
<img width="505" alt="initial" src="https://user-images.githubusercontent.com/1528162/116864326-fc258d00-ac07-11eb-9bf9-38f18197c297.png">

State after selecting '10' in 'per page' dropdown:
<img width="502" alt="after dropdown select" src="https://user-images.githubusercontent.com/1528162/116864328-fd56ba00-ac07-11eb-8cfd-6365b5b9d10f.png">

**Comment by matfish2** [comment]
Thanks for reporting. Should be fixed in 2.2.2
