### ISSUE TITLE
Feature Request: client customFilters with ServerTable

### ISSUE THREAD

**Issue by mooseh** [matfish2/vue-tables-2#956]
Hi There
Firstly I want to say thanks for an awesome package, I'm having a real nasty roadblock with your customFilters with the servertable.
I have built a Filters Class In my laravel project which handles all the following scenarios.
```
        extract($this->request->all('with', 'append', 'withHidden', 'query', 'limit', 'page', 'orderBy', 'ascending', 'byColumn'));
```

unfortunately I need to filter by a relationship field which is going to make this class a real pain, I absolutely love the client sided customFilters as they solve this issue for me, but this seems to be impossible for the server table.

this is what im looking to do

```
      {
          name: "enabled",
          callback: function(row, query){
              if(query){
                  return row.info.enabled !== false
              }
              return true
          }
      },
```

so this is a feature request for either:
- client sided filters with the v-server table.
- append a customFilter to the query split by comma's or key value ",",":"

Any help would be hugely appreciated. thanks

**Comment by matfish2** [comment]
The server table is by definition agnostic, its only job is to display whatever data is returned from the server. You can send all the data to the server using the custom filter event. So rather than emitting a string, you can emit an object containing all the required parameters for parsing the request.

```
Event.$emit('vue-tables.filter::,myCustomFilter', {paramA:'a',paramB:'b'}) 
```

**Comment by mooseh** [comment]
I understand this can be done via the Server Side there are so many scenario's to cover and it can get very difficult with data relationships (table joins), where as if I could just do it client sided like the Client Table I could simple add a quick map return which would mean:
1. less code complexity
2. less DB hits (as the data is already there)
3. more code flexibility

I resolved my last problem with Server Sided filter with a one to one relationship which was pretty difficult to work around.
but now I'm doing one to many so I can filter where the data has a specific relationship which is going to be doubly difficult.
I feel a simple client sided map can do this so easily but working this into an API is pretty painful.

I feel like this feature request is still very much valid and would be a huge improvement to vue-tables-2.
even if you had to name it different like 

```
Event.$emit('vue-tables.reduce::RelationFilter', relation.id) 
```

**Comment by matfish2** [comment]
You can use the `responseAdapter` option to filter or change the structure of the dataset received from the server. Below is the default implementation:

```js
function(resp) { 
var data = this.getResponseData(resp); 

return { data: data.data, count: data.count } 
}
```

**Comment by mooseh** [comment]
haha I knew you might say this, so this is what I have turned to as a workaround and is working as intended, I will close this but I still feel like this could be an excellent additional feature for the v-server-table.

thanks
