### ISSUE TITLE
Feature request: Disabling certain childrow togglers

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-tables-2#957]
- Vue.js version: 2.16
- consumed using: webpack

We use child rows for displaying some details, but sometimes they are not available and expanding the child-row does not make sense. We want to disable the toggler.

Current hacky solution is disabling all pointer-events on the last column when a certain class is set via the rowClassCallback method, but I'd prefer something more elegant.

**Comment by matfish2** [comment]
I suppose what's needed here is a function to encapsulate the logic for excluding togglers. Something like:

```
disabledChildRows: function(row) {
  return row.excludeMe;
}
```

Would that satisfy the need?

**Comment by cmitz** [comment]
Yes, that would satisfy the need 👍

**Comment by matfish2** [comment]
Added. Please see https://matanya.gitbook.io/vue-tables-2/child-rows near the end

**Comment by cmitz** [comment]
Thanks for the quick implementation! We've updated and are using it online already
