### ISSUE TITLE
slot: filter__ does not work

### ISSUE THREAD

**Issue by alexsantm2019** [matfish2/vue-tables-2#958]
Hi everyone,
I have custom filters, like:

<div slot="filter__employees" >
</div>

Inside "employees" I want to put a select component, like:
<div slot="filter__employees" >
<select
                      id="employee"
                      name="employee"
                      @change="searchByEmployee($event)"
                      class="form-control"
                      v-model="keywordEmployee">
                  <option value="">-- Select Employee--</option>
                  <option
                      :value="ser.id"
                      :key="ser.id"
                      v-for="ser in employees">
                      {{ ser.name }}
                  </option>
              </select>
</div>

In old versions, it worked successfully but, in this versión I can not set <select in filter.

Is there a other way to build custom filter?? Thanks a lot

**Comment by matfish2** [comment]
Unable to reproduce. Can you share a fiddle of the issue?
