### ISSUE TITLE
Datepicker not working

### ISSUE THREAD

**Issue by gergo2007** [matfish2/vue-tables-2#96]
- Vue.js version:  2.2.1
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace):
- relevant code:
```

window._ = require('lodash');

window.$ = window.jQuery = require('jquery');

window.moment = require('moment');
require('daterangepicker');

require('bootstrap-sass');

import Vue from 'vue';
import VueRouter from 'vue-router';
import VueResource from 'vue-resource';


import axios from 'axios';
import noty from 'noty';
import sweetalert from 'sweetalert';

window.Vue = Vue;
Vue.use(VueRouter);

window.axios = axios;
window.axios.defaults.headers.common = {
'X-Requested-With': 'XMLHttpRequest'
};
```

```

import {ServerTable, Event} from 'vue-tables-2';
Vue.use(ServerTable, {
filterByColumn: true,
compileTemplates: true,
responseAdapter: function (resp) {
    return {
        data: resp.data,
        count: resp.total
    }
},
templates: {
    open: 'open-vuetable-resource'
},

sortIcon: {
    base:'fa',
    up:'fa-sort-amount-asc',
    down:'fa-sort-amount-desc'
},
rowClassCallback: function(row) {return `row-${row.id}`},

datepickerOptions: {
    showDropdowns: true
}
});

Vue.component('open-vuetable-resource', {
props: ['data'],
template: `<a :href="data.ShowAdmin" class='btn btn-primary'><i class="fa        fa-eye"></i></a>`
});

```

```
$(document).ready(function() {
new Vue({
    el: "#people",
    data: {
        columns: ['id', 'username', 'email', 'created_at', 'open'],

        options: {
            filterable: ['id', 'username', 'created_at', 'email'],
            sortable: ['id', 'username', 'created_at', 'email'],
            dateColumns: ['created_at']
        }
    }
});
});
```

Datetimepicker is not showing up at all, not even the search box, if i use [moment('created_at')] for the datecolumns the search box shows up but not the datetimepicker.

**Comment by matfish2** [comment]
Unable to reproduce. 
Do you get the normal input filter, or there is no filter at all?
Also, to help me debug please add `console.log(column, "x filter")` (replace x with the filter type)  to the different options of the `switch` statement in `compiled/template/column-filters.js` and let me know which one passes.

**Comment by gergo2007** [comment]
@matfish2 
If i use    dateColumns: [moment('created_at').format("YYYY MM DD")] i get:
https://s2.postimg.org/exduvmv3d/screen1.png

And a warning:
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. 

If just  dateColumns: ['created_at']  i get: 
https://s21.postimg.org/4jnbd29pj/screen2.png

Added the console log:
https://s14.postimg.org/g3fgik6k1/screen3.png

Thanks!

**Comment by matfish2** [comment]
Ok. I see that the column **IS** recognized as a date column (Date filters don't use an input, only a clickable `span` which should open the daterangepicker). When you click on it you don't get the datepicker? If not, please open chrome dev-tools and look for a div with a class `.daterangepicker` at the bottom of the page. I have seen before cases in which it was added but was set to `display:none;`.

As for `[moment('created_at').format("YYYY MM DD")]`, this is not the input which is expected. You should only pass an array of column names.

**Comment by gergo2007** [comment]
I dont see daterangepicker class anywhere and no, i dont get a datepicker. Also if i dont use moment the created at is not filterable, only sortable.

**Comment by matfish2** [comment]
I didn't mean that you shouldn't use `moment` for the dates themselves (I even added an option called `toMomentFormat` that converts all date strings to moment objects), just that you shouldn't use it in the `dateColumns` option.
I will try to figure out why you don't get the picker. I assume it has something to do with the initialization. I might need your help with the debugging, so please stay tuned.

**Comment by gergo2007** [comment]
@matfish2 Sure, thank you. If you need access to my code or anything else let me know.

**Comment by matfish2** [comment]
Alright. Please add `console.log(el)` in line 24 on `compiled/methods/init-date-filters.js` and post the output.

**Comment by gergo2007** [comment]
No output.

**Comment by matfish2** [comment]
Odd. How about `console.log(that.opts.dateColumns)` on line 21 (before the `forEach` statement).

**Comment by gergo2007** [comment]
Same, no output.

**Comment by matfish2** [comment]
Note there are two files names `init-date-filters.js`, one in the `lib` folder, and one in the `compiled`. Did you put the logs on the compiled file?
If you did, `console.log(this.hasDateFilters())` on `compiled/v-server-table.js:78`

**Comment by gergo2007** [comment]
Yes, i'm in the compiled/methods folder.

console.log(this.hasDateFilters()) output is 0

**Comment by matfish2** [comment]
Ok. We are zeroing in. 
Now let's check each of the conditions inside `has-date-filters.js`.
Log each condition separately and post the output.

**Comment by gergo2007** [comment]
Output:
https://s7.postimg.org/s90nkr7zv/sceen4.png

**Comment by matfish2** [comment]
Ok, the problem is a faulty `intersection` function. I will replace it with `npm`'s `array-intersection`.

**Comment by vkumarsi1** [comment]
CPTable.vue:

<template>
  <div id="cpTable">
    <div v-if="cmpLoaded">
     <v-client-table :data="getCampaigns" :columns="columns" :options="options" style="padding-left: 50px; width: 97%">
     	<div slot="name" slot-scope="props">
     		<router-link :to="{ name: 'ViewCampaigns', params: { id: props.row.id, data: JSON.stringify(props.row) }}" title="View">{{props.row.name}}</router-link>
     	</div>
     	<div slot="action" slot-scope="props" id='tableMenu' class='spectrum-ActionMenu spectrum--light'>
						<router-link :to="{ name: 'ViewCampaigns', params: { id: props.row.id, data: JSON.stringify(props.row) }}" title="Edit"><i class='glyphicon glyphicon-edit'></i></router-link>
						<router-link :to="{ name: 'ViewCampaigns', params: { id: props.row.id, data: JSON.stringify(props.row) }}" title="Delete"><i class='glyphicon glyphicon-trash'></i></router-link>
						<router-link :to="{ name: 'ViewCampaigns', params: { id: props.row.id, data: JSON.stringify(props.row) }}" title="Duplicate"><i class='glyphicon glyphicon-duplicate'></i></router-link>
					</div>
     </v-client-table>
    </div>
  </div>
</template>

<script>

import daterangepicker from 'daterangepicker'
import {mapActions, mapGetters} from 'vuex'
//import Vuetable from 'vuetable-2/src/components/Vuetable'
//import VuetablePagination from 'vuetable-2/src/components/VuetablePagination'
//import {ClientTable} from 'vue-tables-2'

import MenuIcon from 'vue-material-design-icons/menu.vue'

window.moment = require('moment')
export default {
  name: 'cpTable',
  components: {
    MenuIcon,
    daterangepicker,
    //Vuetable,
    //VuetablePagination,
    //ClientTable
  },
  data () {
    return {
      columns: ['name', 'StartDate', 'id', 'partner', 'campaign_type', 'created_by', 'campaign_status', 'action'],
      options: {
        compileTemplates: true,
        filterByColumn: true,
        perPage: 10,
        perPageValues: [ 10, 20, 50 ],
        texts: {
          filter: 'Filter:',
          filterBy: 'Filter by {column}',
          count: ' ',
          limit: 'Records: '
        },
        dateColumns: ['StartDate'],
        initFilters: {},
        dateFormat: 'DD/MM/YYYY',
        datepickerOptions: {
          showDropdowns: true,
          autoUpdateInput: true,
          locale: { cancelLabel: 'Clear' }
        },
        pagination: { chunk: 10, dropdown: false },
        filterable: ['name','id','StartDate','partner','campaign_type','created_by','campaign_status'],
        sortable: ['name','StartDate','partner','campaign_type','created_by','campaign_status'], 
        headings: {
          name: 'Campaign Name',
          StartDate: 'Start Date',
          id: 'CampaignId',
          partner: 'Partner',
          campaign_type: 'Campaign Type',
          campaign_status: 'Status',
          created_by : 'Created By',
          action: 'Action'
        },
        templates: {
          StartDate: function (h, row, index){
            //window.console('date: ' + row);
            return moment(row.StartDate).format('DD/MM/YYYY');
          },
          campaign_status: function(h, row, index){
            return row.campaign_status == 'Publish' || row.campaign_status == 'Active' ? <button class='spectrum-Button spectrum-Button--primary'>Publish</button> : row.campaign_status;
          },
          name: function (h, row, index){
          }
        },
        listColumns: {
              partner: [{
                id: 'epay',
                text: 'epay'
              }, {
                id: 'Staples',
                text: 'Staples'
              }, {
                id: 'Softbank',
                text: 'Softbank'
              }],
              campaign_status: [{
                id: 'Published',
                text: 'Published'
              }, {
                id: 'Publish',
                text: 'Publish'
              }, {
                id: 'Draft',
                text: 'Draft'
              }, {
                id: 'Active',
                text: 'Active'
              } ],
              campaign_type: [{
                id: 'Direct Purchase',
                text: 'Direct Purchase'
              }, {
                id: 'Retail POSA',
                text: 'Retail POSA'
              }, {
                id: 'eTail',
                text: 'eTail'
              }, {
                id: 'Redemption Camapign',
                text: 'Redemption Camapign'
              }]
        }
      }
    }
  },
  created () {
    this.fetchCampaigns()
  },
  computed: {
    ...mapGetters([
      'getCampaigns',
      'cmpLoaded'
    ])
  },

  methods: {
    ...mapActions([
      'fetchCampaigns'
    ])
  }
}
</script>

<style>

</style>

My vue code is like above everything works fine except datecolumn as filter. Please help. struggling but couldn't find a solution.

**Comment by matfish2** [comment]
Please format your code. It is readable.
Also have a look here: https://github.com/matfish2/vue-tables-2/issues/445#issuecomment-369975272
