### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by polosson** [matfish2/vue-tables-2#960]
Hi!

Is it possible to add and maintain a CHANGELOG.md file or something like that (i.e. the [release page](https://github.com/matfish2/vue-tables-2/releases), but up-to-date with details for every release), which describe the latest changes on every releases?

It would be very useful for updating the dependencies of our projects that use vue-tables-2, making ourselves sure that we don't introduce some regression, and to guide us on possible changes to our code.

Thanks by advance!

**Comment by matfish2** [comment]
Sorry, this was closed by bot. I accept your comment and will log future changes into a changelog.
