### ISSUE TITLE
Variables inside custom header not updating

### ISSUE THREAD

**Issue by Nahid5** [matfish2/vue-tables-2#962]
- Vue.js version: 2.6.12
- Vue-tables-2 version: 2.1.73

I have a multiselect inside a custom column header, and whenever I select something, the multiselect view does not update with what I have selected.
```
<v-client-table ref="table" :columns="fields" v-model="data" :options="vuetableOptions">
<template slot="h__Risk">
              <multiselect
                v-model="filters.selected"
                :multiple="true"
                :close-on-select="true"
                placeholder="Filter By Risk"
                :options="$store.state.risk"
                :hide-selected="true"
              />
 </template>
</v-client-table>
```

I also tried a simpler example with just incrementing a number. The number does increase in the data, however the displayed number always shows 0.
```
<v-client-table ref="table" :columns="fields" v-model="data" :options="vuetableOptions">  
<template slot="h__Risk">  
        <b>Rating</b>  
            <p>{{ increment }}</p>  
        <button class="btn btn-info" @click="incrementBtn">Increment on click</button>  
 </template>  
</v-client-table>  
...
...
...
export default {
  data() {
    return {
      increment: 0, 
}},
methods: {
    incrementBtn() {
      this.increment += 1
    },
}
```

**Comment by SauceTV** [comment]
Here is my code

> The header on my checkbox does not update with the "allSelected" variable. The only way to fix it that I found was to use a ref on the header and change the ".checked" var to true or false. The problem is that vue doesnt like when you change the prop directly.
> 
> HTML:
> 
> ```
> <v-client-table :columns="['name', 'select']" :data="products" :options="table.options" :theme="table.theme" class="dataTable p-0 m-0 w-100">
>       <div slot="h__select" style="float: right">
>             <b-checkbox @change="cart.selectedProducts = selectAll()" color="success" style="float: right"
>                                           v-model="allSelected"/>
>       </div>
>       <div slot="select" slot-scope="props" style="float: right">
>             <b-form-checkbox v-model="cart.selectedProducts" :value="props.row._id" color="success"
>                                           style="float: right" />
>       </div>
> </v-client-table>
> ```
> 
> Vars:
> 
> ```
> data: () => {
>       return {
>             products: {
>                   {name: "socks", _id: 1},
>                   {name: "shirt", _id: 2},
>                   {name: "pants", _id: 3},
>             },
>             cart:  {
>                   selectedProducts: [],
>                   ...  // Other cart Data
>             },
>             allSelected: false,
>             ...  // Other Page Data
>       }
> }
> ```
> 
> Watchers:
> 
> ```
> watch: {
>       selectedProducts: {
>             deep: true,
>             handler() {
>                   let all = this.products.filter(product => {
>                         return this.cart.selectedProducts.includes(product._id);
>                   }
>                   if (all.length === this.products.length) {
>                        console.log("change to true")
>                         this.allSelected = true;
>                   } else {
>                        console.log("change to false")
>                         this.allSelected = false;
>                   }
>             }
>       }
> }
> ```
> 
> Methods:
> 
> ```
> methods: {
>       selectAll() {
>                   let result = [];
>                   let all = this.products.filter(product => {
>                         return this.cart.selectedProducts.includes(product._id);
>                   }
>                   if (all.length === this.products.length) {
>                         return result;
>                   } else {
>                         this.products.forEach(function (product, index) {
>                               Vue.set(result, index, product);
>                         })
>                         return result;
>                   }
>       }
> }
> ```

**Comment by joseanzacarias** [comment]
Hello this works for me, I just use the syntax with the "#" and that's it, in your case it should be something like  `<template #h__Risk>`
