### ISSUE TITLE
MouseUp event conflicts with other MouseUp events

### ISSUE THREAD

**Issue by matburz** [matfish2/vue-tables-2#968]
- Vue.js version: 2

Hey @matfish2 

I'm using el-slider on the same view as Table is implemented.
There is no problem with el-slider when Table isn't visible. 
But when Table pops up(v-if directive), mouseUp event on Table conflicts with mouseUp on el-slider(in my case slider is stuck and it's unable to be dropped so it follows the cursor. Only site refresh resets the problem till Table isn't visible again. Table works properly of course).

I've managed to notice, that removing 'e.stopPropagation();' from 'document.addEventListener' in 'resizeable-columns.js' file solves my problem and doesn't affect the Table.

**Comment by matfish2** [comment]
Thank you for reporting and detecting the issue. Please pull the latest version from npm

**Comment by matburz** [comment]
Yea, it's perfect :)
