### ISSUE TITLE
Server side implementation

### ISSUE THREAD

**Issue by ejlocop** [matfish2/vue-tables-2#97]
- Vue.js version: 2.0.*
- consumed using: webpack
- FULL error message (including stack trace): n/a
- relevant code: see below
- steps for reproducing the issue:

how can i use your Laravel implementation files to my controller returning the data? 
i can't seem to make it work. can you give an example please on how can i make this work?
```php
public function getIndex()
{
 return EloquentUserProvider::get(SomeModel::class); //results to a static related error ofc.
}
```

**Comment by matfish2** [comment]
See https://github.com/matfish2/vue-tables/issues/74

**Comment by ejlocop** [comment]
@matfish2 i've got a question. 

is it possible to cache the response from the initial call ?
as ive read from the documention. there is no cache option

**Comment by matfish2** [comment]
No client-side caching mechanism. Not sure how beneficial that would be given the almost infinite number of combinations (filters, values per page, sorting, page).
