### ISSUE TITLE
evaluate removal of background: white from thead tr th

### ISSUE THREAD

**Issue by masterkain** [matfish2/vue-tables-2#972]
- Vue.js version: 3
- consumed using: vite / tailwind

any special reason why background: white is there, hardcoded?
I find it makes it harder to be customizable.

![Screenshot 2021-09-19 at 01 20 49](https://user-images.githubusercontent.com/12844/133910938-d185f3c4-853d-403d-adb5-1b32357cedb0.png)

**Comment by matfish2** [comment]
I remember fixing it in one of the other repos. Will remove it tomorrow

**Comment by matfish2** [comment]
Just remembered the issue was raised before and I have added a `stickyHeaderBackground` option.
