### ISSUE TITLE
[question] sort by attribute, show another

### ISSUE THREAD

**Issue by masterkain** [matfish2/vue-tables-2#974]
I have this use case, two fields in my data source: `duration` and `durationInSeconds`.

`duration` is an already formatted string, such as `0:10`, while `durationInSeconds` is the corresponding integer, `10`.

if I show `duration` in my table, sorting will be off, and I'll need either a custom sorter or a custom cell to reformat `10` in `0:10` in javascript, but since I already have the corresponding value via API it seems a bit wasteful on resources.

So I'm asking if is there any chance, or it is worth your consideration, to show one attribute but shadow-sort by another, so I can show the formatted string from the server, but use the `duration` to sort, since it's a numeric value and sorting already works out of the box for that.

Based off a request in https://github.com/matfish2/vue-tables-2/issues/973 maybe something like:

```
const columns = [
  { attribute: "durationInSeconds", label: 'Duration', sort: 'duration', filter: 'duration' },
];
```

**Comment by matfish2** [comment]
Yes, there is. Use a template on the `durationInSeconds` column to display the formatted `duration` value:

Include `durationInSeconds` in the `columns` prop:
```
columns:['durationInSeconds'] // + all other columns
```
Add a scoped slot:
```vue
<template v-slot:durationInSeconds="{row}">
   {{row.duration}}
</template>
```

**Comment by masterkain** [comment]
brilliant, thanks
