### ISSUE TITLE
Replacing cell content issues

### ISSUE THREAD

**Issue by masterkain** [matfish2/vue-tables-2#975]
- Vue.js version: 3
- consumed using: vite

My goal is to replace the content of a cell with an image, but for testing I settled on the documentation examples.
Am I doing something wrong?

**first try (scoped slots): https://matanya.gitbook.io/vue-tables-2/templates#scoped-slots**

most likely the documentation might not be up to date for vue 3 https://v3.vuejs.org/guide/component-slots.html#scoped-slots
```
    #media
      v-client-table(:data='mediaFiles' :columns='columns' :options='options' v-if="!playlistLoading")
        a.fa.fa-edit(v-slot:edit='props' :href='edit(props.row.token)')
```
![Screenshot 2021-09-19 at 04 49 40](https://user-images.githubusercontent.com/12844/133913795-69529779-dc71-4d77-803f-10303d8721c4.png)

---

**second try (vue component): https://matanya.gitbook.io/vue-tables-2/templates#vue-components**

`AlbumImageCell.vue`

```
<script>
export default {
  props: ["data", "index"],
};
</script>

<template lang="pug">
a.fa.fa-edit(:href="edit(data.token)")
  | Edit
</template>
```

`Show.vue`

```
import AlbumImageCell from "@/components/AlbumImageCell.vue";

const columns = [
  "artworkPath",

];

const options = {
  templates: {
    artworkPath: AlbumImageCell,
  },
```

![Screenshot 2021-09-19 at 04 52 09](https://user-images.githubusercontent.com/12844/133913840-fefb9671-4ffe-4963-af4a-101c417c9c9b.png)

**Comment by masterkain** [comment]
I was able to proceed with the scoped slot updated for vue 3

```
      v-client-table(:data='mediaFiles' :columns='columns' :options='options' v-if="!playlistLoading")
        template(v-slot:artworkPath='props')
          i.fas.fa-check
          span.green {{ props.item }}
```

**Comment by matfish2** [comment]
Yes, vue3 has a new syntax for scoped slots
