### ISSUE TITLE
xscode down

### ISSUE THREAD

**Issue by woody34** [matfish2/vue-tables-2#981]
I use your paid service and I am unable to install due to the hosting being down, it seems. 

`npm i` results in this error:

![image](https://user-images.githubusercontent.com/8930703/138143999-10a6d04f-5256-4353-a088-265ebdc3b033.png)

![image](https://user-images.githubusercontent.com/8930703/138144064-61dec6bd-8e1f-4389-80fe-7dd7a95edf18.png)

**Comment by matfish2** [comment]
Thank you for reporting. I have contacted xscode and asked the to urgently advise. Will update here once I know more

**Comment by YaraWebDeveloper** [comment]
> Their server has crashed, hopefully fixed by tomorrow. In the meantime, I gave them a public link to share with all paying users. Apologies.

Hi Matfish, I use your paid service, Where can I find the link?

**Comment by matfish2** [comment]
@YaraWebDeveloper their CEO said he'll send it to all subscribed users. You should get it via email

**Comment by duleml012** [comment]
It's happening again. Xscode having problems with SSL certificate, it seems.

**Comment by matfish2** [comment]
@duleml012 can please share a screenshot so I can send them

**Comment by cristian318** [comment]
Xscode having problems with SSL certificate.
![problem](https://user-images.githubusercontent.com/47723166/143260768-26a389c2-4c85-4113-8e21-c1b3c6c719a8.png)

**Comment by matfish2** [comment]
Ok guys, I made the repo public at https://github.com/matfish2/vue-tables-2-private, this time for good. I'll remove the repo from xscode once they notify all subscribers. I'll no longer be able to maintain it though, so if anyone wants to take ownership, please lmk. Feel free to fork and push as npm package if you want.

**Comment by MichaelHeydon** [comment]
Does this also apply to `v-tables-3`?

**Comment by matfish2** [comment]
Yes, `v-tables-3` is on the `vue3` branch

**Comment by MichaelHeydon** [comment]
Would you mind putting up the packages to npm please? If someone else ever does take ownership the account can always be transferred.

**Comment by matfish2** [comment]
https://www.npmjs.com/package/v-tables-3

**Comment by matfish2** [comment]
https://www.npmjs.com/package/vue-tables-2-premium

**Comment by matfish2** [comment]
Updated readme on both repos and gitbook docs https://matanya.gitbook.io/vue-tables-2/installation

**Comment by MichaelHeydon** [comment]
Thanks @matfish2, much appreciated :slightly_smiling_face:
